import { AnimationsService, ControlsService, DemoGroupService, DemosService, PatternsService, StylesService } from "./demo-group-services.mjs";
import { DataTemplate } from "@pragmatic-lab/mural/basic";
import { ListBox } from "@pragmatic-lab/mural/framework/list/list-box.js";
import { Capability, ShellModule } from "@pragmatic-lab/mural/framework/shell/module.js";
import { ContentHostService } from "@pragmatic-lab/mural/framework/shell/services/content-host-service.js";
import { DataContextBinding, DynamicResource, ServiceProvider } from "@pragmatic-lab/mural/runtime";

export const DemoPlatformModule = (() => {
    const _shellModule0 = new ShellModule();
    _shellModule0.set_property_value(ShellModule.NameKey, "µ-mural demos");
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(AnimationsService), (p) => new AnimationsService(p), 'singleton');
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(ControlsService), (p) => new ControlsService(p), 'singleton');
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(DemosService), (p) => new DemosService(p), 'singleton');
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(PatternsService), (p) => new PatternsService(p), 'singleton');
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(StylesService), (p) => new StylesService(p), 'singleton');
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(ContentHostService), (p) => new ContentHostService(p), 'singleton');
    const _rd1 = _shellModule0.Resources;
    const _tmpl2 = new DataTemplate((_data) => {
        const _listBox3 = new ListBox();
        _listBox3.set_property_value(ListBox.ItemsSourceKey, DataContextBinding(_listBox3, "Items"));
        _listBox3.set_property_value(ListBox.SelectedItemKey, DataContextBinding(_listBox3, "SelectedItem"));
        return _listBox3;
    }, DemoGroupService);
    _rd1.Set(DemoGroupService, _tmpl2);
    const _capability4 = new Capability();
    _capability4.set_property_value(Capability.NameKey, "Animation");
    _capability4.set_property_value(Capability.IconKey, DynamicResource(_capability4, "AnimationIcon"));
    _capability4.set_property_value(Capability.ServiceKeyKey, AnimationsService);
    _shellModule0.AddChild(_capability4);
    const _capability5 = new Capability();
    _capability5.set_property_value(Capability.NameKey, "Controls");
    _capability5.set_property_value(Capability.IconKey, DynamicResource(_capability5, "ControlsIcon"));
    _capability5.set_property_value(Capability.ServiceKeyKey, ControlsService);
    _shellModule0.AddChild(_capability5);
    const _capability6 = new Capability();
    _capability6.set_property_value(Capability.NameKey, "Demos");
    _capability6.set_property_value(Capability.IconKey, DynamicResource(_capability6, "DemosIcon"));
    _capability6.set_property_value(Capability.ServiceKeyKey, DemosService);
    _shellModule0.AddChild(_capability6);
    const _capability7 = new Capability();
    _capability7.set_property_value(Capability.NameKey, "Patterns");
    _capability7.set_property_value(Capability.IconKey, DynamicResource(_capability7, "PatternsIcon"));
    _capability7.set_property_value(Capability.ServiceKeyKey, PatternsService);
    _shellModule0.AddChild(_capability7);
    const _capability8 = new Capability();
    _capability8.set_property_value(Capability.NameKey, "Styles & Triggers");
    _capability8.set_property_value(Capability.IconKey, DynamicResource(_capability8, "StylesIcon"));
    _capability8.set_property_value(Capability.ServiceKeyKey, StylesService);
    _shellModule0.AddChild(_capability8);
    return _shellModule0;
})();
