import { GroupVM } from "./platform-vm.mjs";
import { AdornerDecorator, Border, Dock, DockPanel, HierarchicalDataTemplate, PageView, StackPanel } from "@visualisation-sub/mural/basic";
import { TreeView, TreeViewItem } from "@visualisation-sub/mural/framework/list/tree-view.js";
import { ThemeSelector } from "@visualisation-sub/mural/framework/surface.js";
import { TopAppBar } from "@visualisation-sub/mural/framework/top-app-bar/top-app-bar.js";
import { Material, MaterialLight } from "@visualisation-sub/mural/resources/material";
import { Application, DataContextBinding, DynamicResource, NameScope, Setter, Style, Thickness } from "@visualisation-sub/mural/runtime";

export const app = (() => {
    const _app0 = new Application();
    _app0.initialize({ theme: Material, scheme: MaterialLight });
    const _rd1 = _app0.Resources;
    const _tmpl2 = new HierarchicalDataTemplate((_data) => {
        const _treeViewItem3 = new TreeViewItem();
        return _treeViewItem3;
    }, (data) => data?.Demos, undefined, undefined, GroupVM);
    _rd1.Set("GroupTemplate", _tmpl2);
    const _setter4 = new Setter(TreeViewItem, "IsExpanded", true);
    const _style5 = new Style(TreeViewItem, [_setter4], undefined, [], []);
    _rd1.Set("NavRowStyle", _style5);
    const _border6 = new Border();
    _border6.SetNameScope(new NameScope());
    _border6._set_property_value_by_name("Background", DynamicResource(_border6, "Surface"));
    const _adornerDecorator7 = new AdornerDecorator();
    const _dockPanel8 = new DockPanel();
    _dockPanel8._set_property_value_by_name("LastChildFill", true);
    const _topAppBar9 = new TopAppBar();
    _topAppBar9._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
    _topAppBar9._set_property_value_by_name("Title", "µ-mural demos");
    const _themeSelector10 = new ThemeSelector();
    _topAppBar9.AddChild(_themeSelector10);
    _dockPanel8.AddChild(_topAppBar9);
    const _border11 = new Border();
    _border11._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
    _border11._set_property_value_by_name("Height", 1);
    _border11._set_property_value_by_name("Background", DynamicResource(_border11, "OutlineVariant"));
    _dockPanel8.AddChild(_border11);
    const _border12 = new Border();
    _border12._set_property_value_by_name(DockPanel, "Dock", Dock.Left);
    _border12._set_property_value_by_name("Width", 260);
    _border12._set_property_value_by_name("Background", DynamicResource(_border12, "SurfaceContainerLow"));
    _border12._set_property_value_by_name("BorderBrush", DynamicResource(_border12, "OutlineVariant"));
    _border12._set_property_value_by_name("BorderThickness", new Thickness(0, 0, 1, 0));
    const _stackPanel13 = new StackPanel();
    const _treeView14 = new TreeView();
    _treeView14._set_property_value_by_name("Indent", 18);
    _treeView14._set_property_value_by_name("Margin", new Thickness(8, 8, 8, 8));
    _treeView14._set_property_value_by_name("ItemsSource", DataContextBinding(_treeView14, "Groups"));
    _treeView14._set_property_value_by_name("ItemTemplate", DynamicResource(_treeView14, "GroupTemplate"));
    _treeView14._set_property_value_by_name("ItemContainerStyle", DynamicResource(_treeView14, "NavRowStyle"));
    _treeView14._set_property_value_by_name("SelectedDataItem", DataContextBinding(_treeView14, "SelectedDemo"));
    _stackPanel13.AddChild(_treeView14);
    _border12.SetChild(_stackPanel13);
    _dockPanel8.AddChild(_border12);
    const _pageView15 = new PageView();
    _pageView15.Name = "page";
    _border6.nameScope.Register("page", _pageView15);
    _pageView15._set_property_value_by_name("Title", DataContextBinding(_pageView15, "Title"));
    _pageView15._set_property_value_by_name("Subtitle", DataContextBinding(_pageView15, "Subtitle"));
    _pageView15._set_property_value_by_name("Content", DataContextBinding(_pageView15, "Content"));
    _dockPanel8.AddChild(_pageView15);
    _adornerDecorator7.SetChild(_dockPanel8);
    _border6.SetChild(_adornerDecorator7);
    _rd1.Root = _border6;
    return _app0;
})();
