import { AdornerDecorator, Border, Dock, DockPanel, PageView, TextBlock } from "@visualisation-sub/mural/basic";
import { ListBox } from "@visualisation-sub/mural/framework/list/list-box.js";
import { NavigationItem } from "@visualisation-sub/mural/framework/navigation/navigation-item.js";
import { NavigationRail } from "@visualisation-sub/mural/framework/navigation/navigation-rail.js";
import { ThemeSelector } from "@visualisation-sub/mural/framework/surface.js";
import { TopAppBar } from "@visualisation-sub/mural/framework/top-app-bar/top-app-bar.js";
import { Material, MaterialLight } from "@visualisation-sub/mural/resources/material";
import { Application, DataContextBinding, DynamicResource, NameScope, Thickness } from "@visualisation-sub/mural/runtime";

export const app = (() => {
    const _app0 = new Application();
    _app0.initialize({ theme: Material, scheme: MaterialLight });
    const _rd1 = _app0.Resources;
    const _border2 = new Border();
    _border2.SetNameScope(new NameScope());
    _border2.set_property_value(Border.BackgroundKey, DynamicResource(_border2, "Surface"));
    const _adornerDecorator3 = new AdornerDecorator();
    const _dockPanel4 = new DockPanel();
    _dockPanel4.set_property_value(DockPanel.LastChildFillKey, true);
    const _topAppBar5 = new TopAppBar();
    _topAppBar5.set_property_value(DockPanel.DockKey, Dock.Top);
    _topAppBar5.set_property_value(TopAppBar.TitleKey, "µ-mural demos");
    const _themeSelector6 = new ThemeSelector();
    _topAppBar5.AddChild(_themeSelector6);
    _dockPanel4.AddChild(_topAppBar5);
    const _border7 = new Border();
    _border7.set_property_value(DockPanel.DockKey, Dock.Top);
    _border7.set_property_value(Border.HeightKey, 1);
    _border7.set_property_value(Border.BackgroundKey, DynamicResource(_border7, "OutlineVariant"));
    _dockPanel4.AddChild(_border7);
    const _dockPanel8 = new DockPanel();
    _dockPanel8.set_property_value(DockPanel.DockKey, Dock.Left);
    _dockPanel8.set_property_value(DockPanel.LastChildFillKey, true);
    const _navigationRail9 = new NavigationRail();
    _navigationRail9.set_property_value(DockPanel.DockKey, Dock.Left);
    _navigationRail9.set_property_value(NavigationRail.SelectedIndexKey, DataContextBinding(_navigationRail9, "SelectedGroupIndex"));
    const _navigationItem10 = new NavigationItem();
    _navigationItem10.set_property_value(NavigationItem.LabelKey, "Animation");
    const _textBlock11 = new TextBlock();
    _textBlock11.set_property_value(TextBlock.TextKey, "animation");
    _textBlock11.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock11.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem10.Content = _textBlock11;
    _navigationRail9.AddChild(_navigationItem10);
    const _navigationItem12 = new NavigationItem();
    _navigationItem12.set_property_value(NavigationItem.LabelKey, "Controls");
    const _textBlock13 = new TextBlock();
    _textBlock13.set_property_value(TextBlock.TextKey, "tune");
    _textBlock13.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock13.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem12.Content = _textBlock13;
    _navigationRail9.AddChild(_navigationItem12);
    const _navigationItem14 = new NavigationItem();
    _navigationItem14.set_property_value(NavigationItem.LabelKey, "Demos");
    const _textBlock15 = new TextBlock();
    _textBlock15.set_property_value(TextBlock.TextKey, "widgets");
    _textBlock15.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock15.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem14.Content = _textBlock15;
    _navigationRail9.AddChild(_navigationItem14);
    const _navigationItem16 = new NavigationItem();
    _navigationItem16.set_property_value(NavigationItem.LabelKey, "Patterns");
    const _textBlock17 = new TextBlock();
    _textBlock17.set_property_value(TextBlock.TextKey, "grid_view");
    _textBlock17.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock17.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem16.Content = _textBlock17;
    _navigationRail9.AddChild(_navigationItem16);
    const _navigationItem18 = new NavigationItem();
    _navigationItem18.set_property_value(NavigationItem.LabelKey, "Styles & Triggers");
    const _textBlock19 = new TextBlock();
    _textBlock19.set_property_value(TextBlock.TextKey, "palette");
    _textBlock19.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock19.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem18.Content = _textBlock19;
    _navigationRail9.AddChild(_navigationItem18);
    _dockPanel8.AddChild(_navigationRail9);
    const _border20 = new Border();
    _border20.set_property_value(Border.WidthKey, 200);
    _border20.set_property_value(Border.BackgroundKey, DynamicResource(_border20, "SurfaceContainerLow"));
    _border20.set_property_value(Border.BorderBrushKey, DynamicResource(_border20, "OutlineVariant"));
    _border20.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 1, 0));
    const _listBox21 = new ListBox();
    _listBox21.set_property_value(ListBox.MarginKey, new Thickness(8, 8, 8, 8));
    _listBox21.set_property_value(ListBox.ItemsSourceKey, DataContextBinding(_listBox21, "CurrentDemos"));
    _listBox21.set_property_value(ListBox.SelectedItemKey, DataContextBinding(_listBox21, "SelectedDemo"));
    _border20.SetChild(_listBox21);
    _dockPanel8.AddChild(_border20);
    _dockPanel4.AddChild(_dockPanel8);
    const _pageView22 = new PageView();
    _pageView22.Name = "page";
    _border2.nameScope.Register("page", _pageView22);
    _pageView22.set_property_value(PageView.TitleKey, DataContextBinding(_pageView22, "Title"));
    _pageView22.set_property_value(PageView.SubtitleKey, DataContextBinding(_pageView22, "Subtitle"));
    _pageView22.set_property_value(PageView.ContentKey, DataContextBinding(_pageView22, "Content"));
    _dockPanel4.AddChild(_pageView22);
    _adornerDecorator3.SetChild(_dockPanel4);
    _border2.SetChild(_adornerDecorator3);
    _rd1.Root = _border2;
    return _app0;
})();
