import { DemoNavigationService } from "./demo-navigation-service.mjs";
import { Border, Dock, DockPanel, Orientation, PageView, StackPanel, TextBlock } from "@visualisation-sub/mural/basic";
import { ListBox } from "@visualisation-sub/mural/framework/list/list-box.js";
import { NavigationItem } from "@visualisation-sub/mural/framework/navigation/navigation-item.js";
import { NavigationRail } from "@visualisation-sub/mural/framework/navigation/navigation-rail.js";
import { EditorShell } from "@visualisation-sub/mural/framework/shell/editor-shell.js";
import { NavigationService } from "@visualisation-sub/mural/framework/shell/services/navigation-service.js";
import { Shell, ShellRegion } from "@visualisation-sub/mural/framework/shell/shell.js";
import { ThemeSelector } from "@visualisation-sub/mural/framework/surface.js";
import { TopAppBar } from "@visualisation-sub/mural/framework/top-app-bar/top-app-bar.js";
import { Material, MaterialLight } from "@visualisation-sub/mural/resources/material";
import { Application, DynamicResource, NameScope, ServiceBinding, ServiceProvider, Thickness } from "@visualisation-sub/mural/runtime";

export const app = (() => {
    const _app0 = new Application();
    _app0.initialize({ theme: Material, scheme: MaterialLight });
    const _rd1 = _app0.Resources;
    const _editorShell2 = new EditorShell();
    _editorShell2.SetNameScope(new NameScope());
    _editorShell2.Services.register(ServiceProvider.tokenFor(DemoNavigationService), (p) => new DemoNavigationService(p), 'singleton');
    const _stackPanel3 = new StackPanel();
    _stackPanel3.set_property_value(Shell.RegionKey, ShellRegion.Header);
    _stackPanel3.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
    const _topAppBar4 = new TopAppBar();
    _topAppBar4.set_property_value(TopAppBar.TitleKey, "µ-mural demos");
    const _themeSelector5 = new ThemeSelector();
    _topAppBar4.AddChild(_themeSelector5);
    _stackPanel3.AddChild(_topAppBar4);
    const _border6 = new Border();
    _border6.set_property_value(Border.HeightKey, 1);
    _border6.set_property_value(Border.BackgroundKey, DynamicResource(_border6, "OutlineVariant"));
    _stackPanel3.AddChild(_border6);
    _editorShell2.AddChild(_stackPanel3);
    const _dockPanel7 = new DockPanel();
    _dockPanel7.set_property_value(Shell.RegionKey, ShellRegion.Navigation);
    _dockPanel7.set_property_value(DockPanel.LastChildFillKey, true);
    const _navigationRail8 = new NavigationRail();
    _navigationRail8.set_property_value(DockPanel.DockKey, Dock.Left);
    _navigationRail8.set_property_value(NavigationRail.SelectedIndexKey, ServiceBinding(_navigationRail8, ServiceProvider.tokenFor(NavigationService), "SelectedGroupIndex"));
    const _navigationItem9 = new NavigationItem();
    _navigationItem9.set_property_value(NavigationItem.LabelKey, "Animation");
    const _textBlock10 = new TextBlock();
    _textBlock10.set_property_value(TextBlock.TextKey, "animation");
    _textBlock10.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock10.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem9.Content = _textBlock10;
    _navigationRail8.AddChild(_navigationItem9);
    const _navigationItem11 = new NavigationItem();
    _navigationItem11.set_property_value(NavigationItem.LabelKey, "Controls");
    const _textBlock12 = new TextBlock();
    _textBlock12.set_property_value(TextBlock.TextKey, "tune");
    _textBlock12.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock12.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem11.Content = _textBlock12;
    _navigationRail8.AddChild(_navigationItem11);
    const _navigationItem13 = new NavigationItem();
    _navigationItem13.set_property_value(NavigationItem.LabelKey, "Demos");
    const _textBlock14 = new TextBlock();
    _textBlock14.set_property_value(TextBlock.TextKey, "widgets");
    _textBlock14.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock14.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem13.Content = _textBlock14;
    _navigationRail8.AddChild(_navigationItem13);
    const _navigationItem15 = new NavigationItem();
    _navigationItem15.set_property_value(NavigationItem.LabelKey, "Patterns");
    const _textBlock16 = new TextBlock();
    _textBlock16.set_property_value(TextBlock.TextKey, "grid_view");
    _textBlock16.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock16.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem15.Content = _textBlock16;
    _navigationRail8.AddChild(_navigationItem15);
    const _navigationItem17 = new NavigationItem();
    _navigationItem17.set_property_value(NavigationItem.LabelKey, "Styles & Triggers");
    const _textBlock18 = new TextBlock();
    _textBlock18.set_property_value(TextBlock.TextKey, "palette");
    _textBlock18.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
    _textBlock18.set_property_value(TextBlock.FontSizeKey, 24);
    _navigationItem17.Content = _textBlock18;
    _navigationRail8.AddChild(_navigationItem17);
    _dockPanel7.AddChild(_navigationRail8);
    const _border19 = new Border();
    _border19.set_property_value(Border.WidthKey, 200);
    _border19.set_property_value(Border.BackgroundKey, DynamicResource(_border19, "SurfaceContainerLow"));
    _border19.set_property_value(Border.BorderBrushKey, DynamicResource(_border19, "OutlineVariant"));
    _border19.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 1, 0));
    const _listBox20 = new ListBox();
    _listBox20.set_property_value(ListBox.MarginKey, new Thickness(8, 8, 8, 8));
    _listBox20.set_property_value(ListBox.ItemsSourceKey, ServiceBinding(_listBox20, ServiceProvider.tokenFor(NavigationService), "Items"));
    _listBox20.set_property_value(ListBox.SelectedItemKey, ServiceBinding(_listBox20, ServiceProvider.tokenFor(NavigationService), "SelectedItem"));
    _border19.SetChild(_listBox20);
    _dockPanel7.AddChild(_border19);
    _editorShell2.AddChild(_dockPanel7);
    const _pageView21 = new PageView();
    _pageView21.Name = "page";
    _editorShell2.nameScope.Register("page", _pageView21);
    _pageView21.set_property_value(Shell.RegionKey, ShellRegion.Content);
    _pageView21.set_property_value(PageView.TitleKey, ServiceBinding(_pageView21, ServiceProvider.tokenFor(NavigationService), "Title"));
    _pageView21.set_property_value(PageView.SubtitleKey, ServiceBinding(_pageView21, ServiceProvider.tokenFor(NavigationService), "Subtitle"));
    _pageView21.set_property_value(PageView.ContentKey, ServiceBinding(_pageView21, ServiceProvider.tokenFor(NavigationService), "Content"));
    _editorShell2.AddChild(_pageView21);
    _rd1.Root = _editorShell2;
    return _app0;
})();
