import { ContextMenuVM } from "./context-menu-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextAlignment, TextBlock } from "@pragmatic-tech-ai/mural/basic";
import { ContextMenu, ContextMenuService, MenuItem, MenuSeparator } from "@pragmatic-tech-ai/mural/framework/surface.js";
import { Color, DataContextBinding, DynamicResource, HorizontalAlignment, ResourceDictionary, Thickness, VerticalAlignment } from "@pragmatic-tech-ai/mural/runtime";
import { FontWeight, Pen, SolidColorBrush } from "@pragmatic-tech-ai/mural/visual-engine";


const _gate_ContextMenuDemo = Symbol("ContextMenuDemo.ctor");
export class ContextMenuDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_ContextMenuDemo) {
            throw new Error("ContextMenuDemo is private — use ContextMenuDemo.Clone()");
        }
    }
    static Clone() {
        const t = new ContextMenuDemo(_gate_ContextMenuDemo);
        const _contextMenu0 = new ContextMenu();
        const _menuItem1 = new MenuItem();
        _menuItem1.set_property_value(MenuItem.HeaderKey, "Cut");
        _menuItem1.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+X");
        _menuItem1.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem1, "RedCommand"));
        _menuItem1.set_property_value(MenuItem.CommandParameterKey, "Cut");
        _menuItem1.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "content_cut"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _contextMenu0.AddChild(_menuItem1);
        const _menuItem2 = new MenuItem();
        _menuItem2.set_property_value(MenuItem.HeaderKey, "Copy");
        _menuItem2.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+C");
        _menuItem2.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem2, "RedCommand"));
        _menuItem2.set_property_value(MenuItem.CommandParameterKey, "Copy");
        _menuItem2.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "content_copy"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _contextMenu0.AddChild(_menuItem2);
        const _menuItem3 = new MenuItem();
        _menuItem3.set_property_value(MenuItem.HeaderKey, "Paste");
        _menuItem3.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+V");
        _menuItem3.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem3, "RedCommand"));
        _menuItem3.set_property_value(MenuItem.CommandParameterKey, "Paste");
        _menuItem3.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "content_paste"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _contextMenu0.AddChild(_menuItem3);
        const _menuSeparator4 = new MenuSeparator();
        _contextMenu0.AddChild(_menuSeparator4);
        const _menuItem5 = new MenuItem();
        _menuItem5.set_property_value(MenuItem.HeaderKey, "Delete");
        _menuItem5.set_property_value(MenuItem.InputGestureTextKey, "Del");
        _menuItem5.set_property_value(MenuItem.IsEnabledKey, false);
        _menuItem5.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "delete"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _contextMenu0.AddChild(_menuItem5);
        const _menuSeparator6 = new MenuSeparator();
        _contextMenu0.AddChild(_menuSeparator6);
        const _menuItem7 = new MenuItem();
        _menuItem7.set_property_value(MenuItem.HeaderKey, "Transform");
        _menuItem7.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "transform"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        const _menuItem8 = new MenuItem();
        _menuItem8.set_property_value(MenuItem.HeaderKey, "Rotate 90°");
        _menuItem8.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem8, "RedCommand"));
        _menuItem8.set_property_value(MenuItem.CommandParameterKey, "Rotate 90°");
        _menuItem8.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "rotate_right"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _menuItem7.AddChild(_menuItem8);
        const _menuItem9 = new MenuItem();
        _menuItem9.set_property_value(MenuItem.HeaderKey, "Flip Horizontal");
        _menuItem9.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem9, "RedCommand"));
        _menuItem9.set_property_value(MenuItem.CommandParameterKey, "Flip Horizontal");
        _menuItem9.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "swap_horiz"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _menuItem7.AddChild(_menuItem9);
        const _menuItem10 = new MenuItem();
        _menuItem10.set_property_value(MenuItem.HeaderKey, "Flip Vertical");
        _menuItem10.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem10, "RedCommand"));
        _menuItem10.set_property_value(MenuItem.CommandParameterKey, "Flip Vertical");
        _menuItem10.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "swap_vert"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _menuItem7.AddChild(_menuItem10);
        _contextMenu0.AddChild(_menuItem7);
        t.Set("RedMenu", _contextMenu0);
        const _contextMenu11 = new ContextMenu();
        const _menuItem12 = new MenuItem();
        _menuItem12.set_property_value(MenuItem.HeaderKey, "Show Grid");
        _menuItem12.set_property_value(MenuItem.IsCheckableKey, true);
        _menuItem12.set_property_value(MenuItem.IsCheckedKey, DataContextBinding(_menuItem12, "ShowGrid"));
        _menuItem12.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem12, "ShowGridCommand"));
        _contextMenu11.AddChild(_menuItem12);
        const _menuItem13 = new MenuItem();
        _menuItem13.set_property_value(MenuItem.HeaderKey, "Snap to Grid");
        _menuItem13.set_property_value(MenuItem.IsCheckableKey, true);
        _menuItem13.set_property_value(MenuItem.IsCheckedKey, DataContextBinding(_menuItem13, "SnapToGrid"));
        _menuItem13.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem13, "SnapToGridCommand"));
        _contextMenu11.AddChild(_menuItem13);
        const _menuItem14 = new MenuItem();
        _menuItem14.set_property_value(MenuItem.HeaderKey, "Show Rulers");
        _menuItem14.set_property_value(MenuItem.IsCheckableKey, true);
        _menuItem14.set_property_value(MenuItem.IsCheckedKey, DataContextBinding(_menuItem14, "ShowRulers"));
        _menuItem14.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem14, "ShowRulersCommand"));
        _contextMenu11.AddChild(_menuItem14);
        const _menuSeparator15 = new MenuSeparator();
        _contextMenu11.AddChild(_menuSeparator15);
        const _menuItem16 = new MenuItem();
        _menuItem16.set_property_value(MenuItem.HeaderKey, "Zoom");
        _menuItem16.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "zoom_in"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        const _menuItem17 = new MenuItem();
        _menuItem17.set_property_value(MenuItem.HeaderKey, "50%");
        _menuItem17.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem17, "GreenCommand"));
        _menuItem17.set_property_value(MenuItem.CommandParameterKey, "Zoom 50%");
        _menuItem16.AddChild(_menuItem17);
        const _menuItem18 = new MenuItem();
        _menuItem18.set_property_value(MenuItem.HeaderKey, "100%");
        _menuItem18.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem18, "GreenCommand"));
        _menuItem18.set_property_value(MenuItem.CommandParameterKey, "Zoom 100%");
        _menuItem16.AddChild(_menuItem18);
        const _menuItem19 = new MenuItem();
        _menuItem19.set_property_value(MenuItem.HeaderKey, "200%");
        _menuItem19.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem19, "GreenCommand"));
        _menuItem19.set_property_value(MenuItem.CommandParameterKey, "Zoom 200%");
        _menuItem16.AddChild(_menuItem19);
        const _menuSeparator20 = new MenuSeparator();
        _menuItem16.AddChild(_menuSeparator20);
        const _menuItem21 = new MenuItem();
        _menuItem21.set_property_value(MenuItem.HeaderKey, "Fit to Window");
        _menuItem21.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+0");
        _menuItem21.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem21, "GreenCommand"));
        _menuItem21.set_property_value(MenuItem.CommandParameterKey, "Fit to Window");
        _menuItem21.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "fit_screen"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _menuItem16.AddChild(_menuItem21);
        _contextMenu11.AddChild(_menuItem16);
        t.Set("GreenMenu", _contextMenu11);
        const _contextMenu22 = new ContextMenu();
        const _menuItem23 = new MenuItem();
        _menuItem23.set_property_value(MenuItem.HeaderKey, "Open…");
        _menuItem23.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+O");
        _menuItem23.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem23, "BlueCommand"));
        _menuItem23.set_property_value(MenuItem.CommandParameterKey, "Open");
        _menuItem23.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "folder_open"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _contextMenu22.AddChild(_menuItem23);
        const _menuItem24 = new MenuItem();
        _menuItem24.set_property_value(MenuItem.HeaderKey, "Save");
        _menuItem24.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+S");
        _menuItem24.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem24, "BlueCommand"));
        _menuItem24.set_property_value(MenuItem.CommandParameterKey, "Save");
        _menuItem24.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "save"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _contextMenu22.AddChild(_menuItem24);
        const _menuSeparator25 = new MenuSeparator();
        _contextMenu22.AddChild(_menuSeparator25);
        const _menuItem26 = new MenuItem();
        _menuItem26.set_property_value(MenuItem.HeaderKey, "Share");
        _menuItem26.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "share"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        const _menuItem27 = new MenuItem();
        _menuItem27.set_property_value(MenuItem.HeaderKey, "Copy Link");
        _menuItem27.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem27, "BlueCommand"));
        _menuItem27.set_property_value(MenuItem.CommandParameterKey, "Copy Link");
        _menuItem27.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "link"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _menuItem26.AddChild(_menuItem27);
        const _menuItem28 = new MenuItem();
        _menuItem28.set_property_value(MenuItem.HeaderKey, "Email");
        _menuItem28.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem28, "BlueCommand"));
        _menuItem28.set_property_value(MenuItem.CommandParameterKey, "Email");
        _menuItem28.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "mail"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        _menuItem26.AddChild(_menuItem28);
        const _menuSeparator29 = new MenuSeparator();
        _menuItem26.AddChild(_menuSeparator29);
        const _menuItem30 = new MenuItem();
        _menuItem30.set_property_value(MenuItem.HeaderKey, "Export as");
        _menuItem30.set_property_value(MenuItem.IconKey, ((_e) => { _e.Text = "download"; _e.FontFamily = "Material Symbols Outlined"; _e.FontSize = 18; _e.Foreground = DynamicResource(_e, "OnSurfaceVariant"); _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new TextBlock()));
        const _menuItem31 = new MenuItem();
        _menuItem31.set_property_value(MenuItem.HeaderKey, "PNG image");
        _menuItem31.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem31, "BlueCommand"));
        _menuItem31.set_property_value(MenuItem.CommandParameterKey, "Export PNG");
        _menuItem30.AddChild(_menuItem31);
        const _menuItem32 = new MenuItem();
        _menuItem32.set_property_value(MenuItem.HeaderKey, "SVG vector");
        _menuItem32.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem32, "BlueCommand"));
        _menuItem32.set_property_value(MenuItem.CommandParameterKey, "Export SVG");
        _menuItem30.AddChild(_menuItem32);
        const _menuItem33 = new MenuItem();
        _menuItem33.set_property_value(MenuItem.HeaderKey, "PDF document");
        _menuItem33.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem33, "BlueCommand"));
        _menuItem33.set_property_value(MenuItem.CommandParameterKey, "Export PDF");
        _menuItem30.AddChild(_menuItem33);
        _menuItem26.AddChild(_menuItem30);
        _contextMenu22.AddChild(_menuItem26);
        const _menuSeparator34 = new MenuSeparator();
        _contextMenu22.AddChild(_menuSeparator34);
        const _menuItem35 = new MenuItem();
        _menuItem35.set_property_value(MenuItem.HeaderKey, "Bookmark");
        _menuItem35.set_property_value(MenuItem.IsCheckableKey, true);
        _menuItem35.set_property_value(MenuItem.IsCheckedKey, DataContextBinding(_menuItem35, "Bookmarked"));
        _menuItem35.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem35, "BookmarkCommand"));
        _contextMenu22.AddChild(_menuItem35);
        t.Set("BlueMenu", _contextMenu22);
        const _tmpl36 = new DataTemplate((_data) => {
            const _border37 = new Border();
            _border37.set_property_value(Border.FillKey, DynamicResource(_border37, "Surface"));
            _border37.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            const _dockPanel38 = new DockPanel();
            const _border39 = new Border();
            _border39.set_property_value(DockPanel.DockKey, Dock.Top);
            _border39.set_property_value(Border.FillKey, DynamicResource(_border39, "Primary"));
            _border39.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _textBlock40 = new TextBlock();
            _textBlock40.set_property_value(TextBlock.TextKey, "ContextMenu — right-click a panel to open its menu at the cursor. Each shows different features: icons, shortcuts, submenus, checkables.");
            _textBlock40.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock40.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock40.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock40, "OnPrimary"));
            _border39.SetChild(_textBlock40);
            _dockPanel38.AddChild(_border39);
            const _stackPanel41 = new StackPanel();
            _stackPanel41.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel41.set_property_value(StackPanel.MarginKey, new Thickness(16, 16, 16, 16));
            const _stackPanel42 = new StackPanel();
            _stackPanel42.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel42.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 16));
            const _border43 = new Border();
            _border43.set_property_value(Border.FillKey, new SolidColorBrush(Color.FromHex('#ef4444')));
            _border43.set_property_value(Border.WidthKey, 180);
            _border43.set_property_value(Border.HeightKey, 120);
            _border43.set_property_value(Border.MarginKey, new Thickness(0, 0, 12, 0));
            _border43.set_property_value(ContextMenuService.ContextMenuKey, DynamicResource(_border43, "RedMenu"));
            const _textBlock44 = new TextBlock();
            _textBlock44.set_property_value(TextBlock.TextKey, "Edit menu\nicons · shortcuts · disabled · submenu");
            _textBlock44.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock44, "OnPrimary"));
            _textBlock44.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock44.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock44.set_property_value(TextBlock.TextAlignmentKey, TextAlignment.Center);
            _textBlock44.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _textBlock44.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
            _border43.SetChild(_textBlock44);
            _stackPanel42.AddChild(_border43);
            const _border45 = new Border();
            _border45.set_property_value(Border.FillKey, new SolidColorBrush(Color.FromHex('#22c55e')));
            _border45.set_property_value(Border.WidthKey, 180);
            _border45.set_property_value(Border.HeightKey, 120);
            _border45.set_property_value(Border.MarginKey, new Thickness(0, 0, 12, 0));
            _border45.set_property_value(ContextMenuService.ContextMenuKey, DynamicResource(_border45, "GreenMenu"));
            const _textBlock46 = new TextBlock();
            _textBlock46.set_property_value(TextBlock.TextKey, "View menu\ncheckables · Zoom submenu");
            _textBlock46.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock46, "OnPrimary"));
            _textBlock46.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock46.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock46.set_property_value(TextBlock.TextAlignmentKey, TextAlignment.Center);
            _textBlock46.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _textBlock46.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
            _border45.SetChild(_textBlock46);
            _stackPanel42.AddChild(_border45);
            const _border47 = new Border();
            _border47.set_property_value(Border.FillKey, new SolidColorBrush(Color.FromHex('#3b82f6')));
            _border47.set_property_value(Border.WidthKey, 180);
            _border47.set_property_value(Border.HeightKey, 120);
            _border47.set_property_value(ContextMenuService.ContextMenuKey, DynamicResource(_border47, "BlueMenu"));
            const _textBlock48 = new TextBlock();
            _textBlock48.set_property_value(TextBlock.TextKey, "File menu\nnested Share ▸ Export submenu");
            _textBlock48.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock48, "OnPrimary"));
            _textBlock48.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock48.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock48.set_property_value(TextBlock.TextAlignmentKey, TextAlignment.Center);
            _textBlock48.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _textBlock48.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
            _border47.SetChild(_textBlock48);
            _stackPanel42.AddChild(_border47);
            _stackPanel41.AddChild(_stackPanel42);
            const _textBlock49 = new TextBlock();
            _textBlock49.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock49, "Status"));
            _textBlock49.set_property_value(TextBlock.FontSizeKey, 13);
            _textBlock49.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock49, "OnSurface"));
            _stackPanel41.AddChild(_textBlock49);
            _dockPanel38.AddChild(_stackPanel41);
            _border37.SetChild(_dockPanel38);
            return _border37;
        }, ContextMenuVM);
        t.Set(ContextMenuVM, _tmpl36);
        return t;
    }
    get RedMenu() { return this.Resolve("RedMenu"); }
    set RedMenu(v) { this.Set("RedMenu", v); }
    get GreenMenu() { return this.Resolve("GreenMenu"); }
    set GreenMenu(v) { this.Set("GreenMenu", v); }
    get BlueMenu() { return this.Resolve("BlueMenu"); }
    set BlueMenu(v) { this.Set("BlueMenu", v); }
}
