import { ContextMenuVM } from "./context-menu-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Basic";
import { ContextMenu, ContextMenuService, MenuItem, MenuSeparator } from "@visualisation-sub/mural/framework/surface.js";
import { Color, DataContextBinding, DynamicResource, HorizontalAlignment, ResourceDictionary, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _contextMenu1 = new ContextMenu();
    const _menuItem2 = new MenuItem();
    _menuItem2._set_property_value_by_name("Header", "Red — Cut");
    _menuItem2._set_property_value_by_name("Command", DataContextBinding(_menuItem2, "RedCommand"));
    _menuItem2._set_property_value_by_name("CommandParameter", "Cut");
    _contextMenu1.AddChild(_menuItem2);
    const _menuItem3 = new MenuItem();
    _menuItem3._set_property_value_by_name("Header", "Red — Copy");
    _menuItem3._set_property_value_by_name("Command", DataContextBinding(_menuItem3, "RedCommand"));
    _menuItem3._set_property_value_by_name("CommandParameter", "Copy");
    _contextMenu1.AddChild(_menuItem3);
    const _menuSeparator4 = new MenuSeparator();
    _contextMenu1.AddChild(_menuSeparator4);
    const _menuItem5 = new MenuItem();
    _menuItem5._set_property_value_by_name("Header", "Red — Delete");
    _menuItem5._set_property_value_by_name("Command", DataContextBinding(_menuItem5, "RedCommand"));
    _menuItem5._set_property_value_by_name("CommandParameter", "Delete");
    _contextMenu1.AddChild(_menuItem5);
    _rd0.Set("RedMenu", _contextMenu1);
    const _contextMenu6 = new ContextMenu();
    const _menuItem7 = new MenuItem();
    _menuItem7._set_property_value_by_name("Header", "Green — Inspect");
    _menuItem7._set_property_value_by_name("Command", DataContextBinding(_menuItem7, "GreenCommand"));
    _menuItem7._set_property_value_by_name("CommandParameter", "Inspect");
    _contextMenu6.AddChild(_menuItem7);
    const _menuItem8 = new MenuItem();
    _menuItem8._set_property_value_by_name("Header", "Green — Highlight");
    _menuItem8._set_property_value_by_name("Command", DataContextBinding(_menuItem8, "GreenCommand"));
    _menuItem8._set_property_value_by_name("CommandParameter", "Highlight");
    _contextMenu6.AddChild(_menuItem8);
    const _menuSeparator9 = new MenuSeparator();
    _contextMenu6.AddChild(_menuSeparator9);
    const _menuItem10 = new MenuItem();
    _menuItem10._set_property_value_by_name("Header", "Green — Rename");
    _menuItem10._set_property_value_by_name("Command", DataContextBinding(_menuItem10, "GreenCommand"));
    _menuItem10._set_property_value_by_name("CommandParameter", "Rename");
    _contextMenu6.AddChild(_menuItem10);
    _rd0.Set("GreenMenu", _contextMenu6);
    const _contextMenu11 = new ContextMenu();
    const _menuItem12 = new MenuItem();
    _menuItem12._set_property_value_by_name("Header", "Blue — Open");
    _menuItem12._set_property_value_by_name("Command", DataContextBinding(_menuItem12, "BlueCommand"));
    _menuItem12._set_property_value_by_name("CommandParameter", "Open");
    _contextMenu11.AddChild(_menuItem12);
    const _menuItem13 = new MenuItem();
    _menuItem13._set_property_value_by_name("Header", "Blue — Bookmark");
    _menuItem13._set_property_value_by_name("Command", DataContextBinding(_menuItem13, "BlueCommand"));
    _menuItem13._set_property_value_by_name("CommandParameter", "Bookmark");
    _contextMenu11.AddChild(_menuItem13);
    const _menuSeparator14 = new MenuSeparator();
    _contextMenu11.AddChild(_menuSeparator14);
    const _menuItem15 = new MenuItem();
    _menuItem15._set_property_value_by_name("Header", "Blue — Share");
    _menuItem15._set_property_value_by_name("Command", DataContextBinding(_menuItem15, "BlueCommand"));
    _menuItem15._set_property_value_by_name("CommandParameter", "Share");
    _contextMenu11.AddChild(_menuItem15);
    _rd0.Set("BlueMenu", _contextMenu11);
    const _tmpl16 = new DataTemplate((_data) => {
        const _border17 = new Border();
        _border17._set_property_value_by_name("Background", DynamicResource(_border17, "Surface"));
        _border17._set_property_value_by_name("BorderBrush", DynamicResource(_border17, "OutlineVariant"));
        _border17._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel18 = new DockPanel();
        const _border19 = new Border();
        _border19._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border19._set_property_value_by_name("Background", DynamicResource(_border19, "Primary"));
        _border19._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "ContextMenu — right-click any panel; the nearest ancestor's menu opens at the cursor.");
        _textBlock20._set_property_value_by_name("FontSize", 15);
        _textBlock20._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock20._set_property_value_by_name("Foreground", DynamicResource(_textBlock20, "OnPrimary"));
        _border19.SetChild(_textBlock20);
        _dockPanel18.AddChild(_border19);
        const _stackPanel21 = new StackPanel();
        _stackPanel21._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel21._set_property_value_by_name("Margin", new Thickness(16, 16, 16, 16));
        const _stackPanel22 = new StackPanel();
        _stackPanel22._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel22._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
        const _border23 = new Border();
        _border23._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ef4444')));
        _border23._set_property_value_by_name("Width", 180);
        _border23._set_property_value_by_name("Height", 120);
        _border23._set_property_value_by_name("Margin", new Thickness(0, 0, 12, 0));
        _border23._set_property_value_by_name(ContextMenuService, "ContextMenu", DynamicResource(_border23, "RedMenu"));
        const _textBlock24 = new TextBlock();
        _textBlock24._set_property_value_by_name("Text", "Right-click me");
        _textBlock24._set_property_value_by_name("Foreground", DynamicResource(_textBlock24, "OnPrimary"));
        _textBlock24._set_property_value_by_name("FontSize", 14);
        _textBlock24._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock24._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
        _textBlock24._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
        _border23.SetChild(_textBlock24);
        _stackPanel22.AddChild(_border23);
        const _border25 = new Border();
        _border25._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#22c55e')));
        _border25._set_property_value_by_name("Width", 180);
        _border25._set_property_value_by_name("Height", 120);
        _border25._set_property_value_by_name("Margin", new Thickness(0, 0, 12, 0));
        _border25._set_property_value_by_name(ContextMenuService, "ContextMenu", DynamicResource(_border25, "GreenMenu"));
        const _textBlock26 = new TextBlock();
        _textBlock26._set_property_value_by_name("Text", "Right-click me");
        _textBlock26._set_property_value_by_name("Foreground", DynamicResource(_textBlock26, "OnPrimary"));
        _textBlock26._set_property_value_by_name("FontSize", 14);
        _textBlock26._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock26._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
        _textBlock26._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
        _border25.SetChild(_textBlock26);
        _stackPanel22.AddChild(_border25);
        const _border27 = new Border();
        _border27._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#3b82f6')));
        _border27._set_property_value_by_name("Width", 180);
        _border27._set_property_value_by_name("Height", 120);
        _border27._set_property_value_by_name(ContextMenuService, "ContextMenu", DynamicResource(_border27, "BlueMenu"));
        const _textBlock28 = new TextBlock();
        _textBlock28._set_property_value_by_name("Text", "Right-click me");
        _textBlock28._set_property_value_by_name("Foreground", DynamicResource(_textBlock28, "OnPrimary"));
        _textBlock28._set_property_value_by_name("FontSize", 14);
        _textBlock28._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock28._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
        _textBlock28._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
        _border27.SetChild(_textBlock28);
        _stackPanel22.AddChild(_border27);
        _stackPanel21.AddChild(_stackPanel22);
        const _textBlock29 = new TextBlock();
        _textBlock29._set_property_value_by_name("Text", DataContextBinding(_textBlock29, "Status"));
        _textBlock29._set_property_value_by_name("FontSize", 13);
        _textBlock29._set_property_value_by_name("Foreground", DynamicResource(_textBlock29, "OnSurface"));
        _stackPanel21.AddChild(_textBlock29);
        _dockPanel18.AddChild(_stackPanel21);
        _border17.SetChild(_dockPanel18);
        return _border17;
    }, ContextMenuVM);
    _rd0.Set("ContextMenuTemplate", _tmpl16);
    return _rd0;
}
