import { IconButtonVM } from "./icon-button-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, Shape, StackPanel, TextBlock } from "@visualisation-sub/mural/basic";
import { ButtonVariant } from "@visualisation-sub/mural/framework/buttons/button.js";
import { IconButtonToggle } from "@visualisation-sub/mural/framework/buttons/icon-button-toggle.js";
import { IconButton } from "@visualisation-sub/mural/framework/buttons/icon-button.js";
import { DataContextBinding, DynamicResource, ResourceDictionary, SelfBinding, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, LineSegment, PathFigure, PathGeometry, Point, QuadraticBezierSegment } from "@visualisation-sub/mural/visual-engine";


const _gate_IconButtonDemo = Symbol("IconButtonDemo.ctor");
export class IconButtonDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_IconButtonDemo) {
            throw new Error("IconButtonDemo is private — use IconButtonDemo.Clone()");
        }
    }
    static Clone() {
        const t = new IconButtonDemo(_gate_IconButtonDemo);
        t.Set("check", new PathGeometry([new PathFigure(new Point(806, -664), [new LineSegment(new Point(382, -240)), new LineSegment(new Point(154, -468)), new LineSegment(new Point(211, -525)), new LineSegment(new Point(382, -354)), new LineSegment(new Point(749, -721)), new LineSegment(new Point(806, -664))], true)]));
        t.Set("star", new PathGeometry([new PathFigure(new Point(387, -430), [new LineSegment(new Point(354, -287)), new LineSegment(new Point(480, -363)), new LineSegment(new Point(606, -286)), new LineSegment(new Point(573, -430)), new LineSegment(new Point(684, -526)), new LineSegment(new Point(538, -539)), new LineSegment(new Point(480, -675)), new LineSegment(new Point(422, -540)), new LineSegment(new Point(276, -527)), new LineSegment(new Point(387, -430))], true), new PathFigure(new Point(480, -269), [new LineSegment(new Point(233, -120)), new LineSegment(new Point(298, -401)), new LineSegment(new Point(80, -590)), new LineSegment(new Point(368, -615)), new LineSegment(new Point(480, -880)), new LineSegment(new Point(592, -615)), new LineSegment(new Point(880, -590)), new LineSegment(new Point(662, -401)), new LineSegment(new Point(727, -120)), new LineSegment(new Point(480, -269))], true), new PathFigure(new Point(480, -470), [new LineSegment(new Point(480, -470)), new LineSegment(new Point(480, -470)), new LineSegment(new Point(480, -470)), new LineSegment(new Point(480, -470)), new LineSegment(new Point(480, -470)), new LineSegment(new Point(480, -470)), new LineSegment(new Point(480, -470)), new LineSegment(new Point(480, -470)), new LineSegment(new Point(480, -470)), new LineSegment(new Point(480, -470))], true)]));
        t.Set("north_east", new PathGeometry([new PathFigure(new Point(680, -624), [new LineSegment(new Point(216, -160)), new LineSegment(new Point(160, -216)), new LineSegment(new Point(624, -680)), new LineSegment(new Point(360, -680)), new LineSegment(new Point(360, -760)), new LineSegment(new Point(760, -760)), new LineSegment(new Point(760, -360)), new LineSegment(new Point(680, -360)), new LineSegment(new Point(680, -624))], true)]));
        t.Set("more_horiz", new PathGeometry([new PathFigure(new Point(240, -400), [new LineSegment(new Point(240, -400)), new QuadraticBezierSegment(new Point(207, -400), new Point(183.5, -423.5)), new QuadraticBezierSegment(new Point(160, -447), new Point(160, -480)), new LineSegment(new Point(160, -480)), new QuadraticBezierSegment(new Point(160, -513), new Point(183.5, -536.5)), new QuadraticBezierSegment(new Point(207, -560), new Point(240, -560)), new LineSegment(new Point(240, -560)), new QuadraticBezierSegment(new Point(273, -560), new Point(296.5, -536.5)), new QuadraticBezierSegment(new Point(320, -513), new Point(320, -480)), new LineSegment(new Point(320, -480)), new QuadraticBezierSegment(new Point(320, -447), new Point(296.5, -423.5)), new QuadraticBezierSegment(new Point(273, -400), new Point(240, -400))], true), new PathFigure(new Point(480, -400), [new LineSegment(new Point(480, -400)), new QuadraticBezierSegment(new Point(447, -400), new Point(423.5, -423.5)), new QuadraticBezierSegment(new Point(400, -447), new Point(400, -480)), new LineSegment(new Point(400, -480)), new QuadraticBezierSegment(new Point(400, -513), new Point(423.5, -536.5)), new QuadraticBezierSegment(new Point(447, -560), new Point(480, -560)), new LineSegment(new Point(480, -560)), new QuadraticBezierSegment(new Point(513, -560), new Point(536.5, -536.5)), new QuadraticBezierSegment(new Point(560, -513), new Point(560, -480)), new LineSegment(new Point(560, -480)), new QuadraticBezierSegment(new Point(560, -447), new Point(536.5, -423.5)), new QuadraticBezierSegment(new Point(513, -400), new Point(480, -400))], true), new PathFigure(new Point(720, -400), [new LineSegment(new Point(720, -400)), new QuadraticBezierSegment(new Point(687, -400), new Point(663.5, -423.5)), new QuadraticBezierSegment(new Point(640, -447), new Point(640, -480)), new LineSegment(new Point(640, -480)), new QuadraticBezierSegment(new Point(640, -513), new Point(663.5, -536.5)), new QuadraticBezierSegment(new Point(687, -560), new Point(720, -560)), new LineSegment(new Point(720, -560)), new QuadraticBezierSegment(new Point(753, -560), new Point(776.5, -536.5)), new QuadraticBezierSegment(new Point(800, -513), new Point(800, -480)), new LineSegment(new Point(800, -480)), new QuadraticBezierSegment(new Point(800, -447), new Point(776.5, -423.5)), new QuadraticBezierSegment(new Point(753, -400), new Point(720, -400))], true)]));
        t.Set("favorite", new PathGeometry([new PathFigure(new Point(538, -172), [new LineSegment(new Point(480, -120)), new LineSegment(new Point(422, -172)), new QuadraticBezierSegment(new Point(321, -263), new Point(255, -329)), new QuadraticBezierSegment(new Point(189, -395), new Point(150, -447.5)), new QuadraticBezierSegment(new Point(111, -500), new Point(95.5, -544)), new QuadraticBezierSegment(new Point(80, -588), new Point(80, -634)), new LineSegment(new Point(80, -634)), new QuadraticBezierSegment(new Point(80, -728), new Point(143, -791)), new QuadraticBezierSegment(new Point(206, -854), new Point(300, -854)), new LineSegment(new Point(300, -854)), new QuadraticBezierSegment(new Point(352, -854), new Point(399, -832)), new QuadraticBezierSegment(new Point(446, -810), new Point(480, -770)), new LineSegment(new Point(480, -770)), new QuadraticBezierSegment(new Point(514, -810), new Point(561, -832)), new QuadraticBezierSegment(new Point(608, -854), new Point(660, -854)), new LineSegment(new Point(660, -854)), new QuadraticBezierSegment(new Point(754, -854), new Point(817, -791)), new QuadraticBezierSegment(new Point(880, -728), new Point(880, -634)), new LineSegment(new Point(880, -634)), new QuadraticBezierSegment(new Point(880, -588), new Point(864.5, -544)), new QuadraticBezierSegment(new Point(849, -500), new Point(810, -447.5)), new QuadraticBezierSegment(new Point(771, -395), new Point(705, -329)), new QuadraticBezierSegment(new Point(639, -263), new Point(538, -172)), new LineSegment(new Point(538, -172))], true), new PathFigure(new Point(480, -228), [new LineSegment(new Point(480, -228)), new QuadraticBezierSegment(new Point(576, -314), new Point(638, -375.5)), new QuadraticBezierSegment(new Point(700, -437), new Point(736, -482.5)), new QuadraticBezierSegment(new Point(772, -528), new Point(786, -563.5)), new QuadraticBezierSegment(new Point(800, -599), new Point(800, -634)), new LineSegment(new Point(800, -634)), new QuadraticBezierSegment(new Point(800, -694), new Point(760, -734)), new QuadraticBezierSegment(new Point(720, -774), new Point(660, -774)), new LineSegment(new Point(660, -774)), new QuadraticBezierSegment(new Point(613, -774), new Point(573, -747.5)), new QuadraticBezierSegment(new Point(533, -721), new Point(518, -680)), new LineSegment(new Point(518, -680)), new LineSegment(new Point(518, -680)), new LineSegment(new Point(442, -680)), new LineSegment(new Point(442, -680)), new QuadraticBezierSegment(new Point(427, -721), new Point(387, -747.5)), new QuadraticBezierSegment(new Point(347, -774), new Point(300, -774)), new LineSegment(new Point(300, -774)), new QuadraticBezierSegment(new Point(240, -774), new Point(200, -734)), new QuadraticBezierSegment(new Point(160, -694), new Point(160, -634)), new LineSegment(new Point(160, -634)), new QuadraticBezierSegment(new Point(160, -599), new Point(174, -563.5)), new QuadraticBezierSegment(new Point(188, -528), new Point(224, -482.5)), new QuadraticBezierSegment(new Point(260, -437), new Point(322, -375.5)), new QuadraticBezierSegment(new Point(384, -314), new Point(480, -228))], true), new PathFigure(new Point(480, -501), [new LineSegment(new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new LineSegment(new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new LineSegment(new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new LineSegment(new Point(480, -501)), new LineSegment(new Point(480, -501)), new LineSegment(new Point(480, -501)), new LineSegment(new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new LineSegment(new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new LineSegment(new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501)), new QuadraticBezierSegment(new Point(480, -501), new Point(480, -501))], true)]));
        t.Set("notifications", new PathGeometry([new PathFigure(new Point(800, -200), [new LineSegment(new Point(160, -200)), new LineSegment(new Point(160, -280)), new LineSegment(new Point(240, -280)), new LineSegment(new Point(240, -560)), new QuadraticBezierSegment(new Point(240, -643), new Point(290, -707.5)), new QuadraticBezierSegment(new Point(340, -772), new Point(420, -792)), new LineSegment(new Point(420, -792)), new LineSegment(new Point(420, -820)), new QuadraticBezierSegment(new Point(420, -845), new Point(437.5, -862.5)), new QuadraticBezierSegment(new Point(455, -880), new Point(480, -880)), new QuadraticBezierSegment(new Point(505, -880), new Point(522.5, -862.5)), new QuadraticBezierSegment(new Point(540, -845), new Point(540, -820)), new LineSegment(new Point(540, -820)), new LineSegment(new Point(540, -792)), new QuadraticBezierSegment(new Point(620, -772), new Point(670, -707.5)), new QuadraticBezierSegment(new Point(720, -643), new Point(720, -560)), new LineSegment(new Point(720, -560)), new LineSegment(new Point(720, -280)), new LineSegment(new Point(800, -280)), new LineSegment(new Point(800, -200))], true), new PathFigure(new Point(480, -500), [new LineSegment(new Point(480, -500)), new LineSegment(new Point(480, -500)), new LineSegment(new Point(480, -500)), new LineSegment(new Point(480, -500)), new QuadraticBezierSegment(new Point(480, -500), new Point(480, -500)), new QuadraticBezierSegment(new Point(480, -500), new Point(480, -500)), new QuadraticBezierSegment(new Point(480, -500), new Point(480, -500)), new QuadraticBezierSegment(new Point(480, -500), new Point(480, -500))], true), new PathFigure(new Point(480, -80), [new LineSegment(new Point(480, -80)), new QuadraticBezierSegment(new Point(447, -80), new Point(423.5, -103.5)), new QuadraticBezierSegment(new Point(400, -127), new Point(400, -160)), new LineSegment(new Point(400, -160)), new LineSegment(new Point(560, -160)), new QuadraticBezierSegment(new Point(560, -127), new Point(536.5, -103.5)), new QuadraticBezierSegment(new Point(513, -80), new Point(480, -80))], true), new PathFigure(new Point(320, -560), [new LineSegment(new Point(320, -280)), new LineSegment(new Point(640, -280)), new LineSegment(new Point(640, -560)), new QuadraticBezierSegment(new Point(640, -626), new Point(593, -673)), new QuadraticBezierSegment(new Point(546, -720), new Point(480, -720)), new QuadraticBezierSegment(new Point(414, -720), new Point(367, -673)), new QuadraticBezierSegment(new Point(320, -626), new Point(320, -560)), new LineSegment(new Point(320, -560))], true)]));
        t.Set("dark_mode", new PathGeometry([new PathFigure(new Point(480, -120), [new LineSegment(new Point(480, -120)), new QuadraticBezierSegment(new Point(330, -120), new Point(225, -225)), new QuadraticBezierSegment(new Point(120, -330), new Point(120, -480)), new LineSegment(new Point(120, -480)), new QuadraticBezierSegment(new Point(120, -630), new Point(225, -735)), new QuadraticBezierSegment(new Point(330, -840), new Point(480, -840)), new LineSegment(new Point(480, -840)), new QuadraticBezierSegment(new Point(494, -840), new Point(507.5, -839)), new QuadraticBezierSegment(new Point(521, -838), new Point(534, -836)), new LineSegment(new Point(534, -836)), new QuadraticBezierSegment(new Point(493, -807), new Point(468.5, -760.5)), new QuadraticBezierSegment(new Point(444, -714), new Point(444, -660)), new LineSegment(new Point(444, -660)), new QuadraticBezierSegment(new Point(444, -570), new Point(507, -507)), new QuadraticBezierSegment(new Point(570, -444), new Point(660, -444)), new LineSegment(new Point(660, -444)), new QuadraticBezierSegment(new Point(715, -444), new Point(761, -468.5)), new QuadraticBezierSegment(new Point(807, -493), new Point(836, -534)), new LineSegment(new Point(836, -534)), new QuadraticBezierSegment(new Point(838, -521), new Point(839, -507.5)), new QuadraticBezierSegment(new Point(840, -494), new Point(840, -480)), new LineSegment(new Point(840, -480)), new QuadraticBezierSegment(new Point(840, -330), new Point(735, -225)), new QuadraticBezierSegment(new Point(630, -120), new Point(480, -120))], true), new PathFigure(new Point(480, -200), [new LineSegment(new Point(480, -200)), new QuadraticBezierSegment(new Point(568, -200), new Point(638, -248.5)), new QuadraticBezierSegment(new Point(708, -297), new Point(740, -375)), new LineSegment(new Point(740, -375)), new QuadraticBezierSegment(new Point(720, -370), new Point(700, -367)), new QuadraticBezierSegment(new Point(680, -364), new Point(660, -364)), new LineSegment(new Point(660, -364)), new QuadraticBezierSegment(new Point(537, -364), new Point(450.5, -450.5)), new QuadraticBezierSegment(new Point(364, -537), new Point(364, -660)), new LineSegment(new Point(364, -660)), new QuadraticBezierSegment(new Point(364, -680), new Point(367, -700)), new QuadraticBezierSegment(new Point(370, -720), new Point(375, -740)), new LineSegment(new Point(375, -740)), new QuadraticBezierSegment(new Point(297, -708), new Point(248.5, -638)), new QuadraticBezierSegment(new Point(200, -568), new Point(200, -480)), new LineSegment(new Point(200, -480)), new QuadraticBezierSegment(new Point(200, -364), new Point(282, -282)), new QuadraticBezierSegment(new Point(364, -200), new Point(480, -200))], true), new PathFigure(new Point(470, -470), [new LineSegment(new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new LineSegment(new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new LineSegment(new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new LineSegment(new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new LineSegment(new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new LineSegment(new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470)), new QuadraticBezierSegment(new Point(470, -470), new Point(470, -470))], true)]));
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.set_property_value(Border.BackgroundKey, DynamicResource(_border1, "Surface"));
            _border1.set_property_value(Border.BorderBrushKey, DynamicResource(_border1, "OutlineVariant"));
            _border1.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.BackgroundKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4.set_property_value(TextBlock.TextKey, "IconButton — M3's compact square button. Four variants drive the chrome via Button.Variant.");
            _textBlock4.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock4.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock4.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel5.set_property_value(StackPanel.MarginKey, new Thickness(24, 24, 24, 24));
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "IconButton — Variant: Filled / Tonal / Outlined / Standard");
            _textBlock6.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock6.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock6, "OnSurface"));
            _textBlock6.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 12));
            _stackPanel5.AddChild(_textBlock6);
            const _stackPanel7 = new StackPanel();
            _stackPanel7.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel7.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 8));
            const _iconButton8 = new IconButton();
            _iconButton8.set_property_value(IconButton.VariantKey, ButtonVariant.Filled);
            _iconButton8.set_property_value(IconButton.CommandKey, DataContextBinding(_iconButton8, "ClickFilledCommand"));
            const _shape9 = new Shape();
            _shape9.set_property_value(Shape.GeometryKey, DynamicResource(_shape9, "check"));
            _shape9.set_property_value(Shape.FillKey, SelfBinding(_shape9, TextBlock, "Foreground"));
            _shape9.set_property_value(Shape.WidthKey, 20);
            _shape9.set_property_value(Shape.HeightKey, 20);
            _iconButton8.Content = _shape9;
            _stackPanel7.AddChild(_iconButton8);
            const _iconButton10 = new IconButton();
            _iconButton10.set_property_value(IconButton.VariantKey, ButtonVariant.Tonal);
            _iconButton10.set_property_value(IconButton.CommandKey, DataContextBinding(_iconButton10, "ClickTonalCommand"));
            const _shape11 = new Shape();
            _shape11.set_property_value(Shape.GeometryKey, DynamicResource(_shape11, "star"));
            _shape11.set_property_value(Shape.FillKey, SelfBinding(_shape11, TextBlock, "Foreground"));
            _shape11.set_property_value(Shape.WidthKey, 20);
            _shape11.set_property_value(Shape.HeightKey, 20);
            _iconButton10.Content = _shape11;
            _stackPanel7.AddChild(_iconButton10);
            const _iconButton12 = new IconButton();
            _iconButton12.set_property_value(IconButton.VariantKey, ButtonVariant.Outlined);
            _iconButton12.set_property_value(IconButton.CommandKey, DataContextBinding(_iconButton12, "ClickOutlinedCommand"));
            const _shape13 = new Shape();
            _shape13.set_property_value(Shape.GeometryKey, DynamicResource(_shape13, "north_east"));
            _shape13.set_property_value(Shape.FillKey, SelfBinding(_shape13, TextBlock, "Foreground"));
            _shape13.set_property_value(Shape.WidthKey, 20);
            _shape13.set_property_value(Shape.HeightKey, 20);
            _iconButton12.Content = _shape13;
            _stackPanel7.AddChild(_iconButton12);
            const _iconButton14 = new IconButton();
            _iconButton14.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton14.set_property_value(IconButton.CommandKey, DataContextBinding(_iconButton14, "ClickStandardCommand"));
            const _shape15 = new Shape();
            _shape15.set_property_value(Shape.GeometryKey, DynamicResource(_shape15, "more_horiz"));
            _shape15.set_property_value(Shape.FillKey, SelfBinding(_shape15, TextBlock, "Foreground"));
            _shape15.set_property_value(Shape.WidthKey, 20);
            _shape15.set_property_value(Shape.HeightKey, 20);
            _iconButton14.Content = _shape15;
            _stackPanel7.AddChild(_iconButton14);
            _stackPanel5.AddChild(_stackPanel7);
            const _stackPanel16 = new StackPanel();
            _stackPanel16.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel16.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "Clicks — Filled: ");
            _textBlock17.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock17.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock17, "OnSurfaceVariant"));
            _stackPanel16.AddChild(_textBlock17);
            const _textBlock18 = new TextBlock();
            _textBlock18.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock18, "FilledClicks"));
            _textBlock18.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock18.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock18.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock18, "OnSurface"));
            _stackPanel16.AddChild(_textBlock18);
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "  Tonal: ");
            _textBlock19.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock19.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock19, "OnSurfaceVariant"));
            _stackPanel16.AddChild(_textBlock19);
            const _textBlock20 = new TextBlock();
            _textBlock20.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock20, "TonalClicks"));
            _textBlock20.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock20.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock20.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock20, "OnSurface"));
            _stackPanel16.AddChild(_textBlock20);
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "  Outlined: ");
            _textBlock21.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock21.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock21, "OnSurfaceVariant"));
            _stackPanel16.AddChild(_textBlock21);
            const _textBlock22 = new TextBlock();
            _textBlock22.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock22, "OutlinedClicks"));
            _textBlock22.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock22.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock22.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock22, "OnSurface"));
            _stackPanel16.AddChild(_textBlock22);
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, "  Standard: ");
            _textBlock23.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock23.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock23, "OnSurfaceVariant"));
            _stackPanel16.AddChild(_textBlock23);
            const _textBlock24 = new TextBlock();
            _textBlock24.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock24, "StandardClicks"));
            _textBlock24.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock24.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock24.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock24, "OnSurface"));
            _stackPanel16.AddChild(_textBlock24);
            _stackPanel5.AddChild(_stackPanel16);
            const _textBlock25 = new TextBlock();
            _textBlock25.set_property_value(TextBlock.TextKey, "IconButtonToggle — same Variant set; IsChecked flips Background + glyph ink.");
            _textBlock25.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock25.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock25.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock25, "OnSurface"));
            _textBlock25.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 12));
            _stackPanel5.AddChild(_textBlock25);
            const _stackPanel26 = new StackPanel();
            _stackPanel26.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel26.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel26.set_property_value(TextBlock.ForegroundKey, DynamicResource(_stackPanel26, "OnSurface"));
            const _iconButtonToggle27 = new IconButtonToggle();
            _iconButtonToggle27.set_property_value(IconButtonToggle.VariantKey, ButtonVariant.Filled);
            _iconButtonToggle27.set_property_value(IconButtonToggle.IsCheckedKey, DataContextBinding(_iconButtonToggle27, "FilledChecked"));
            const _shape28 = new Shape();
            _shape28.set_property_value(Shape.GeometryKey, DynamicResource(_shape28, "favorite"));
            _shape28.set_property_value(Shape.FillKey, SelfBinding(_shape28, TextBlock, "Foreground"));
            _shape28.set_property_value(Shape.WidthKey, 20);
            _shape28.set_property_value(Shape.HeightKey, 20);
            _iconButtonToggle27.Content = _shape28;
            _stackPanel26.AddChild(_iconButtonToggle27);
            const _iconButtonToggle29 = new IconButtonToggle();
            _iconButtonToggle29.set_property_value(IconButtonToggle.VariantKey, ButtonVariant.Tonal);
            _iconButtonToggle29.set_property_value(IconButtonToggle.IsCheckedKey, DataContextBinding(_iconButtonToggle29, "TonalChecked"));
            const _shape30 = new Shape();
            _shape30.set_property_value(Shape.GeometryKey, DynamicResource(_shape30, "star"));
            _shape30.set_property_value(Shape.FillKey, SelfBinding(_shape30, TextBlock, "Foreground"));
            _shape30.set_property_value(Shape.WidthKey, 20);
            _shape30.set_property_value(Shape.HeightKey, 20);
            _iconButtonToggle29.Content = _shape30;
            _stackPanel26.AddChild(_iconButtonToggle29);
            const _iconButtonToggle31 = new IconButtonToggle();
            _iconButtonToggle31.set_property_value(IconButtonToggle.VariantKey, ButtonVariant.Outlined);
            _iconButtonToggle31.set_property_value(IconButtonToggle.IsCheckedKey, DataContextBinding(_iconButtonToggle31, "OutlinedChecked"));
            const _shape32 = new Shape();
            _shape32.set_property_value(Shape.GeometryKey, DynamicResource(_shape32, "notifications"));
            _shape32.set_property_value(Shape.FillKey, SelfBinding(_shape32, TextBlock, "Foreground"));
            _shape32.set_property_value(Shape.WidthKey, 20);
            _shape32.set_property_value(Shape.HeightKey, 20);
            _iconButtonToggle31.Content = _shape32;
            _stackPanel26.AddChild(_iconButtonToggle31);
            const _iconButtonToggle33 = new IconButtonToggle();
            _iconButtonToggle33.set_property_value(IconButtonToggle.VariantKey, ButtonVariant.Standard);
            _iconButtonToggle33.set_property_value(IconButtonToggle.IsCheckedKey, DataContextBinding(_iconButtonToggle33, "StandardChecked"));
            const _shape34 = new Shape();
            _shape34.set_property_value(Shape.GeometryKey, DynamicResource(_shape34, "dark_mode"));
            _shape34.set_property_value(Shape.FillKey, SelfBinding(_shape34, TextBlock, "Foreground"));
            _shape34.set_property_value(Shape.WidthKey, 20);
            _shape34.set_property_value(Shape.HeightKey, 20);
            _iconButtonToggle33.Content = _shape34;
            _stackPanel26.AddChild(_iconButtonToggle33);
            _stackPanel5.AddChild(_stackPanel26);
            const _stackPanel35 = new StackPanel();
            _stackPanel35.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _textBlock36 = new TextBlock();
            _textBlock36.set_property_value(TextBlock.TextKey, "Checked — Filled: ");
            _textBlock36.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock36.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock36, "OnSurfaceVariant"));
            _stackPanel35.AddChild(_textBlock36);
            const _textBlock37 = new TextBlock();
            _textBlock37.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock37, "FilledChecked"));
            _textBlock37.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock37.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock37.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock37, "OnSurface"));
            _stackPanel35.AddChild(_textBlock37);
            const _textBlock38 = new TextBlock();
            _textBlock38.set_property_value(TextBlock.TextKey, "  Tonal: ");
            _textBlock38.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock38.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock38, "OnSurfaceVariant"));
            _stackPanel35.AddChild(_textBlock38);
            const _textBlock39 = new TextBlock();
            _textBlock39.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock39, "TonalChecked"));
            _textBlock39.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock39.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock39.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock39, "OnSurface"));
            _stackPanel35.AddChild(_textBlock39);
            const _textBlock40 = new TextBlock();
            _textBlock40.set_property_value(TextBlock.TextKey, "  Outlined: ");
            _textBlock40.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock40.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock40, "OnSurfaceVariant"));
            _stackPanel35.AddChild(_textBlock40);
            const _textBlock41 = new TextBlock();
            _textBlock41.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock41, "OutlinedChecked"));
            _textBlock41.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock41.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock41.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock41, "OnSurface"));
            _stackPanel35.AddChild(_textBlock41);
            const _textBlock42 = new TextBlock();
            _textBlock42.set_property_value(TextBlock.TextKey, "  Standard: ");
            _textBlock42.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock42.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock42, "OnSurfaceVariant"));
            _stackPanel35.AddChild(_textBlock42);
            const _textBlock43 = new TextBlock();
            _textBlock43.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock43, "StandardChecked"));
            _textBlock43.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock43.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock43.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock43, "OnSurface"));
            _stackPanel35.AddChild(_textBlock43);
            _stackPanel5.AddChild(_stackPanel35);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, IconButtonVM);
        t.Set("IconButtonTemplate", _tmpl0);
        return t;
    }
    get IconButtonTemplate() { return this.Resolve("IconButtonTemplate"); }
    set IconButtonTemplate(v) { this.Set("IconButtonTemplate", v); }
}
