import { IconButtonVM } from "./icon-button-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/basic";
import { ButtonVariant } from "@visualisation-sub/mural/framework/button.js";
import { IconButtonToggle } from "@visualisation-sub/mural/framework/icon-button-toggle.js";
import { IconButton } from "@visualisation-sub/mural/framework/icon-button.js";
import { DataContextBinding, DynamicResource, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_IconButtonDemo = Symbol("IconButtonDemo.ctor");
export class IconButtonDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_IconButtonDemo) {
            throw new Error("IconButtonDemo is private — use IconButtonDemo.Clone()");
        }
    }
    static Clone() {
        const t = new IconButtonDemo(_gate_IconButtonDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1._set_property_value_by_name("Background", DynamicResource(_border1, "Surface"));
            _border1._set_property_value_by_name("BorderBrush", DynamicResource(_border1, "OutlineVariant"));
            _border1._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border3._set_property_value_by_name("Background", DynamicResource(_border3, "Primary"));
            _border3._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4._set_property_value_by_name("Text", "IconButton — M3's compact square button. Four variants drive the chrome via Button.Variant.");
            _textBlock4._set_property_value_by_name("FontSize", 15);
            _textBlock4._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock4._set_property_value_by_name("Foreground", DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel5._set_property_value_by_name("Margin", new Thickness(24, 24, 24, 24));
            const _textBlock6 = new TextBlock();
            _textBlock6._set_property_value_by_name("Text", "IconButton — Variant: Filled / Tonal / Outlined / Standard");
            _textBlock6._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock6._set_property_value_by_name("FontSize", 14);
            _textBlock6._set_property_value_by_name("Foreground", DynamicResource(_textBlock6, "OnSurface"));
            _textBlock6._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 12));
            _stackPanel5.AddChild(_textBlock6);
            const _stackPanel7 = new StackPanel();
            _stackPanel7._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel7._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            const _iconButton8 = new IconButton();
            _iconButton8._set_property_value_by_name("Variant", ButtonVariant.Filled);
            _iconButton8._set_property_value_by_name("Command", DataContextBinding(_iconButton8, "ClickFilledCommand"));
            _iconButton8._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
            const _textBlock9 = new TextBlock();
            _textBlock9._set_property_value_by_name("Text", "✓");
            _textBlock9._set_property_value_by_name("FontSize", 18);
            _iconButton8.Content = _textBlock9;
            _stackPanel7.AddChild(_iconButton8);
            const _iconButton10 = new IconButton();
            _iconButton10._set_property_value_by_name("Variant", ButtonVariant.Tonal);
            _iconButton10._set_property_value_by_name("Command", DataContextBinding(_iconButton10, "ClickTonalCommand"));
            _iconButton10._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
            const _textBlock11 = new TextBlock();
            _textBlock11._set_property_value_by_name("Text", "★");
            _textBlock11._set_property_value_by_name("FontSize", 18);
            _iconButton10.Content = _textBlock11;
            _stackPanel7.AddChild(_iconButton10);
            const _iconButton12 = new IconButton();
            _iconButton12._set_property_value_by_name("Variant", ButtonVariant.Outlined);
            _iconButton12._set_property_value_by_name("Command", DataContextBinding(_iconButton12, "ClickOutlinedCommand"));
            _iconButton12._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
            const _textBlock13 = new TextBlock();
            _textBlock13._set_property_value_by_name("Text", "↗");
            _textBlock13._set_property_value_by_name("FontSize", 18);
            _iconButton12.Content = _textBlock13;
            _stackPanel7.AddChild(_iconButton12);
            const _iconButton14 = new IconButton();
            _iconButton14._set_property_value_by_name("Variant", ButtonVariant.Standard);
            _iconButton14._set_property_value_by_name("Command", DataContextBinding(_iconButton14, "ClickStandardCommand"));
            const _textBlock15 = new TextBlock();
            _textBlock15._set_property_value_by_name("Text", "⋯");
            _textBlock15._set_property_value_by_name("FontSize", 18);
            _iconButton14.Content = _textBlock15;
            _stackPanel7.AddChild(_iconButton14);
            _stackPanel5.AddChild(_stackPanel7);
            const _stackPanel16 = new StackPanel();
            _stackPanel16._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel16._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 24));
            const _textBlock17 = new TextBlock();
            _textBlock17._set_property_value_by_name("Text", "Clicks — Filled: ");
            _textBlock17._set_property_value_by_name("FontSize", 12);
            _textBlock17._set_property_value_by_name("Foreground", DynamicResource(_textBlock17, "OnSurfaceVariant"));
            _stackPanel16.AddChild(_textBlock17);
            const _textBlock18 = new TextBlock();
            _textBlock18._set_property_value_by_name("Text", DataContextBinding(_textBlock18, "FilledClicks"));
            _textBlock18._set_property_value_by_name("FontSize", 12);
            _textBlock18._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock18._set_property_value_by_name("Foreground", DynamicResource(_textBlock18, "OnSurface"));
            _stackPanel16.AddChild(_textBlock18);
            const _textBlock19 = new TextBlock();
            _textBlock19._set_property_value_by_name("Text", "  Tonal: ");
            _textBlock19._set_property_value_by_name("FontSize", 12);
            _textBlock19._set_property_value_by_name("Foreground", DynamicResource(_textBlock19, "OnSurfaceVariant"));
            _stackPanel16.AddChild(_textBlock19);
            const _textBlock20 = new TextBlock();
            _textBlock20._set_property_value_by_name("Text", DataContextBinding(_textBlock20, "TonalClicks"));
            _textBlock20._set_property_value_by_name("FontSize", 12);
            _textBlock20._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock20._set_property_value_by_name("Foreground", DynamicResource(_textBlock20, "OnSurface"));
            _stackPanel16.AddChild(_textBlock20);
            const _textBlock21 = new TextBlock();
            _textBlock21._set_property_value_by_name("Text", "  Outlined: ");
            _textBlock21._set_property_value_by_name("FontSize", 12);
            _textBlock21._set_property_value_by_name("Foreground", DynamicResource(_textBlock21, "OnSurfaceVariant"));
            _stackPanel16.AddChild(_textBlock21);
            const _textBlock22 = new TextBlock();
            _textBlock22._set_property_value_by_name("Text", DataContextBinding(_textBlock22, "OutlinedClicks"));
            _textBlock22._set_property_value_by_name("FontSize", 12);
            _textBlock22._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock22._set_property_value_by_name("Foreground", DynamicResource(_textBlock22, "OnSurface"));
            _stackPanel16.AddChild(_textBlock22);
            const _textBlock23 = new TextBlock();
            _textBlock23._set_property_value_by_name("Text", "  Standard: ");
            _textBlock23._set_property_value_by_name("FontSize", 12);
            _textBlock23._set_property_value_by_name("Foreground", DynamicResource(_textBlock23, "OnSurfaceVariant"));
            _stackPanel16.AddChild(_textBlock23);
            const _textBlock24 = new TextBlock();
            _textBlock24._set_property_value_by_name("Text", DataContextBinding(_textBlock24, "StandardClicks"));
            _textBlock24._set_property_value_by_name("FontSize", 12);
            _textBlock24._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock24._set_property_value_by_name("Foreground", DynamicResource(_textBlock24, "OnSurface"));
            _stackPanel16.AddChild(_textBlock24);
            _stackPanel5.AddChild(_stackPanel16);
            const _textBlock25 = new TextBlock();
            _textBlock25._set_property_value_by_name("Text", "IconButtonToggle — same Variant set; IsChecked flips Background + glyph ink.");
            _textBlock25._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock25._set_property_value_by_name("FontSize", 14);
            _textBlock25._set_property_value_by_name("Foreground", DynamicResource(_textBlock25, "OnSurface"));
            _textBlock25._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 12));
            _stackPanel5.AddChild(_textBlock25);
            const _stackPanel26 = new StackPanel();
            _stackPanel26._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel26._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            const _iconButtonToggle27 = new IconButtonToggle();
            _iconButtonToggle27._set_property_value_by_name("Variant", ButtonVariant.Filled);
            _iconButtonToggle27._set_property_value_by_name("IsChecked", DataContextBinding(_iconButtonToggle27, "FilledChecked"));
            _iconButtonToggle27._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
            const _textBlock28 = new TextBlock();
            _textBlock28._set_property_value_by_name("Text", "♥");
            _textBlock28._set_property_value_by_name("FontSize", 18);
            _iconButtonToggle27.Content = _textBlock28;
            _stackPanel26.AddChild(_iconButtonToggle27);
            const _iconButtonToggle29 = new IconButtonToggle();
            _iconButtonToggle29._set_property_value_by_name("Variant", ButtonVariant.Tonal);
            _iconButtonToggle29._set_property_value_by_name("IsChecked", DataContextBinding(_iconButtonToggle29, "TonalChecked"));
            _iconButtonToggle29._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
            const _textBlock30 = new TextBlock();
            _textBlock30._set_property_value_by_name("Text", "☆");
            _textBlock30._set_property_value_by_name("FontSize", 18);
            _iconButtonToggle29.Content = _textBlock30;
            _stackPanel26.AddChild(_iconButtonToggle29);
            const _iconButtonToggle31 = new IconButtonToggle();
            _iconButtonToggle31._set_property_value_by_name("Variant", ButtonVariant.Outlined);
            _iconButtonToggle31._set_property_value_by_name("IsChecked", DataContextBinding(_iconButtonToggle31, "OutlinedChecked"));
            _iconButtonToggle31._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
            const _textBlock32 = new TextBlock();
            _textBlock32._set_property_value_by_name("Text", "🔔");
            _textBlock32._set_property_value_by_name("FontSize", 18);
            _iconButtonToggle31.Content = _textBlock32;
            _stackPanel26.AddChild(_iconButtonToggle31);
            const _iconButtonToggle33 = new IconButtonToggle();
            _iconButtonToggle33._set_property_value_by_name("Variant", ButtonVariant.Standard);
            _iconButtonToggle33._set_property_value_by_name("IsChecked", DataContextBinding(_iconButtonToggle33, "StandardChecked"));
            const _textBlock34 = new TextBlock();
            _textBlock34._set_property_value_by_name("Text", "🌙");
            _textBlock34._set_property_value_by_name("FontSize", 18);
            _iconButtonToggle33.Content = _textBlock34;
            _stackPanel26.AddChild(_iconButtonToggle33);
            _stackPanel5.AddChild(_stackPanel26);
            const _stackPanel35 = new StackPanel();
            _stackPanel35._set_property_value_by_name("Orientation", Orientation.Horizontal);
            const _textBlock36 = new TextBlock();
            _textBlock36._set_property_value_by_name("Text", "Checked — Filled: ");
            _textBlock36._set_property_value_by_name("FontSize", 12);
            _textBlock36._set_property_value_by_name("Foreground", DynamicResource(_textBlock36, "OnSurfaceVariant"));
            _stackPanel35.AddChild(_textBlock36);
            const _textBlock37 = new TextBlock();
            _textBlock37._set_property_value_by_name("Text", DataContextBinding(_textBlock37, "FilledChecked"));
            _textBlock37._set_property_value_by_name("FontSize", 12);
            _textBlock37._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock37._set_property_value_by_name("Foreground", DynamicResource(_textBlock37, "OnSurface"));
            _stackPanel35.AddChild(_textBlock37);
            const _textBlock38 = new TextBlock();
            _textBlock38._set_property_value_by_name("Text", "  Tonal: ");
            _textBlock38._set_property_value_by_name("FontSize", 12);
            _textBlock38._set_property_value_by_name("Foreground", DynamicResource(_textBlock38, "OnSurfaceVariant"));
            _stackPanel35.AddChild(_textBlock38);
            const _textBlock39 = new TextBlock();
            _textBlock39._set_property_value_by_name("Text", DataContextBinding(_textBlock39, "TonalChecked"));
            _textBlock39._set_property_value_by_name("FontSize", 12);
            _textBlock39._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock39._set_property_value_by_name("Foreground", DynamicResource(_textBlock39, "OnSurface"));
            _stackPanel35.AddChild(_textBlock39);
            const _textBlock40 = new TextBlock();
            _textBlock40._set_property_value_by_name("Text", "  Outlined: ");
            _textBlock40._set_property_value_by_name("FontSize", 12);
            _textBlock40._set_property_value_by_name("Foreground", DynamicResource(_textBlock40, "OnSurfaceVariant"));
            _stackPanel35.AddChild(_textBlock40);
            const _textBlock41 = new TextBlock();
            _textBlock41._set_property_value_by_name("Text", DataContextBinding(_textBlock41, "OutlinedChecked"));
            _textBlock41._set_property_value_by_name("FontSize", 12);
            _textBlock41._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock41._set_property_value_by_name("Foreground", DynamicResource(_textBlock41, "OnSurface"));
            _stackPanel35.AddChild(_textBlock41);
            const _textBlock42 = new TextBlock();
            _textBlock42._set_property_value_by_name("Text", "  Standard: ");
            _textBlock42._set_property_value_by_name("FontSize", 12);
            _textBlock42._set_property_value_by_name("Foreground", DynamicResource(_textBlock42, "OnSurfaceVariant"));
            _stackPanel35.AddChild(_textBlock42);
            const _textBlock43 = new TextBlock();
            _textBlock43._set_property_value_by_name("Text", DataContextBinding(_textBlock43, "StandardChecked"));
            _textBlock43._set_property_value_by_name("FontSize", 12);
            _textBlock43._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock43._set_property_value_by_name("Foreground", DynamicResource(_textBlock43, "OnSurface"));
            _stackPanel35.AddChild(_textBlock43);
            _stackPanel5.AddChild(_stackPanel35);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, IconButtonVM);
        t.Set("IconButtonTemplate", _tmpl0);
        return t;
    }
    get IconButtonTemplate() { return this.Resolve("IconButtonTemplate"); }
    set IconButtonTemplate(v) { this.Set("IconButtonTemplate", v); }
}
