import { TopAppBarVM } from "./top-app-bar-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/basic";
import { ButtonVariant } from "@visualisation-sub/mural/framework/button.js";
import { IconButton } from "@visualisation-sub/mural/framework/icon-button.js";
import { TopAppBar } from "@visualisation-sub/mural/framework/top-app-bar/top-app-bar.js";
import { DataContextBinding, DynamicResource, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_TopAppBarDemo = Symbol("TopAppBarDemo.ctor");
export class TopAppBarDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_TopAppBarDemo) {
            throw new Error("TopAppBarDemo is private — use TopAppBarDemo.Clone()");
        }
    }
    static Clone() {
        const t = new TopAppBarDemo(_gate_TopAppBarDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1._set_property_value_by_name("Background", DynamicResource(_border1, "SurfaceContainerLow"));
            _border1._set_property_value_by_name("BorderBrush", DynamicResource(_border1, "OutlineVariant"));
            _border1._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border3._set_property_value_by_name("Background", DynamicResource(_border3, "Primary"));
            _border3._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4._set_property_value_by_name("Text", "TopAppBar — M3 screen header. Four variants vary title alignment and row count.");
            _textBlock4._set_property_value_by_name("FontSize", 15);
            _textBlock4._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock4._set_property_value_by_name("Foreground", DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel5._set_property_value_by_name("Margin", new Thickness(24, 24, 24, 24));
            const _textBlock6 = new TextBlock();
            _textBlock6._set_property_value_by_name("Text", "Small — single row, leading-aligned title.");
            _textBlock6._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock6._set_property_value_by_name("FontSize", 12);
            _textBlock6._set_property_value_by_name("Foreground", DynamicResource(_textBlock6, "OnSurfaceVariant"));
            _textBlock6._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            _stackPanel5.AddChild(_textBlock6);
            const _border7 = new Border();
            _border7._set_property_value_by_name("Background", DynamicResource(_border7, "OutlineVariant"));
            _border7._set_property_value_by_name("BorderThickness", new Thickness(0));
            _border7._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
            const _topAppBar8 = new TopAppBar();
            _topAppBar8._set_property_value_by_name("Variant", DataContextBinding(_topAppBar8, "SmallVariant"));
            _topAppBar8._set_property_value_by_name("Title", "Inbox");
            const _iconButton9 = new IconButton();
            _iconButton9._set_property_value_by_name("Variant", ButtonVariant.Standard);
            _iconButton9._set_property_value_by_name("Command", DataContextBinding(_iconButton9, "SearchCommand"));
            const _textBlock10 = new TextBlock();
            _textBlock10._set_property_value_by_name("Text", "🔍");
            _textBlock10._set_property_value_by_name("FontSize", 16);
            _iconButton9.Content = _textBlock10;
            _topAppBar8.AddChild(_iconButton9);
            const _iconButton11 = new IconButton();
            _iconButton11._set_property_value_by_name("Variant", ButtonVariant.Standard);
            _iconButton11._set_property_value_by_name("Command", DataContextBinding(_iconButton11, "MoreCommand"));
            const _textBlock12 = new TextBlock();
            _textBlock12._set_property_value_by_name("Text", "⋯");
            _textBlock12._set_property_value_by_name("FontSize", 18);
            _iconButton11.Content = _textBlock12;
            _topAppBar8.AddChild(_iconButton11);
            _border7.SetChild(_topAppBar8);
            _stackPanel5.AddChild(_border7);
            const _textBlock13 = new TextBlock();
            _textBlock13._set_property_value_by_name("Text", "CenterAligned — single row, centered title.");
            _textBlock13._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock13._set_property_value_by_name("FontSize", 12);
            _textBlock13._set_property_value_by_name("Foreground", DynamicResource(_textBlock13, "OnSurfaceVariant"));
            _textBlock13._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            _stackPanel5.AddChild(_textBlock13);
            const _border14 = new Border();
            _border14._set_property_value_by_name("Background", DynamicResource(_border14, "OutlineVariant"));
            _border14._set_property_value_by_name("BorderThickness", new Thickness(0));
            _border14._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
            const _topAppBar15 = new TopAppBar();
            _topAppBar15._set_property_value_by_name("Variant", DataContextBinding(_topAppBar15, "CenterAlignedVariant"));
            _topAppBar15._set_property_value_by_name("Title", "Settings");
            const _iconButton16 = new IconButton();
            _iconButton16._set_property_value_by_name("Variant", ButtonVariant.Standard);
            _iconButton16._set_property_value_by_name("Command", DataContextBinding(_iconButton16, "MoreCommand"));
            const _textBlock17 = new TextBlock();
            _textBlock17._set_property_value_by_name("Text", "⋯");
            _textBlock17._set_property_value_by_name("FontSize", 18);
            _iconButton16.Content = _textBlock17;
            _topAppBar15.AddChild(_iconButton16);
            _border14.SetChild(_topAppBar15);
            _stackPanel5.AddChild(_border14);
            const _textBlock18 = new TextBlock();
            _textBlock18._set_property_value_by_name("Text", "Medium — two rows, HeadlineSmall title (112dp tall).");
            _textBlock18._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock18._set_property_value_by_name("FontSize", 12);
            _textBlock18._set_property_value_by_name("Foreground", DynamicResource(_textBlock18, "OnSurfaceVariant"));
            _textBlock18._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            _stackPanel5.AddChild(_textBlock18);
            const _border19 = new Border();
            _border19._set_property_value_by_name("Background", DynamicResource(_border19, "OutlineVariant"));
            _border19._set_property_value_by_name("BorderThickness", new Thickness(0));
            _border19._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
            const _topAppBar20 = new TopAppBar();
            _topAppBar20._set_property_value_by_name("Variant", DataContextBinding(_topAppBar20, "MediumVariant"));
            _topAppBar20._set_property_value_by_name("Title", "Workspace");
            const _iconButton21 = new IconButton();
            _iconButton21._set_property_value_by_name("Variant", ButtonVariant.Standard);
            _iconButton21._set_property_value_by_name("Command", DataContextBinding(_iconButton21, "SearchCommand"));
            const _textBlock22 = new TextBlock();
            _textBlock22._set_property_value_by_name("Text", "🔍");
            _textBlock22._set_property_value_by_name("FontSize", 16);
            _iconButton21.Content = _textBlock22;
            _topAppBar20.AddChild(_iconButton21);
            const _iconButton23 = new IconButton();
            _iconButton23._set_property_value_by_name("Variant", ButtonVariant.Standard);
            _iconButton23._set_property_value_by_name("Command", DataContextBinding(_iconButton23, "MoreCommand"));
            const _textBlock24 = new TextBlock();
            _textBlock24._set_property_value_by_name("Text", "⋯");
            _textBlock24._set_property_value_by_name("FontSize", 18);
            _iconButton23.Content = _textBlock24;
            _topAppBar20.AddChild(_iconButton23);
            _border19.SetChild(_topAppBar20);
            _stackPanel5.AddChild(_border19);
            const _textBlock25 = new TextBlock();
            _textBlock25._set_property_value_by_name("Text", "Large — two rows, HeadlineMedium title (152dp tall).");
            _textBlock25._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock25._set_property_value_by_name("FontSize", 12);
            _textBlock25._set_property_value_by_name("Foreground", DynamicResource(_textBlock25, "OnSurfaceVariant"));
            _textBlock25._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            _stackPanel5.AddChild(_textBlock25);
            const _border26 = new Border();
            _border26._set_property_value_by_name("Background", DynamicResource(_border26, "OutlineVariant"));
            _border26._set_property_value_by_name("BorderThickness", new Thickness(0));
            _border26._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
            const _topAppBar27 = new TopAppBar();
            _topAppBar27._set_property_value_by_name("Variant", DataContextBinding(_topAppBar27, "LargeVariant"));
            _topAppBar27._set_property_value_by_name("Title", "Documents");
            const _iconButton28 = new IconButton();
            _iconButton28._set_property_value_by_name("Variant", ButtonVariant.Standard);
            _iconButton28._set_property_value_by_name("Command", DataContextBinding(_iconButton28, "SearchCommand"));
            const _textBlock29 = new TextBlock();
            _textBlock29._set_property_value_by_name("Text", "🔍");
            _textBlock29._set_property_value_by_name("FontSize", 16);
            _iconButton28.Content = _textBlock29;
            _topAppBar27.AddChild(_iconButton28);
            const _iconButton30 = new IconButton();
            _iconButton30._set_property_value_by_name("Variant", ButtonVariant.Standard);
            _iconButton30._set_property_value_by_name("Command", DataContextBinding(_iconButton30, "MoreCommand"));
            const _textBlock31 = new TextBlock();
            _textBlock31._set_property_value_by_name("Text", "⋯");
            _textBlock31._set_property_value_by_name("FontSize", 18);
            _iconButton30.Content = _textBlock31;
            _topAppBar27.AddChild(_iconButton30);
            _border26.SetChild(_topAppBar27);
            _stackPanel5.AddChild(_border26);
            const _stackPanel32 = new StackPanel();
            _stackPanel32._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel32._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
            const _textBlock33 = new TextBlock();
            _textBlock33._set_property_value_by_name("Text", "Clicks — Search: ");
            _textBlock33._set_property_value_by_name("FontSize", 12);
            _textBlock33._set_property_value_by_name("Foreground", DynamicResource(_textBlock33, "OnSurfaceVariant"));
            _stackPanel32.AddChild(_textBlock33);
            const _textBlock34 = new TextBlock();
            _textBlock34._set_property_value_by_name("Text", DataContextBinding(_textBlock34, "SearchClicks"));
            _textBlock34._set_property_value_by_name("FontSize", 12);
            _textBlock34._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock34._set_property_value_by_name("Foreground", DynamicResource(_textBlock34, "OnSurface"));
            _stackPanel32.AddChild(_textBlock34);
            const _textBlock35 = new TextBlock();
            _textBlock35._set_property_value_by_name("Text", "  More: ");
            _textBlock35._set_property_value_by_name("FontSize", 12);
            _textBlock35._set_property_value_by_name("Foreground", DynamicResource(_textBlock35, "OnSurfaceVariant"));
            _stackPanel32.AddChild(_textBlock35);
            const _textBlock36 = new TextBlock();
            _textBlock36._set_property_value_by_name("Text", DataContextBinding(_textBlock36, "MoreClicks"));
            _textBlock36._set_property_value_by_name("FontSize", 12);
            _textBlock36._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock36._set_property_value_by_name("Foreground", DynamicResource(_textBlock36, "OnSurface"));
            _stackPanel32.AddChild(_textBlock36);
            _stackPanel5.AddChild(_stackPanel32);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, TopAppBarVM);
        t.Set("TopAppBarTemplate", _tmpl0);
        return t;
    }
    get TopAppBarTemplate() { return this.Resolve("TopAppBarTemplate"); }
    set TopAppBarTemplate(v) { this.Set("TopAppBarTemplate", v); }
}
