import { Border, DataTemplate, DockPanel, Orientation, Slider, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { Color, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2.set_property_value("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2.set_property_value("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2.set_property_value("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4.set_property_value(DockPanel, "Dock", "Top");
        _border4.set_property_value("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border4.set_property_value("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5.set_property_value("Text", "Slider demo — single-thumb range, horizontal + vertical");
        _textBlock5.set_property_value("FontSize", 15);
        _textBlock5.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock5.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6.set_property_value("Orientation", Orientation.Horizontal);
        const _stackPanel7 = new StackPanel();
        _stackPanel7.set_property_value("Orientation", Orientation.Vertical);
        _stackPanel7.set_property_value("Width", 240);
        _stackPanel7.set_property_value("Margin", new Thickness(16, 24, 8, 16));
        const _textBlock8 = new TextBlock();
        _textBlock8.set_property_value("Text", "Brightness (0–1):");
        _textBlock8.set_property_value("FontSize", 12);
        _textBlock8.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock8.set_property_value("Margin", new Thickness(0, 0, 0, 12));
        _stackPanel7.AddChild(_textBlock8);
        const _slider9 = new Slider();
        _slider9.set_property_value("Width", 200);
        _slider9.set_property_value("Value", 0.6);
        _stackPanel7.AddChild(_slider9);
        const _textBlock10 = new TextBlock();
        _textBlock10.set_property_value("Text", "Default 0..1 range; SmallChange 0.01, LargeChange 0.1.");
        _textBlock10.set_property_value("FontSize", 11);
        _textBlock10.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock10.set_property_value("Margin", new Thickness(0, 12, 0, 0));
        _stackPanel7.AddChild(_textBlock10);
        _stackPanel6.AddChild(_stackPanel7);
        const _stackPanel11 = new StackPanel();
        _stackPanel11.set_property_value("Orientation", Orientation.Vertical);
        _stackPanel11.set_property_value("Width", 240);
        _stackPanel11.set_property_value("Margin", new Thickness(8, 24, 8, 16));
        const _textBlock12 = new TextBlock();
        _textBlock12.set_property_value("Text", "Volume (0–11):");
        _textBlock12.set_property_value("FontSize", 12);
        _textBlock12.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock12.set_property_value("Margin", new Thickness(0, 0, 0, 12));
        _stackPanel11.AddChild(_textBlock12);
        const _slider13 = new Slider();
        _slider13.set_property_value("Width", 200);
        _slider13.set_property_value("Minimum", 0);
        _slider13.set_property_value("Maximum", 11);
        _slider13.set_property_value("Value", 7);
        _slider13.set_property_value("SmallChange", 1);
        _slider13.set_property_value("LargeChange", 2);
        _stackPanel11.AddChild(_slider13);
        const _textBlock14 = new TextBlock();
        _textBlock14.set_property_value("Text", "Arrow ±1, Page ±2, Home / End snap to 0 / 11.");
        _textBlock14.set_property_value("FontSize", 11);
        _textBlock14.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock14.set_property_value("Margin", new Thickness(0, 12, 0, 0));
        _stackPanel11.AddChild(_textBlock14);
        _stackPanel6.AddChild(_stackPanel11);
        const _stackPanel15 = new StackPanel();
        _stackPanel15.set_property_value("Orientation", Orientation.Vertical);
        _stackPanel15.set_property_value("Width", 240);
        _stackPanel15.set_property_value("Margin", new Thickness(8, 24, 16, 16));
        const _textBlock16 = new TextBlock();
        _textBlock16.set_property_value("Text", "Mix (vertical):");
        _textBlock16.set_property_value("FontSize", 12);
        _textBlock16.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock16.set_property_value("Margin", new Thickness(0, 0, 0, 12));
        _stackPanel15.AddChild(_textBlock16);
        const _slider17 = new Slider();
        _slider17.set_property_value("Orientation", Orientation.Vertical);
        _slider17.set_property_value("Height", 200);
        _slider17.set_property_value("Value", 0.35);
        _stackPanel15.AddChild(_slider17);
        const _textBlock18 = new TextBlock();
        _textBlock18.set_property_value("Text", "Up = higher; thumb sits at Min when at the bottom.");
        _textBlock18.set_property_value("FontSize", 11);
        _textBlock18.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock18.set_property_value("Margin", new Thickness(0, 12, 0, 0));
        _stackPanel15.AddChild(_textBlock18);
        _stackPanel6.AddChild(_stackPanel15);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, "SliderVM");
    _rd0.Set("SliderTemplate", _tmpl1);
    return _rd0;
}
