import { SliderVM } from "./slider-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, Slider, StackPanel, TextBlock } from "@visualisation-sub/mural/Basic";
import { Color, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border4._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border4._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name("Text", "Slider demo — single-thumb range, horizontal + vertical");
        _textBlock5._set_property_value_by_name("FontSize", 15);
        _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock5._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _stackPanel7 = new StackPanel();
        _stackPanel7._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel7._set_property_value_by_name("Width", 240);
        _stackPanel7._set_property_value_by_name("Margin", new Thickness(16, 24, 8, 16));
        const _textBlock8 = new TextBlock();
        _textBlock8._set_property_value_by_name("Text", "Brightness (0–1):");
        _textBlock8._set_property_value_by_name("FontSize", 12);
        _textBlock8._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock8._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 12));
        _stackPanel7.AddChild(_textBlock8);
        const _slider9 = new Slider();
        _slider9._set_property_value_by_name("Width", 200);
        _slider9._set_property_value_by_name("Value", 0.6);
        _stackPanel7.AddChild(_slider9);
        const _textBlock10 = new TextBlock();
        _textBlock10._set_property_value_by_name("Text", "Default 0..1 range; SmallChange 0.01, LargeChange 0.1.");
        _textBlock10._set_property_value_by_name("FontSize", 11);
        _textBlock10._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock10._set_property_value_by_name("Margin", new Thickness(0, 12, 0, 0));
        _stackPanel7.AddChild(_textBlock10);
        _stackPanel6.AddChild(_stackPanel7);
        const _stackPanel11 = new StackPanel();
        _stackPanel11._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel11._set_property_value_by_name("Width", 240);
        _stackPanel11._set_property_value_by_name("Margin", new Thickness(8, 24, 8, 16));
        const _textBlock12 = new TextBlock();
        _textBlock12._set_property_value_by_name("Text", "Volume (0–11):");
        _textBlock12._set_property_value_by_name("FontSize", 12);
        _textBlock12._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock12._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 12));
        _stackPanel11.AddChild(_textBlock12);
        const _slider13 = new Slider();
        _slider13._set_property_value_by_name("Width", 200);
        _slider13._set_property_value_by_name("Minimum", 0);
        _slider13._set_property_value_by_name("Maximum", 11);
        _slider13._set_property_value_by_name("Value", 7);
        _slider13._set_property_value_by_name("SmallChange", 1);
        _slider13._set_property_value_by_name("LargeChange", 2);
        _stackPanel11.AddChild(_slider13);
        const _textBlock14 = new TextBlock();
        _textBlock14._set_property_value_by_name("Text", "Arrow ±1, Page ±2, Home / End snap to 0 / 11.");
        _textBlock14._set_property_value_by_name("FontSize", 11);
        _textBlock14._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock14._set_property_value_by_name("Margin", new Thickness(0, 12, 0, 0));
        _stackPanel11.AddChild(_textBlock14);
        _stackPanel6.AddChild(_stackPanel11);
        const _stackPanel15 = new StackPanel();
        _stackPanel15._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel15._set_property_value_by_name("Width", 240);
        _stackPanel15._set_property_value_by_name("Margin", new Thickness(8, 24, 16, 16));
        const _textBlock16 = new TextBlock();
        _textBlock16._set_property_value_by_name("Text", "Mix (vertical):");
        _textBlock16._set_property_value_by_name("FontSize", 12);
        _textBlock16._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock16._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 12));
        _stackPanel15.AddChild(_textBlock16);
        const _slider17 = new Slider();
        _slider17._set_property_value_by_name("Orientation", Orientation.Vertical);
        _slider17._set_property_value_by_name("Height", 200);
        _slider17._set_property_value_by_name("Value", 0.35);
        _stackPanel15.AddChild(_slider17);
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", "Up = higher; thumb sits at Min when at the bottom.");
        _textBlock18._set_property_value_by_name("FontSize", 11);
        _textBlock18._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock18._set_property_value_by_name("Margin", new Thickness(0, 12, 0, 0));
        _stackPanel15.AddChild(_textBlock18);
        _stackPanel6.AddChild(_stackPanel15);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, SliderVM);
    _rd0.Set("SliderTemplate", _tmpl1);
    return _rd0;
}
