import { ShapesVM } from "./shapes-vm.mjs";
import { Arch, Arrow, Boom, Border, Bun, Burst, Clamshell, DataTemplate, Diamond, EightLeafClover, Ellipse, Fan, Flower, FourLeafClover, FourSidedCookie, Gem, Ghostish, Heart, NineSidedCookie, Orientation, Pentagon, Pill, PixelCircle, PixelTriangle, Puffy, PuffyDiamond, Semicircle, SevenSidedCookie, SixSidedCookie, Slanted, SoftBoom, SoftBurst, Squircle, StackPanel, Sunny, TextBlock, TextWrapping, Triangle, TwelveSidedCookie, UniformGrid, VerySunny } from "@visualisation-sub/mural/basic";
import { ScrollViewer } from "@visualisation-sub/mural/framework/scroll-viewer.js";
import { DynamicResource, HorizontalAlignment, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_ShapesDemo = Symbol("ShapesDemo.ctor");
export class ShapesDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_ShapesDemo) {
            throw new Error("ShapesDemo is private — use ShapesDemo.Clone()");
        }
    }
    static Clone() {
        const t = new ShapesDemo(_gate_ShapesDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.set_property_value(Border.BackgroundKey, DynamicResource(_border1, "Surface"));
            const _scrollViewer2 = new ScrollViewer();
            const _border3 = new Border();
            _border3.set_property_value(Border.PaddingKey, new Thickness(24, 24, 24, 24));
            _border3.set_property_value(Border.BackgroundKey, DynamicResource(_border3, "Surface"));
            const _stackPanel4 = new StackPanel();
            _stackPanel4.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock5 = new TextBlock();
            _textBlock5.set_property_value(TextBlock.TextKey, "M3 Expressive Shape Library");
            _textBlock5.set_property_value(TextBlock.FontSizeKey, 24);
            _textBlock5.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock5.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock5, "OnSurface"));
            _textBlock5.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel4.AddChild(_textBlock5);
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "35 named shapes from the M3 Expressive shape system — base + architectural + cookies + clovers + radial waves + puffies + glyphs + pixel art. Rows 1-2 are the round/rectangular base + diamond/pentagon/gem; rows 3-4 architectural + N-sided cookies; row 5 spans clovers into the radial-wave family; row 6 finishes the radial waves + puffies; row 7 the special glyphs + pixel art.");
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 13);
            _textBlock6.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock6.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock6, "OnSurfaceVariant"));
            _textBlock6.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 24));
            _stackPanel4.AddChild(_textBlock6);
            const _uniformGrid7 = new UniformGrid();
            _uniformGrid7.set_property_value(UniformGrid.RowsKey, 7);
            _uniformGrid7.set_property_value(UniformGrid.ColumnsKey, 5);
            const _border8 = new Border();
            _border8.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel9 = new StackPanel();
            _stackPanel9.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel9.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _ellipse10 = new Ellipse();
            _ellipse10.set_property_value(Ellipse.WidthKey, 64);
            _ellipse10.set_property_value(Ellipse.HeightKey, 64);
            _ellipse10.set_property_value(Ellipse.FillKey, DynamicResource(_ellipse10, "Primary"));
            _stackPanel9.AddChild(_ellipse10);
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "Circle (Ellipse)");
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock11.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock11, "OnSurfaceVariant"));
            _textBlock11.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock11.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel9.AddChild(_textBlock11);
            _border8.SetChild(_stackPanel9);
            _uniformGrid7.AddChild(_border8);
            const _border12 = new Border();
            _border12.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel13 = new StackPanel();
            _stackPanel13.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel13.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _squircle14 = new Squircle();
            _squircle14.set_property_value(Squircle.WidthKey, 64);
            _squircle14.set_property_value(Squircle.HeightKey, 64);
            _squircle14.set_property_value(Squircle.FillKey, DynamicResource(_squircle14, "Primary"));
            _stackPanel13.AddChild(_squircle14);
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, "Square (Squircle)");
            _textBlock15.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock15.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock15, "OnSurfaceVariant"));
            _textBlock15.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock15.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel13.AddChild(_textBlock15);
            _border12.SetChild(_stackPanel13);
            _uniformGrid7.AddChild(_border12);
            const _border16 = new Border();
            _border16.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel17 = new StackPanel();
            _stackPanel17.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel17.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _slanted18 = new Slanted();
            _slanted18.set_property_value(Slanted.WidthKey, 64);
            _slanted18.set_property_value(Slanted.HeightKey, 64);
            _slanted18.set_property_value(Slanted.FillKey, DynamicResource(_slanted18, "Primary"));
            _stackPanel17.AddChild(_slanted18);
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "Slanted");
            _textBlock19.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock19.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock19, "OnSurfaceVariant"));
            _textBlock19.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock19.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel17.AddChild(_textBlock19);
            _border16.SetChild(_stackPanel17);
            _uniformGrid7.AddChild(_border16);
            const _border20 = new Border();
            _border20.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel21 = new StackPanel();
            _stackPanel21.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel21.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _ellipse22 = new Ellipse();
            _ellipse22.set_property_value(Ellipse.WidthKey, 80);
            _ellipse22.set_property_value(Ellipse.HeightKey, 48);
            _ellipse22.set_property_value(Ellipse.FillKey, DynamicResource(_ellipse22, "Primary"));
            _stackPanel21.AddChild(_ellipse22);
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, "Oval (Ellipse)");
            _textBlock23.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock23.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock23, "OnSurfaceVariant"));
            _textBlock23.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock23.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel21.AddChild(_textBlock23);
            _border20.SetChild(_stackPanel21);
            _uniformGrid7.AddChild(_border20);
            const _border24 = new Border();
            _border24.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel25 = new StackPanel();
            _stackPanel25.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel25.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _pill26 = new Pill();
            _pill26.set_property_value(Pill.WidthKey, 80);
            _pill26.set_property_value(Pill.HeightKey, 48);
            _pill26.set_property_value(Pill.FillKey, DynamicResource(_pill26, "Primary"));
            _stackPanel25.AddChild(_pill26);
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, "Pill");
            _textBlock27.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock27.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock27, "OnSurfaceVariant"));
            _textBlock27.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock27.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel25.AddChild(_textBlock27);
            _border24.SetChild(_stackPanel25);
            _uniformGrid7.AddChild(_border24);
            const _border28 = new Border();
            _border28.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel29 = new StackPanel();
            _stackPanel29.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel29.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _diamond30 = new Diamond();
            _diamond30.set_property_value(Diamond.WidthKey, 64);
            _diamond30.set_property_value(Diamond.HeightKey, 64);
            _diamond30.set_property_value(Diamond.FillKey, DynamicResource(_diamond30, "Primary"));
            _stackPanel29.AddChild(_diamond30);
            const _textBlock31 = new TextBlock();
            _textBlock31.set_property_value(TextBlock.TextKey, "Diamond");
            _textBlock31.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock31.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock31, "OnSurfaceVariant"));
            _textBlock31.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock31.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel29.AddChild(_textBlock31);
            _border28.SetChild(_stackPanel29);
            _uniformGrid7.AddChild(_border28);
            const _border32 = new Border();
            _border32.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel33 = new StackPanel();
            _stackPanel33.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel33.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _pentagon34 = new Pentagon();
            _pentagon34.set_property_value(Pentagon.WidthKey, 64);
            _pentagon34.set_property_value(Pentagon.HeightKey, 64);
            _pentagon34.set_property_value(Pentagon.FillKey, DynamicResource(_pentagon34, "Primary"));
            _stackPanel33.AddChild(_pentagon34);
            const _textBlock35 = new TextBlock();
            _textBlock35.set_property_value(TextBlock.TextKey, "Pentagon");
            _textBlock35.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock35.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock35, "OnSurfaceVariant"));
            _textBlock35.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock35.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel33.AddChild(_textBlock35);
            _border32.SetChild(_stackPanel33);
            _uniformGrid7.AddChild(_border32);
            const _border36 = new Border();
            _border36.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel37 = new StackPanel();
            _stackPanel37.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel37.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _gem38 = new Gem();
            _gem38.set_property_value(Gem.WidthKey, 64);
            _gem38.set_property_value(Gem.HeightKey, 64);
            _gem38.set_property_value(Gem.FillKey, DynamicResource(_gem38, "Primary"));
            _stackPanel37.AddChild(_gem38);
            const _textBlock39 = new TextBlock();
            _textBlock39.set_property_value(TextBlock.TextKey, "Gem");
            _textBlock39.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock39.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock39, "OnSurfaceVariant"));
            _textBlock39.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock39.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel37.AddChild(_textBlock39);
            _border36.SetChild(_stackPanel37);
            _uniformGrid7.AddChild(_border36);
            const _border40 = new Border();
            _border40.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel41 = new StackPanel();
            _stackPanel41.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel41.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _arch42 = new Arch();
            _arch42.set_property_value(Arch.WidthKey, 64);
            _arch42.set_property_value(Arch.HeightKey, 64);
            _arch42.set_property_value(Arch.FillKey, DynamicResource(_arch42, "Primary"));
            _stackPanel41.AddChild(_arch42);
            const _textBlock43 = new TextBlock();
            _textBlock43.set_property_value(TextBlock.TextKey, "Arch");
            _textBlock43.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock43.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock43, "OnSurfaceVariant"));
            _textBlock43.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock43.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel41.AddChild(_textBlock43);
            _border40.SetChild(_stackPanel41);
            _uniformGrid7.AddChild(_border40);
            const _border44 = new Border();
            _border44.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel45 = new StackPanel();
            _stackPanel45.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel45.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _semicircle46 = new Semicircle();
            _semicircle46.set_property_value(Semicircle.WidthKey, 64);
            _semicircle46.set_property_value(Semicircle.HeightKey, 64);
            _semicircle46.set_property_value(Semicircle.FillKey, DynamicResource(_semicircle46, "Primary"));
            _stackPanel45.AddChild(_semicircle46);
            const _textBlock47 = new TextBlock();
            _textBlock47.set_property_value(TextBlock.TextKey, "Semicircle");
            _textBlock47.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock47.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock47, "OnSurfaceVariant"));
            _textBlock47.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock47.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel45.AddChild(_textBlock47);
            _border44.SetChild(_stackPanel45);
            _uniformGrid7.AddChild(_border44);
            const _border48 = new Border();
            _border48.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel49 = new StackPanel();
            _stackPanel49.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel49.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _triangle50 = new Triangle();
            _triangle50.set_property_value(Triangle.WidthKey, 64);
            _triangle50.set_property_value(Triangle.HeightKey, 64);
            _triangle50.set_property_value(Triangle.FillKey, DynamicResource(_triangle50, "Primary"));
            _triangle50.set_property_value(Triangle.CornerRadiusKey, 10);
            _stackPanel49.AddChild(_triangle50);
            const _textBlock51 = new TextBlock();
            _textBlock51.set_property_value(TextBlock.TextKey, "Triangle");
            _textBlock51.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock51.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock51, "OnSurfaceVariant"));
            _textBlock51.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock51.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel49.AddChild(_textBlock51);
            _border48.SetChild(_stackPanel49);
            _uniformGrid7.AddChild(_border48);
            const _border52 = new Border();
            _border52.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel53 = new StackPanel();
            _stackPanel53.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel53.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _arrow54 = new Arrow();
            _arrow54.set_property_value(Arrow.WidthKey, 64);
            _arrow54.set_property_value(Arrow.HeightKey, 64);
            _arrow54.set_property_value(Arrow.FillKey, DynamicResource(_arrow54, "Primary"));
            _arrow54.set_property_value(Arrow.CornerRadiusKey, 10);
            _stackPanel53.AddChild(_arrow54);
            const _textBlock55 = new TextBlock();
            _textBlock55.set_property_value(TextBlock.TextKey, "Arrow");
            _textBlock55.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock55.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock55, "OnSurfaceVariant"));
            _textBlock55.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock55.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel53.AddChild(_textBlock55);
            _border52.SetChild(_stackPanel53);
            _uniformGrid7.AddChild(_border52);
            const _border56 = new Border();
            _border56.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel57 = new StackPanel();
            _stackPanel57.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel57.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _fan58 = new Fan();
            _fan58.set_property_value(Fan.WidthKey, 64);
            _fan58.set_property_value(Fan.HeightKey, 64);
            _fan58.set_property_value(Fan.FillKey, DynamicResource(_fan58, "Primary"));
            _stackPanel57.AddChild(_fan58);
            const _textBlock59 = new TextBlock();
            _textBlock59.set_property_value(TextBlock.TextKey, "Fan");
            _textBlock59.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock59.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock59, "OnSurfaceVariant"));
            _textBlock59.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock59.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel57.AddChild(_textBlock59);
            _border56.SetChild(_stackPanel57);
            _uniformGrid7.AddChild(_border56);
            const _border60 = new Border();
            _border60.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel61 = new StackPanel();
            _stackPanel61.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel61.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _clamshell62 = new Clamshell();
            _clamshell62.set_property_value(Clamshell.WidthKey, 80);
            _clamshell62.set_property_value(Clamshell.HeightKey, 48);
            _clamshell62.set_property_value(Clamshell.FillKey, DynamicResource(_clamshell62, "Primary"));
            _clamshell62.set_property_value(Clamshell.CornerRadiusKey, 8);
            _stackPanel61.AddChild(_clamshell62);
            const _textBlock63 = new TextBlock();
            _textBlock63.set_property_value(TextBlock.TextKey, "Clamshell");
            _textBlock63.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock63.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock63, "OnSurfaceVariant"));
            _textBlock63.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock63.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel61.AddChild(_textBlock63);
            _border60.SetChild(_stackPanel61);
            _uniformGrid7.AddChild(_border60);
            const _border64 = new Border();
            _border64.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel65 = new StackPanel();
            _stackPanel65.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel65.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _fourSidedCookie66 = new FourSidedCookie();
            _fourSidedCookie66.set_property_value(FourSidedCookie.WidthKey, 64);
            _fourSidedCookie66.set_property_value(FourSidedCookie.HeightKey, 64);
            _fourSidedCookie66.set_property_value(FourSidedCookie.FillKey, DynamicResource(_fourSidedCookie66, "Primary"));
            _fourSidedCookie66.set_property_value(FourSidedCookie.CornerRadiusKey, 10);
            _stackPanel65.AddChild(_fourSidedCookie66);
            const _textBlock67 = new TextBlock();
            _textBlock67.set_property_value(TextBlock.TextKey, "4-Cookie");
            _textBlock67.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock67.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock67, "OnSurfaceVariant"));
            _textBlock67.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock67.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel65.AddChild(_textBlock67);
            _border64.SetChild(_stackPanel65);
            _uniformGrid7.AddChild(_border64);
            const _border68 = new Border();
            _border68.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel69 = new StackPanel();
            _stackPanel69.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel69.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _sixSidedCookie70 = new SixSidedCookie();
            _sixSidedCookie70.set_property_value(SixSidedCookie.WidthKey, 64);
            _sixSidedCookie70.set_property_value(SixSidedCookie.HeightKey, 64);
            _sixSidedCookie70.set_property_value(SixSidedCookie.FillKey, DynamicResource(_sixSidedCookie70, "Primary"));
            _sixSidedCookie70.set_property_value(SixSidedCookie.CornerRadiusKey, 8);
            _stackPanel69.AddChild(_sixSidedCookie70);
            const _textBlock71 = new TextBlock();
            _textBlock71.set_property_value(TextBlock.TextKey, "6-Cookie");
            _textBlock71.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock71.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock71, "OnSurfaceVariant"));
            _textBlock71.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock71.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel69.AddChild(_textBlock71);
            _border68.SetChild(_stackPanel69);
            _uniformGrid7.AddChild(_border68);
            const _border72 = new Border();
            _border72.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel73 = new StackPanel();
            _stackPanel73.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel73.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _sevenSidedCookie74 = new SevenSidedCookie();
            _sevenSidedCookie74.set_property_value(SevenSidedCookie.WidthKey, 64);
            _sevenSidedCookie74.set_property_value(SevenSidedCookie.HeightKey, 64);
            _sevenSidedCookie74.set_property_value(SevenSidedCookie.FillKey, DynamicResource(_sevenSidedCookie74, "Primary"));
            _sevenSidedCookie74.set_property_value(SevenSidedCookie.CornerRadiusKey, 8);
            _stackPanel73.AddChild(_sevenSidedCookie74);
            const _textBlock75 = new TextBlock();
            _textBlock75.set_property_value(TextBlock.TextKey, "7-Cookie");
            _textBlock75.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock75.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock75, "OnSurfaceVariant"));
            _textBlock75.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock75.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel73.AddChild(_textBlock75);
            _border72.SetChild(_stackPanel73);
            _uniformGrid7.AddChild(_border72);
            const _border76 = new Border();
            _border76.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel77 = new StackPanel();
            _stackPanel77.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel77.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _nineSidedCookie78 = new NineSidedCookie();
            _nineSidedCookie78.set_property_value(NineSidedCookie.WidthKey, 64);
            _nineSidedCookie78.set_property_value(NineSidedCookie.HeightKey, 64);
            _nineSidedCookie78.set_property_value(NineSidedCookie.FillKey, DynamicResource(_nineSidedCookie78, "Primary"));
            _nineSidedCookie78.set_property_value(NineSidedCookie.CornerRadiusKey, 6);
            _stackPanel77.AddChild(_nineSidedCookie78);
            const _textBlock79 = new TextBlock();
            _textBlock79.set_property_value(TextBlock.TextKey, "9-Cookie");
            _textBlock79.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock79.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock79, "OnSurfaceVariant"));
            _textBlock79.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock79.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel77.AddChild(_textBlock79);
            _border76.SetChild(_stackPanel77);
            _uniformGrid7.AddChild(_border76);
            const _border80 = new Border();
            _border80.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel81 = new StackPanel();
            _stackPanel81.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel81.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _twelveSidedCookie82 = new TwelveSidedCookie();
            _twelveSidedCookie82.set_property_value(TwelveSidedCookie.WidthKey, 64);
            _twelveSidedCookie82.set_property_value(TwelveSidedCookie.HeightKey, 64);
            _twelveSidedCookie82.set_property_value(TwelveSidedCookie.FillKey, DynamicResource(_twelveSidedCookie82, "Primary"));
            _twelveSidedCookie82.set_property_value(TwelveSidedCookie.CornerRadiusKey, 5);
            _stackPanel81.AddChild(_twelveSidedCookie82);
            const _textBlock83 = new TextBlock();
            _textBlock83.set_property_value(TextBlock.TextKey, "12-Cookie");
            _textBlock83.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock83.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock83, "OnSurfaceVariant"));
            _textBlock83.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock83.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel81.AddChild(_textBlock83);
            _border80.SetChild(_stackPanel81);
            _uniformGrid7.AddChild(_border80);
            const _border84 = new Border();
            _border84.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel85 = new StackPanel();
            _stackPanel85.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel85.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _fourLeafClover86 = new FourLeafClover();
            _fourLeafClover86.set_property_value(FourLeafClover.WidthKey, 64);
            _fourLeafClover86.set_property_value(FourLeafClover.HeightKey, 64);
            _fourLeafClover86.set_property_value(FourLeafClover.FillKey, DynamicResource(_fourLeafClover86, "Primary"));
            _stackPanel85.AddChild(_fourLeafClover86);
            const _textBlock87 = new TextBlock();
            _textBlock87.set_property_value(TextBlock.TextKey, "4-Leaf Clover");
            _textBlock87.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock87.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock87, "OnSurfaceVariant"));
            _textBlock87.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock87.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel85.AddChild(_textBlock87);
            _border84.SetChild(_stackPanel85);
            _uniformGrid7.AddChild(_border84);
            const _border88 = new Border();
            _border88.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel89 = new StackPanel();
            _stackPanel89.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel89.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _eightLeafClover90 = new EightLeafClover();
            _eightLeafClover90.set_property_value(EightLeafClover.WidthKey, 64);
            _eightLeafClover90.set_property_value(EightLeafClover.HeightKey, 64);
            _eightLeafClover90.set_property_value(EightLeafClover.FillKey, DynamicResource(_eightLeafClover90, "Primary"));
            _stackPanel89.AddChild(_eightLeafClover90);
            const _textBlock91 = new TextBlock();
            _textBlock91.set_property_value(TextBlock.TextKey, "8-Leaf Clover");
            _textBlock91.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock91.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock91, "OnSurfaceVariant"));
            _textBlock91.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock91.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel89.AddChild(_textBlock91);
            _border88.SetChild(_stackPanel89);
            _uniformGrid7.AddChild(_border88);
            const _border92 = new Border();
            _border92.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel93 = new StackPanel();
            _stackPanel93.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel93.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _sunny94 = new Sunny();
            _sunny94.set_property_value(Sunny.WidthKey, 64);
            _sunny94.set_property_value(Sunny.HeightKey, 64);
            _sunny94.set_property_value(Sunny.FillKey, DynamicResource(_sunny94, "Primary"));
            _stackPanel93.AddChild(_sunny94);
            const _textBlock95 = new TextBlock();
            _textBlock95.set_property_value(TextBlock.TextKey, "Sunny");
            _textBlock95.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock95.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock95, "OnSurfaceVariant"));
            _textBlock95.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock95.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel93.AddChild(_textBlock95);
            _border92.SetChild(_stackPanel93);
            _uniformGrid7.AddChild(_border92);
            const _border96 = new Border();
            _border96.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel97 = new StackPanel();
            _stackPanel97.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel97.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _verySunny98 = new VerySunny();
            _verySunny98.set_property_value(VerySunny.WidthKey, 64);
            _verySunny98.set_property_value(VerySunny.HeightKey, 64);
            _verySunny98.set_property_value(VerySunny.FillKey, DynamicResource(_verySunny98, "Primary"));
            _stackPanel97.AddChild(_verySunny98);
            const _textBlock99 = new TextBlock();
            _textBlock99.set_property_value(TextBlock.TextKey, "VerySunny");
            _textBlock99.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock99.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock99, "OnSurfaceVariant"));
            _textBlock99.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock99.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel97.AddChild(_textBlock99);
            _border96.SetChild(_stackPanel97);
            _uniformGrid7.AddChild(_border96);
            const _border100 = new Border();
            _border100.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel101 = new StackPanel();
            _stackPanel101.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel101.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _burst102 = new Burst();
            _burst102.set_property_value(Burst.WidthKey, 64);
            _burst102.set_property_value(Burst.HeightKey, 64);
            _burst102.set_property_value(Burst.FillKey, DynamicResource(_burst102, "Primary"));
            _stackPanel101.AddChild(_burst102);
            const _textBlock103 = new TextBlock();
            _textBlock103.set_property_value(TextBlock.TextKey, "Burst");
            _textBlock103.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock103.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock103, "OnSurfaceVariant"));
            _textBlock103.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock103.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel101.AddChild(_textBlock103);
            _border100.SetChild(_stackPanel101);
            _uniformGrid7.AddChild(_border100);
            const _border104 = new Border();
            _border104.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel105 = new StackPanel();
            _stackPanel105.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel105.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _softBurst106 = new SoftBurst();
            _softBurst106.set_property_value(SoftBurst.WidthKey, 64);
            _softBurst106.set_property_value(SoftBurst.HeightKey, 64);
            _softBurst106.set_property_value(SoftBurst.FillKey, DynamicResource(_softBurst106, "Primary"));
            _stackPanel105.AddChild(_softBurst106);
            const _textBlock107 = new TextBlock();
            _textBlock107.set_property_value(TextBlock.TextKey, "SoftBurst");
            _textBlock107.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock107.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock107, "OnSurfaceVariant"));
            _textBlock107.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock107.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel105.AddChild(_textBlock107);
            _border104.SetChild(_stackPanel105);
            _uniformGrid7.AddChild(_border104);
            const _border108 = new Border();
            _border108.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel109 = new StackPanel();
            _stackPanel109.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel109.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _boom110 = new Boom();
            _boom110.set_property_value(Boom.WidthKey, 64);
            _boom110.set_property_value(Boom.HeightKey, 64);
            _boom110.set_property_value(Boom.FillKey, DynamicResource(_boom110, "Primary"));
            _stackPanel109.AddChild(_boom110);
            const _textBlock111 = new TextBlock();
            _textBlock111.set_property_value(TextBlock.TextKey, "Boom");
            _textBlock111.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock111.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock111, "OnSurfaceVariant"));
            _textBlock111.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock111.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel109.AddChild(_textBlock111);
            _border108.SetChild(_stackPanel109);
            _uniformGrid7.AddChild(_border108);
            const _border112 = new Border();
            _border112.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel113 = new StackPanel();
            _stackPanel113.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel113.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _softBoom114 = new SoftBoom();
            _softBoom114.set_property_value(SoftBoom.WidthKey, 64);
            _softBoom114.set_property_value(SoftBoom.HeightKey, 64);
            _softBoom114.set_property_value(SoftBoom.FillKey, DynamicResource(_softBoom114, "Primary"));
            _stackPanel113.AddChild(_softBoom114);
            const _textBlock115 = new TextBlock();
            _textBlock115.set_property_value(TextBlock.TextKey, "SoftBoom");
            _textBlock115.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock115.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock115, "OnSurfaceVariant"));
            _textBlock115.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock115.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel113.AddChild(_textBlock115);
            _border112.SetChild(_stackPanel113);
            _uniformGrid7.AddChild(_border112);
            const _border116 = new Border();
            _border116.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel117 = new StackPanel();
            _stackPanel117.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel117.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _flower118 = new Flower();
            _flower118.set_property_value(Flower.WidthKey, 64);
            _flower118.set_property_value(Flower.HeightKey, 64);
            _flower118.set_property_value(Flower.FillKey, DynamicResource(_flower118, "Primary"));
            _stackPanel117.AddChild(_flower118);
            const _textBlock119 = new TextBlock();
            _textBlock119.set_property_value(TextBlock.TextKey, "Flower");
            _textBlock119.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock119.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock119, "OnSurfaceVariant"));
            _textBlock119.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock119.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel117.AddChild(_textBlock119);
            _border116.SetChild(_stackPanel117);
            _uniformGrid7.AddChild(_border116);
            const _border120 = new Border();
            _border120.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel121 = new StackPanel();
            _stackPanel121.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel121.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _puffy122 = new Puffy();
            _puffy122.set_property_value(Puffy.WidthKey, 64);
            _puffy122.set_property_value(Puffy.HeightKey, 64);
            _puffy122.set_property_value(Puffy.FillKey, DynamicResource(_puffy122, "Primary"));
            _stackPanel121.AddChild(_puffy122);
            const _textBlock123 = new TextBlock();
            _textBlock123.set_property_value(TextBlock.TextKey, "Puffy");
            _textBlock123.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock123.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock123, "OnSurfaceVariant"));
            _textBlock123.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock123.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel121.AddChild(_textBlock123);
            _border120.SetChild(_stackPanel121);
            _uniformGrid7.AddChild(_border120);
            const _border124 = new Border();
            _border124.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel125 = new StackPanel();
            _stackPanel125.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel125.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _puffyDiamond126 = new PuffyDiamond();
            _puffyDiamond126.set_property_value(PuffyDiamond.WidthKey, 64);
            _puffyDiamond126.set_property_value(PuffyDiamond.HeightKey, 64);
            _puffyDiamond126.set_property_value(PuffyDiamond.FillKey, DynamicResource(_puffyDiamond126, "Primary"));
            _stackPanel125.AddChild(_puffyDiamond126);
            const _textBlock127 = new TextBlock();
            _textBlock127.set_property_value(TextBlock.TextKey, "PuffyDiamond");
            _textBlock127.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock127.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock127, "OnSurfaceVariant"));
            _textBlock127.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock127.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel125.AddChild(_textBlock127);
            _border124.SetChild(_stackPanel125);
            _uniformGrid7.AddChild(_border124);
            const _border128 = new Border();
            _border128.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel129 = new StackPanel();
            _stackPanel129.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel129.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _ghostish130 = new Ghostish();
            _ghostish130.set_property_value(Ghostish.WidthKey, 64);
            _ghostish130.set_property_value(Ghostish.HeightKey, 64);
            _ghostish130.set_property_value(Ghostish.FillKey, DynamicResource(_ghostish130, "Primary"));
            _stackPanel129.AddChild(_ghostish130);
            const _textBlock131 = new TextBlock();
            _textBlock131.set_property_value(TextBlock.TextKey, "Ghost-ish");
            _textBlock131.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock131.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock131, "OnSurfaceVariant"));
            _textBlock131.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock131.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel129.AddChild(_textBlock131);
            _border128.SetChild(_stackPanel129);
            _uniformGrid7.AddChild(_border128);
            const _border132 = new Border();
            _border132.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel133 = new StackPanel();
            _stackPanel133.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel133.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _bun134 = new Bun();
            _bun134.set_property_value(Bun.WidthKey, 64);
            _bun134.set_property_value(Bun.HeightKey, 64);
            _bun134.set_property_value(Bun.FillKey, DynamicResource(_bun134, "Primary"));
            _stackPanel133.AddChild(_bun134);
            const _textBlock135 = new TextBlock();
            _textBlock135.set_property_value(TextBlock.TextKey, "Bun");
            _textBlock135.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock135.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock135, "OnSurfaceVariant"));
            _textBlock135.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock135.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel133.AddChild(_textBlock135);
            _border132.SetChild(_stackPanel133);
            _uniformGrid7.AddChild(_border132);
            const _border136 = new Border();
            _border136.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel137 = new StackPanel();
            _stackPanel137.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel137.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _heart138 = new Heart();
            _heart138.set_property_value(Heart.WidthKey, 64);
            _heart138.set_property_value(Heart.HeightKey, 64);
            _heart138.set_property_value(Heart.FillKey, DynamicResource(_heart138, "Primary"));
            _stackPanel137.AddChild(_heart138);
            const _textBlock139 = new TextBlock();
            _textBlock139.set_property_value(TextBlock.TextKey, "Heart");
            _textBlock139.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock139.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock139, "OnSurfaceVariant"));
            _textBlock139.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock139.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel137.AddChild(_textBlock139);
            _border136.SetChild(_stackPanel137);
            _uniformGrid7.AddChild(_border136);
            const _border140 = new Border();
            _border140.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel141 = new StackPanel();
            _stackPanel141.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel141.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _pixelCircle142 = new PixelCircle();
            _pixelCircle142.set_property_value(PixelCircle.WidthKey, 64);
            _pixelCircle142.set_property_value(PixelCircle.HeightKey, 64);
            _pixelCircle142.set_property_value(PixelCircle.FillKey, DynamicResource(_pixelCircle142, "Primary"));
            _stackPanel141.AddChild(_pixelCircle142);
            const _textBlock143 = new TextBlock();
            _textBlock143.set_property_value(TextBlock.TextKey, "PixelCircle");
            _textBlock143.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock143.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock143, "OnSurfaceVariant"));
            _textBlock143.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock143.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel141.AddChild(_textBlock143);
            _border140.SetChild(_stackPanel141);
            _uniformGrid7.AddChild(_border140);
            const _border144 = new Border();
            _border144.set_property_value(Border.PaddingKey, new Thickness(8, 8, 8, 8));
            const _stackPanel145 = new StackPanel();
            _stackPanel145.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel145.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _pixelTriangle146 = new PixelTriangle();
            _pixelTriangle146.set_property_value(PixelTriangle.WidthKey, 64);
            _pixelTriangle146.set_property_value(PixelTriangle.HeightKey, 64);
            _pixelTriangle146.set_property_value(PixelTriangle.FillKey, DynamicResource(_pixelTriangle146, "Primary"));
            _stackPanel145.AddChild(_pixelTriangle146);
            const _textBlock147 = new TextBlock();
            _textBlock147.set_property_value(TextBlock.TextKey, "PixelTriangle");
            _textBlock147.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock147.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock147, "OnSurfaceVariant"));
            _textBlock147.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _textBlock147.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel145.AddChild(_textBlock147);
            _border144.SetChild(_stackPanel145);
            _uniformGrid7.AddChild(_border144);
            _stackPanel4.AddChild(_uniformGrid7);
            const _textBlock148 = new TextBlock();
            _textBlock148.set_property_value(TextBlock.TextKey, "All 35 shapes live — Circle / Oval delegate to Ellipse, Square delegates to Squircle. The remaining named shapes ship as parametric families (Cookie, Clover, RadialWave, Puffy, PixelArt) with named-stop aliases that just override metadata defaults.");
            _textBlock148.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock148.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock148.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock148, "OnSurfaceVariant"));
            _textBlock148.set_property_value(TextBlock.MarginKey, new Thickness(0, 24, 0, 0));
            _stackPanel4.AddChild(_textBlock148);
            _border3.SetChild(_stackPanel4);
            _scrollViewer2.Content = _border3;
            _border1.SetChild(_scrollViewer2);
            return _border1;
        }, ShapesVM);
        t.Set("ShapesTemplate", _tmpl0);
        return t;
    }
    get ShapesTemplate() { return this.Resolve("ShapesTemplate"); }
    set ShapesTemplate(v) { this.Set("ShapesTemplate", v); }
}
