import { TreeViewVM } from "./tree-view-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Basic";
import { TreeView, TreeViewItem } from "@visualisation-sub/mural/framework/list/tree-view.js";
import { DynamicResource, NameScope, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2.SetNameScope(new NameScope());
        _border2._set_property_value_by_name("Background", DynamicResource(_border2, "Surface"));
        _border2._set_property_value_by_name("BorderBrush", DynamicResource(_border2, "OutlineVariant"));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border4._set_property_value_by_name("Background", DynamicResource(_border4, "Primary"));
        _border4._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name("Text", "TreeView — composed markup vs. HierarchicalDataTemplate");
        _textBlock5._set_property_value_by_name("FontSize", 15);
        _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock5._set_property_value_by_name("Foreground", DynamicResource(_textBlock5, "Surface"));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _stackPanel7 = new StackPanel();
        _stackPanel7._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel7._set_property_value_by_name("Width", 300);
        _stackPanel7._set_property_value_by_name("Margin", new Thickness(12, 12, 6, 12));
        const _textBlock8 = new TextBlock();
        _textBlock8._set_property_value_by_name("Text", "Composed markup");
        _textBlock8._set_property_value_by_name("FontSize", 12);
        _textBlock8._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock8._set_property_value_by_name("Foreground", DynamicResource(_textBlock8, "OnSurfaceVariant"));
        _textBlock8._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel7.AddChild(_textBlock8);
        const _treeView9 = new TreeView();
        _treeView9._set_property_value_by_name("Indent", 18);
        const _treeViewItem10 = new TreeViewItem();
        _treeViewItem10._set_property_value_by_name("Header", "src/");
        _treeViewItem10._set_property_value_by_name("IsExpanded", true);
        const _treeViewItem11 = new TreeViewItem();
        _treeViewItem11._set_property_value_by_name("Header", "runtime/");
        _treeViewItem11._set_property_value_by_name("IsExpanded", true);
        const _treeViewItem12 = new TreeViewItem();
        _treeViewItem12._set_property_value_by_name("Header", "visual.ts");
        _treeViewItem11.AddChild(_treeViewItem12);
        const _treeViewItem13 = new TreeViewItem();
        _treeViewItem13._set_property_value_by_name("Header", "model.ts");
        _treeViewItem11.AddChild(_treeViewItem13);
        const _treeViewItem14 = new TreeViewItem();
        _treeViewItem14._set_property_value_by_name("Header", "routed-event.ts");
        _treeViewItem11.AddChild(_treeViewItem14);
        const _treeViewItem15 = new TreeViewItem();
        _treeViewItem15._set_property_value_by_name("Header", "input-manager.ts");
        _treeViewItem11.AddChild(_treeViewItem15);
        _treeViewItem10.AddChild(_treeViewItem11);
        const _treeViewItem16 = new TreeViewItem();
        _treeViewItem16._set_property_value_by_name("Header", "visual-engine/");
        const _treeViewItem17 = new TreeViewItem();
        _treeViewItem17._set_property_value_by_name("Header", "presentation-target.ts");
        _treeViewItem16.AddChild(_treeViewItem17);
        const _treeViewItem18 = new TreeViewItem();
        _treeViewItem18._set_property_value_by_name("Header", "svg-renderer.ts");
        _treeViewItem16.AddChild(_treeViewItem18);
        const _treeViewItem19 = new TreeViewItem();
        _treeViewItem19._set_property_value_by_name("Header", "overlay-layer.ts");
        _treeViewItem16.AddChild(_treeViewItem19);
        _treeViewItem10.AddChild(_treeViewItem16);
        const _treeViewItem20 = new TreeViewItem();
        _treeViewItem20._set_property_value_by_name("Header", "Controls/");
        _treeViewItem20._set_property_value_by_name("IsExpanded", true);
        const _treeViewItem21 = new TreeViewItem();
        _treeViewItem21._set_property_value_by_name("Header", "border.ts");
        _treeViewItem20.AddChild(_treeViewItem21);
        const _treeViewItem22 = new TreeViewItem();
        _treeViewItem22._set_property_value_by_name("Header", "button.ts");
        _treeViewItem20.AddChild(_treeViewItem22);
        const _treeViewItem23 = new TreeViewItem();
        _treeViewItem23._set_property_value_by_name("Header", "tree-view.ts");
        _treeViewItem20.AddChild(_treeViewItem23);
        _treeViewItem10.AddChild(_treeViewItem20);
        _treeView9.AddChild(_treeViewItem10);
        const _treeViewItem24 = new TreeViewItem();
        _treeViewItem24._set_property_value_by_name("Header", "demo/");
        const _treeViewItem25 = new TreeViewItem();
        _treeViewItem25._set_property_value_by_name("Header", "counter.mu");
        _treeViewItem24.AddChild(_treeViewItem25);
        const _treeViewItem26 = new TreeViewItem();
        _treeViewItem26._set_property_value_by_name("Header", "tree-view.mu");
        _treeViewItem24.AddChild(_treeViewItem26);
        _treeView9.AddChild(_treeViewItem24);
        _stackPanel7.AddChild(_treeView9);
        _stackPanel6.AddChild(_stackPanel7);
        const _border27 = new Border();
        _border27._set_property_value_by_name("Width", 1);
        _border27._set_property_value_by_name("Background", DynamicResource(_border27, "OutlineVariant"));
        _border27._set_property_value_by_name("Margin", new Thickness(0, 12, 0, 12));
        _stackPanel6.AddChild(_border27);
        const _stackPanel28 = new StackPanel();
        _stackPanel28._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel28._set_property_value_by_name("Width", 300);
        _stackPanel28._set_property_value_by_name("Margin", new Thickness(6, 12, 12, 12));
        const _textBlock29 = new TextBlock();
        _textBlock29._set_property_value_by_name("Text", "HierarchicalDataTemplate");
        _textBlock29._set_property_value_by_name("FontSize", 12);
        _textBlock29._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock29._set_property_value_by_name("Foreground", DynamicResource(_textBlock29, "OnSurfaceVariant"));
        _textBlock29._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel28.AddChild(_textBlock29);
        const _treeView30 = new TreeView();
        _treeView30.Name = "bound";
        _treeView30._set_property_value_by_name("Indent", 18);
        _stackPanel28.AddChild(_treeView30);
        _stackPanel6.AddChild(_stackPanel28);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, TreeViewVM);
    _rd0.Set("TreeViewTemplate", _tmpl1);
    return _rd0;
}
