import { TreeViewVM } from "./tree-view-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@pragmatic-lab/mural/basic";
import { TreeView, TreeViewItem } from "@pragmatic-lab/mural/framework/list/tree-view.js";
import { DynamicResource, NameScope, ResourceDictionary, Thickness } from "@pragmatic-lab/mural/runtime";
import { FontWeight, Pen } from "@pragmatic-lab/mural/visual-engine";


const _gate_TreeViewDemo = Symbol("TreeViewDemo.ctor");
export class TreeViewDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_TreeViewDemo) {
            throw new Error("TreeViewDemo is private — use TreeViewDemo.Clone()");
        }
    }
    static Clone() {
        const t = new TreeViewDemo(_gate_TreeViewDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            let _treeView1;
            const _border2 = new Border();
            _border2.SetNameScope(new NameScope());
            _border2.set_property_value(Border.FillKey, DynamicResource(_border2, "Surface"));
            _border2.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            const _dockPanel3 = new DockPanel();
            const _border4 = new Border();
            _border4.set_property_value(DockPanel.DockKey, Dock.Top);
            _border4.set_property_value(Border.FillKey, DynamicResource(_border4, "Primary"));
            _border4.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _textBlock5 = new TextBlock();
            _textBlock5.set_property_value(TextBlock.TextKey, "TreeView — composed markup vs. HierarchicalDataTemplate");
            _textBlock5.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock5.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock5.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock5, "OnPrimary"));
            _border4.SetChild(_textBlock5);
            _dockPanel3.AddChild(_border4);
            const _stackPanel6 = new StackPanel();
            _stackPanel6.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _stackPanel7 = new StackPanel();
            _stackPanel7.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel7.set_property_value(StackPanel.WidthKey, 300);
            _stackPanel7.set_property_value(StackPanel.MarginKey, new Thickness(12, 12, 6, 12));
            const _textBlock8 = new TextBlock();
            _textBlock8.set_property_value(TextBlock.TextKey, "Composed markup");
            _textBlock8.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock8.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock8.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock8, "OnSurfaceVariant"));
            _textBlock8.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel7.AddChild(_textBlock8);
            const _treeView9 = new TreeView();
            _treeView9.set_property_value(TreeView.IndentKey, 18);
            const _treeViewItem10 = new TreeViewItem();
            _treeViewItem10.set_property_value(TreeViewItem.HeaderKey, "src/");
            _treeViewItem10.set_property_value(TreeViewItem.IsExpandedKey, true);
            const _treeViewItem11 = new TreeViewItem();
            _treeViewItem11.set_property_value(TreeViewItem.HeaderKey, "runtime/");
            _treeViewItem11.set_property_value(TreeViewItem.IsExpandedKey, true);
            const _treeViewItem12 = new TreeViewItem();
            _treeViewItem12.set_property_value(TreeViewItem.HeaderKey, "visual.ts");
            _treeViewItem11.AddChild(_treeViewItem12);
            const _treeViewItem13 = new TreeViewItem();
            _treeViewItem13.set_property_value(TreeViewItem.HeaderKey, "model.ts");
            _treeViewItem11.AddChild(_treeViewItem13);
            const _treeViewItem14 = new TreeViewItem();
            _treeViewItem14.set_property_value(TreeViewItem.HeaderKey, "routed-event.ts");
            _treeViewItem11.AddChild(_treeViewItem14);
            const _treeViewItem15 = new TreeViewItem();
            _treeViewItem15.set_property_value(TreeViewItem.HeaderKey, "input-manager.ts");
            _treeViewItem11.AddChild(_treeViewItem15);
            _treeViewItem10.AddChild(_treeViewItem11);
            const _treeViewItem16 = new TreeViewItem();
            _treeViewItem16.set_property_value(TreeViewItem.HeaderKey, "visual-engine/");
            const _treeViewItem17 = new TreeViewItem();
            _treeViewItem17.set_property_value(TreeViewItem.HeaderKey, "presentation-target.ts");
            _treeViewItem16.AddChild(_treeViewItem17);
            const _treeViewItem18 = new TreeViewItem();
            _treeViewItem18.set_property_value(TreeViewItem.HeaderKey, "svg-renderer.ts");
            _treeViewItem16.AddChild(_treeViewItem18);
            const _treeViewItem19 = new TreeViewItem();
            _treeViewItem19.set_property_value(TreeViewItem.HeaderKey, "overlay-layer.ts");
            _treeViewItem16.AddChild(_treeViewItem19);
            _treeViewItem10.AddChild(_treeViewItem16);
            const _treeViewItem20 = new TreeViewItem();
            _treeViewItem20.set_property_value(TreeViewItem.HeaderKey, "Controls/");
            _treeViewItem20.set_property_value(TreeViewItem.IsExpandedKey, true);
            const _treeViewItem21 = new TreeViewItem();
            _treeViewItem21.set_property_value(TreeViewItem.HeaderKey, "border.ts");
            _treeViewItem20.AddChild(_treeViewItem21);
            const _treeViewItem22 = new TreeViewItem();
            _treeViewItem22.set_property_value(TreeViewItem.HeaderKey, "button.ts");
            _treeViewItem20.AddChild(_treeViewItem22);
            const _treeViewItem23 = new TreeViewItem();
            _treeViewItem23.set_property_value(TreeViewItem.HeaderKey, "tree-view.ts");
            _treeViewItem20.AddChild(_treeViewItem23);
            _treeViewItem10.AddChild(_treeViewItem20);
            _treeView9.AddChild(_treeViewItem10);
            const _treeViewItem24 = new TreeViewItem();
            _treeViewItem24.set_property_value(TreeViewItem.HeaderKey, "demo/");
            const _treeViewItem25 = new TreeViewItem();
            _treeViewItem25.set_property_value(TreeViewItem.HeaderKey, "counter.mu");
            _treeViewItem24.AddChild(_treeViewItem25);
            const _treeViewItem26 = new TreeViewItem();
            _treeViewItem26.set_property_value(TreeViewItem.HeaderKey, "tree-view.mu");
            _treeViewItem24.AddChild(_treeViewItem26);
            _treeView9.AddChild(_treeViewItem24);
            _stackPanel7.AddChild(_treeView9);
            _stackPanel6.AddChild(_stackPanel7);
            const _border27 = new Border();
            _border27.set_property_value(Border.WidthKey, 1);
            _border27.set_property_value(Border.FillKey, DynamicResource(_border27, "OutlineVariant"));
            _border27.set_property_value(Border.MarginKey, new Thickness(0, 12, 0, 12));
            _stackPanel6.AddChild(_border27);
            const _stackPanel28 = new StackPanel();
            _stackPanel28.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel28.set_property_value(StackPanel.WidthKey, 300);
            _stackPanel28.set_property_value(StackPanel.MarginKey, new Thickness(6, 12, 12, 12));
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, "HierarchicalDataTemplate");
            _textBlock29.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock29.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock29.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock29, "OnSurfaceVariant"));
            _textBlock29.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel28.AddChild(_textBlock29);
            _treeView1 = new TreeView();
            _treeView1.Name = "bound";
            _treeView1.set_property_value(TreeView.IndentKey, 18);
            _stackPanel28.AddChild(_treeView1);
            _stackPanel6.AddChild(_stackPanel28);
            _dockPanel3.AddChild(_stackPanel6);
            _border2.SetChild(_dockPanel3);
            return _border2;
        }, TreeViewVM);
        t.Set(TreeViewVM, _tmpl0);
        return t;
    }
}
