import { RichTextEditorVM } from "./rich-text-editor-vm.mjs";
import { Bold, Border, DataTemplate, Dock, DockPanel, FlowDocument, Italic, List, ListItem, ListMarkerStyle, Orientation, Paragraph, RichTextBox, Run, StackPanel, TextBlock, TextWrapping, Underline } from "@visualisation-sub/mural/basic";
import { Button, ButtonVariant } from "@visualisation-sub/mural/framework/buttons/button.js";
import { DynamicResource, NameScope, ResourceDictionary, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontStyle, FontWeight, TextDecorations } from "@visualisation-sub/mural/visual-engine";


const _gate_RichTextEditorDemo = Symbol("RichTextEditorDemo.ctor");
export class RichTextEditorDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_RichTextEditorDemo) {
            throw new Error("RichTextEditorDemo is private — use RichTextEditorDemo.Clone()");
        }
    }
    static Clone() {
        const t = new RichTextEditorDemo(_gate_RichTextEditorDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            let _button1, _button2, _button3, _button4, _button5, _richTextBox6;
            const _border7 = new Border();
            _border7.SetNameScope(new NameScope());
            _border7.set_property_value(Border.BackgroundKey, DynamicResource(_border7, "Surface"));
            const _dockPanel8 = new DockPanel();
            const _border9 = new Border();
            _border9.set_property_value(DockPanel.DockKey, Dock.Top);
            _border9.set_property_value(Border.BackgroundKey, DynamicResource(_border9, "Primary"));
            _border9.set_property_value(Border.PaddingKey, new Thickness(20, 14, 20, 14));
            const _stackPanel10 = new StackPanel();
            _stackPanel10.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "Rich text editor");
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock11.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock11.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock11, "OnPrimary"));
            _stackPanel10.AddChild(_textBlock11);
            const _textBlock12 = new TextBlock();
            _textBlock12.set_property_value(TextBlock.TextKey, "Click in, select text, and format with the toolbar or Ctrl+B / Ctrl+I / Ctrl+U. Enter splits a paragraph; Tab / Shift+Tab indent and outdent list items.");
            _textBlock12.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock12.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock12, "OnPrimary"));
            _textBlock12.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock12.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _stackPanel10.AddChild(_textBlock12);
            _border9.SetChild(_stackPanel10);
            _dockPanel8.AddChild(_border9);
            const _border13 = new Border();
            _border13.set_property_value(DockPanel.DockKey, Dock.Top);
            _border13.set_property_value(Border.BackgroundKey, DynamicResource(_border13, "SurfaceContainerLow"));
            _border13.set_property_value(Border.BorderBrushKey, DynamicResource(_border13, "OutlineVariant"));
            _border13.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 0, 1));
            _border13.set_property_value(Border.PaddingKey, new Thickness(16, 8, 16, 8));
            const _stackPanel14 = new StackPanel();
            _stackPanel14.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _button1 = new Button();
            _button1.Name = "BoldBtn";
            _button1.set_property_value(Button.VariantKey, ButtonVariant.Tonal);
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, "B");
            _textBlock15.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock15.set_property_value(TextBlock.FontSizeKey, 15);
            _button1.Content = _textBlock15;
            _stackPanel14.AddChild(_button1);
            _button2 = new Button();
            _button2.Name = "ItalicBtn";
            _button2.set_property_value(Button.VariantKey, ButtonVariant.Tonal);
            _button2.set_property_value(Button.MarginKey, new Thickness(6, 0, 0, 0));
            const _textBlock16 = new TextBlock();
            _textBlock16.set_property_value(TextBlock.TextKey, "I");
            _textBlock16.set_property_value(TextBlock.FontStyleKey, FontStyle.Italic);
            _textBlock16.set_property_value(TextBlock.FontSizeKey, 15);
            _button2.Content = _textBlock16;
            _stackPanel14.AddChild(_button2);
            _button3 = new Button();
            _button3.Name = "UnderlineBtn";
            _button3.set_property_value(Button.VariantKey, ButtonVariant.Tonal);
            _button3.set_property_value(Button.MarginKey, new Thickness(6, 0, 0, 0));
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "U");
            _textBlock17.set_property_value(TextBlock.TextDecorationsKey, TextDecorations.Underline);
            _textBlock17.set_property_value(TextBlock.FontSizeKey, 15);
            _button3.Content = _textBlock17;
            _stackPanel14.AddChild(_button3);
            _button4 = new Button();
            _button4.Name = "IndentBtn";
            _button4.set_property_value(Button.VariantKey, ButtonVariant.Outlined);
            _button4.set_property_value(Button.MarginKey, new Thickness(16, 0, 0, 0));
            const _textBlock18 = new TextBlock();
            _textBlock18.set_property_value(TextBlock.TextKey, "Indent");
            _button4.Content = _textBlock18;
            _stackPanel14.AddChild(_button4);
            _button5 = new Button();
            _button5.Name = "OutdentBtn";
            _button5.set_property_value(Button.VariantKey, ButtonVariant.Outlined);
            _button5.set_property_value(Button.MarginKey, new Thickness(6, 0, 0, 0));
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "Outdent");
            _button5.Content = _textBlock19;
            _stackPanel14.AddChild(_button5);
            _border13.SetChild(_stackPanel14);
            _dockPanel8.AddChild(_border13);
            const _border20 = new Border();
            _border20.set_property_value(Border.PaddingKey, new Thickness(28, 24, 28, 24));
            _richTextBox6 = new RichTextBox();
            _richTextBox6.Name = "Editor";
            _richTextBox6.set_property_value(RichTextBox.VerticalAlignmentKey, VerticalAlignment.Top);
            _richTextBox6.set_property_value(RichTextBox.FontSizeKey, 15);
            const _flowDocument21 = new FlowDocument();
            const _paragraph22 = new Paragraph();
            const _run23 = new Run("Rich text editing in ");
            _paragraph22.AddChild(_run23);
            const _bold24 = new Bold();
            const _run25 = new Run("mural");
            _bold24.AddChild(_run25);
            _paragraph22.AddChild(_bold24);
            const _run26 = new Run(".");
            _paragraph22.AddChild(_run26);
            _flowDocument21.AddChild(_paragraph22);
            const _paragraph27 = new Paragraph();
            const _run28 = new Run("Select any text and toggle ");
            _paragraph27.AddChild(_run28);
            const _bold29 = new Bold();
            const _run30 = new Run("bold");
            _bold29.AddChild(_run30);
            _paragraph27.AddChild(_bold29);
            const _run31 = new Run(", ");
            _paragraph27.AddChild(_run31);
            const _italic32 = new Italic();
            const _run33 = new Run("italic");
            _italic32.AddChild(_run33);
            _paragraph27.AddChild(_italic32);
            const _run34 = new Run(", or ");
            _paragraph27.AddChild(_run34);
            const _underline35 = new Underline();
            const _run36 = new Run("underline");
            _underline35.AddChild(_run36);
            _paragraph27.AddChild(_underline35);
            const _run37 = new Run(". Press Enter to start a new paragraph, and keep typing to edit.");
            _paragraph27.AddChild(_run37);
            _flowDocument21.AddChild(_paragraph27);
            const _list38 = new List();
            _list38.set_property_value(List.MarkerStyleKey, ListMarkerStyle.Disc);
            const _listItem39 = new ListItem();
            const _paragraph40 = new Paragraph();
            const _run41 = new Run("A bulleted list item");
            _paragraph40.AddChild(_run41);
            _listItem39.AddChild(_paragraph40);
            _list38.AddChild(_listItem39);
            const _listItem42 = new ListItem();
            const _paragraph43 = new Paragraph();
            const _run44 = new Run("Put the caret here and press Tab to nest it, Shift+Tab to outdent");
            _paragraph43.AddChild(_run44);
            _listItem42.AddChild(_paragraph43);
            _list38.AddChild(_listItem42);
            _flowDocument21.AddChild(_list38);
            const _list45 = new List();
            _list45.set_property_value(List.MarkerStyleKey, ListMarkerStyle.Decimal);
            const _listItem46 = new ListItem();
            const _paragraph47 = new Paragraph();
            const _run48 = new Run("An ordered item");
            _paragraph47.AddChild(_run48);
            _listItem46.AddChild(_paragraph47);
            _list45.AddChild(_listItem46);
            const _listItem49 = new ListItem();
            const _paragraph50 = new Paragraph();
            const _run51 = new Run("Another ordered item");
            _paragraph50.AddChild(_run51);
            _listItem49.AddChild(_paragraph50);
            _list45.AddChild(_listItem49);
            _flowDocument21.AddChild(_list45);
            _richTextBox6.Document = _flowDocument21;
            _border20.SetChild(_richTextBox6);
            _dockPanel8.AddChild(_border20);
            _border7.SetChild(_dockPanel8);
            return _border7;
        }, RichTextEditorVM);
        t.Set("RichTextEditorTemplate", _tmpl0);
        return t;
    }
    get RichTextEditorTemplate() { return this.Resolve("RichTextEditorTemplate"); }
    set RichTextEditorTemplate(v) { this.Set("RichTextEditorTemplate", v); }
}
