import { Border, DataTemplate, DockPanel, Orientation, StackPanel, TextBlock, TextBox, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Color, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4._set_property_value_by_name(DockPanel, "Dock", "Top");
        _border4._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border4._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name("Text", "TextBox demo — single-line + multi-line");
        _textBlock5._set_property_value_by_name("FontSize", 15);
        _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock5._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _stackPanel7 = new StackPanel();
        _stackPanel7._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel7._set_property_value_by_name("Width", 300);
        _stackPanel7._set_property_value_by_name("Margin", new Thickness(16, 16, 8, 16));
        const _textBlock8 = new TextBlock();
        _textBlock8._set_property_value_by_name("Text", "Single-line:");
        _textBlock8._set_property_value_by_name("FontSize", 12);
        _textBlock8._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock8._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel7.AddChild(_textBlock8);
        const _textBox9 = new TextBox();
        _textBox9._set_property_value_by_name("Width", 260);
        _textBox9._set_property_value_by_name("Text", "This is a single-line TextBox whose content overflows the field width.");
        _stackPanel7.AddChild(_textBox9);
        const _textBlock10 = new TextBlock();
        _textBlock10._set_property_value_by_name("Text", "No scrollbar. Type / Home / End — text follows the caret.");
        _textBlock10._set_property_value_by_name("FontSize", 11);
        _textBlock10._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock10._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel7.AddChild(_textBlock10);
        _stackPanel6.AddChild(_stackPanel7);
        const _stackPanel11 = new StackPanel();
        _stackPanel11._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel11._set_property_value_by_name("Width", 300);
        _stackPanel11._set_property_value_by_name("Margin", new Thickness(8, 16, 8, 16));
        const _textBlock12 = new TextBlock();
        _textBlock12._set_property_value_by_name("Text", "Multi-line — Wrap:");
        _textBlock12._set_property_value_by_name("FontSize", 12);
        _textBlock12._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock12._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel11.AddChild(_textBlock12);
        const _textBox13 = new TextBox();
        _textBox13._set_property_value_by_name("Width", 280);
        _textBox13._set_property_value_by_name("Height", 160);
        _textBox13._set_property_value_by_name("AcceptsReturn", true);
        _textBox13._set_property_value_by_name("Text", "Default wrap mode: this paragraph is long enough that it should break across several visual lines at word boundaries. ArrowDown moves down visual rows.\nA hard newline starts a new logical line that also wraps on overflow.");
        _stackPanel11.AddChild(_textBox13);
        const _textBlock14 = new TextBlock();
        _textBlock14._set_property_value_by_name("Text", "Word-wrap. Resize the column to see lines re-flow.");
        _textBlock14._set_property_value_by_name("FontSize", 11);
        _textBlock14._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock14._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel11.AddChild(_textBlock14);
        _stackPanel6.AddChild(_stackPanel11);
        const _stackPanel15 = new StackPanel();
        _stackPanel15._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel15._set_property_value_by_name("Width", 300);
        _stackPanel15._set_property_value_by_name("Margin", new Thickness(8, 16, 16, 16));
        const _textBlock16 = new TextBlock();
        _textBlock16._set_property_value_by_name("Text", "Multi-line — NoWrap:");
        _textBlock16._set_property_value_by_name("FontSize", 12);
        _textBlock16._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock16._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel15.AddChild(_textBlock16);
        const _textBox17 = new TextBox();
        _textBox17._set_property_value_by_name("Width", 280);
        _textBox17._set_property_value_by_name("Height", 160);
        _textBox17._set_property_value_by_name("AcceptsReturn", true);
        _textBox17._set_property_value_by_name("AcceptsTab", true);
        _textBox17._set_property_value_by_name("TextWrapping", TextWrapping.NoWrap);
        _textBox17._set_property_value_by_name("Text", "function example() {\n    const longLineThatWillNotWrap = 'extends past the viewport horizontally';\n    return longLineThatWillNotWrap;\n}");
        _stackPanel15.AddChild(_textBox17);
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", "Both axes scroll; lines never break.");
        _textBlock18._set_property_value_by_name("FontSize", 11);
        _textBlock18._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock18._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel15.AddChild(_textBlock18);
        _stackPanel6.AddChild(_stackPanel15);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, "TextBoxVM");
    _rd0.Set("TextBoxTemplate", _tmpl1);
    return _rd0;
}
