import { AnimationVM } from "./animation-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/basic";
import { Button } from "@visualisation-sub/mural/framework/button.js";
import { Color, DynamicResource, NameScope, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_AnimationDemo = Symbol("AnimationDemo.ctor");
export class AnimationDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_AnimationDemo) {
            throw new Error("AnimationDemo is private — use AnimationDemo.Clone()");
        }
    }
    static Clone() {
        const t = new AnimationDemo(_gate_AnimationDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.SetNameScope(new NameScope());
            _border1.set_property_value(Border.BackgroundKey, DynamicResource(_border1, "Surface"));
            _border1.set_property_value(Border.BorderBrushKey, DynamicResource(_border1, "OutlineVariant"));
            _border1.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.BackgroundKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4.set_property_value(TextBlock.TextKey, "Animation — From/To, AutoReverse + Repeat, keyframes");
            _textBlock4.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock4.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock4.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel5.set_property_value(StackPanel.MarginKey, new Thickness(20, 20, 20, 20));
            const _stackPanel6 = new StackPanel();
            _stackPanel6.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel6.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock7 = new TextBlock();
            _textBlock7.set_property_value(TextBlock.TextKey, "Slide — Width animates 100 → 300 with CubicOut easing.");
            _textBlock7.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock7.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock7.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel6.AddChild(_textBlock7);
            const _stackPanel8 = new StackPanel();
            _stackPanel8.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _button9 = new Button();
            _button9.Name = "slideBtn";
            _button9.set_property_value(Button.WidthKey, 90);
            const _textBlock10 = new TextBlock();
            _textBlock10.set_property_value(TextBlock.TextKey, "Play");
            _button9.Content = _textBlock10;
            _stackPanel8.AddChild(_button9);
            const _border11 = new Border();
            _border11.Name = "slideTarget";
            _border11.set_property_value(Border.BackgroundKey, new SolidColorBrush(Color.FromHex('#4caf50')));
            _border11.set_property_value(Border.WidthKey, 100);
            _border11.set_property_value(Border.HeightKey, 24);
            _border11.set_property_value(Border.CornerRadiusKey, 4);
            _border11.set_property_value(Border.MarginKey, new Thickness(20, 4, 0, 0));
            _stackPanel8.AddChild(_border11);
            _stackPanel6.AddChild(_stackPanel8);
            const _textBlock12 = new TextBlock();
            _textBlock12.set_property_value(TextBlock.TextKey, "Click to reset and animate. Each click cancels any in-flight slide.");
            _textBlock12.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock12.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock12, "OnSurfaceVariant"));
            _textBlock12.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel6.AddChild(_textBlock12);
            _stackPanel5.AddChild(_stackPanel6);
            const _stackPanel13 = new StackPanel();
            _stackPanel13.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel13.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock14 = new TextBlock();
            _textBlock14.set_property_value(TextBlock.TextKey, "Bouncing loop — Width 100 ↔ 250, AutoReverse + Infinity.");
            _textBlock14.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock14.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock14.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel13.AddChild(_textBlock14);
            const _stackPanel15 = new StackPanel();
            _stackPanel15.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _button16 = new Button();
            _button16.Name = "loopBtn";
            _button16.set_property_value(Button.WidthKey, 90);
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "Start");
            _button16.Content = _textBlock17;
            _stackPanel15.AddChild(_button16);
            const _border18 = new Border();
            _border18.Name = "loopTarget";
            _border18.set_property_value(Border.BackgroundKey, DynamicResource(_border18, "Primary"));
            _border18.set_property_value(Border.WidthKey, 100);
            _border18.set_property_value(Border.HeightKey, 24);
            _border18.set_property_value(Border.CornerRadiusKey, 4);
            _border18.set_property_value(Border.MarginKey, new Thickness(20, 4, 0, 0));
            _stackPanel15.AddChild(_border18);
            _stackPanel13.AddChild(_stackPanel15);
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "Click again to Stop — the animation slot releases and Width returns to 100.");
            _textBlock19.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock19.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock19, "OnSurfaceVariant"));
            _textBlock19.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel13.AddChild(_textBlock19);
            _stackPanel5.AddChild(_stackPanel13);
            const _stackPanel20 = new StackPanel();
            _stackPanel20.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel20.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "Padding ripple — ThicknessAnimationUsingKeyFrames, 4 waypoints.");
            _textBlock21.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock21.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock21.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel20.AddChild(_textBlock21);
            const _stackPanel22 = new StackPanel();
            _stackPanel22.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _button23 = new Button();
            _button23.Name = "pulseBtn";
            _button23.set_property_value(Button.WidthKey, 90);
            const _textBlock24 = new TextBlock();
            _textBlock24.set_property_value(TextBlock.TextKey, "Play");
            _button23.Content = _textBlock24;
            _stackPanel22.AddChild(_button23);
            const _border25 = new Border();
            _border25.Name = "pulseTarget";
            _border25.set_property_value(Border.BackgroundKey, new SolidColorBrush(Color.FromHex('#4caf50')));
            _border25.set_property_value(Border.BorderBrushKey, DynamicResource(_border25, "Primary"));
            _border25.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _border25.set_property_value(Border.CornerRadiusKey, 4);
            _border25.set_property_value(Border.MarginKey, new Thickness(20, 4, 0, 0));
            _border25.set_property_value(Border.PaddingKey, new Thickness(8));
            const _textBlock26 = new TextBlock();
            _textBlock26.set_property_value(TextBlock.TextKey, "Padding ripple");
            _textBlock26.set_property_value(TextBlock.FontSizeKey, 11);
            _border25.SetChild(_textBlock26);
            _stackPanel22.AddChild(_border25);
            _stackPanel20.AddChild(_stackPanel22);
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, "Padding cycles (8) → (24, 8, 24, 8) → (8, 24, 8, 24) → (8).");
            _textBlock27.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock27.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock27, "OnSurfaceVariant"));
            _textBlock27.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel20.AddChild(_textBlock27);
            _stackPanel5.AddChild(_stackPanel20);
            const _stackPanel28 = new StackPanel();
            _stackPanel28.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel28.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, "Brush colour fade — SolidColorBrushAnimation on Background, cubic-bezier easing.");
            _textBlock29.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock29.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock29.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel28.AddChild(_textBlock29);
            const _stackPanel30 = new StackPanel();
            _stackPanel30.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _button31 = new Button();
            _button31.Name = "colorBtn";
            _button31.set_property_value(Button.WidthKey, 90);
            const _textBlock32 = new TextBlock();
            _textBlock32.set_property_value(TextBlock.TextKey, "Play");
            _button31.Content = _textBlock32;
            _stackPanel30.AddChild(_button31);
            const _border33 = new Border();
            _border33.Name = "colorTarget";
            _border33.set_property_value(Border.BackgroundKey, DynamicResource(_border33, "Primary"));
            _border33.set_property_value(Border.WidthKey, 140);
            _border33.set_property_value(Border.HeightKey, 24);
            _border33.set_property_value(Border.CornerRadiusKey, 4);
            _border33.set_property_value(Border.MarginKey, new Thickness(20, 4, 0, 0));
            _stackPanel30.AddChild(_border33);
            _stackPanel28.AddChild(_stackPanel30);
            const _textBlock34 = new TextBlock();
            _textBlock34.set_property_value(TextBlock.TextKey, "Background brush fades blue → green → blue using CSS-style ease-in-out.");
            _textBlock34.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock34.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock34, "OnSurfaceVariant"));
            _textBlock34.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel28.AddChild(_textBlock34);
            _stackPanel5.AddChild(_stackPanel28);
            const _stackPanel35 = new StackPanel();
            _stackPanel35.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock36 = new TextBlock();
            _textBlock36.set_property_value(TextBlock.TextKey, "Cubic-bezier easing — same animation, two control-point profiles.");
            _textBlock36.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock36.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock36.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel35.AddChild(_textBlock36);
            const _stackPanel37 = new StackPanel();
            _stackPanel37.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _button38 = new Button();
            _button38.Name = "bezierBtn";
            _button38.set_property_value(Button.WidthKey, 90);
            const _textBlock39 = new TextBlock();
            _textBlock39.set_property_value(TextBlock.TextKey, "Play both");
            _button38.Content = _textBlock39;
            _stackPanel37.AddChild(_button38);
            const _stackPanel40 = new StackPanel();
            _stackPanel40.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel40.set_property_value(StackPanel.MarginKey, new Thickness(20, 0, 0, 0));
            const _border41 = new Border();
            _border41.Name = "bezierA";
            _border41.set_property_value(Border.BackgroundKey, DynamicResource(_border41, "Primary"));
            _border41.set_property_value(Border.WidthKey, 100);
            _border41.set_property_value(Border.HeightKey, 14);
            _border41.set_property_value(Border.CornerRadiusKey, 2);
            _border41.set_property_value(Border.MarginKey, new Thickness(0, 2, 0, 2));
            _stackPanel40.AddChild(_border41);
            const _border42 = new Border();
            _border42.Name = "bezierB";
            _border42.set_property_value(Border.BackgroundKey, new SolidColorBrush(Color.FromHex('#4caf50')));
            _border42.set_property_value(Border.WidthKey, 100);
            _border42.set_property_value(Border.HeightKey, 14);
            _border42.set_property_value(Border.CornerRadiusKey, 2);
            _border42.set_property_value(Border.MarginKey, new Thickness(0, 2, 0, 2));
            _stackPanel40.AddChild(_border42);
            _stackPanel37.AddChild(_stackPanel40);
            _stackPanel35.AddChild(_stackPanel37);
            const _textBlock43 = new TextBlock();
            _textBlock43.set_property_value(TextBlock.TextKey, "Top: linear. Bottom: cubicBezier(0.68, -0.55, 0.27, 1.55) — anticipate + overshoot.");
            _textBlock43.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock43.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock43, "OnSurfaceVariant"));
            _textBlock43.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel35.AddChild(_textBlock43);
            _stackPanel5.AddChild(_stackPanel35);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, AnimationVM);
        t.Set("AnimationTemplate", _tmpl0);
        return t;
    }
    get AnimationTemplate() { return this.Resolve("AnimationTemplate"); }
    set AnimationTemplate(v) { this.Set("AnimationTemplate", v); }
}
