import { AnimationVM } from "./animation-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Basic";
import { Button } from "@visualisation-sub/mural/framework/button.js";
import { Color, DynamicResource, NameScope, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2.SetNameScope(new NameScope());
        _border2._set_property_value_by_name("Background", DynamicResource(_border2, "Surface"));
        _border2._set_property_value_by_name("BorderBrush", DynamicResource(_border2, "OutlineVariant"));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border4._set_property_value_by_name("Background", DynamicResource(_border4, "Primary"));
        _border4._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name("Text", "Animation — From/To, AutoReverse + Repeat, keyframes");
        _textBlock5._set_property_value_by_name("FontSize", 15);
        _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock5._set_property_value_by_name("Foreground", DynamicResource(_textBlock5, "OnPrimary"));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel6._set_property_value_by_name("Margin", new Thickness(20, 20, 20, 20));
        const _stackPanel7 = new StackPanel();
        _stackPanel7._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel7._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 24));
        const _textBlock8 = new TextBlock();
        _textBlock8._set_property_value_by_name("Text", "Slide — Width animates 100 → 300 with CubicOut easing.");
        _textBlock8._set_property_value_by_name("FontSize", 12);
        _textBlock8._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock8._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel7.AddChild(_textBlock8);
        const _stackPanel9 = new StackPanel();
        _stackPanel9._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _button10 = new Button();
        _button10.Name = "slideBtn";
        _button10._set_property_value_by_name("Width", 90);
        const _textBlock11 = new TextBlock();
        _textBlock11._set_property_value_by_name("Text", "Play");
        _button10.Content = _textBlock11;
        _stackPanel9.AddChild(_button10);
        const _border12 = new Border();
        _border12.Name = "slideTarget";
        _border12._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#4caf50')));
        _border12._set_property_value_by_name("Width", 100);
        _border12._set_property_value_by_name("Height", 24);
        _border12._set_property_value_by_name("CornerRadius", 4);
        _border12._set_property_value_by_name("Margin", new Thickness(20, 4, 0, 0));
        _stackPanel9.AddChild(_border12);
        _stackPanel7.AddChild(_stackPanel9);
        const _textBlock13 = new TextBlock();
        _textBlock13._set_property_value_by_name("Text", "Click to reset and animate. Each click cancels any in-flight slide.");
        _textBlock13._set_property_value_by_name("FontSize", 11);
        _textBlock13._set_property_value_by_name("Foreground", DynamicResource(_textBlock13, "OnSurfaceVariant"));
        _textBlock13._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel7.AddChild(_textBlock13);
        _stackPanel6.AddChild(_stackPanel7);
        const _stackPanel14 = new StackPanel();
        _stackPanel14._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel14._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 24));
        const _textBlock15 = new TextBlock();
        _textBlock15._set_property_value_by_name("Text", "Bouncing loop — Width 100 ↔ 250, AutoReverse + Infinity.");
        _textBlock15._set_property_value_by_name("FontSize", 12);
        _textBlock15._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock15._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel14.AddChild(_textBlock15);
        const _stackPanel16 = new StackPanel();
        _stackPanel16._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _button17 = new Button();
        _button17.Name = "loopBtn";
        _button17._set_property_value_by_name("Width", 90);
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", "Start");
        _button17.Content = _textBlock18;
        _stackPanel16.AddChild(_button17);
        const _border19 = new Border();
        _border19.Name = "loopTarget";
        _border19._set_property_value_by_name("Background", DynamicResource(_border19, "Primary"));
        _border19._set_property_value_by_name("Width", 100);
        _border19._set_property_value_by_name("Height", 24);
        _border19._set_property_value_by_name("CornerRadius", 4);
        _border19._set_property_value_by_name("Margin", new Thickness(20, 4, 0, 0));
        _stackPanel16.AddChild(_border19);
        _stackPanel14.AddChild(_stackPanel16);
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "Click again to Stop — the animation slot releases and Width returns to 100.");
        _textBlock20._set_property_value_by_name("FontSize", 11);
        _textBlock20._set_property_value_by_name("Foreground", DynamicResource(_textBlock20, "OnSurfaceVariant"));
        _textBlock20._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel14.AddChild(_textBlock20);
        _stackPanel6.AddChild(_stackPanel14);
        const _stackPanel21 = new StackPanel();
        _stackPanel21._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel21._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 24));
        const _textBlock22 = new TextBlock();
        _textBlock22._set_property_value_by_name("Text", "Padding ripple — ThicknessAnimationUsingKeyFrames, 4 waypoints.");
        _textBlock22._set_property_value_by_name("FontSize", 12);
        _textBlock22._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock22._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel21.AddChild(_textBlock22);
        const _stackPanel23 = new StackPanel();
        _stackPanel23._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _button24 = new Button();
        _button24.Name = "pulseBtn";
        _button24._set_property_value_by_name("Width", 90);
        const _textBlock25 = new TextBlock();
        _textBlock25._set_property_value_by_name("Text", "Play");
        _button24.Content = _textBlock25;
        _stackPanel23.AddChild(_button24);
        const _border26 = new Border();
        _border26.Name = "pulseTarget";
        _border26._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#4caf50')));
        _border26._set_property_value_by_name("BorderBrush", DynamicResource(_border26, "Primary"));
        _border26._set_property_value_by_name("BorderThickness", new Thickness(1));
        _border26._set_property_value_by_name("CornerRadius", 4);
        _border26._set_property_value_by_name("Margin", new Thickness(20, 4, 0, 0));
        _border26._set_property_value_by_name("Padding", new Thickness(8));
        const _textBlock27 = new TextBlock();
        _textBlock27._set_property_value_by_name("Text", "Padding ripple");
        _textBlock27._set_property_value_by_name("FontSize", 11);
        _border26.SetChild(_textBlock27);
        _stackPanel23.AddChild(_border26);
        _stackPanel21.AddChild(_stackPanel23);
        const _textBlock28 = new TextBlock();
        _textBlock28._set_property_value_by_name("Text", "Padding cycles (8) → (24, 8, 24, 8) → (8, 24, 8, 24) → (8).");
        _textBlock28._set_property_value_by_name("FontSize", 11);
        _textBlock28._set_property_value_by_name("Foreground", DynamicResource(_textBlock28, "OnSurfaceVariant"));
        _textBlock28._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel21.AddChild(_textBlock28);
        _stackPanel6.AddChild(_stackPanel21);
        const _stackPanel29 = new StackPanel();
        _stackPanel29._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel29._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 24));
        const _textBlock30 = new TextBlock();
        _textBlock30._set_property_value_by_name("Text", "Brush colour fade — SolidColorBrushAnimation on Background, cubic-bezier easing.");
        _textBlock30._set_property_value_by_name("FontSize", 12);
        _textBlock30._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock30._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel29.AddChild(_textBlock30);
        const _stackPanel31 = new StackPanel();
        _stackPanel31._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _button32 = new Button();
        _button32.Name = "colorBtn";
        _button32._set_property_value_by_name("Width", 90);
        const _textBlock33 = new TextBlock();
        _textBlock33._set_property_value_by_name("Text", "Play");
        _button32.Content = _textBlock33;
        _stackPanel31.AddChild(_button32);
        const _border34 = new Border();
        _border34.Name = "colorTarget";
        _border34._set_property_value_by_name("Background", DynamicResource(_border34, "Primary"));
        _border34._set_property_value_by_name("Width", 140);
        _border34._set_property_value_by_name("Height", 24);
        _border34._set_property_value_by_name("CornerRadius", 4);
        _border34._set_property_value_by_name("Margin", new Thickness(20, 4, 0, 0));
        _stackPanel31.AddChild(_border34);
        _stackPanel29.AddChild(_stackPanel31);
        const _textBlock35 = new TextBlock();
        _textBlock35._set_property_value_by_name("Text", "Background brush fades blue → green → blue using CSS-style ease-in-out.");
        _textBlock35._set_property_value_by_name("FontSize", 11);
        _textBlock35._set_property_value_by_name("Foreground", DynamicResource(_textBlock35, "OnSurfaceVariant"));
        _textBlock35._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel29.AddChild(_textBlock35);
        _stackPanel6.AddChild(_stackPanel29);
        const _stackPanel36 = new StackPanel();
        _stackPanel36._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _textBlock37 = new TextBlock();
        _textBlock37._set_property_value_by_name("Text", "Cubic-bezier easing — same animation, two control-point profiles.");
        _textBlock37._set_property_value_by_name("FontSize", 12);
        _textBlock37._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock37._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel36.AddChild(_textBlock37);
        const _stackPanel38 = new StackPanel();
        _stackPanel38._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _button39 = new Button();
        _button39.Name = "bezierBtn";
        _button39._set_property_value_by_name("Width", 90);
        const _textBlock40 = new TextBlock();
        _textBlock40._set_property_value_by_name("Text", "Play both");
        _button39.Content = _textBlock40;
        _stackPanel38.AddChild(_button39);
        const _stackPanel41 = new StackPanel();
        _stackPanel41._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel41._set_property_value_by_name("Margin", new Thickness(20, 0, 0, 0));
        const _border42 = new Border();
        _border42.Name = "bezierA";
        _border42._set_property_value_by_name("Background", DynamicResource(_border42, "Primary"));
        _border42._set_property_value_by_name("Width", 100);
        _border42._set_property_value_by_name("Height", 14);
        _border42._set_property_value_by_name("CornerRadius", 2);
        _border42._set_property_value_by_name("Margin", new Thickness(0, 2, 0, 2));
        _stackPanel41.AddChild(_border42);
        const _border43 = new Border();
        _border43.Name = "bezierB";
        _border43._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#4caf50')));
        _border43._set_property_value_by_name("Width", 100);
        _border43._set_property_value_by_name("Height", 14);
        _border43._set_property_value_by_name("CornerRadius", 2);
        _border43._set_property_value_by_name("Margin", new Thickness(0, 2, 0, 2));
        _stackPanel41.AddChild(_border43);
        _stackPanel38.AddChild(_stackPanel41);
        _stackPanel36.AddChild(_stackPanel38);
        const _textBlock44 = new TextBlock();
        _textBlock44._set_property_value_by_name("Text", "Top: linear. Bottom: cubicBezier(0.68, -0.55, 0.27, 1.55) — anticipate + overshoot.");
        _textBlock44._set_property_value_by_name("FontSize", 11);
        _textBlock44._set_property_value_by_name("Foreground", DynamicResource(_textBlock44, "OnSurfaceVariant"));
        _textBlock44._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel36.AddChild(_textBlock44);
        _stackPanel6.AddChild(_stackPanel36);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, AnimationVM);
    _rd0.Set("AnimationTemplate", _tmpl1);
    return _rd0;
}
