import { AnimationVM } from "./animation-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@pragmatic-lab/mural/basic";
import { Button } from "@pragmatic-lab/mural/framework/buttons/button.js";
import { Color, DynamicResource, NameScope, ResourceDictionary, Thickness } from "@pragmatic-lab/mural/runtime";
import { FontWeight, SolidColorBrush } from "@pragmatic-lab/mural/visual-engine";


const _gate_AnimationDemo = Symbol("AnimationDemo.ctor");
export class AnimationDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_AnimationDemo) {
            throw new Error("AnimationDemo is private — use AnimationDemo.Clone()");
        }
    }
    static Clone() {
        const t = new AnimationDemo(_gate_AnimationDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            let _button1, _border2, _button3, _border4, _button5, _border6, _button7, _border8, _button9, _border10, _border11;
            const _border12 = new Border();
            _border12.SetNameScope(new NameScope());
            _border12.set_property_value(Border.FillKey, DynamicResource(_border12, "Surface"));
            _border12.set_property_value(Border.BorderBrushKey, DynamicResource(_border12, "OutlineVariant"));
            _border12.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _dockPanel13 = new DockPanel();
            const _border14 = new Border();
            _border14.set_property_value(DockPanel.DockKey, Dock.Top);
            _border14.set_property_value(Border.FillKey, DynamicResource(_border14, "Primary"));
            _border14.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, "Animation — From/To, AutoReverse + Repeat, keyframes");
            _textBlock15.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock15.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock15.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock15, "OnPrimary"));
            _border14.SetChild(_textBlock15);
            _dockPanel13.AddChild(_border14);
            const _stackPanel16 = new StackPanel();
            _stackPanel16.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel16.set_property_value(StackPanel.MarginKey, new Thickness(20, 20, 20, 20));
            const _stackPanel17 = new StackPanel();
            _stackPanel17.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel17.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock18 = new TextBlock();
            _textBlock18.set_property_value(TextBlock.TextKey, "Slide — Width animates 100 → 300 with CubicOut easing.");
            _textBlock18.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock18.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock18.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel17.AddChild(_textBlock18);
            const _stackPanel19 = new StackPanel();
            _stackPanel19.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _button1 = new Button();
            _button1.Name = "slideBtn";
            _button1.set_property_value(Button.WidthKey, 90);
            const _textBlock20 = new TextBlock();
            _textBlock20.set_property_value(TextBlock.TextKey, "Play");
            _button1.Content = _textBlock20;
            _stackPanel19.AddChild(_button1);
            _border2 = new Border();
            _border2.Name = "slideTarget";
            _border2.set_property_value(Border.FillKey, new SolidColorBrush(Color.FromHex('#4caf50')));
            _border2.set_property_value(Border.WidthKey, 100);
            _border2.set_property_value(Border.HeightKey, 24);
            _border2.set_property_value(Border.CornerRadiusKey, 4);
            _border2.set_property_value(Border.MarginKey, new Thickness(20, 4, 0, 0));
            _stackPanel19.AddChild(_border2);
            _stackPanel17.AddChild(_stackPanel19);
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "Click to reset and animate. Each click cancels any in-flight slide.");
            _textBlock21.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock21.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock21, "OnSurfaceVariant"));
            _textBlock21.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel17.AddChild(_textBlock21);
            _stackPanel16.AddChild(_stackPanel17);
            const _stackPanel22 = new StackPanel();
            _stackPanel22.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel22.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, "Bouncing loop — Width 100 ↔ 250, AutoReverse + Infinity.");
            _textBlock23.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock23.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock23.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel22.AddChild(_textBlock23);
            const _stackPanel24 = new StackPanel();
            _stackPanel24.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _button3 = new Button();
            _button3.Name = "loopBtn";
            _button3.set_property_value(Button.WidthKey, 90);
            const _textBlock25 = new TextBlock();
            _textBlock25.set_property_value(TextBlock.TextKey, "Start");
            _button3.Content = _textBlock25;
            _stackPanel24.AddChild(_button3);
            _border4 = new Border();
            _border4.Name = "loopTarget";
            _border4.set_property_value(Border.FillKey, DynamicResource(_border4, "Primary"));
            _border4.set_property_value(Border.WidthKey, 100);
            _border4.set_property_value(Border.HeightKey, 24);
            _border4.set_property_value(Border.CornerRadiusKey, 4);
            _border4.set_property_value(Border.MarginKey, new Thickness(20, 4, 0, 0));
            _stackPanel24.AddChild(_border4);
            _stackPanel22.AddChild(_stackPanel24);
            const _textBlock26 = new TextBlock();
            _textBlock26.set_property_value(TextBlock.TextKey, "Click again to Stop — the animation slot releases and Width returns to 100.");
            _textBlock26.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock26.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock26, "OnSurfaceVariant"));
            _textBlock26.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel22.AddChild(_textBlock26);
            _stackPanel16.AddChild(_stackPanel22);
            const _stackPanel27 = new StackPanel();
            _stackPanel27.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel27.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock28 = new TextBlock();
            _textBlock28.set_property_value(TextBlock.TextKey, "Padding ripple — ThicknessAnimationUsingKeyFrames, 4 waypoints.");
            _textBlock28.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock28.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock28.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel27.AddChild(_textBlock28);
            const _stackPanel29 = new StackPanel();
            _stackPanel29.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _button5 = new Button();
            _button5.Name = "pulseBtn";
            _button5.set_property_value(Button.WidthKey, 90);
            const _textBlock30 = new TextBlock();
            _textBlock30.set_property_value(TextBlock.TextKey, "Play");
            _button5.Content = _textBlock30;
            _stackPanel29.AddChild(_button5);
            _border6 = new Border();
            _border6.Name = "pulseTarget";
            _border6.set_property_value(Border.FillKey, new SolidColorBrush(Color.FromHex('#4caf50')));
            _border6.set_property_value(Border.BorderBrushKey, DynamicResource(_border6, "Primary"));
            _border6.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _border6.set_property_value(Border.CornerRadiusKey, 4);
            _border6.set_property_value(Border.MarginKey, new Thickness(20, 4, 0, 0));
            _border6.set_property_value(Border.PaddingKey, new Thickness(8));
            const _textBlock31 = new TextBlock();
            _textBlock31.set_property_value(TextBlock.TextKey, "Padding ripple");
            _textBlock31.set_property_value(TextBlock.FontSizeKey, 11);
            _border6.SetChild(_textBlock31);
            _stackPanel29.AddChild(_border6);
            _stackPanel27.AddChild(_stackPanel29);
            const _textBlock32 = new TextBlock();
            _textBlock32.set_property_value(TextBlock.TextKey, "Padding cycles (8) → (24, 8, 24, 8) → (8, 24, 8, 24) → (8).");
            _textBlock32.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock32.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock32, "OnSurfaceVariant"));
            _textBlock32.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel27.AddChild(_textBlock32);
            _stackPanel16.AddChild(_stackPanel27);
            const _stackPanel33 = new StackPanel();
            _stackPanel33.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel33.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock34 = new TextBlock();
            _textBlock34.set_property_value(TextBlock.TextKey, "Brush colour fade — SolidColorBrushAnimation on Fill, cubic-bezier easing.");
            _textBlock34.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock34.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock34.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel33.AddChild(_textBlock34);
            const _stackPanel35 = new StackPanel();
            _stackPanel35.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _button7 = new Button();
            _button7.Name = "colorBtn";
            _button7.set_property_value(Button.WidthKey, 90);
            const _textBlock36 = new TextBlock();
            _textBlock36.set_property_value(TextBlock.TextKey, "Play");
            _button7.Content = _textBlock36;
            _stackPanel35.AddChild(_button7);
            _border8 = new Border();
            _border8.Name = "colorTarget";
            _border8.set_property_value(Border.FillKey, DynamicResource(_border8, "Primary"));
            _border8.set_property_value(Border.WidthKey, 140);
            _border8.set_property_value(Border.HeightKey, 24);
            _border8.set_property_value(Border.CornerRadiusKey, 4);
            _border8.set_property_value(Border.MarginKey, new Thickness(20, 4, 0, 0));
            _stackPanel35.AddChild(_border8);
            _stackPanel33.AddChild(_stackPanel35);
            const _textBlock37 = new TextBlock();
            _textBlock37.set_property_value(TextBlock.TextKey, "Fill brush fades blue → green → blue using CSS-style ease-in-out.");
            _textBlock37.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock37.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock37, "OnSurfaceVariant"));
            _textBlock37.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel33.AddChild(_textBlock37);
            _stackPanel16.AddChild(_stackPanel33);
            const _stackPanel38 = new StackPanel();
            _stackPanel38.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock39 = new TextBlock();
            _textBlock39.set_property_value(TextBlock.TextKey, "Cubic-bezier easing — same animation, two control-point profiles.");
            _textBlock39.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock39.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock39.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel38.AddChild(_textBlock39);
            const _stackPanel40 = new StackPanel();
            _stackPanel40.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _button9 = new Button();
            _button9.Name = "bezierBtn";
            _button9.set_property_value(Button.WidthKey, 90);
            const _textBlock41 = new TextBlock();
            _textBlock41.set_property_value(TextBlock.TextKey, "Play both");
            _button9.Content = _textBlock41;
            _stackPanel40.AddChild(_button9);
            const _stackPanel42 = new StackPanel();
            _stackPanel42.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel42.set_property_value(StackPanel.MarginKey, new Thickness(20, 0, 0, 0));
            _border10 = new Border();
            _border10.Name = "bezierA";
            _border10.set_property_value(Border.FillKey, DynamicResource(_border10, "Primary"));
            _border10.set_property_value(Border.WidthKey, 100);
            _border10.set_property_value(Border.HeightKey, 14);
            _border10.set_property_value(Border.CornerRadiusKey, 2);
            _border10.set_property_value(Border.MarginKey, new Thickness(0, 2, 0, 2));
            _stackPanel42.AddChild(_border10);
            _border11 = new Border();
            _border11.Name = "bezierB";
            _border11.set_property_value(Border.FillKey, new SolidColorBrush(Color.FromHex('#4caf50')));
            _border11.set_property_value(Border.WidthKey, 100);
            _border11.set_property_value(Border.HeightKey, 14);
            _border11.set_property_value(Border.CornerRadiusKey, 2);
            _border11.set_property_value(Border.MarginKey, new Thickness(0, 2, 0, 2));
            _stackPanel42.AddChild(_border11);
            _stackPanel40.AddChild(_stackPanel42);
            _stackPanel38.AddChild(_stackPanel40);
            const _textBlock43 = new TextBlock();
            _textBlock43.set_property_value(TextBlock.TextKey, "Top: linear. Bottom: cubicBezier(0.68, -0.55, 0.27, 1.55) — anticipate + overshoot.");
            _textBlock43.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock43.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock43, "OnSurfaceVariant"));
            _textBlock43.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel38.AddChild(_textBlock43);
            _stackPanel16.AddChild(_stackPanel38);
            _dockPanel13.AddChild(_stackPanel16);
            _border12.SetChild(_dockPanel13);
            return _border12;
        }, AnimationVM);
        t.Set(AnimationVM, _tmpl0);
        return t;
    }
}
