import { FabVM } from "./fab-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/basic";
import { FabSize, FloatingActionButton } from "@visualisation-sub/mural/framework/fab.js";
import { DataContextBinding, DynamicResource, ResourceDictionary, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_FabDemo = Symbol("FabDemo.ctor");
export class FabDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_FabDemo) {
            throw new Error("FabDemo is private — use FabDemo.Clone()");
        }
    }
    static Clone() {
        const t = new FabDemo(_gate_FabDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1._set_property_value_by_name("Background", DynamicResource(_border1, "Surface"));
            _border1._set_property_value_by_name("BorderBrush", DynamicResource(_border1, "OutlineVariant"));
            _border1._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border3._set_property_value_by_name("Background", DynamicResource(_border3, "Primary"));
            _border3._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4._set_property_value_by_name("Text", "FloatingActionButton — M3's primary screen action. Size drives chrome dimensions; Extended slots an icon + label.");
            _textBlock4._set_property_value_by_name("FontSize", 15);
            _textBlock4._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock4._set_property_value_by_name("Foreground", DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel5._set_property_value_by_name("Margin", new Thickness(24, 24, 24, 24));
            const _textBlock6 = new TextBlock();
            _textBlock6._set_property_value_by_name("Text", "Icon-only — Size: Small (40dp) / Default (56dp) / Large (96dp)");
            _textBlock6._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock6._set_property_value_by_name("FontSize", 14);
            _textBlock6._set_property_value_by_name("Foreground", DynamicResource(_textBlock6, "OnSurface"));
            _textBlock6._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 12));
            _stackPanel5.AddChild(_textBlock6);
            const _stackPanel7 = new StackPanel();
            _stackPanel7._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel7._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _stackPanel7._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            const _floatingActionButton8 = new FloatingActionButton();
            _floatingActionButton8._set_property_value_by_name("Size", FabSize.Small);
            _floatingActionButton8._set_property_value_by_name("Command", DataContextBinding(_floatingActionButton8, "ClickSmallCommand"));
            _floatingActionButton8._set_property_value_by_name("Margin", new Thickness(0, 0, 24, 0));
            const _textBlock9 = new TextBlock();
            _textBlock9._set_property_value_by_name("Text", "+");
            _textBlock9._set_property_value_by_name("FontSize", 20);
            _floatingActionButton8.Content = _textBlock9;
            _stackPanel7.AddChild(_floatingActionButton8);
            const _floatingActionButton10 = new FloatingActionButton();
            _floatingActionButton10._set_property_value_by_name("Size", FabSize.Default);
            _floatingActionButton10._set_property_value_by_name("Command", DataContextBinding(_floatingActionButton10, "ClickDefaultCommand"));
            _floatingActionButton10._set_property_value_by_name("Margin", new Thickness(0, 0, 24, 0));
            const _textBlock11 = new TextBlock();
            _textBlock11._set_property_value_by_name("Text", "✎");
            _textBlock11._set_property_value_by_name("FontSize", 22);
            _floatingActionButton10.Content = _textBlock11;
            _stackPanel7.AddChild(_floatingActionButton10);
            const _floatingActionButton12 = new FloatingActionButton();
            _floatingActionButton12._set_property_value_by_name("Size", FabSize.Large);
            _floatingActionButton12._set_property_value_by_name("Command", DataContextBinding(_floatingActionButton12, "ClickLargeCommand"));
            const _textBlock13 = new TextBlock();
            _textBlock13._set_property_value_by_name("Text", "★");
            _textBlock13._set_property_value_by_name("FontSize", 34);
            _floatingActionButton12.Content = _textBlock13;
            _stackPanel7.AddChild(_floatingActionButton12);
            _stackPanel5.AddChild(_stackPanel7);
            const _stackPanel14 = new StackPanel();
            _stackPanel14._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel14._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 24));
            const _textBlock15 = new TextBlock();
            _textBlock15._set_property_value_by_name("Text", "Clicks — Small: ");
            _textBlock15._set_property_value_by_name("FontSize", 12);
            _textBlock15._set_property_value_by_name("Foreground", DynamicResource(_textBlock15, "OnSurfaceVariant"));
            _stackPanel14.AddChild(_textBlock15);
            const _textBlock16 = new TextBlock();
            _textBlock16._set_property_value_by_name("Text", DataContextBinding(_textBlock16, "SmallClicks"));
            _textBlock16._set_property_value_by_name("FontSize", 12);
            _textBlock16._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock16._set_property_value_by_name("Foreground", DynamicResource(_textBlock16, "OnSurface"));
            _stackPanel14.AddChild(_textBlock16);
            const _textBlock17 = new TextBlock();
            _textBlock17._set_property_value_by_name("Text", "  Default: ");
            _textBlock17._set_property_value_by_name("FontSize", 12);
            _textBlock17._set_property_value_by_name("Foreground", DynamicResource(_textBlock17, "OnSurfaceVariant"));
            _stackPanel14.AddChild(_textBlock17);
            const _textBlock18 = new TextBlock();
            _textBlock18._set_property_value_by_name("Text", DataContextBinding(_textBlock18, "DefaultClicks"));
            _textBlock18._set_property_value_by_name("FontSize", 12);
            _textBlock18._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock18._set_property_value_by_name("Foreground", DynamicResource(_textBlock18, "OnSurface"));
            _stackPanel14.AddChild(_textBlock18);
            const _textBlock19 = new TextBlock();
            _textBlock19._set_property_value_by_name("Text", "  Large: ");
            _textBlock19._set_property_value_by_name("FontSize", 12);
            _textBlock19._set_property_value_by_name("Foreground", DynamicResource(_textBlock19, "OnSurfaceVariant"));
            _stackPanel14.AddChild(_textBlock19);
            const _textBlock20 = new TextBlock();
            _textBlock20._set_property_value_by_name("Text", DataContextBinding(_textBlock20, "LargeClicks"));
            _textBlock20._set_property_value_by_name("FontSize", 12);
            _textBlock20._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock20._set_property_value_by_name("Foreground", DynamicResource(_textBlock20, "OnSurface"));
            _stackPanel14.AddChild(_textBlock20);
            _stackPanel5.AddChild(_stackPanel14);
            const _textBlock21 = new TextBlock();
            _textBlock21._set_property_value_by_name("Text", "Extended — 56dp tall, content-driven width. Slot accepts icon + label.");
            _textBlock21._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock21._set_property_value_by_name("FontSize", 14);
            _textBlock21._set_property_value_by_name("Foreground", DynamicResource(_textBlock21, "OnSurface"));
            _textBlock21._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 12));
            _stackPanel5.AddChild(_textBlock21);
            const _stackPanel22 = new StackPanel();
            _stackPanel22._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel22._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _stackPanel22._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            const _floatingActionButton23 = new FloatingActionButton();
            _floatingActionButton23._set_property_value_by_name("Size", FabSize.Extended);
            _floatingActionButton23._set_property_value_by_name("Command", DataContextBinding(_floatingActionButton23, "ClickExtendedCommand"));
            _floatingActionButton23._set_property_value_by_name("Margin", new Thickness(0, 0, 24, 0));
            const _stackPanel24 = new StackPanel();
            _stackPanel24._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel24._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            const _textBlock25 = new TextBlock();
            _textBlock25._set_property_value_by_name("Text", "✎");
            _textBlock25._set_property_value_by_name("FontSize", 18);
            _textBlock25._set_property_value_by_name("Margin", new Thickness(0, 0, 12, 0));
            _stackPanel24.AddChild(_textBlock25);
            const _textBlock26 = new TextBlock();
            _textBlock26._set_property_value_by_name("Text", "Edit");
            _stackPanel24.AddChild(_textBlock26);
            _floatingActionButton23.Content = _stackPanel24;
            _stackPanel22.AddChild(_floatingActionButton23);
            const _floatingActionButton27 = new FloatingActionButton();
            _floatingActionButton27._set_property_value_by_name("Size", FabSize.Extended);
            _floatingActionButton27._set_property_value_by_name("Command", DataContextBinding(_floatingActionButton27, "ClickComposeCommand"));
            const _stackPanel28 = new StackPanel();
            _stackPanel28._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel28._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            const _textBlock29 = new TextBlock();
            _textBlock29._set_property_value_by_name("Text", "✉");
            _textBlock29._set_property_value_by_name("FontSize", 18);
            _textBlock29._set_property_value_by_name("Margin", new Thickness(0, 0, 12, 0));
            _stackPanel28.AddChild(_textBlock29);
            const _textBlock30 = new TextBlock();
            _textBlock30._set_property_value_by_name("Text", "Compose");
            _stackPanel28.AddChild(_textBlock30);
            _floatingActionButton27.Content = _stackPanel28;
            _stackPanel22.AddChild(_floatingActionButton27);
            _stackPanel5.AddChild(_stackPanel22);
            const _stackPanel31 = new StackPanel();
            _stackPanel31._set_property_value_by_name("Orientation", Orientation.Horizontal);
            const _textBlock32 = new TextBlock();
            _textBlock32._set_property_value_by_name("Text", "Clicks — Edit: ");
            _textBlock32._set_property_value_by_name("FontSize", 12);
            _textBlock32._set_property_value_by_name("Foreground", DynamicResource(_textBlock32, "OnSurfaceVariant"));
            _stackPanel31.AddChild(_textBlock32);
            const _textBlock33 = new TextBlock();
            _textBlock33._set_property_value_by_name("Text", DataContextBinding(_textBlock33, "ExtendedClicks"));
            _textBlock33._set_property_value_by_name("FontSize", 12);
            _textBlock33._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock33._set_property_value_by_name("Foreground", DynamicResource(_textBlock33, "OnSurface"));
            _stackPanel31.AddChild(_textBlock33);
            const _textBlock34 = new TextBlock();
            _textBlock34._set_property_value_by_name("Text", "  Compose: ");
            _textBlock34._set_property_value_by_name("FontSize", 12);
            _textBlock34._set_property_value_by_name("Foreground", DynamicResource(_textBlock34, "OnSurfaceVariant"));
            _stackPanel31.AddChild(_textBlock34);
            const _textBlock35 = new TextBlock();
            _textBlock35._set_property_value_by_name("Text", DataContextBinding(_textBlock35, "ComposeClicks"));
            _textBlock35._set_property_value_by_name("FontSize", 12);
            _textBlock35._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock35._set_property_value_by_name("Foreground", DynamicResource(_textBlock35, "OnSurface"));
            _stackPanel31.AddChild(_textBlock35);
            _stackPanel5.AddChild(_stackPanel31);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, FabVM);
        t.Set("FabTemplate", _tmpl0);
        return t;
    }
    get FabTemplate() { return this.Resolve("FabTemplate"); }
    set FabTemplate(v) { this.Set("FabTemplate", v); }
}
