import { FabVM } from "./fab-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@pragmatic-lab/mural/basic";
import { FabSize, FloatingActionButton } from "@pragmatic-lab/mural/framework/buttons/fab.js";
import { DataContextBinding, DynamicResource, ResourceDictionary, Thickness, VerticalAlignment } from "@pragmatic-lab/mural/runtime";
import { FontWeight } from "@pragmatic-lab/mural/visual-engine";


const _gate_FabDemo = Symbol("FabDemo.ctor");
export class FabDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_FabDemo) {
            throw new Error("FabDemo is private — use FabDemo.Clone()");
        }
    }
    static Clone() {
        const t = new FabDemo(_gate_FabDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.set_property_value(Border.FillKey, DynamicResource(_border1, "Surface"));
            _border1.set_property_value(Border.BorderBrushKey, DynamicResource(_border1, "OutlineVariant"));
            _border1.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.FillKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4.set_property_value(TextBlock.TextKey, "FloatingActionButton — M3's primary screen action. Size drives chrome dimensions; Extended slots an icon + label.");
            _textBlock4.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock4.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock4.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel5.set_property_value(StackPanel.MarginKey, new Thickness(24, 24, 24, 24));
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "Icon-only — Size: Small (40dp) / Default (56dp) / Large (96dp)");
            _textBlock6.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock6.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock6, "OnSurface"));
            _textBlock6.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 12));
            _stackPanel5.AddChild(_textBlock6);
            const _stackPanel7 = new StackPanel();
            _stackPanel7.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel7.set_property_value(StackPanel.VerticalAlignmentKey, VerticalAlignment.Center);
            _stackPanel7.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 8));
            const _floatingActionButton8 = new FloatingActionButton();
            _floatingActionButton8.set_property_value(FloatingActionButton.SizeKey, FabSize.Small);
            _floatingActionButton8.set_property_value(FloatingActionButton.CommandKey, DataContextBinding(_floatingActionButton8, "ClickSmallCommand"));
            _floatingActionButton8.set_property_value(FloatingActionButton.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock9 = new TextBlock();
            _textBlock9.set_property_value(TextBlock.TextKey, "add");
            _textBlock9.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
            _textBlock9.set_property_value(TextBlock.FontSizeKey, 24);
            _floatingActionButton8.Content = _textBlock9;
            _stackPanel7.AddChild(_floatingActionButton8);
            const _floatingActionButton10 = new FloatingActionButton();
            _floatingActionButton10.set_property_value(FloatingActionButton.SizeKey, FabSize.Default);
            _floatingActionButton10.set_property_value(FloatingActionButton.CommandKey, DataContextBinding(_floatingActionButton10, "ClickDefaultCommand"));
            _floatingActionButton10.set_property_value(FloatingActionButton.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "edit");
            _textBlock11.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 24);
            _floatingActionButton10.Content = _textBlock11;
            _stackPanel7.AddChild(_floatingActionButton10);
            const _floatingActionButton12 = new FloatingActionButton();
            _floatingActionButton12.set_property_value(FloatingActionButton.SizeKey, FabSize.Large);
            _floatingActionButton12.set_property_value(FloatingActionButton.CommandKey, DataContextBinding(_floatingActionButton12, "ClickLargeCommand"));
            const _textBlock13 = new TextBlock();
            _textBlock13.set_property_value(TextBlock.TextKey, "star");
            _textBlock13.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
            _textBlock13.set_property_value(TextBlock.FontSizeKey, 36);
            _floatingActionButton12.Content = _textBlock13;
            _stackPanel7.AddChild(_floatingActionButton12);
            _stackPanel5.AddChild(_stackPanel7);
            const _stackPanel14 = new StackPanel();
            _stackPanel14.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel14.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 24));
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, "Clicks — Small: ");
            _textBlock15.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock15.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock15, "OnSurfaceVariant"));
            _stackPanel14.AddChild(_textBlock15);
            const _textBlock16 = new TextBlock();
            _textBlock16.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock16, "SmallClicks"));
            _textBlock16.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock16.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock16.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock16, "OnSurface"));
            _stackPanel14.AddChild(_textBlock16);
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "  Default: ");
            _textBlock17.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock17.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock17, "OnSurfaceVariant"));
            _stackPanel14.AddChild(_textBlock17);
            const _textBlock18 = new TextBlock();
            _textBlock18.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock18, "DefaultClicks"));
            _textBlock18.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock18.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock18.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock18, "OnSurface"));
            _stackPanel14.AddChild(_textBlock18);
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "  Large: ");
            _textBlock19.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock19.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock19, "OnSurfaceVariant"));
            _stackPanel14.AddChild(_textBlock19);
            const _textBlock20 = new TextBlock();
            _textBlock20.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock20, "LargeClicks"));
            _textBlock20.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock20.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock20.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock20, "OnSurface"));
            _stackPanel14.AddChild(_textBlock20);
            _stackPanel5.AddChild(_stackPanel14);
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "Extended — 56dp tall, content-driven width. Slot accepts icon + label.");
            _textBlock21.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock21.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock21.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock21, "OnSurface"));
            _textBlock21.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 12));
            _stackPanel5.AddChild(_textBlock21);
            const _stackPanel22 = new StackPanel();
            _stackPanel22.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel22.set_property_value(StackPanel.VerticalAlignmentKey, VerticalAlignment.Center);
            _stackPanel22.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 8));
            const _floatingActionButton23 = new FloatingActionButton();
            _floatingActionButton23.set_property_value(FloatingActionButton.SizeKey, FabSize.Extended);
            _floatingActionButton23.set_property_value(FloatingActionButton.CommandKey, DataContextBinding(_floatingActionButton23, "ClickExtendedCommand"));
            _floatingActionButton23.set_property_value(FloatingActionButton.MarginKey, new Thickness(0, 0, 24, 0));
            const _stackPanel24 = new StackPanel();
            _stackPanel24.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel24.set_property_value(StackPanel.VerticalAlignmentKey, VerticalAlignment.Center);
            const _border25 = new Border();
            _border25.set_property_value(Border.WidthKey, 24);
            _border25.set_property_value(Border.HeightKey, 24);
            _border25.set_property_value(Border.MarginKey, new Thickness(0, 0, 12, 0));
            const _textBlock26 = new TextBlock();
            _textBlock26.set_property_value(TextBlock.TextKey, "edit");
            _textBlock26.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
            _textBlock26.set_property_value(TextBlock.FontSizeKey, 24);
            _border25.SetChild(_textBlock26);
            _stackPanel24.AddChild(_border25);
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, "Edit");
            _textBlock27.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
            _stackPanel24.AddChild(_textBlock27);
            _floatingActionButton23.Content = _stackPanel24;
            _stackPanel22.AddChild(_floatingActionButton23);
            const _floatingActionButton28 = new FloatingActionButton();
            _floatingActionButton28.set_property_value(FloatingActionButton.SizeKey, FabSize.Extended);
            _floatingActionButton28.set_property_value(FloatingActionButton.CommandKey, DataContextBinding(_floatingActionButton28, "ClickComposeCommand"));
            const _stackPanel29 = new StackPanel();
            _stackPanel29.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel29.set_property_value(StackPanel.VerticalAlignmentKey, VerticalAlignment.Center);
            const _border30 = new Border();
            _border30.set_property_value(Border.WidthKey, 24);
            _border30.set_property_value(Border.HeightKey, 24);
            _border30.set_property_value(Border.MarginKey, new Thickness(0, 0, 12, 0));
            const _textBlock31 = new TextBlock();
            _textBlock31.set_property_value(TextBlock.TextKey, "edit_note");
            _textBlock31.set_property_value(TextBlock.FontFamilyKey, "Material Symbols Outlined");
            _textBlock31.set_property_value(TextBlock.FontSizeKey, 24);
            _border30.SetChild(_textBlock31);
            _stackPanel29.AddChild(_border30);
            const _textBlock32 = new TextBlock();
            _textBlock32.set_property_value(TextBlock.TextKey, "Compose");
            _textBlock32.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
            _stackPanel29.AddChild(_textBlock32);
            _floatingActionButton28.Content = _stackPanel29;
            _stackPanel22.AddChild(_floatingActionButton28);
            _stackPanel5.AddChild(_stackPanel22);
            const _stackPanel33 = new StackPanel();
            _stackPanel33.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _textBlock34 = new TextBlock();
            _textBlock34.set_property_value(TextBlock.TextKey, "Clicks — Edit: ");
            _textBlock34.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock34.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock34, "OnSurfaceVariant"));
            _stackPanel33.AddChild(_textBlock34);
            const _textBlock35 = new TextBlock();
            _textBlock35.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock35, "ExtendedClicks"));
            _textBlock35.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock35.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock35.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock35, "OnSurface"));
            _stackPanel33.AddChild(_textBlock35);
            const _textBlock36 = new TextBlock();
            _textBlock36.set_property_value(TextBlock.TextKey, "  Compose: ");
            _textBlock36.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock36.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock36, "OnSurfaceVariant"));
            _stackPanel33.AddChild(_textBlock36);
            const _textBlock37 = new TextBlock();
            _textBlock37.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock37, "ComposeClicks"));
            _textBlock37.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock37.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock37.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock37, "OnSurface"));
            _stackPanel33.AddChild(_textBlock37);
            _stackPanel5.AddChild(_stackPanel33);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, FabVM);
        t.Set(FabVM, _tmpl0);
        return t;
    }
}
