import { TextOnPathVM } from "./text-on-path-vm.mjs";
import { Border, Canvas, DataTemplate, Dock, DockPanel, Orientation, Slider, StackPanel, TextBlock, TextBox, TextWrapping } from "@visualisation-sub/mural/basic";
import { Button } from "@visualisation-sub/mural/framework/button.js";
import { ComboBox } from "@visualisation-sub/mural/framework/list/combo-box.js";
import { DataContextBinding, DynamicResource, NameScope, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_TextOnPathDemo = Symbol("TextOnPathDemo.ctor");
export class TextOnPathDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_TextOnPathDemo) {
            throw new Error("TextOnPathDemo is private — use TextOnPathDemo.Clone()");
        }
    }
    static Clone() {
        const t = new TextOnPathDemo(_gate_TextOnPathDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.SetNameScope(new NameScope());
            _border1._set_property_value_by_name("Background", DynamicResource(_border1, "Surface"));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border3._set_property_value_by_name("Background", DynamicResource(_border3, "Primary"));
            _border3._set_property_value_by_name("Padding", new Thickness(20, 14, 20, 14));
            const _stackPanel4 = new StackPanel();
            _stackPanel4._set_property_value_by_name("Orientation", Orientation.Vertical);
            const _textBlock5 = new TextBlock();
            _textBlock5._set_property_value_by_name("Text", "Text on a path");
            _textBlock5._set_property_value_by_name("FontSize", 18);
            _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock5._set_property_value_by_name("Foreground", DynamicResource(_textBlock5, "OnPrimary"));
            _stackPanel4.AddChild(_textBlock5);
            const _textBlock6 = new TextBlock();
            _textBlock6._set_property_value_by_name("Text", DataContextBinding(_textBlock6, "Status"));
            _textBlock6._set_property_value_by_name("FontSize", 12);
            _textBlock6._set_property_value_by_name("Foreground", DynamicResource(_textBlock6, "OnPrimary"));
            _textBlock6._set_property_value_by_name("Margin", new Thickness(0, 4, 0, 0));
            _stackPanel4.AddChild(_textBlock6);
            _border3.SetChild(_stackPanel4);
            _dockPanel2.AddChild(_border3);
            const _textBlock7 = new TextBlock();
            _textBlock7._set_property_value_by_name(DockPanel, "Dock", Dock.Bottom);
            _textBlock7._set_property_value_by_name("Margin", new Thickness(20, 8, 20, 16));
            _textBlock7._set_property_value_by_name("FontSize", 11);
            _textBlock7._set_property_value_by_name("Foreground", DynamicResource(_textBlock7, "OnSurfaceVariant"));
            _textBlock7._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
            _textBlock7._set_property_value_by_name("Text", "Each path is flattened to a polyline, then arclength-sampled so every glyph lands at the right tangent. The picker switches the underlying PathGeometry; the text input updates the rendered run; the slider scales the glyph outlines.");
            _dockPanel2.AddChild(_textBlock7);
            const _border8 = new Border();
            _border8._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border8._set_property_value_by_name("Padding", new Thickness(20, 12, 20, 12));
            _border8._set_property_value_by_name("BorderBrush", DynamicResource(_border8, "OutlineVariant"));
            _border8._set_property_value_by_name("BorderThickness", new Thickness(0, 0, 0, 1));
            const _stackPanel9 = new StackPanel();
            _stackPanel9._set_property_value_by_name("Orientation", Orientation.Horizontal);
            const _stackPanel10 = new StackPanel();
            _stackPanel10._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel10._set_property_value_by_name("Margin", new Thickness(0, 0, 24, 0));
            const _textBlock11 = new TextBlock();
            _textBlock11._set_property_value_by_name("Text", "Text");
            _textBlock11._set_property_value_by_name("FontSize", 11);
            _textBlock11._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock11._set_property_value_by_name("Foreground", DynamicResource(_textBlock11, "OnSurface"));
            _textBlock11._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 4));
            _stackPanel10.AddChild(_textBlock11);
            const _textBox12 = new TextBox();
            _textBox12._set_property_value_by_name("Width", 320);
            _textBox12._set_property_value_by_name("Text", DataContextBinding(_textBox12, "Text"));
            _stackPanel10.AddChild(_textBox12);
            _stackPanel9.AddChild(_stackPanel10);
            const _stackPanel13 = new StackPanel();
            _stackPanel13._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel13._set_property_value_by_name("Margin", new Thickness(0, 0, 24, 0));
            const _textBlock14 = new TextBlock();
            _textBlock14._set_property_value_by_name("Text", "Path");
            _textBlock14._set_property_value_by_name("FontSize", 11);
            _textBlock14._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock14._set_property_value_by_name("Foreground", DynamicResource(_textBlock14, "OnSurface"));
            _textBlock14._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 4));
            _stackPanel13.AddChild(_textBlock14);
            const _comboBox15 = new ComboBox();
            _comboBox15._set_property_value_by_name("Width", 220);
            _comboBox15._set_property_value_by_name("Items", DataContextBinding(_comboBox15, "Paths"));
            _comboBox15._set_property_value_by_name("SelectedItem", DataContextBinding(_comboBox15, "SelectedPathOption"));
            _comboBox15._set_property_value_by_name("DisplayMemberPath", "Label");
            _stackPanel13.AddChild(_comboBox15);
            _stackPanel9.AddChild(_stackPanel13);
            const _stackPanel16 = new StackPanel();
            _stackPanel16._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel16._set_property_value_by_name("Margin", new Thickness(0, 0, 24, 0));
            const _textBlock17 = new TextBlock();
            _textBlock17._set_property_value_by_name("Text", "Font size");
            _textBlock17._set_property_value_by_name("FontSize", 11);
            _textBlock17._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock17._set_property_value_by_name("Foreground", DynamicResource(_textBlock17, "OnSurface"));
            _textBlock17._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 4));
            _stackPanel16.AddChild(_textBlock17);
            const _slider18 = new Slider();
            _slider18._set_property_value_by_name("Width", 180);
            _slider18._set_property_value_by_name("Minimum", 10);
            _slider18._set_property_value_by_name("Maximum", 72);
            _slider18._set_property_value_by_name("Value", DataContextBinding(_slider18, "FontSize"));
            _slider18._set_property_value_by_name("SmallChange", 1);
            _slider18._set_property_value_by_name("LargeChange", 4);
            _stackPanel16.AddChild(_slider18);
            _stackPanel9.AddChild(_stackPanel16);
            const _stackPanel19 = new StackPanel();
            _stackPanel19._set_property_value_by_name("Orientation", Orientation.Vertical);
            const _textBlock20 = new TextBlock();
            _textBlock20._set_property_value_by_name("Text", "Show");
            _textBlock20._set_property_value_by_name("FontSize", 11);
            _textBlock20._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock20._set_property_value_by_name("Foreground", DynamicResource(_textBlock20, "OnSurface"));
            _textBlock20._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 4));
            _stackPanel19.AddChild(_textBlock20);
            const _stackPanel21 = new StackPanel();
            _stackPanel21._set_property_value_by_name("Orientation", Orientation.Horizontal);
            const _button22 = new Button();
            _button22._set_property_value_by_name("Margin", new Thickness(0, 0, 8, 0));
            _button22._set_property_value_by_name("Padding", new Thickness(10, 4, 10, 4));
            _button22._set_property_value_by_name("Command", DataContextBinding(_button22, "TogglePathCommand"));
            const _textBlock23 = new TextBlock();
            _textBlock23._set_property_value_by_name("Text", "Path");
            _button22.Content = _textBlock23;
            _stackPanel21.AddChild(_button22);
            const _button24 = new Button();
            _button24._set_property_value_by_name("Padding", new Thickness(10, 4, 10, 4));
            _button24._set_property_value_by_name("Command", DataContextBinding(_button24, "ToggleGlyphsCommand"));
            const _textBlock25 = new TextBlock();
            _textBlock25._set_property_value_by_name("Text", "Glyphs");
            _button24.Content = _textBlock25;
            _stackPanel21.AddChild(_button24);
            _stackPanel19.AddChild(_stackPanel21);
            _stackPanel9.AddChild(_stackPanel19);
            _border8.SetChild(_stackPanel9);
            _dockPanel2.AddChild(_border8);
            const _border26 = new Border();
            _border26._set_property_value_by_name("Background", DynamicResource(_border26, "SurfaceContainerLow"));
            _border26._set_property_value_by_name("Padding", new Thickness(20, 20, 20, 20));
            const _border27 = new Border();
            _border27._set_property_value_by_name("Background", DynamicResource(_border27, "Surface"));
            _border27._set_property_value_by_name("BorderBrush", DynamicResource(_border27, "OutlineVariant"));
            _border27._set_property_value_by_name("BorderThickness", new Thickness(1));
            _border27._set_property_value_by_name("Padding", new Thickness(0));
            const _canvas28 = new Canvas();
            _canvas28.Name = "surface";
            _canvas28._set_property_value_by_name("Width", 700);
            _canvas28._set_property_value_by_name("Height", 440);
            _border27.SetChild(_canvas28);
            _border26.SetChild(_border27);
            _dockPanel2.AddChild(_border26);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, TextOnPathVM);
        t.Set("TextOnPathTemplate", _tmpl0);
        return t;
    }
    get TextOnPathTemplate() { return this.Resolve("TextOnPathTemplate"); }
    set TextOnPathTemplate(v) { this.Set("TextOnPathTemplate", v); }
}
