import { TextOnPathVM } from "./text-on-path-vm.mjs";
import { Border, Canvas, DataTemplate, Dock, DockPanel, Orientation, Slider, StackPanel, TextBlock, TextBox, TextWrapping } from "@visualisation-sub/mural/basic";
import { ColorPicker } from "@visualisation-sub/mural/framework";
import { Button } from "@visualisation-sub/mural/framework/button.js";
import { ComboBox } from "@visualisation-sub/mural/framework/list/combo-box.js";
import { DataContextBinding, DynamicResource, NameScope, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_TextOnPathDemo = Symbol("TextOnPathDemo.ctor");
export class TextOnPathDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_TextOnPathDemo) {
            throw new Error("TextOnPathDemo is private — use TextOnPathDemo.Clone()");
        }
    }
    static Clone() {
        const t = new TextOnPathDemo(_gate_TextOnPathDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.SetNameScope(new NameScope());
            _border1.set_property_value(Border.BackgroundKey, DynamicResource(_border1, "Surface"));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.BackgroundKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(20, 14, 20, 14));
            const _stackPanel4 = new StackPanel();
            _stackPanel4.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock5 = new TextBlock();
            _textBlock5.set_property_value(TextBlock.TextKey, "Text on a path");
            _textBlock5.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock5.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock5.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock5, "OnPrimary"));
            _stackPanel4.AddChild(_textBlock5);
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock6, "Status"));
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock6.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock6, "OnPrimary"));
            _textBlock6.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _stackPanel4.AddChild(_textBlock6);
            _border3.SetChild(_stackPanel4);
            _dockPanel2.AddChild(_border3);
            const _textBlock7 = new TextBlock();
            _textBlock7.set_property_value(DockPanel.DockKey, Dock.Bottom);
            _textBlock7.set_property_value(TextBlock.MarginKey, new Thickness(20, 8, 20, 16));
            _textBlock7.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock7.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock7, "OnSurfaceVariant"));
            _textBlock7.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock7.set_property_value(TextBlock.TextKey, "Each path is flattened to a polyline, then arclength-sampled so every glyph lands at the right tangent. The picker switches the underlying PathGeometry; the text input updates the rendered run; the slider scales the glyph outlines.");
            _dockPanel2.AddChild(_textBlock7);
            const _border8 = new Border();
            _border8.set_property_value(DockPanel.DockKey, Dock.Top);
            _border8.set_property_value(Border.PaddingKey, new Thickness(20, 12, 20, 12));
            _border8.set_property_value(Border.BorderBrushKey, DynamicResource(_border8, "OutlineVariant"));
            _border8.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 0, 1));
            const _stackPanel9 = new StackPanel();
            _stackPanel9.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _stackPanel10 = new StackPanel();
            _stackPanel10.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel10.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "Text");
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock11.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock11.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock11, "OnSurface"));
            _textBlock11.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel10.AddChild(_textBlock11);
            const _textBox12 = new TextBox();
            _textBox12.set_property_value(TextBox.WidthKey, 320);
            _textBox12.set_property_value(TextBox.TextKey, DataContextBinding(_textBox12, "Text"));
            _stackPanel10.AddChild(_textBox12);
            _stackPanel9.AddChild(_stackPanel10);
            const _stackPanel13 = new StackPanel();
            _stackPanel13.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel13.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock14 = new TextBlock();
            _textBlock14.set_property_value(TextBlock.TextKey, "Path");
            _textBlock14.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock14.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock14.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock14, "OnSurface"));
            _textBlock14.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel13.AddChild(_textBlock14);
            const _comboBox15 = new ComboBox();
            _comboBox15.set_property_value(ComboBox.WidthKey, 220);
            _comboBox15.set_property_value(ComboBox.ItemsKey, DataContextBinding(_comboBox15, "Paths"));
            _comboBox15.set_property_value(ComboBox.SelectedItemKey, DataContextBinding(_comboBox15, "SelectedPathOption"));
            _comboBox15.set_property_value(ComboBox.DisplayMemberPathKey, "Label");
            _stackPanel13.AddChild(_comboBox15);
            _stackPanel9.AddChild(_stackPanel13);
            const _stackPanel16 = new StackPanel();
            _stackPanel16.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel16.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "Font size");
            _textBlock17.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock17.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock17.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock17, "OnSurface"));
            _textBlock17.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel16.AddChild(_textBlock17);
            const _slider18 = new Slider();
            _slider18.set_property_value(Slider.WidthKey, 180);
            _slider18.set_property_value(Slider.MinimumKey, 10);
            _slider18.set_property_value(Slider.MaximumKey, 72);
            _slider18.set_property_value(Slider.ValueKey, DataContextBinding(_slider18, "FontSize"));
            _slider18.set_property_value(Slider.SmallChangeKey, 1);
            _slider18.set_property_value(Slider.LargeChangeKey, 4);
            _stackPanel16.AddChild(_slider18);
            _stackPanel9.AddChild(_stackPanel16);
            const _stackPanel19 = new StackPanel();
            _stackPanel19.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel19.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock20 = new TextBlock();
            _textBlock20.set_property_value(TextBlock.TextKey, "Side offset");
            _textBlock20.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock20.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock20.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock20, "OnSurface"));
            _textBlock20.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel19.AddChild(_textBlock20);
            const _slider21 = new Slider();
            _slider21.set_property_value(Slider.WidthKey, 180);
            _slider21.set_property_value(Slider.MinimumKey, -50);
            _slider21.set_property_value(Slider.MaximumKey, 50);
            _slider21.set_property_value(Slider.ValueKey, DataContextBinding(_slider21, "SideOffset"));
            _slider21.set_property_value(Slider.SmallChangeKey, 1);
            _slider21.set_property_value(Slider.LargeChangeKey, 5);
            _stackPanel19.AddChild(_slider21);
            _stackPanel9.AddChild(_stackPanel19);
            const _stackPanel22 = new StackPanel();
            _stackPanel22.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel22.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, "Show");
            _textBlock23.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock23.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock23.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock23, "OnSurface"));
            _textBlock23.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel22.AddChild(_textBlock23);
            const _stackPanel24 = new StackPanel();
            _stackPanel24.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _button25 = new Button();
            _button25.set_property_value(Button.MarginKey, new Thickness(0, 0, 8, 0));
            _button25.set_property_value(Button.CommandKey, DataContextBinding(_button25, "TogglePathCommand"));
            const _textBlock26 = new TextBlock();
            _textBlock26.set_property_value(TextBlock.TextKey, "Path");
            _button25.Content = _textBlock26;
            _stackPanel24.AddChild(_button25);
            const _button27 = new Button();
            _button27.set_property_value(Button.CommandKey, DataContextBinding(_button27, "ToggleGlyphsCommand"));
            const _textBlock28 = new TextBlock();
            _textBlock28.set_property_value(TextBlock.TextKey, "Glyphs");
            _button27.Content = _textBlock28;
            _stackPanel24.AddChild(_button27);
            _stackPanel22.AddChild(_stackPanel24);
            _stackPanel9.AddChild(_stackPanel22);
            const _stackPanel29 = new StackPanel();
            _stackPanel29.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel29.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 16, 0));
            const _textBlock30 = new TextBlock();
            _textBlock30.set_property_value(TextBlock.TextKey, "Path colour");
            _textBlock30.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock30.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock30.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock30, "OnSurface"));
            _textBlock30.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel29.AddChild(_textBlock30);
            const _colorPicker31 = new ColorPicker();
            _colorPicker31.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker31, "PathColorHex"));
            _stackPanel29.AddChild(_colorPicker31);
            _stackPanel9.AddChild(_stackPanel29);
            const _stackPanel32 = new StackPanel();
            _stackPanel32.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock33 = new TextBlock();
            _textBlock33.set_property_value(TextBlock.TextKey, "Glyph colour");
            _textBlock33.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock33.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock33.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock33, "OnSurface"));
            _textBlock33.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel32.AddChild(_textBlock33);
            const _colorPicker34 = new ColorPicker();
            _colorPicker34.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker34, "GlyphColorHex"));
            _stackPanel32.AddChild(_colorPicker34);
            _stackPanel9.AddChild(_stackPanel32);
            _border8.SetChild(_stackPanel9);
            _dockPanel2.AddChild(_border8);
            const _border35 = new Border();
            _border35.set_property_value(Border.BackgroundKey, DynamicResource(_border35, "SurfaceContainerLow"));
            _border35.set_property_value(Border.PaddingKey, new Thickness(20, 20, 20, 20));
            const _border36 = new Border();
            _border36.set_property_value(Border.BackgroundKey, DynamicResource(_border36, "Surface"));
            _border36.set_property_value(Border.BorderBrushKey, DynamicResource(_border36, "OutlineVariant"));
            _border36.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _border36.set_property_value(Border.PaddingKey, new Thickness(0));
            const _canvas37 = new Canvas();
            _canvas37.Name = "surface";
            _canvas37.set_property_value(Canvas.WidthKey, 700);
            _canvas37.set_property_value(Canvas.HeightKey, 440);
            _border36.SetChild(_canvas37);
            _border35.SetChild(_border36);
            _dockPanel2.AddChild(_border35);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, TextOnPathVM);
        t.Set("TextOnPathTemplate", _tmpl0);
        return t;
    }
    get TextOnPathTemplate() { return this.Resolve("TextOnPathTemplate"); }
    set TextOnPathTemplate(v) { this.Set("TextOnPathTemplate", v); }
}
