import { Border, DataTemplate, DockPanel, Orientation, SpinEdit, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { Color, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2.set_property_value("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2.set_property_value("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2.set_property_value("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4.set_property_value(DockPanel, "Dock", "Top");
        _border4.set_property_value("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border4.set_property_value("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5.set_property_value("Text", "SpinEdit demo — value, range, precision, read-only");
        _textBlock5.set_property_value("FontSize", 15);
        _textBlock5.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock5.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6.set_property_value("Orientation", Orientation.Horizontal);
        const _stackPanel7 = new StackPanel();
        _stackPanel7.set_property_value("Orientation", Orientation.Vertical);
        _stackPanel7.set_property_value("Width", 200);
        _stackPanel7.set_property_value("Margin", new Thickness(16, 16, 8, 16));
        const _textBlock8 = new TextBlock();
        _textBlock8.set_property_value("Text", "Integer:");
        _textBlock8.set_property_value("FontSize", 12);
        _textBlock8.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock8.set_property_value("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel7.AddChild(_textBlock8);
        const _spinEdit9 = new SpinEdit();
        _spinEdit9.set_property_value("Width", 140);
        _spinEdit9.set_property_value("Height", 32);
        _spinEdit9.set_property_value("Value", 10);
        _stackPanel7.AddChild(_spinEdit9);
        const _textBlock10 = new TextBlock();
        _textBlock10.set_property_value("Text", "Default — ±1 per ▴/▾, ±10 per Page.");
        _textBlock10.set_property_value("FontSize", 11);
        _textBlock10.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock10.set_property_value("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel7.AddChild(_textBlock10);
        _stackPanel6.AddChild(_stackPanel7);
        const _stackPanel11 = new StackPanel();
        _stackPanel11.set_property_value("Orientation", Orientation.Vertical);
        _stackPanel11.set_property_value("Width", 200);
        _stackPanel11.set_property_value("Margin", new Thickness(8, 16, 8, 16));
        const _textBlock12 = new TextBlock();
        _textBlock12.set_property_value("Text", "Percent (0.00–100.00):");
        _textBlock12.set_property_value("FontSize", 12);
        _textBlock12.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock12.set_property_value("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel11.AddChild(_textBlock12);
        const _spinEdit13 = new SpinEdit();
        _spinEdit13.set_property_value("Width", 140);
        _spinEdit13.set_property_value("Height", 32);
        _spinEdit13.set_property_value("Value", 37.5);
        _spinEdit13.set_property_value("Minimum", 0);
        _spinEdit13.set_property_value("Maximum", 100);
        _spinEdit13.set_property_value("DecimalPlaces", 2);
        _spinEdit13.set_property_value("SmallChange", 0.5);
        _spinEdit13.set_property_value("LargeChange", 10);
        _stackPanel11.AddChild(_spinEdit13);
        const _textBlock14 = new TextBlock();
        _textBlock14.set_property_value("Text", "Half-step increments; clamps at edges.");
        _textBlock14.set_property_value("FontSize", 11);
        _textBlock14.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock14.set_property_value("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel11.AddChild(_textBlock14);
        _stackPanel6.AddChild(_stackPanel11);
        const _stackPanel15 = new StackPanel();
        _stackPanel15.set_property_value("Orientation", Orientation.Vertical);
        _stackPanel15.set_property_value("Width", 200);
        _stackPanel15.set_property_value("Margin", new Thickness(8, 16, 8, 16));
        const _textBlock16 = new TextBlock();
        _textBlock16.set_property_value("Text", "Volume (0–11):");
        _textBlock16.set_property_value("FontSize", 12);
        _textBlock16.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock16.set_property_value("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel15.AddChild(_textBlock16);
        const _spinEdit17 = new SpinEdit();
        _spinEdit17.set_property_value("Width", 140);
        _spinEdit17.set_property_value("Height", 32);
        _spinEdit17.set_property_value("Value", 7);
        _spinEdit17.set_property_value("Minimum", 0);
        _spinEdit17.set_property_value("Maximum", 11);
        _spinEdit17.set_property_value("SmallChange", 1);
        _spinEdit17.set_property_value("LargeChange", 2);
        _stackPanel15.AddChild(_spinEdit17);
        const _textBlock18 = new TextBlock();
        _textBlock18.set_property_value("Text", "PageUp / PageDown step by 2.");
        _textBlock18.set_property_value("FontSize", 11);
        _textBlock18.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock18.set_property_value("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel15.AddChild(_textBlock18);
        _stackPanel6.AddChild(_stackPanel15);
        const _stackPanel19 = new StackPanel();
        _stackPanel19.set_property_value("Orientation", Orientation.Vertical);
        _stackPanel19.set_property_value("Width", 200);
        _stackPanel19.set_property_value("Margin", new Thickness(8, 16, 16, 16));
        const _textBlock20 = new TextBlock();
        _textBlock20.set_property_value("Text", "Locked:");
        _textBlock20.set_property_value("FontSize", 12);
        _textBlock20.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock20.set_property_value("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel19.AddChild(_textBlock20);
        const _spinEdit21 = new SpinEdit();
        _spinEdit21.set_property_value("Width", 140);
        _spinEdit21.set_property_value("Height", 32);
        _spinEdit21.set_property_value("Value", 42);
        _spinEdit21.set_property_value("IsReadOnly", true);
        _stackPanel19.AddChild(_spinEdit21);
        const _textBlock22 = new TextBlock();
        _textBlock22.set_property_value("Text", "Buttons + keys are inert; display only.");
        _textBlock22.set_property_value("FontSize", 11);
        _textBlock22.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock22.set_property_value("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel19.AddChild(_textBlock22);
        _stackPanel6.AddChild(_stackPanel19);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, "SpinEditVM");
    _rd0.Set("SpinEditTemplate", _tmpl1);
    return _rd0;
}
