import { SpinEditVM } from "./spin-edit-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, SpinEdit, StackPanel, TextBlock } from "@visualisation-sub/mural/Basic";
import { DynamicResource, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2._set_property_value_by_name("Background", DynamicResource(_border2, "Surface"));
        _border2._set_property_value_by_name("BorderBrush", DynamicResource(_border2, "OutlineVariant"));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border4._set_property_value_by_name("Background", DynamicResource(_border4, "Primary"));
        _border4._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name("Text", "SpinEdit demo — value, range, precision, read-only");
        _textBlock5._set_property_value_by_name("FontSize", 15);
        _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock5._set_property_value_by_name("Foreground", DynamicResource(_textBlock5, "Surface"));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _stackPanel7 = new StackPanel();
        _stackPanel7._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel7._set_property_value_by_name("Width", 200);
        _stackPanel7._set_property_value_by_name("Margin", new Thickness(16, 16, 8, 16));
        const _textBlock8 = new TextBlock();
        _textBlock8._set_property_value_by_name("Text", "Integer:");
        _textBlock8._set_property_value_by_name("FontSize", 12);
        _textBlock8._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock8._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel7.AddChild(_textBlock8);
        const _spinEdit9 = new SpinEdit();
        _spinEdit9._set_property_value_by_name("Width", 140);
        _spinEdit9._set_property_value_by_name("Height", 32);
        _spinEdit9._set_property_value_by_name("Value", 10);
        _stackPanel7.AddChild(_spinEdit9);
        const _textBlock10 = new TextBlock();
        _textBlock10._set_property_value_by_name("Text", "Default — ±1 per ▴/▾, ±10 per Page.");
        _textBlock10._set_property_value_by_name("FontSize", 11);
        _textBlock10._set_property_value_by_name("Foreground", DynamicResource(_textBlock10, "OnSurfaceVariant"));
        _textBlock10._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel7.AddChild(_textBlock10);
        _stackPanel6.AddChild(_stackPanel7);
        const _stackPanel11 = new StackPanel();
        _stackPanel11._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel11._set_property_value_by_name("Width", 200);
        _stackPanel11._set_property_value_by_name("Margin", new Thickness(8, 16, 8, 16));
        const _textBlock12 = new TextBlock();
        _textBlock12._set_property_value_by_name("Text", "Percent (0.00–100.00):");
        _textBlock12._set_property_value_by_name("FontSize", 12);
        _textBlock12._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock12._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel11.AddChild(_textBlock12);
        const _spinEdit13 = new SpinEdit();
        _spinEdit13._set_property_value_by_name("Width", 140);
        _spinEdit13._set_property_value_by_name("Height", 32);
        _spinEdit13._set_property_value_by_name("Value", 37.5);
        _spinEdit13._set_property_value_by_name("Minimum", 0);
        _spinEdit13._set_property_value_by_name("Maximum", 100);
        _spinEdit13._set_property_value_by_name("DecimalPlaces", 2);
        _spinEdit13._set_property_value_by_name("SmallChange", 0.5);
        _spinEdit13._set_property_value_by_name("LargeChange", 10);
        _stackPanel11.AddChild(_spinEdit13);
        const _textBlock14 = new TextBlock();
        _textBlock14._set_property_value_by_name("Text", "Half-step increments; clamps at edges.");
        _textBlock14._set_property_value_by_name("FontSize", 11);
        _textBlock14._set_property_value_by_name("Foreground", DynamicResource(_textBlock14, "OnSurfaceVariant"));
        _textBlock14._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel11.AddChild(_textBlock14);
        _stackPanel6.AddChild(_stackPanel11);
        const _stackPanel15 = new StackPanel();
        _stackPanel15._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel15._set_property_value_by_name("Width", 200);
        _stackPanel15._set_property_value_by_name("Margin", new Thickness(8, 16, 8, 16));
        const _textBlock16 = new TextBlock();
        _textBlock16._set_property_value_by_name("Text", "Volume (0–11):");
        _textBlock16._set_property_value_by_name("FontSize", 12);
        _textBlock16._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock16._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel15.AddChild(_textBlock16);
        const _spinEdit17 = new SpinEdit();
        _spinEdit17._set_property_value_by_name("Width", 140);
        _spinEdit17._set_property_value_by_name("Height", 32);
        _spinEdit17._set_property_value_by_name("Value", 7);
        _spinEdit17._set_property_value_by_name("Minimum", 0);
        _spinEdit17._set_property_value_by_name("Maximum", 11);
        _spinEdit17._set_property_value_by_name("SmallChange", 1);
        _spinEdit17._set_property_value_by_name("LargeChange", 2);
        _stackPanel15.AddChild(_spinEdit17);
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", "PageUp / PageDown step by 2.");
        _textBlock18._set_property_value_by_name("FontSize", 11);
        _textBlock18._set_property_value_by_name("Foreground", DynamicResource(_textBlock18, "OnSurfaceVariant"));
        _textBlock18._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel15.AddChild(_textBlock18);
        _stackPanel6.AddChild(_stackPanel15);
        const _stackPanel19 = new StackPanel();
        _stackPanel19._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel19._set_property_value_by_name("Width", 200);
        _stackPanel19._set_property_value_by_name("Margin", new Thickness(8, 16, 16, 16));
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "Locked:");
        _textBlock20._set_property_value_by_name("FontSize", 12);
        _textBlock20._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock20._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        _stackPanel19.AddChild(_textBlock20);
        const _spinEdit21 = new SpinEdit();
        _spinEdit21._set_property_value_by_name("Width", 140);
        _spinEdit21._set_property_value_by_name("Height", 32);
        _spinEdit21._set_property_value_by_name("Value", 42);
        _spinEdit21._set_property_value_by_name("IsReadOnly", true);
        _stackPanel19.AddChild(_spinEdit21);
        const _textBlock22 = new TextBlock();
        _textBlock22._set_property_value_by_name("Text", "Buttons + keys are inert; display only.");
        _textBlock22._set_property_value_by_name("FontSize", 11);
        _textBlock22._set_property_value_by_name("Foreground", DynamicResource(_textBlock22, "OnSurfaceVariant"));
        _textBlock22._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel19.AddChild(_textBlock22);
        _stackPanel6.AddChild(_stackPanel19);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, SpinEditVM);
    _rd0.Set("SpinEditTemplate", _tmpl1);
    return _rd0;
}
