import { SpinEditVM } from "./spin-edit-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, SpinEdit, StackPanel, TextBlock } from "@visualisation-sub/mural/Basic";
import { DynamicResource, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_SpinEditDemo = Symbol("SpinEditDemo.ctor");
export class SpinEditDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_SpinEditDemo) {
            throw new Error("SpinEditDemo is private — use SpinEditDemo.Clone()");
        }
    }
    static Clone() {
        const t = new SpinEditDemo(_gate_SpinEditDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1._set_property_value_by_name("Background", DynamicResource(_border1, "Surface"));
            _border1._set_property_value_by_name("BorderBrush", DynamicResource(_border1, "OutlineVariant"));
            _border1._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border3._set_property_value_by_name("Background", DynamicResource(_border3, "Primary"));
            _border3._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4._set_property_value_by_name("Text", "SpinEdit demo — value, range, precision, read-only");
            _textBlock4._set_property_value_by_name("FontSize", 15);
            _textBlock4._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock4._set_property_value_by_name("Foreground", DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5._set_property_value_by_name("Orientation", Orientation.Horizontal);
            const _stackPanel6 = new StackPanel();
            _stackPanel6._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel6._set_property_value_by_name("Width", 200);
            _stackPanel6._set_property_value_by_name("Margin", new Thickness(16, 16, 8, 16));
            const _textBlock7 = new TextBlock();
            _textBlock7._set_property_value_by_name("Text", "Integer:");
            _textBlock7._set_property_value_by_name("FontSize", 12);
            _textBlock7._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock7._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
            _stackPanel6.AddChild(_textBlock7);
            const _spinEdit8 = new SpinEdit();
            _spinEdit8._set_property_value_by_name("Width", 140);
            _spinEdit8._set_property_value_by_name("Height", 32);
            _spinEdit8._set_property_value_by_name("Value", 10);
            _stackPanel6.AddChild(_spinEdit8);
            const _textBlock9 = new TextBlock();
            _textBlock9._set_property_value_by_name("Text", "Default — ±1 per ▴/▾, ±10 per Page.");
            _textBlock9._set_property_value_by_name("FontSize", 11);
            _textBlock9._set_property_value_by_name("Foreground", DynamicResource(_textBlock9, "OnSurfaceVariant"));
            _textBlock9._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
            _stackPanel6.AddChild(_textBlock9);
            _stackPanel5.AddChild(_stackPanel6);
            const _stackPanel10 = new StackPanel();
            _stackPanel10._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel10._set_property_value_by_name("Width", 200);
            _stackPanel10._set_property_value_by_name("Margin", new Thickness(8, 16, 8, 16));
            const _textBlock11 = new TextBlock();
            _textBlock11._set_property_value_by_name("Text", "Percent (0.00–100.00):");
            _textBlock11._set_property_value_by_name("FontSize", 12);
            _textBlock11._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock11._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
            _stackPanel10.AddChild(_textBlock11);
            const _spinEdit12 = new SpinEdit();
            _spinEdit12._set_property_value_by_name("Width", 140);
            _spinEdit12._set_property_value_by_name("Height", 32);
            _spinEdit12._set_property_value_by_name("Value", 37.5);
            _spinEdit12._set_property_value_by_name("Minimum", 0);
            _spinEdit12._set_property_value_by_name("Maximum", 100);
            _spinEdit12._set_property_value_by_name("DecimalPlaces", 2);
            _spinEdit12._set_property_value_by_name("SmallChange", 0.5);
            _spinEdit12._set_property_value_by_name("LargeChange", 10);
            _stackPanel10.AddChild(_spinEdit12);
            const _textBlock13 = new TextBlock();
            _textBlock13._set_property_value_by_name("Text", "Half-step increments; clamps at edges.");
            _textBlock13._set_property_value_by_name("FontSize", 11);
            _textBlock13._set_property_value_by_name("Foreground", DynamicResource(_textBlock13, "OnSurfaceVariant"));
            _textBlock13._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
            _stackPanel10.AddChild(_textBlock13);
            _stackPanel5.AddChild(_stackPanel10);
            const _stackPanel14 = new StackPanel();
            _stackPanel14._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel14._set_property_value_by_name("Width", 200);
            _stackPanel14._set_property_value_by_name("Margin", new Thickness(8, 16, 8, 16));
            const _textBlock15 = new TextBlock();
            _textBlock15._set_property_value_by_name("Text", "Volume (0–11):");
            _textBlock15._set_property_value_by_name("FontSize", 12);
            _textBlock15._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock15._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
            _stackPanel14.AddChild(_textBlock15);
            const _spinEdit16 = new SpinEdit();
            _spinEdit16._set_property_value_by_name("Width", 140);
            _spinEdit16._set_property_value_by_name("Height", 32);
            _spinEdit16._set_property_value_by_name("Value", 7);
            _spinEdit16._set_property_value_by_name("Minimum", 0);
            _spinEdit16._set_property_value_by_name("Maximum", 11);
            _spinEdit16._set_property_value_by_name("SmallChange", 1);
            _spinEdit16._set_property_value_by_name("LargeChange", 2);
            _stackPanel14.AddChild(_spinEdit16);
            const _textBlock17 = new TextBlock();
            _textBlock17._set_property_value_by_name("Text", "PageUp / PageDown step by 2.");
            _textBlock17._set_property_value_by_name("FontSize", 11);
            _textBlock17._set_property_value_by_name("Foreground", DynamicResource(_textBlock17, "OnSurfaceVariant"));
            _textBlock17._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
            _stackPanel14.AddChild(_textBlock17);
            _stackPanel5.AddChild(_stackPanel14);
            const _stackPanel18 = new StackPanel();
            _stackPanel18._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel18._set_property_value_by_name("Width", 200);
            _stackPanel18._set_property_value_by_name("Margin", new Thickness(8, 16, 16, 16));
            const _textBlock19 = new TextBlock();
            _textBlock19._set_property_value_by_name("Text", "Locked:");
            _textBlock19._set_property_value_by_name("FontSize", 12);
            _textBlock19._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock19._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
            _stackPanel18.AddChild(_textBlock19);
            const _spinEdit20 = new SpinEdit();
            _spinEdit20._set_property_value_by_name("Width", 140);
            _spinEdit20._set_property_value_by_name("Height", 32);
            _spinEdit20._set_property_value_by_name("Value", 42);
            _spinEdit20._set_property_value_by_name("IsReadOnly", true);
            _stackPanel18.AddChild(_spinEdit20);
            const _textBlock21 = new TextBlock();
            _textBlock21._set_property_value_by_name("Text", "Buttons + keys are inert; display only.");
            _textBlock21._set_property_value_by_name("FontSize", 11);
            _textBlock21._set_property_value_by_name("Foreground", DynamicResource(_textBlock21, "OnSurfaceVariant"));
            _textBlock21._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
            _stackPanel18.AddChild(_textBlock21);
            _stackPanel5.AddChild(_stackPanel18);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, SpinEditVM);
        t.Set("SpinEditTemplate", _tmpl0);
        return t;
    }
    get SpinEditTemplate() { return this.Resolve("SpinEditTemplate"); }
    set SpinEditTemplate(v) { this.Set("SpinEditTemplate", v); }
}
