import { CounterVM } from "./counter-vm.mjs";
import { Border, Canvas, DataTemplate, TextBlock, TextWrapping } from "@visualisation-sub/mural/Basic";
import { Button } from "@visualisation-sub/mural/framework/button.js";
import { ComboBox } from "@visualisation-sub/mural/framework/list/combo-box.js";
import { DataContextBinding, DynamicResource, MultiBinding, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2._set_property_value_by_name("Background", DynamicResource(_border2, "Surface"));
        _border2._set_property_value_by_name("BorderBrush", DynamicResource(_border2, "OutlineVariant"));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _canvas3 = new Canvas();
        const _textBlock4 = new TextBlock();
        _textBlock4._set_property_value_by_name(Canvas, "Left", 24);
        _textBlock4._set_property_value_by_name(Canvas, "Top", 20);
        _textBlock4._set_property_value_by_name("FontSize", 14);
        _textBlock4._set_property_value_by_name("Foreground", DynamicResource(_textBlock4, "OnSurfaceVariant"));
        _textBlock4._set_property_value_by_name("Text", "Counter:");
        _canvas3.AddChild(_textBlock4);
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name(Canvas, "Left", 24);
        _textBlock5._set_property_value_by_name(Canvas, "Top", 40);
        _textBlock5._set_property_value_by_name("FontSize", 42);
        _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock5._set_property_value_by_name("Foreground", DynamicResource(_textBlock5, "Primary"));
        _textBlock5._set_property_value_by_name("Text", MultiBinding(_textBlock5, ["Count"], (_p0) => ( String(_p0) )));
        _canvas3.AddChild(_textBlock5);
        const _textBlock6 = new TextBlock();
        _textBlock6._set_property_value_by_name(Canvas, "Left", 170);
        _textBlock6._set_property_value_by_name(Canvas, "Top", 124);
        _textBlock6._set_property_value_by_name("FontSize", 12);
        _textBlock6._set_property_value_by_name("Foreground", DynamicResource(_textBlock6, "OnSurfaceVariant"));
        _textBlock6._set_property_value_by_name("Text", "Step:");
        _canvas3.AddChild(_textBlock6);
        const _comboBox7 = new ComboBox();
        _comboBox7._set_property_value_by_name(Canvas, "Left", 170);
        _comboBox7._set_property_value_by_name(Canvas, "Top", 140);
        _comboBox7._set_property_value_by_name("Width", 164);
        _comboBox7._set_property_value_by_name("Items", DataContextBinding(_comboBox7, "Steps"));
        _comboBox7._set_property_value_by_name("SelectedItem", DataContextBinding(_comboBox7, "Step"));
        _canvas3.AddChild(_comboBox7);
        const _button8 = new Button();
        _button8._set_property_value_by_name(Canvas, "Left", 24);
        _button8._set_property_value_by_name(Canvas, "Top", 140);
        _button8._set_property_value_by_name("Width", 80);
        _button8._set_property_value_by_name("Command", DataContextBinding(_button8, "Increment"));
        const _textBlock9 = new TextBlock();
        _textBlock9._set_property_value_by_name("Text", "+ Step");
        _button8.Content = _textBlock9;
        _canvas3.AddChild(_button8);
        const _button10 = new Button();
        _button10._set_property_value_by_name(Canvas, "Left", 24);
        _button10._set_property_value_by_name(Canvas, "Top", 190);
        _button10._set_property_value_by_name("Width", 80);
        _button10._set_property_value_by_name("Command", DataContextBinding(_button10, "Reset"));
        const _textBlock11 = new TextBlock();
        _textBlock11._set_property_value_by_name("Text", "Reset");
        _button10.Content = _textBlock11;
        _canvas3.AddChild(_button10);
        const _textBlock12 = new TextBlock();
        _textBlock12._set_property_value_by_name(Canvas, "Left", 24);
        _textBlock12._set_property_value_by_name(Canvas, "Top", 232);
        _textBlock12._set_property_value_by_name("Width", 312);
        _textBlock12._set_property_value_by_name("FontSize", 12);
        _textBlock12._set_property_value_by_name("Foreground", DynamicResource(_textBlock12, "OnSurfaceVariant"));
        _textBlock12._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
        _textBlock12._set_property_value_by_name("Text", "The ComboBox sets Step. Increment adds Step to Count and stops at 10. Reset always works.");
        _canvas3.AddChild(_textBlock12);
        _border2.SetChild(_canvas3);
        return _border2;
    }, CounterVM);
    _rd0.Set("CounterTemplate", _tmpl1);
    return _rd0;
}
