import { Border, Button, DataTemplate, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { BeginStoryboardAction, Color, DoubleAnimation, EventTrigger, ResourceDictionary, Storyboard, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _rd3 = _border2.Resources;
        const _act5 = new BeginStoryboardAction((_target) => {
            const _sb4 = new Storyboard();
            _sb4.Add(_target, "Width", new DoubleAnimation({ From: 80, To: 240, Duration: 400 }));
            return _sb4;
        });
        const _evt6 = new EventTrigger("Click", [_act5]);
        const _style7 = new Style(Button, [], undefined, [], [], [_evt6]);
        _rd3.Set(Button, _style7);
        const _dockPanel8 = new DockPanel();
        const _border9 = new Border();
        _border9._set_property_value_by_name(DockPanel, "Dock", "Top");
        _border9._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border9._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock10 = new TextBlock();
        _textBlock10._set_property_value_by_name("Text", "Declarative animation — on Click { BeginStoryboard { ... } }");
        _textBlock10._set_property_value_by_name("FontSize", 15);
        _textBlock10._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock10._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border9.SetChild(_textBlock10);
        _dockPanel8.AddChild(_border9);
        const _stackPanel11 = new StackPanel();
        _stackPanel11._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel11._set_property_value_by_name("Margin", new Thickness(20, 24, 20, 20));
        const _textBlock12 = new TextBlock();
        _textBlock12._set_property_value_by_name("Text", "Click any Button. The style's EventTrigger animates the Button's own Width from 80 to 240 over 400 ms — no host-side handler wired.");
        _textBlock12._set_property_value_by_name("FontSize", 12);
        _textBlock12._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock12._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
        _stackPanel11.AddChild(_textBlock12);
        const _stackPanel13 = new StackPanel();
        _stackPanel13._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _button14 = new Button();
        _button14._set_property_value_by_name("Width", 80);
        _button14._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        const _textBlock15 = new TextBlock();
        _textBlock15._set_property_value_by_name("Text", "Slide A");
        _button14.Content = _textBlock15;
        _stackPanel13.AddChild(_button14);
        const _button16 = new Button();
        _button16._set_property_value_by_name("Width", 80);
        _button16._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        const _textBlock17 = new TextBlock();
        _textBlock17._set_property_value_by_name("Text", "Slide B");
        _button16.Content = _textBlock17;
        _stackPanel13.AddChild(_button16);
        const _button18 = new Button();
        _button18._set_property_value_by_name("Width", 80);
        _button18._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        const _textBlock19 = new TextBlock();
        _textBlock19._set_property_value_by_name("Text", "Slide C");
        _button18.Content = _textBlock19;
        _stackPanel13.AddChild(_button18);
        _stackPanel11.AddChild(_stackPanel13);
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "Each Button carries its own animation instance — clicking them simultaneously plays independent storyboards (each baseline-captures From=80 at fire time).");
        _textBlock20._set_property_value_by_name("FontSize", 11);
        _textBlock20._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock20._set_property_value_by_name("Margin", new Thickness(0, 16, 0, 0));
        _stackPanel11.AddChild(_textBlock20);
        _dockPanel8.AddChild(_stackPanel11);
        _border2.SetChild(_dockPanel8);
        return _border2;
    }, "AnimationDeclarativeVM");
    _rd0.Set("AnimationDeclarativeTemplate", _tmpl1);
    return _rd0;
}
