import { RichTextBlockVM } from "./rich-text-block-vm.mjs";
import { Bold, Border, DataTemplate, Dock, DockPanel, FlowDocument, InlineUIContainer, Italic, Orientation, Paragraph, RichTextBlock, Run, Span, StackPanel, TextBlock, TextWrapping, Underline } from "@pragmatic-tech-ai/mural/basic";
import { Chip, ChipVariant } from "@pragmatic-tech-ai/mural/framework/markers/chip.js";
import { DynamicResource, HorizontalAlignment, NameScope, ResourceDictionary, Thickness, VerticalAlignment } from "@pragmatic-tech-ai/mural/runtime";
import { FontStyle, FontWeight } from "@pragmatic-tech-ai/mural/visual-engine";


const _gate_RichTextBlockDemo = Symbol("RichTextBlockDemo.ctor");
export class RichTextBlockDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_RichTextBlockDemo) {
            throw new Error("RichTextBlockDemo is private — use RichTextBlockDemo.Clone()");
        }
    }
    static Clone() {
        const t = new RichTextBlockDemo(_gate_RichTextBlockDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.SetNameScope(new NameScope());
            _border1.set_property_value(Border.FillKey, DynamicResource(_border1, "Surface"));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.FillKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(20, 14, 20, 14));
            const _stackPanel4 = new StackPanel();
            _stackPanel4.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock5 = new TextBlock();
            _textBlock5.set_property_value(TextBlock.TextKey, "Rich text block");
            _textBlock5.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock5.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock5.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock5, "OnPrimary"));
            _stackPanel4.AddChild(_textBlock5);
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "A read-only RichTextBlock: mixed inline styles and baseline-aligned chips flowing over one FlowDocument.");
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock6.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock6, "OnPrimary"));
            _textBlock6.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock6.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _stackPanel4.AddChild(_textBlock6);
            _border3.SetChild(_stackPanel4);
            _dockPanel2.AddChild(_border3);
            const _border7 = new Border();
            _border7.set_property_value(Border.PaddingKey, new Thickness(28, 24, 28, 24));
            const _richTextBlock8 = new RichTextBlock();
            _richTextBlock8.set_property_value(RichTextBlock.VerticalAlignmentKey, VerticalAlignment.Top);
            _richTextBlock8.set_property_value(RichTextBlock.HorizontalAlignmentKey, HorizontalAlignment.Left);
            _richTextBlock8.set_property_value(RichTextBlock.MaxWidthKey, 560);
            _richTextBlock8.set_property_value(RichTextBlock.FontSizeKey, 15);
            const _flowDocument9 = new FlowDocument();
            const _paragraph10 = new Paragraph();
            const _span11 = new Span();
            _span11.set_property_value(Span.FontSizeKey, 24);
            _span11.set_property_value(Span.FontWeightKey, FontWeight.Bold);
            _span11.set_property_value(Span.ForegroundKey, DynamicResource(_span11, "Primary"));
            const _run12 = new Run("One flow, many styles");
            _span11.AddChild(_run12);
            _paragraph10.AddChild(_span11);
            _flowDocument9.AddChild(_paragraph10);
            const _paragraph13 = new Paragraph();
            const _run14 = new Run("This paragraph mixes ");
            _paragraph13.AddChild(_run14);
            const _bold15 = new Bold();
            const _run16 = new Run("bold");
            _bold15.AddChild(_run16);
            _paragraph13.AddChild(_bold15);
            const _run17 = new Run(", ");
            _paragraph13.AddChild(_run17);
            const _italic18 = new Italic();
            const _run19 = new Run("italic");
            _italic18.AddChild(_run19);
            _paragraph13.AddChild(_italic18);
            const _run20 = new Run(", ");
            _paragraph13.AddChild(_run20);
            const _underline21 = new Underline();
            const _run22 = new Run("underlined");
            _underline21.AddChild(_run22);
            _paragraph13.AddChild(_underline21);
            const _run23 = new Run(", and ");
            _paragraph13.AddChild(_run23);
            const _span24 = new Span();
            _span24.set_property_value(Span.FontWeightKey, FontWeight.Bold);
            _span24.set_property_value(Span.FontStyleKey, FontStyle.Italic);
            const _run25 = new Run("bold-italic");
            _span24.AddChild(_run25);
            _paragraph13.AddChild(_span24);
            const _run26 = new Run(" runs. It also carries ");
            _paragraph13.AddChild(_run26);
            const _span27 = new Span();
            _span27.set_property_value(Span.ForegroundKey, DynamicResource(_span27, "Error"));
            const _run28 = new Run("coloured");
            _span27.AddChild(_run28);
            _paragraph13.AddChild(_span27);
            const _run29 = new Run(" and ");
            _paragraph13.AddChild(_run29);
            const _span30 = new Span();
            _span30.set_property_value(Span.FontSizeKey, 21);
            _span30.set_property_value(Span.ForegroundKey, DynamicResource(_span30, "Tertiary"));
            const _run31 = new Run("larger");
            _span30.AddChild(_run31);
            _paragraph13.AddChild(_span30);
            const _run32 = new Run(" text — the line box grows to fit the tallest run and the rest sit on the same baseline.");
            _paragraph13.AddChild(_run32);
            _flowDocument9.AddChild(_paragraph13);
            const _paragraph33 = new Paragraph();
            const _run34 = new Run("Chips embed inline too — filter by ");
            _paragraph33.AddChild(_run34);
            const _inlineUIContainer35 = new InlineUIContainer();
            const _chip36 = new Chip();
            _chip36.set_property_value(Chip.KindKey, ChipVariant.Assist);
            const _textBlock37 = new TextBlock();
            _textBlock37.set_property_value(TextBlock.TextKey, "Design");
            _chip36.Content = _textBlock37;
            _inlineUIContainer35.Child = _chip36;
            _paragraph33.AddChild(_inlineUIContainer35);
            const _run38 = new Run(" ");
            _paragraph33.AddChild(_run38);
            const _inlineUIContainer39 = new InlineUIContainer();
            const _chip40 = new Chip();
            _chip40.set_property_value(Chip.KindKey, ChipVariant.Assist);
            const _textBlock41 = new TextBlock();
            _textBlock41.set_property_value(TextBlock.TextKey, "Engineering");
            _chip40.Content = _textBlock41;
            _inlineUIContainer39.Child = _chip40;
            _paragraph33.AddChild(_inlineUIContainer39);
            const _run42 = new Run(" or a selected ");
            _paragraph33.AddChild(_run42);
            const _inlineUIContainer43 = new InlineUIContainer();
            const _chip44 = new Chip();
            _chip44.set_property_value(Chip.KindKey, ChipVariant.Filter);
            _chip44.set_property_value(Chip.IsCheckedKey, true);
            const _textBlock45 = new TextBlock();
            _textBlock45.set_property_value(TextBlock.TextKey, "Favorites");
            _chip44.Content = _textBlock45;
            _inlineUIContainer43.Child = _chip44;
            _paragraph33.AddChild(_inlineUIContainer43);
            const _run46 = new Run(" chip. Each Chip is wrapped in an InlineUIContainer, and its label baseline lands on the text baseline while the pill hangs below.");
            _paragraph33.AddChild(_run46);
            _flowDocument9.AddChild(_paragraph33);
            const _paragraph47 = new Paragraph();
            const _span48 = new Span();
            _span48.set_property_value(Span.FontSizeKey, 12);
            _span48.set_property_value(Span.ForegroundKey, DynamicResource(_span48, "OnSurfaceVariant"));
            const _run49 = new Run("All of the above is authored declaratively as a FlowDocument of Paragraphs, Runs, Spans, and InlineUIContainers — no per-run layout code.");
            _span48.AddChild(_run49);
            _paragraph47.AddChild(_span48);
            _flowDocument9.AddChild(_paragraph47);
            _richTextBlock8.Document = _flowDocument9;
            _border7.SetChild(_richTextBlock8);
            _dockPanel2.AddChild(_border7);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, RichTextBlockVM);
        t.Set(RichTextBlockVM, _tmpl0);
        return t;
    }
}
