import { SplitterVM } from "./splitter-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, Splitter, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/Basic";
import { Color, DynamicResource, HorizontalAlignment, ResourceDictionary, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2._set_property_value_by_name("Background", DynamicResource(_border2, "Surface"));
        _border2._set_property_value_by_name("BorderBrush", DynamicResource(_border2, "OutlineVariant"));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border4._set_property_value_by_name("Background", DynamicResource(_border4, "Primary"));
        _border4._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _stackPanel5 = new StackPanel();
        _stackPanel5._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _textBlock6 = new TextBlock();
        _textBlock6._set_property_value_by_name("Text", "Splitter demo — standalone draggable bar");
        _textBlock6._set_property_value_by_name("FontSize", 15);
        _textBlock6._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock6._set_property_value_by_name("Foreground", DynamicResource(_textBlock6, "OnPrimary"));
        _stackPanel5.AddChild(_textBlock6);
        const _textBlock7 = new TextBlock();
        _textBlock7._set_property_value_by_name("Text", "Drag the gray bars to resize. ArrowLeft / ArrowRight (or Up / Down) nudge by 10px when focused.");
        _textBlock7._set_property_value_by_name("FontSize", 11);
        _textBlock7._set_property_value_by_name("Foreground", DynamicResource(_textBlock7, "Outline"));
        _textBlock7._set_property_value_by_name("Margin", new Thickness(0, 4, 0, 0));
        _stackPanel5.AddChild(_textBlock7);
        _border4.SetChild(_stackPanel5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel8 = new StackPanel();
        _stackPanel8._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel8._set_property_value_by_name("Margin", new Thickness(16));
        const _textBlock9 = new TextBlock();
        _textBlock9._set_property_value_by_name("Text", "Vertical Splitter — horizontal StackPanel sibling resize");
        _textBlock9._set_property_value_by_name("FontSize", 12);
        _textBlock9._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock9._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 8));
        _stackPanel8.AddChild(_textBlock9);
        const _border10 = new Border();
        _border10._set_property_value_by_name("Height", 140);
        _border10._set_property_value_by_name("BorderBrush", DynamicResource(_border10, "Outline"));
        _border10._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _stackPanel11 = new StackPanel();
        _stackPanel11._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _border12 = new Border();
        _border12._set_property_value_by_name("Width", 200);
        _border12._set_property_value_by_name("Height", 138);
        _border12._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#dbeafe')));
        const _textBlock13 = new TextBlock();
        _textBlock13._set_property_value_by_name("Text", "Width=200");
        _textBlock13._set_property_value_by_name("FontSize", 14);
        _textBlock13._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock13._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
        _textBlock13._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
        _textBlock13._set_property_value_by_name("Foreground", DynamicResource(_textBlock13, "PrimaryContainer"));
        _border12.SetChild(_textBlock13);
        _stackPanel11.AddChild(_border12);
        const _splitter14 = new Splitter();
        _splitter14._set_property_value_by_name("Width", 8);
        _splitter14._set_property_value_by_name("Height", 138);
        _stackPanel11.AddChild(_splitter14);
        const _border15 = new Border();
        _border15._set_property_value_by_name("Width", 300);
        _border15._set_property_value_by_name("Height", 138);
        _border15._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#e0f2fe')));
        const _textBlock16 = new TextBlock();
        _textBlock16._set_property_value_by_name("Text", "Width=300 — drag the gray bar to resize the LEFT pane");
        _textBlock16._set_property_value_by_name("FontSize", 13);
        _textBlock16._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
        _textBlock16._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
        _textBlock16._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#075985')));
        _textBlock16._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
        _border15.SetChild(_textBlock16);
        _stackPanel11.AddChild(_border15);
        _border10.SetChild(_stackPanel11);
        _stackPanel8.AddChild(_border10);
        const _textBlock17 = new TextBlock();
        _textBlock17._set_property_value_by_name("Text", "Horizontal Splitter — DockPanel top-sibling resize");
        _textBlock17._set_property_value_by_name("FontSize", 12);
        _textBlock17._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock17._set_property_value_by_name("Margin", new Thickness(0, 24, 0, 8));
        _stackPanel8.AddChild(_textBlock17);
        const _border18 = new Border();
        _border18._set_property_value_by_name("Height", 260);
        _border18._set_property_value_by_name("BorderBrush", DynamicResource(_border18, "Outline"));
        _border18._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel19 = new DockPanel();
        const _border20 = new Border();
        _border20._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border20._set_property_value_by_name("Height", 80);
        _border20._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#dcfce7')));
        const _textBlock21 = new TextBlock();
        _textBlock21._set_property_value_by_name("Text", "Height=80");
        _textBlock21._set_property_value_by_name("FontSize", 14);
        _textBlock21._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock21._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
        _textBlock21._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
        _textBlock21._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#166534')));
        _border20.SetChild(_textBlock21);
        _dockPanel19.AddChild(_border20);
        const _splitter22 = new Splitter();
        _splitter22._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _splitter22._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _splitter22._set_property_value_by_name("Height", 8);
        _dockPanel19.AddChild(_splitter22);
        const _border23 = new Border();
        _border23._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#bbf7d0')));
        const _textBlock24 = new TextBlock();
        _textBlock24._set_property_value_by_name("Text", "Drag the gray bar to resize the TOP pane.");
        _textBlock24._set_property_value_by_name("FontSize", 13);
        _textBlock24._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
        _textBlock24._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
        _textBlock24._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#14532d')));
        _textBlock24._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
        _border23.SetChild(_textBlock24);
        _dockPanel19.AddChild(_border23);
        _border18.SetChild(_dockPanel19);
        _stackPanel8.AddChild(_border18);
        _dockPanel3.AddChild(_stackPanel8);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, SplitterVM);
    _rd0.Set("SplitterTemplate", _tmpl1);
    return _rd0;
}
