import { SplitterVM } from "./splitter-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, Splitter, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/basic";
import { Color, DynamicResource, HorizontalAlignment, ResourceDictionary, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_SplitterDemo = Symbol("SplitterDemo.ctor");
export class SplitterDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_SplitterDemo) {
            throw new Error("SplitterDemo is private — use SplitterDemo.Clone()");
        }
    }
    static Clone() {
        const t = new SplitterDemo(_gate_SplitterDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1._set_property_value_by_name("Background", DynamicResource(_border1, "Surface"));
            _border1._set_property_value_by_name("BorderBrush", DynamicResource(_border1, "OutlineVariant"));
            _border1._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border3._set_property_value_by_name("Background", DynamicResource(_border3, "Primary"));
            _border3._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
            const _stackPanel4 = new StackPanel();
            _stackPanel4._set_property_value_by_name("Orientation", Orientation.Vertical);
            const _textBlock5 = new TextBlock();
            _textBlock5._set_property_value_by_name("Text", "Splitter demo — standalone draggable bar");
            _textBlock5._set_property_value_by_name("FontSize", 15);
            _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock5._set_property_value_by_name("Foreground", DynamicResource(_textBlock5, "OnPrimary"));
            _stackPanel4.AddChild(_textBlock5);
            const _textBlock6 = new TextBlock();
            _textBlock6._set_property_value_by_name("Text", "Drag the gray bars to resize. ArrowLeft / ArrowRight (or Up / Down) nudge by 10px when focused.");
            _textBlock6._set_property_value_by_name("FontSize", 11);
            _textBlock6._set_property_value_by_name("Foreground", DynamicResource(_textBlock6, "Outline"));
            _textBlock6._set_property_value_by_name("Margin", new Thickness(0, 4, 0, 0));
            _stackPanel4.AddChild(_textBlock6);
            _border3.SetChild(_stackPanel4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel7 = new StackPanel();
            _stackPanel7._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel7._set_property_value_by_name("Margin", new Thickness(16));
            const _textBlock8 = new TextBlock();
            _textBlock8._set_property_value_by_name("Text", "Vertical Splitter — horizontal StackPanel sibling resize");
            _textBlock8._set_property_value_by_name("FontSize", 12);
            _textBlock8._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock8._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 8));
            _stackPanel7.AddChild(_textBlock8);
            const _border9 = new Border();
            _border9._set_property_value_by_name("Height", 140);
            _border9._set_property_value_by_name("BorderBrush", DynamicResource(_border9, "Outline"));
            _border9._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _stackPanel10 = new StackPanel();
            _stackPanel10._set_property_value_by_name("Orientation", Orientation.Horizontal);
            const _border11 = new Border();
            _border11._set_property_value_by_name("Width", 200);
            _border11._set_property_value_by_name("Height", 138);
            _border11._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#dbeafe')));
            const _textBlock12 = new TextBlock();
            _textBlock12._set_property_value_by_name("Text", "Width=200");
            _textBlock12._set_property_value_by_name("FontSize", 14);
            _textBlock12._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock12._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock12._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _textBlock12._set_property_value_by_name("Foreground", DynamicResource(_textBlock12, "PrimaryContainer"));
            _border11.SetChild(_textBlock12);
            _stackPanel10.AddChild(_border11);
            const _splitter13 = new Splitter();
            _splitter13._set_property_value_by_name("Width", 8);
            _splitter13._set_property_value_by_name("Height", 138);
            _stackPanel10.AddChild(_splitter13);
            const _border14 = new Border();
            _border14._set_property_value_by_name("Width", 300);
            _border14._set_property_value_by_name("Height", 138);
            _border14._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#e0f2fe')));
            const _textBlock15 = new TextBlock();
            _textBlock15._set_property_value_by_name("Text", "Width=300 — drag the gray bar to resize the LEFT pane");
            _textBlock15._set_property_value_by_name("FontSize", 13);
            _textBlock15._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock15._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _textBlock15._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#075985')));
            _textBlock15._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
            _border14.SetChild(_textBlock15);
            _stackPanel10.AddChild(_border14);
            _border9.SetChild(_stackPanel10);
            _stackPanel7.AddChild(_border9);
            const _textBlock16 = new TextBlock();
            _textBlock16._set_property_value_by_name("Text", "Horizontal Splitter — DockPanel top-sibling resize");
            _textBlock16._set_property_value_by_name("FontSize", 12);
            _textBlock16._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock16._set_property_value_by_name("Margin", new Thickness(0, 24, 0, 8));
            _stackPanel7.AddChild(_textBlock16);
            const _border17 = new Border();
            _border17._set_property_value_by_name("Height", 260);
            _border17._set_property_value_by_name("BorderBrush", DynamicResource(_border17, "Outline"));
            _border17._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel18 = new DockPanel();
            const _border19 = new Border();
            _border19._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border19._set_property_value_by_name("Height", 80);
            _border19._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#dcfce7')));
            const _textBlock20 = new TextBlock();
            _textBlock20._set_property_value_by_name("Text", "Height=80");
            _textBlock20._set_property_value_by_name("FontSize", 14);
            _textBlock20._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock20._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock20._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _textBlock20._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#166534')));
            _border19.SetChild(_textBlock20);
            _dockPanel18.AddChild(_border19);
            const _splitter21 = new Splitter();
            _splitter21._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _splitter21._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _splitter21._set_property_value_by_name("Height", 8);
            _dockPanel18.AddChild(_splitter21);
            const _border22 = new Border();
            _border22._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#bbf7d0')));
            const _textBlock23 = new TextBlock();
            _textBlock23._set_property_value_by_name("Text", "Drag the gray bar to resize the TOP pane.");
            _textBlock23._set_property_value_by_name("FontSize", 13);
            _textBlock23._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock23._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _textBlock23._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#14532d')));
            _textBlock23._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
            _border22.SetChild(_textBlock23);
            _dockPanel18.AddChild(_border22);
            _border17.SetChild(_dockPanel18);
            _stackPanel7.AddChild(_border17);
            _dockPanel2.AddChild(_stackPanel7);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, SplitterVM);
        t.Set("SplitterTemplate", _tmpl0);
        return t;
    }
    get SplitterTemplate() { return this.Resolve("SplitterTemplate"); }
    set SplitterTemplate(v) { this.Set("SplitterTemplate", v); }
}
