import { ButtonGroupVM } from "./button-group-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/basic";
import { ButtonGroup } from "@visualisation-sub/mural/framework/button-group.js";
import { Button, ButtonVariant } from "@visualisation-sub/mural/framework/button.js";
import { DataContextBinding, DynamicResource, HorizontalAlignment, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_ButtonGroupDemo = Symbol("ButtonGroupDemo.ctor");
export class ButtonGroupDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_ButtonGroupDemo) {
            throw new Error("ButtonGroupDemo is private — use ButtonGroupDemo.Clone()");
        }
    }
    static Clone() {
        const t = new ButtonGroupDemo(_gate_ButtonGroupDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1._set_property_value_by_name("Background", DynamicResource(_border1, "Surface"));
            _border1._set_property_value_by_name("BorderBrush", DynamicResource(_border1, "OutlineVariant"));
            _border1._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border3._set_property_value_by_name("Background", DynamicResource(_border3, "Primary"));
            _border3._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4._set_property_value_by_name("Text", "ButtonGroup — M3 2024 hover-expand row of action buttons. Hover a segment to see it widen as neighbours shrink in lockstep.");
            _textBlock4._set_property_value_by_name("FontSize", 15);
            _textBlock4._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock4._set_property_value_by_name("Foreground", DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel5._set_property_value_by_name("Margin", new Thickness(24, 24, 24, 24));
            const _textBlock6 = new TextBlock();
            _textBlock6._set_property_value_by_name("Text", "Edit actions");
            _textBlock6._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock6._set_property_value_by_name("FontSize", 14);
            _textBlock6._set_property_value_by_name("Foreground", DynamicResource(_textBlock6, "OnSurface"));
            _textBlock6._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 12));
            _stackPanel5.AddChild(_textBlock6);
            const _buttonGroup7 = new ButtonGroup();
            _buttonGroup7._set_property_value_by_name("BaseWidth", 80);
            _buttonGroup7._set_property_value_by_name("HoverWidth", 130);
            _buttonGroup7._set_property_value_by_name("Spacing", 4);
            _buttonGroup7._set_property_value_by_name("DurationMs", 200);
            _buttonGroup7._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Left);
            _buttonGroup7._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 24));
            const _button8 = new Button();
            _button8._set_property_value_by_name("Variant", ButtonVariant.Tonal);
            _button8._set_property_value_by_name("Command", DataContextBinding(_button8, "UndoCommand"));
            const _textBlock9 = new TextBlock();
            _textBlock9._set_property_value_by_name("Text", "Undo");
            _button8.Content = _textBlock9;
            _buttonGroup7.AddChild(_button8);
            const _button10 = new Button();
            _button10._set_property_value_by_name("Variant", ButtonVariant.Tonal);
            _button10._set_property_value_by_name("Command", DataContextBinding(_button10, "RedoCommand"));
            const _textBlock11 = new TextBlock();
            _textBlock11._set_property_value_by_name("Text", "Redo");
            _button10.Content = _textBlock11;
            _buttonGroup7.AddChild(_button10);
            const _button12 = new Button();
            _button12._set_property_value_by_name("Variant", ButtonVariant.Tonal);
            _button12._set_property_value_by_name("Command", DataContextBinding(_button12, "CutCommand"));
            const _textBlock13 = new TextBlock();
            _textBlock13._set_property_value_by_name("Text", "Cut");
            _button12.Content = _textBlock13;
            _buttonGroup7.AddChild(_button12);
            const _button14 = new Button();
            _button14._set_property_value_by_name("Variant", ButtonVariant.Tonal);
            _button14._set_property_value_by_name("Command", DataContextBinding(_button14, "CopyCommand"));
            const _textBlock15 = new TextBlock();
            _textBlock15._set_property_value_by_name("Text", "Copy");
            _button14.Content = _textBlock15;
            _buttonGroup7.AddChild(_button14);
            const _button16 = new Button();
            _button16._set_property_value_by_name("Variant", ButtonVariant.Tonal);
            _button16._set_property_value_by_name("Command", DataContextBinding(_button16, "PasteCommand"));
            const _textBlock17 = new TextBlock();
            _textBlock17._set_property_value_by_name("Text", "Paste");
            _button16.Content = _textBlock17;
            _buttonGroup7.AddChild(_button16);
            _stackPanel5.AddChild(_buttonGroup7);
            const _stackPanel18 = new StackPanel();
            _stackPanel18._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel18._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            const _textBlock19 = new TextBlock();
            _textBlock19._set_property_value_by_name("Text", "Clicks — ");
            _textBlock19._set_property_value_by_name("FontSize", 12);
            _textBlock19._set_property_value_by_name("Foreground", DynamicResource(_textBlock19, "OnSurfaceVariant"));
            _stackPanel18.AddChild(_textBlock19);
            const _textBlock20 = new TextBlock();
            _textBlock20._set_property_value_by_name("Text", "Undo: ");
            _textBlock20._set_property_value_by_name("FontSize", 12);
            _textBlock20._set_property_value_by_name("Foreground", DynamicResource(_textBlock20, "OnSurfaceVariant"));
            _stackPanel18.AddChild(_textBlock20);
            const _textBlock21 = new TextBlock();
            _textBlock21._set_property_value_by_name("Text", DataContextBinding(_textBlock21, "UndoClicks"));
            _textBlock21._set_property_value_by_name("FontSize", 12);
            _textBlock21._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock21._set_property_value_by_name("Foreground", DynamicResource(_textBlock21, "OnSurface"));
            _stackPanel18.AddChild(_textBlock21);
            const _textBlock22 = new TextBlock();
            _textBlock22._set_property_value_by_name("Text", "  Redo: ");
            _textBlock22._set_property_value_by_name("FontSize", 12);
            _textBlock22._set_property_value_by_name("Foreground", DynamicResource(_textBlock22, "OnSurfaceVariant"));
            _stackPanel18.AddChild(_textBlock22);
            const _textBlock23 = new TextBlock();
            _textBlock23._set_property_value_by_name("Text", DataContextBinding(_textBlock23, "RedoClicks"));
            _textBlock23._set_property_value_by_name("FontSize", 12);
            _textBlock23._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock23._set_property_value_by_name("Foreground", DynamicResource(_textBlock23, "OnSurface"));
            _stackPanel18.AddChild(_textBlock23);
            const _textBlock24 = new TextBlock();
            _textBlock24._set_property_value_by_name("Text", "  Cut: ");
            _textBlock24._set_property_value_by_name("FontSize", 12);
            _textBlock24._set_property_value_by_name("Foreground", DynamicResource(_textBlock24, "OnSurfaceVariant"));
            _stackPanel18.AddChild(_textBlock24);
            const _textBlock25 = new TextBlock();
            _textBlock25._set_property_value_by_name("Text", DataContextBinding(_textBlock25, "CutClicks"));
            _textBlock25._set_property_value_by_name("FontSize", 12);
            _textBlock25._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock25._set_property_value_by_name("Foreground", DynamicResource(_textBlock25, "OnSurface"));
            _stackPanel18.AddChild(_textBlock25);
            const _textBlock26 = new TextBlock();
            _textBlock26._set_property_value_by_name("Text", "  Copy: ");
            _textBlock26._set_property_value_by_name("FontSize", 12);
            _textBlock26._set_property_value_by_name("Foreground", DynamicResource(_textBlock26, "OnSurfaceVariant"));
            _stackPanel18.AddChild(_textBlock26);
            const _textBlock27 = new TextBlock();
            _textBlock27._set_property_value_by_name("Text", DataContextBinding(_textBlock27, "CopyClicks"));
            _textBlock27._set_property_value_by_name("FontSize", 12);
            _textBlock27._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock27._set_property_value_by_name("Foreground", DynamicResource(_textBlock27, "OnSurface"));
            _stackPanel18.AddChild(_textBlock27);
            const _textBlock28 = new TextBlock();
            _textBlock28._set_property_value_by_name("Text", "  Paste: ");
            _textBlock28._set_property_value_by_name("FontSize", 12);
            _textBlock28._set_property_value_by_name("Foreground", DynamicResource(_textBlock28, "OnSurfaceVariant"));
            _stackPanel18.AddChild(_textBlock28);
            const _textBlock29 = new TextBlock();
            _textBlock29._set_property_value_by_name("Text", DataContextBinding(_textBlock29, "PasteClicks"));
            _textBlock29._set_property_value_by_name("FontSize", 12);
            _textBlock29._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock29._set_property_value_by_name("Foreground", DynamicResource(_textBlock29, "OnSurface"));
            _stackPanel18.AddChild(_textBlock29);
            _stackPanel5.AddChild(_stackPanel18);
            const _textBlock30 = new TextBlock();
            _textBlock30._set_property_value_by_name("Text", "Try a different cadence");
            _textBlock30._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock30._set_property_value_by_name("FontSize", 14);
            _textBlock30._set_property_value_by_name("Foreground", DynamicResource(_textBlock30, "OnSurface"));
            _textBlock30._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 12));
            _stackPanel5.AddChild(_textBlock30);
            const _buttonGroup31 = new ButtonGroup();
            _buttonGroup31._set_property_value_by_name("BaseWidth", 64);
            _buttonGroup31._set_property_value_by_name("HoverWidth", 96);
            _buttonGroup31._set_property_value_by_name("Spacing", 2);
            _buttonGroup31._set_property_value_by_name("DurationMs", 400);
            _buttonGroup31._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Left);
            const _button32 = new Button();
            _button32._set_property_value_by_name("Variant", ButtonVariant.Outlined);
            const _textBlock33 = new TextBlock();
            _textBlock33._set_property_value_by_name("Text", "Reply");
            _button32.Content = _textBlock33;
            _buttonGroup31.AddChild(_button32);
            const _button34 = new Button();
            _button34._set_property_value_by_name("Variant", ButtonVariant.Outlined);
            const _textBlock35 = new TextBlock();
            _textBlock35._set_property_value_by_name("Text", "Fwd");
            _button34.Content = _textBlock35;
            _buttonGroup31.AddChild(_button34);
            const _button36 = new Button();
            _button36._set_property_value_by_name("Variant", ButtonVariant.Outlined);
            const _textBlock37 = new TextBlock();
            _textBlock37._set_property_value_by_name("Text", "Archive");
            _button36.Content = _textBlock37;
            _buttonGroup31.AddChild(_button36);
            const _button38 = new Button();
            _button38._set_property_value_by_name("Variant", ButtonVariant.Outlined);
            const _textBlock39 = new TextBlock();
            _textBlock39._set_property_value_by_name("Text", "Trash");
            _button38.Content = _textBlock39;
            _buttonGroup31.AddChild(_button38);
            _stackPanel5.AddChild(_buttonGroup31);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, ButtonGroupVM);
        t.Set("ButtonGroupTemplate", _tmpl0);
        return t;
    }
    get ButtonGroupTemplate() { return this.Resolve("ButtonGroupTemplate"); }
    set ButtonGroupTemplate(v) { this.Set("ButtonGroupTemplate", v); }
}
