import { MenuVM } from "./menu-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Basic";
import { MenuButton, MenuItem, MenuSeparator } from "@visualisation-sub/mural/framework/surface.js";
import { DataContextBinding, DynamicResource, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2._set_property_value_by_name("Background", DynamicResource(_border2, "Surface"));
        _border2._set_property_value_by_name("BorderBrush", DynamicResource(_border2, "OutlineVariant"));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border4._set_property_value_by_name("Background", DynamicResource(_border4, "Primary"));
        _border4._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name("Text", "MenuButton — hamburger fly-out with checkable items and gesture text.");
        _textBlock5._set_property_value_by_name("FontSize", 15);
        _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock5._set_property_value_by_name("Foreground", DynamicResource(_textBlock5, "Surface"));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel6._set_property_value_by_name("Margin", new Thickness(16, 16, 16, 16));
        const _textBlock7 = new TextBlock();
        _textBlock7._set_property_value_by_name("Text", "Click the button to open the menu:");
        _textBlock7._set_property_value_by_name("FontSize", 12);
        _textBlock7._set_property_value_by_name("Foreground", DynamicResource(_textBlock7, "OnSurfaceVariant"));
        _textBlock7._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel6.AddChild(_textBlock7);
        const _menuButton8 = new MenuButton();
        _menuButton8._set_property_value_by_name("Header", "☰  File");
        const _menuItem9 = new MenuItem();
        _menuItem9._set_property_value_by_name("Header", "New");
        _menuItem9._set_property_value_by_name("InputGestureText", "Ctrl+N");
        _menuItem9._set_property_value_by_name("Command", DataContextBinding(_menuItem9, "NewCommand"));
        _menuButton8.AddChild(_menuItem9);
        const _menuItem10 = new MenuItem();
        _menuItem10._set_property_value_by_name("Header", "Open…");
        _menuItem10._set_property_value_by_name("InputGestureText", "Ctrl+O");
        _menuItem10._set_property_value_by_name("Command", DataContextBinding(_menuItem10, "OpenCommand"));
        _menuButton8.AddChild(_menuItem10);
        const _menuSeparator11 = new MenuSeparator();
        _menuButton8.AddChild(_menuSeparator11);
        const _menuItem12 = new MenuItem();
        _menuItem12._set_property_value_by_name("Header", "Save");
        _menuItem12._set_property_value_by_name("InputGestureText", "Ctrl+S");
        _menuItem12._set_property_value_by_name("Command", DataContextBinding(_menuItem12, "SaveCommand"));
        _menuButton8.AddChild(_menuItem12);
        const _menuItem13 = new MenuItem();
        _menuItem13._set_property_value_by_name("Header", "Save As…");
        _menuItem13._set_property_value_by_name("InputGestureText", "Ctrl+Shift+S");
        _menuItem13._set_property_value_by_name("Command", DataContextBinding(_menuItem13, "SaveAsCommand"));
        _menuButton8.AddChild(_menuItem13);
        const _menuSeparator14 = new MenuSeparator();
        _menuButton8.AddChild(_menuSeparator14);
        const _menuItem15 = new MenuItem();
        _menuItem15._set_property_value_by_name("Header", "Close");
        _menuItem15._set_property_value_by_name("InputGestureText", "Ctrl+F4");
        _menuItem15._set_property_value_by_name("Command", DataContextBinding(_menuItem15, "CloseCommand"));
        _menuButton8.AddChild(_menuItem15);
        const _menuSeparator16 = new MenuSeparator();
        _menuButton8.AddChild(_menuSeparator16);
        const _menuItem17 = new MenuItem();
        _menuItem17._set_property_value_by_name("Header", "Undo");
        _menuItem17._set_property_value_by_name("InputGestureText", "Ctrl+Z");
        _menuItem17._set_property_value_by_name("Command", DataContextBinding(_menuItem17, "UndoCommand"));
        _menuButton8.AddChild(_menuItem17);
        const _menuItem18 = new MenuItem();
        _menuItem18._set_property_value_by_name("Header", "Redo");
        _menuItem18._set_property_value_by_name("InputGestureText", "Ctrl+Y");
        _menuItem18._set_property_value_by_name("Command", DataContextBinding(_menuItem18, "RedoCommand"));
        _menuButton8.AddChild(_menuItem18);
        const _menuSeparator19 = new MenuSeparator();
        _menuButton8.AddChild(_menuSeparator19);
        const _menuItem20 = new MenuItem();
        _menuItem20._set_property_value_by_name("Header", "Show Grid");
        _menuItem20._set_property_value_by_name("IsCheckable", true);
        _menuItem20._set_property_value_by_name("IsChecked", DataContextBinding(_menuItem20, "ShowGrid"));
        _menuItem20._set_property_value_by_name("Command", DataContextBinding(_menuItem20, "ShowGridCommand"));
        _menuButton8.AddChild(_menuItem20);
        const _menuItem21 = new MenuItem();
        _menuItem21._set_property_value_by_name("Header", "Snap to Grid");
        _menuItem21._set_property_value_by_name("IsCheckable", true);
        _menuItem21._set_property_value_by_name("IsChecked", DataContextBinding(_menuItem21, "SnapToGrid"));
        _menuItem21._set_property_value_by_name("Command", DataContextBinding(_menuItem21, "SnapToGridCommand"));
        _menuButton8.AddChild(_menuItem21);
        _stackPanel6.AddChild(_menuButton8);
        const _textBlock22 = new TextBlock();
        _textBlock22._set_property_value_by_name("Text", DataContextBinding(_textBlock22, "Status"));
        _textBlock22._set_property_value_by_name("FontSize", 13);
        _textBlock22._set_property_value_by_name("Foreground", DynamicResource(_textBlock22, "OnSurface"));
        _textBlock22._set_property_value_by_name("Margin", new Thickness(0, 16, 0, 0));
        _stackPanel6.AddChild(_textBlock22);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, MenuVM);
    _rd0.Set("MenuTemplate", _tmpl1);
    return _rd0;
}
