import { Border, Button, DataTemplate, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { BeginStoryboardAction, Color, DoubleAnimation, EventTrigger, NameScope, PropertyTrigger, ResourceDictionary, Storyboard, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2.SetNameScope(new NameScope());
        _border2._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _rd3 = _border2.Resources;
        const _act5 = new BeginStoryboardAction((_target) => {
            const _sb4 = new Storyboard();
            _sb4.Add(_target, "Width", new DoubleAnimation({ From: 60, To: 140, Duration: 500 }));
            return _sb4;
        });
        const _evt6 = new EventTrigger("Loaded", [_act5]);
        const _act8 = new BeginStoryboardAction((_target) => {
            const _sb7 = new Storyboard();
            _sb7.Add((_target.FindName("banner") ?? _target), "Width", new DoubleAnimation({ From: 80, To: 320, Duration: 500 }));
            return _sb7;
        });
        const _evt9 = new EventTrigger("Click", [_act8]);
        const _act11 = new BeginStoryboardAction((_target) => {
            const _sb10 = new Storyboard();
            _sb10.Add(_target, "Height", new DoubleAnimation({ To: 36, Duration: 180 }));
            return _sb10;
        });
        const _act13 = new BeginStoryboardAction((_target) => {
            const _sb12 = new Storyboard();
            _sb12.Add(_target, "Height", new DoubleAnimation({ To: 28, Duration: 180 }));
            return _sb12;
        });
        const _sArr14 = [];
        const _enter15 = [_act11];
        const _exit16 = [_act13];
        const _trigger17 = new PropertyTrigger(Button, "IsMouseOver", true, _sArr14, _enter15, _exit16);
        const _style18 = new Style(Button, [], undefined, [_trigger17], [], [_evt6, _evt9]);
        _rd3.Set(Button, _style18);
        const _dockPanel19 = new DockPanel();
        const _border20 = new Border();
        _border20._set_property_value_by_name(DockPanel, "Dock", "Top");
        _border20._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border20._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock21 = new TextBlock();
        _textBlock21._set_property_value_by_name("Text", "Trigger actions — enter/exit, Loaded, TargetName");
        _textBlock21._set_property_value_by_name("FontSize", 15);
        _textBlock21._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock21._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border20.SetChild(_textBlock21);
        _dockPanel19.AddChild(_border20);
        const _stackPanel22 = new StackPanel();
        _stackPanel22._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel22._set_property_value_by_name("Margin", new Thickness(20, 24, 20, 20));
        const _stackPanel23 = new StackPanel();
        _stackPanel23._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel23._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 28));
        const _textBlock24 = new TextBlock();
        _textBlock24._set_property_value_by_name("Text", "Hover an entry — `when(IsMouseOver) { on enter / on exit }` drives Height.");
        _textBlock24._set_property_value_by_name("FontSize", 12);
        _textBlock24._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock24._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel23.AddChild(_textBlock24);
        const _stackPanel25 = new StackPanel();
        _stackPanel25._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _button26 = new Button();
        _button26._set_property_value_by_name("Height", 28);
        _button26._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        const _textBlock27 = new TextBlock();
        _textBlock27._set_property_value_by_name("Text", "Hover me");
        _button26.Content = _textBlock27;
        _stackPanel25.AddChild(_button26);
        const _button28 = new Button();
        _button28._set_property_value_by_name("Height", 28);
        _button28._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        const _textBlock29 = new TextBlock();
        _textBlock29._set_property_value_by_name("Text", "Hover me too");
        _button28.Content = _textBlock29;
        _stackPanel25.AddChild(_button28);
        const _button30 = new Button();
        _button30._set_property_value_by_name("Height", 28);
        _button30._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 6));
        const _textBlock31 = new TextBlock();
        _textBlock31._set_property_value_by_name("Text", "And me");
        _button30.Content = _textBlock31;
        _stackPanel25.AddChild(_button30);
        _stackPanel23.AddChild(_stackPanel25);
        const _textBlock32 = new TextBlock();
        _textBlock32._set_property_value_by_name("Text", "On first mount the same buttons run the Loaded storyboard — Width grows from 60 to 140.");
        _textBlock32._set_property_value_by_name("FontSize", 11);
        _textBlock32._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock32._set_property_value_by_name("Margin", new Thickness(0, 12, 0, 0));
        _stackPanel23.AddChild(_textBlock32);
        _stackPanel22.AddChild(_stackPanel23);
        const _stackPanel33 = new StackPanel();
        _stackPanel33._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _textBlock34 = new TextBlock();
        _textBlock34._set_property_value_by_name("Text", "`TargetName=banner` redirects the storyboard target to the named sibling Border.");
        _textBlock34._set_property_value_by_name("FontSize", 12);
        _textBlock34._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock34._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel33.AddChild(_textBlock34);
        const _button35 = new Button();
        _button35.Name = "bannerBtn";
        _border2.nameScope.Register("bannerBtn", _button35);
        _button35._set_property_value_by_name("Width", 200);
        _button35._set_property_value_by_name("Height", 28);
        _button35._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 12));
        const _textBlock36 = new TextBlock();
        _textBlock36._set_property_value_by_name("Text", "Animate banner");
        _button35.Content = _textBlock36;
        _stackPanel33.AddChild(_button35);
        const _border37 = new Border();
        _border37.Name = "banner";
        _border2.nameScope.Register("banner", _border37);
        _border37._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ff9800')));
        _border37._set_property_value_by_name("Width", 80);
        _border37._set_property_value_by_name("Height", 20);
        _border37._set_property_value_by_name("CornerRadius", 4);
        _stackPanel33.AddChild(_border37);
        _stackPanel22.AddChild(_stackPanel33);
        _dockPanel19.AddChild(_stackPanel22);
        _border2.SetChild(_dockPanel19);
        return _border2;
    }, "AnimationTriggersVM");
    _rd0.Set("AnimationTriggersTemplate", _tmpl1);
    return _rd0;
}
