import { DragDropExtendedVM, DroppedFileVM, RowVM } from "./drag-drop-extended-vm.mjs";
import { Border, ContentPresenter, DataTemplate, Dock, DockPanel, ItemsPanelTemplate, ListReorderBehavior, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/basic";
import { ItemsControl } from "@visualisation-sub/mural/framework/base/items-control.js";
import { ScrollViewer } from "@visualisation-sub/mural/framework/surfaces/scroll-viewer.js";
import { Color, DataContextBinding, DynamicResource, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_DragDropExtendedDemo = Symbol("DragDropExtendedDemo.ctor");
export class DragDropExtendedDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_DragDropExtendedDemo) {
            throw new Error("DragDropExtendedDemo is private — use DragDropExtendedDemo.Clone()");
        }
    }
    static Clone() {
        const t = new DragDropExtendedDemo(_gate_DragDropExtendedDemo);
        const _tmpl0 = new ItemsPanelTemplate(() => {
            const _stackPanel1 = new StackPanel();
            return _stackPanel1;
        });
        t.Set("ReorderListPanel", _tmpl0);
        const _tmpl2 = new DataTemplate((_data) => {
            const _border3 = new Border();
            _border3.set_property_value(Border.BackgroundKey, DynamicResource(_border3, "Surface"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(12, 6, 12, 6));
            const _textBlock4 = new TextBlock();
            _textBlock4.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock4, "Label"));
            _textBlock4.set_property_value(TextBlock.FontSizeKey, 13);
            _textBlock4.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock4, "OnSurface"));
            _border3.SetChild(_textBlock4);
            return _border3;
        }, RowVM);
        t.Set(RowVM, _tmpl2);
        const _tmpl5 = new DataTemplate((_data) => {
            const _border6 = new Border();
            _border6.set_property_value(Border.PaddingKey, new Thickness(8, 3, 8, 3));
            const _stackPanel7 = new StackPanel();
            _stackPanel7.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _textBlock8 = new TextBlock();
            _textBlock8.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock8, "Name"));
            _textBlock8.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock8.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock8, "OnSurface"));
            _stackPanel7.AddChild(_textBlock8);
            const _textBlock9 = new TextBlock();
            _textBlock9.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock9, "Size"));
            _textBlock9.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock9.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock9, "OnSurfaceVariant"));
            _textBlock9.set_property_value(TextBlock.MarginKey, new Thickness(8, 1, 0, 0));
            _stackPanel7.AddChild(_textBlock9);
            _border6.SetChild(_stackPanel7);
            return _border6;
        }, DroppedFileVM);
        t.Set(DroppedFileVM, _tmpl5);
        const _tmpl10 = new DataTemplate((_data) => {
            let _scrollViewer11, _itemsControl12, _listReorderBehavior13, _itemsControl14;
            const _border15 = new Border();
            _border15.SetNameScope(new NameScope());
            _border15.set_property_value(Border.BackgroundKey, DynamicResource(_border15, "Surface"));
            _border15.set_property_value(Border.BorderBrushKey, DynamicResource(_border15, "OutlineVariant"));
            _border15.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _rd16 = _border15.Resources;
            const _setter17 = new Setter(ContentPresenter, "IsDraggable", true);
            const _setter18 = new Setter(ContentPresenter, "OnDragStart", new SetterFactory((_t) => DataContextBinding(_t, "BeginDragData")));
            const _style19 = new Style(ContentPresenter, [_setter17, _setter18], undefined, [], []);
            _rd16.Set(ContentPresenter, _style19);
            const _dockPanel20 = new DockPanel();
            const _border21 = new Border();
            _border21.set_property_value(DockPanel.DockKey, Dock.Top);
            _border21.set_property_value(Border.BackgroundKey, DynamicResource(_border21, "InverseSurface"));
            _border21.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _stackPanel22 = new StackPanel();
            _stackPanel22.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, "Drag & drop extended");
            _textBlock23.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock23.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock23.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock23, "InverseOnSurface"));
            _stackPanel22.AddChild(_textBlock23);
            const _stackPanel24 = new StackPanel();
            _stackPanel24.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel24.set_property_value(StackPanel.MarginKey, new Thickness(0, 4, 0, 0));
            const _textBlock25 = new TextBlock();
            _textBlock25.set_property_value(TextBlock.TextKey, "Last receiver effect:");
            _textBlock25.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock25.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock25, "Outline"));
            _stackPanel24.AddChild(_textBlock25);
            const _textBlock26 = new TextBlock();
            _textBlock26.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock26, "LastEffect"));
            _textBlock26.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock26.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock26.set_property_value(TextBlock.ForegroundKey, new SolidColorBrush(Color.FromHex('#60a5fa')));
            _textBlock26.set_property_value(TextBlock.MarginKey, new Thickness(6, 0, 16, 0));
            _stackPanel24.AddChild(_textBlock26);
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock27, "ShiftHint"));
            _textBlock27.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock27.set_property_value(TextBlock.ForegroundKey, new SolidColorBrush(Color.FromHex('#fbbf24')));
            _stackPanel24.AddChild(_textBlock27);
            _stackPanel22.AddChild(_stackPanel24);
            _border21.SetChild(_stackPanel22);
            _dockPanel20.AddChild(_border21);
            const _textBlock28 = new TextBlock();
            _textBlock28.set_property_value(DockPanel.DockKey, Dock.Bottom);
            _textBlock28.set_property_value(TextBlock.MarginKey, new Thickness(20, 4, 20, 16));
            _textBlock28.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock28.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock28, "OnSurfaceVariant"));
            _textBlock28.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock28.set_property_value(TextBlock.TextKey, "LEFT: drag any row to reorder — the blue insertion line previews the drop position (backlog 8.5). Drag toward the top / bottom edges to auto-scroll the ScrollViewer (8.4). Hold Shift mid-drag to cancel via OnContinueQuery (8.3). RIGHT: drop files, text, or URLs from your OS / other browser windows (8.1).");
            _dockPanel20.AddChild(_textBlock28);
            const _stackPanel29 = new StackPanel();
            _stackPanel29.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel29.set_property_value(StackPanel.MarginKey, new Thickness(20));
            _stackPanel29.set_property_value(StackPanel.VerticalAlignmentKey, VerticalAlignment.Stretch);
            const _border30 = new Border();
            _border30.set_property_value(Border.WidthKey, 320);
            _border30.set_property_value(Border.HeightKey, 280);
            _border30.set_property_value(Border.BorderBrushKey, DynamicResource(_border30, "OutlineVariant"));
            _border30.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _border30.set_property_value(Border.MarginKey, new Thickness(0, 0, 16, 0));
            _scrollViewer11 = new ScrollViewer();
            _scrollViewer11.Name = "scroll";
            _scrollViewer11.set_property_value(ScrollViewer.AutoScrollGutterKey, 32);
            _scrollViewer11.set_property_value(ScrollViewer.AutoScrollStepKey, 6);
            _scrollViewer11.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, false);
            _itemsControl12 = new ItemsControl();
            _itemsControl12.Name = "reorderList";
            _itemsControl12.set_property_value(ItemsControl.ItemsSourceKey, DataContextBinding(_itemsControl12, "Rows"));
            _itemsControl12.set_property_value(ItemsControl.ItemsPanelKey, _tmpl0);
            _listReorderBehavior13 = new ListReorderBehavior();
            _listReorderBehavior13.Name = "reorder";
            _listReorderBehavior13.set_property_value(ListReorderBehavior.FromIndexFormatKey, "mural/reorder/from-index");
            _itemsControl12.AddBehavior(_listReorderBehavior13);
            _scrollViewer11.Content = _itemsControl12;
            _border30.SetChild(_scrollViewer11);
            _stackPanel29.AddChild(_border30);
            const _border31 = new Border();
            _border31.set_property_value(Border.WidthKey, 320);
            _border31.set_property_value(Border.HeightKey, 280);
            _border31.set_property_value(Border.BorderBrushKey, DynamicResource(_border31, "Outline"));
            _border31.set_property_value(Border.BorderThicknessKey, new Thickness(2));
            _border31.set_property_value(Border.BackgroundKey, DynamicResource(_border31, "SurfaceContainerLow"));
            const _dockPanel32 = new DockPanel();
            const _border33 = new Border();
            _border33.set_property_value(DockPanel.DockKey, Dock.Top);
            _border33.set_property_value(Border.BackgroundKey, new SolidColorBrush(Color.FromHex('#dbeafe')));
            _border33.set_property_value(Border.PaddingKey, new Thickness(12, 10, 12, 10));
            const _stackPanel34 = new StackPanel();
            _stackPanel34.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock35 = new TextBlock();
            _textBlock35.set_property_value(TextBlock.TextKey, "OS file drop zone");
            _textBlock35.set_property_value(TextBlock.FontSizeKey, 13);
            _textBlock35.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock35.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock35, "OnSurface"));
            _stackPanel34.AddChild(_textBlock35);
            const _textBlock36 = new TextBlock();
            _textBlock36.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock36, "FileStatus"));
            _textBlock36.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock36.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock36, "PrimaryContainer"));
            _textBlock36.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _textBlock36.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _stackPanel34.AddChild(_textBlock36);
            _border33.SetChild(_stackPanel34);
            _dockPanel32.AddChild(_border33);
            const _scrollViewer37 = new ScrollViewer();
            _scrollViewer37.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, true);
            _itemsControl14 = new ItemsControl();
            _itemsControl14.Name = "filesList";
            _itemsControl14.set_property_value(ItemsControl.ItemsSourceKey, DataContextBinding(_itemsControl14, "DroppedFiles"));
            _itemsControl14.set_property_value(ItemsControl.ItemsPanelKey, _tmpl0);
            _scrollViewer37.Content = _itemsControl14;
            _dockPanel32.AddChild(_scrollViewer37);
            _border31.SetChild(_dockPanel32);
            _stackPanel29.AddChild(_border31);
            _dockPanel20.AddChild(_stackPanel29);
            _border15.SetChild(_dockPanel20);
            return _border15;
        }, DragDropExtendedVM);
        t.Set(DragDropExtendedVM, _tmpl10);
        return t;
    }
    get ReorderListPanel() { return this.Resolve("ReorderListPanel"); }
    set ReorderListPanel(v) { this.Set("ReorderListPanel", v); }
}
