import { DragDropExtendedVM, DroppedFileVM, RowVM } from "./drag-drop-extended-vm.mjs";
import { Border, ContentPresenter, DataTemplate, Dock, DockPanel, ItemsPanelTemplate, ListReorderBehavior, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/basic";
import { ItemsControl } from "@visualisation-sub/mural/framework/items-control.js";
import { ScrollViewer } from "@visualisation-sub/mural/framework/scroll-viewer.js";
import { Color, DataContextBinding, DynamicResource, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_DragDropExtendedDemo = Symbol("DragDropExtendedDemo.ctor");
export class DragDropExtendedDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_DragDropExtendedDemo) {
            throw new Error("DragDropExtendedDemo is private — use DragDropExtendedDemo.Clone()");
        }
    }
    static Clone() {
        const t = new DragDropExtendedDemo(_gate_DragDropExtendedDemo);
        const _tmpl0 = new ItemsPanelTemplate(() => {
            const _stackPanel1 = new StackPanel();
            return _stackPanel1;
        });
        t.Set("ReorderListPanel", _tmpl0);
        const _tmpl2 = new DataTemplate((_data) => {
            const _border3 = new Border();
            _border3.set_property_value(Border.BackgroundKey, DynamicResource(_border3, "Surface"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(12, 6, 12, 6));
            const _textBlock4 = new TextBlock();
            _textBlock4.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock4, "Label"));
            _textBlock4.set_property_value(TextBlock.FontSizeKey, 13);
            _textBlock4.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock4, "OnSurface"));
            _border3.SetChild(_textBlock4);
            return _border3;
        }, RowVM);
        t.Set(RowVM, _tmpl2);
        const _tmpl5 = new DataTemplate((_data) => {
            const _border6 = new Border();
            _border6.set_property_value(Border.PaddingKey, new Thickness(8, 3, 8, 3));
            const _stackPanel7 = new StackPanel();
            _stackPanel7.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _textBlock8 = new TextBlock();
            _textBlock8.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock8, "Name"));
            _textBlock8.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock8.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock8, "OnSurface"));
            _stackPanel7.AddChild(_textBlock8);
            const _textBlock9 = new TextBlock();
            _textBlock9.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock9, "Size"));
            _textBlock9.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock9.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock9, "OnSurfaceVariant"));
            _textBlock9.set_property_value(TextBlock.MarginKey, new Thickness(8, 1, 0, 0));
            _stackPanel7.AddChild(_textBlock9);
            _border6.SetChild(_stackPanel7);
            return _border6;
        }, DroppedFileVM);
        t.Set(DroppedFileVM, _tmpl5);
        const _tmpl10 = new DataTemplate((_data) => {
            const _border11 = new Border();
            _border11.SetNameScope(new NameScope());
            _border11.set_property_value(Border.BackgroundKey, DynamicResource(_border11, "Surface"));
            _border11.set_property_value(Border.BorderBrushKey, DynamicResource(_border11, "OutlineVariant"));
            _border11.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _rd12 = _border11.Resources;
            const _setter13 = new Setter(ContentPresenter, "IsDraggable", true);
            const _setter14 = new Setter(ContentPresenter, "OnDragStart", new SetterFactory((_t) => DataContextBinding(_t, "BeginDragData")));
            const _style15 = new Style(ContentPresenter, [_setter13, _setter14], undefined, [], []);
            _rd12.Set(ContentPresenter, _style15);
            const _dockPanel16 = new DockPanel();
            const _border17 = new Border();
            _border17.set_property_value(DockPanel.DockKey, Dock.Top);
            _border17.set_property_value(Border.BackgroundKey, DynamicResource(_border17, "InverseSurface"));
            _border17.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _stackPanel18 = new StackPanel();
            _stackPanel18.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "Drag & drop extended");
            _textBlock19.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock19.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock19.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock19, "InverseOnSurface"));
            _stackPanel18.AddChild(_textBlock19);
            const _stackPanel20 = new StackPanel();
            _stackPanel20.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel20.set_property_value(StackPanel.MarginKey, new Thickness(0, 4, 0, 0));
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "Last receiver effect:");
            _textBlock21.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock21.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock21, "Outline"));
            _stackPanel20.AddChild(_textBlock21);
            const _textBlock22 = new TextBlock();
            _textBlock22.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock22, "LastEffect"));
            _textBlock22.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock22.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock22.set_property_value(TextBlock.ForegroundKey, new SolidColorBrush(Color.FromHex('#60a5fa')));
            _textBlock22.set_property_value(TextBlock.MarginKey, new Thickness(6, 0, 16, 0));
            _stackPanel20.AddChild(_textBlock22);
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock23, "ShiftHint"));
            _textBlock23.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock23.set_property_value(TextBlock.ForegroundKey, new SolidColorBrush(Color.FromHex('#fbbf24')));
            _stackPanel20.AddChild(_textBlock23);
            _stackPanel18.AddChild(_stackPanel20);
            _border17.SetChild(_stackPanel18);
            _dockPanel16.AddChild(_border17);
            const _textBlock24 = new TextBlock();
            _textBlock24.set_property_value(DockPanel.DockKey, Dock.Bottom);
            _textBlock24.set_property_value(TextBlock.MarginKey, new Thickness(20, 4, 20, 16));
            _textBlock24.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock24.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock24, "OnSurfaceVariant"));
            _textBlock24.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock24.set_property_value(TextBlock.TextKey, "LEFT: drag any row to reorder — the blue insertion line previews the drop position (backlog 8.5). Drag toward the top / bottom edges to auto-scroll the ScrollViewer (8.4). Hold Shift mid-drag to cancel via OnContinueQuery (8.3). RIGHT: drop files, text, or URLs from your OS / other browser windows (8.1).");
            _dockPanel16.AddChild(_textBlock24);
            const _stackPanel25 = new StackPanel();
            _stackPanel25.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel25.set_property_value(StackPanel.MarginKey, new Thickness(20));
            _stackPanel25.set_property_value(StackPanel.VerticalAlignmentKey, VerticalAlignment.Stretch);
            const _border26 = new Border();
            _border26.set_property_value(Border.WidthKey, 320);
            _border26.set_property_value(Border.HeightKey, 280);
            _border26.set_property_value(Border.BorderBrushKey, DynamicResource(_border26, "OutlineVariant"));
            _border26.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _border26.set_property_value(Border.MarginKey, new Thickness(0, 0, 16, 0));
            const _scrollViewer27 = new ScrollViewer();
            _scrollViewer27.Name = "scroll";
            _scrollViewer27.set_property_value(ScrollViewer.AutoScrollGutterKey, 32);
            _scrollViewer27.set_property_value(ScrollViewer.AutoScrollStepKey, 6);
            _scrollViewer27.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, false);
            const _itemsControl28 = new ItemsControl();
            _itemsControl28.Name = "reorderList";
            _itemsControl28.set_property_value(ItemsControl.ItemsSourceKey, DataContextBinding(_itemsControl28, "Rows"));
            _itemsControl28.set_property_value(ItemsControl.ItemsPanelKey, _tmpl0);
            const _listReorderBehavior29 = new ListReorderBehavior();
            _listReorderBehavior29.Name = "reorder";
            _listReorderBehavior29.set_property_value(ListReorderBehavior.FromIndexFormatKey, "mural/reorder/from-index");
            _itemsControl28.AddBehavior(_listReorderBehavior29);
            _scrollViewer27.Content = _itemsControl28;
            _border26.SetChild(_scrollViewer27);
            _stackPanel25.AddChild(_border26);
            const _border30 = new Border();
            _border30.set_property_value(Border.WidthKey, 320);
            _border30.set_property_value(Border.HeightKey, 280);
            _border30.set_property_value(Border.BorderBrushKey, DynamicResource(_border30, "Outline"));
            _border30.set_property_value(Border.BorderThicknessKey, new Thickness(2));
            _border30.set_property_value(Border.BackgroundKey, DynamicResource(_border30, "SurfaceContainerLow"));
            const _dockPanel31 = new DockPanel();
            const _border32 = new Border();
            _border32.set_property_value(DockPanel.DockKey, Dock.Top);
            _border32.set_property_value(Border.BackgroundKey, new SolidColorBrush(Color.FromHex('#dbeafe')));
            _border32.set_property_value(Border.PaddingKey, new Thickness(12, 10, 12, 10));
            const _stackPanel33 = new StackPanel();
            _stackPanel33.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock34 = new TextBlock();
            _textBlock34.set_property_value(TextBlock.TextKey, "OS file drop zone");
            _textBlock34.set_property_value(TextBlock.FontSizeKey, 13);
            _textBlock34.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock34.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock34, "OnSurface"));
            _stackPanel33.AddChild(_textBlock34);
            const _textBlock35 = new TextBlock();
            _textBlock35.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock35, "FileStatus"));
            _textBlock35.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock35.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock35, "PrimaryContainer"));
            _textBlock35.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _textBlock35.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _stackPanel33.AddChild(_textBlock35);
            _border32.SetChild(_stackPanel33);
            _dockPanel31.AddChild(_border32);
            const _scrollViewer36 = new ScrollViewer();
            _scrollViewer36.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, true);
            const _itemsControl37 = new ItemsControl();
            _itemsControl37.Name = "filesList";
            _itemsControl37.set_property_value(ItemsControl.ItemsSourceKey, DataContextBinding(_itemsControl37, "DroppedFiles"));
            _itemsControl37.set_property_value(ItemsControl.ItemsPanelKey, _tmpl0);
            _scrollViewer36.Content = _itemsControl37;
            _dockPanel31.AddChild(_scrollViewer36);
            _border30.SetChild(_dockPanel31);
            _stackPanel25.AddChild(_border30);
            _dockPanel16.AddChild(_stackPanel25);
            _border11.SetChild(_dockPanel16);
            return _border11;
        }, DragDropExtendedVM);
        t.Set(DragDropExtendedVM, _tmpl10);
        return t;
    }
    get ReorderListPanel() { return this.Resolve("ReorderListPanel"); }
    set ReorderListPanel(v) { this.Set("ReorderListPanel", v); }
}
