import { DragDropExtendedVM, DroppedFileVM, RowVM } from "./drag-drop-extended-vm.mjs";
import { Border, ContentPresenter, DataTemplate, Dock, DockPanel, ItemsPanelTemplate, ListReorderBehavior, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/Basic";
import { ItemsControl } from "@visualisation-sub/mural/framework/items-control.js";
import { ScrollViewer } from "@visualisation-sub/mural/framework/scroll-viewer.js";
import { Color, DataContextBinding, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new ItemsPanelTemplate(() => {
        const _stackPanel2 = new StackPanel();
        return _stackPanel2;
    });
    _rd0.Set("ReorderListPanel", _tmpl1);
    const _tmpl3 = new DataTemplate((_data) => {
        const _border4 = new Border();
        _border4._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border4._set_property_value_by_name("Padding", new Thickness(12, 6, 12, 6));
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name("Text", DataContextBinding(_textBlock5, "Label"));
        _textBlock5._set_property_value_by_name("FontSize", 13);
        _textBlock5._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#1f2937')));
        _border4.SetChild(_textBlock5);
        return _border4;
    }, RowVM);
    _rd0.Set(RowVM, _tmpl3);
    const _tmpl6 = new DataTemplate((_data) => {
        const _border7 = new Border();
        _border7._set_property_value_by_name("Padding", new Thickness(8, 3, 8, 3));
        const _stackPanel8 = new StackPanel();
        _stackPanel8._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _textBlock9 = new TextBlock();
        _textBlock9._set_property_value_by_name("Text", DataContextBinding(_textBlock9, "Name"));
        _textBlock9._set_property_value_by_name("FontSize", 12);
        _textBlock9._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#0f172a')));
        _stackPanel8.AddChild(_textBlock9);
        const _textBlock10 = new TextBlock();
        _textBlock10._set_property_value_by_name("Text", DataContextBinding(_textBlock10, "Size"));
        _textBlock10._set_property_value_by_name("FontSize", 11);
        _textBlock10._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock10._set_property_value_by_name("Margin", new Thickness(8, 1, 0, 0));
        _stackPanel8.AddChild(_textBlock10);
        _border7.SetChild(_stackPanel8);
        return _border7;
    }, DroppedFileVM);
    _rd0.Set(DroppedFileVM, _tmpl6);
    const _tmpl11 = new DataTemplate((_data) => {
        const _border12 = new Border();
        _border12.SetNameScope(new NameScope());
        _border12._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border12._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border12._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _rd13 = _border12.Resources;
        const _setter14 = new Setter(ContentPresenter, "IsDraggable", true);
        const _setter15 = new Setter(ContentPresenter, "OnDragStart", new SetterFactory((_t) => DataContextBinding(_t, "BeginDragData")));
        const _style16 = new Style(ContentPresenter, [_setter14, _setter15], undefined, [], []);
        _rd13.Set(ContentPresenter, _style16);
        const _dockPanel17 = new DockPanel();
        const _border18 = new Border();
        _border18._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border18._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#0f172a')));
        _border18._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _stackPanel19 = new StackPanel();
        _stackPanel19._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "Drag & drop extended");
        _textBlock20._set_property_value_by_name("FontSize", 15);
        _textBlock20._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock20._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#f8fafc')));
        _stackPanel19.AddChild(_textBlock20);
        const _stackPanel21 = new StackPanel();
        _stackPanel21._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel21._set_property_value_by_name("Margin", new Thickness(0, 4, 0, 0));
        const _textBlock22 = new TextBlock();
        _textBlock22._set_property_value_by_name("Text", "Last receiver effect:");
        _textBlock22._set_property_value_by_name("FontSize", 11);
        _textBlock22._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#cbd5e1')));
        _stackPanel21.AddChild(_textBlock22);
        const _textBlock23 = new TextBlock();
        _textBlock23._set_property_value_by_name("Text", DataContextBinding(_textBlock23, "LastEffect"));
        _textBlock23._set_property_value_by_name("FontSize", 11);
        _textBlock23._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock23._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#60a5fa')));
        _textBlock23._set_property_value_by_name("Margin", new Thickness(6, 0, 16, 0));
        _stackPanel21.AddChild(_textBlock23);
        const _textBlock24 = new TextBlock();
        _textBlock24._set_property_value_by_name("Text", DataContextBinding(_textBlock24, "ShiftHint"));
        _textBlock24._set_property_value_by_name("FontSize", 11);
        _textBlock24._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#fbbf24')));
        _stackPanel21.AddChild(_textBlock24);
        _stackPanel19.AddChild(_stackPanel21);
        _border18.SetChild(_stackPanel19);
        _dockPanel17.AddChild(_border18);
        const _textBlock25 = new TextBlock();
        _textBlock25._set_property_value_by_name(DockPanel, "Dock", Dock.Bottom);
        _textBlock25._set_property_value_by_name("Margin", new Thickness(20, 4, 20, 16));
        _textBlock25._set_property_value_by_name("FontSize", 11);
        _textBlock25._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock25._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
        _textBlock25._set_property_value_by_name("Text", "LEFT: drag any row to reorder — the blue insertion line previews the drop position (backlog 8.5). Drag toward the top / bottom edges to auto-scroll the ScrollViewer (8.4). Hold Shift mid-drag to cancel via OnContinueQuery (8.3). RIGHT: drop files, text, or URLs from your OS / other browser windows (8.1).");
        _dockPanel17.AddChild(_textBlock25);
        const _stackPanel26 = new StackPanel();
        _stackPanel26._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel26._set_property_value_by_name("Margin", new Thickness(20));
        _stackPanel26._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Stretch);
        const _border27 = new Border();
        _border27._set_property_value_by_name("Width", 320);
        _border27._set_property_value_by_name("Height", 280);
        _border27._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border27._set_property_value_by_name("BorderThickness", new Thickness(1));
        _border27._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
        const _scrollViewer28 = new ScrollViewer();
        _scrollViewer28.Name = "scroll";
        _scrollViewer28._set_property_value_by_name("AutoScrollGutter", 32);
        _scrollViewer28._set_property_value_by_name("AutoScrollStep", 6);
        _scrollViewer28._set_property_value_by_name("IsAutoHideScrollBars", false);
        const _itemsControl29 = new ItemsControl();
        _itemsControl29.Name = "reorderList";
        _itemsControl29._set_property_value_by_name("ItemsSource", DataContextBinding(_itemsControl29, "Rows"));
        _itemsControl29._set_property_value_by_name("ItemsPanel", _tmpl1);
        const _listReorderBehavior30 = new ListReorderBehavior();
        _listReorderBehavior30.Name = "reorder";
        _listReorderBehavior30._set_property_value_by_name("FromIndexFormat", "mural/reorder/from-index");
        _itemsControl29.AddBehavior(_listReorderBehavior30);
        _scrollViewer28.Content = _itemsControl29;
        _border27.SetChild(_scrollViewer28);
        _stackPanel26.AddChild(_border27);
        const _border31 = new Border();
        _border31._set_property_value_by_name("Width", 320);
        _border31._set_property_value_by_name("Height", 280);
        _border31._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#cbd5e1')));
        _border31._set_property_value_by_name("BorderThickness", new Thickness(2));
        _border31._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#f1f5f9')));
        const _dockPanel32 = new DockPanel();
        const _border33 = new Border();
        _border33._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border33._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#dbeafe')));
        _border33._set_property_value_by_name("Padding", new Thickness(12, 10, 12, 10));
        const _stackPanel34 = new StackPanel();
        _stackPanel34._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _textBlock35 = new TextBlock();
        _textBlock35._set_property_value_by_name("Text", "OS file drop zone");
        _textBlock35._set_property_value_by_name("FontSize", 13);
        _textBlock35._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock35._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#0f172a')));
        _stackPanel34.AddChild(_textBlock35);
        const _textBlock36 = new TextBlock();
        _textBlock36._set_property_value_by_name("Text", DataContextBinding(_textBlock36, "FileStatus"));
        _textBlock36._set_property_value_by_name("FontSize", 11);
        _textBlock36._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#1e3a8a')));
        _textBlock36._set_property_value_by_name("Margin", new Thickness(0, 4, 0, 0));
        _textBlock36._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
        _stackPanel34.AddChild(_textBlock36);
        _border33.SetChild(_stackPanel34);
        _dockPanel32.AddChild(_border33);
        const _scrollViewer37 = new ScrollViewer();
        _scrollViewer37._set_property_value_by_name("IsAutoHideScrollBars", true);
        const _itemsControl38 = new ItemsControl();
        _itemsControl38.Name = "filesList";
        _itemsControl38._set_property_value_by_name("ItemsSource", DataContextBinding(_itemsControl38, "DroppedFiles"));
        _itemsControl38._set_property_value_by_name("ItemsPanel", _tmpl1);
        _scrollViewer37.Content = _itemsControl38;
        _dockPanel32.AddChild(_scrollViewer37);
        _border31.SetChild(_dockPanel32);
        _stackPanel26.AddChild(_border31);
        _dockPanel17.AddChild(_stackPanel26);
        _border12.SetChild(_dockPanel17);
        return _border12;
    }, DragDropExtendedVM);
    _rd0.Set(DragDropExtendedVM, _tmpl11);
    return _rd0;
}
