import { Border, DataTemplate, DockPanel, ListBox, ListBoxItem, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Application, Color, DataContextBinding, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _textBlock2 = new TextBlock();
        _textBlock2._set_property_value_by_name("Text", DataContextBinding(_textBlock2, "Label"));
        _textBlock2._set_property_value_by_name("Margin", new Thickness(8, 4, 8, 4));
        _textBlock2._set_property_value_by_name("FontSize", 12);
        return _textBlock2;
    }, "ItemVM");
    _rd0.Set("DragDropItemTemplate", _tmpl1);
    const _setter3 = new Setter(ListBoxItem, "IsDraggable", true);
    const _setter4 = new Setter(ListBoxItem, "OnDragStart", new SetterFactory((_t) => DataContextBinding(_t, "BeginDragData")));
    const _style5 = new Style(ListBoxItem, [_setter3, _setter4], undefined, [], []);
    _rd0.Set("DragDropItemContainerStyle", _style5);
    const _tmpl6 = new DataTemplate((_data) => {
        const _border7 = new Border();
        _border7.SetNameScope(new NameScope());
        _border7._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border7._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border7._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel8 = new DockPanel();
        const _border9 = new Border();
        _border9._set_property_value_by_name(DockPanel, "Dock", "Top");
        _border9._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border9._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _stackPanel10 = new StackPanel();
        _stackPanel10._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _textBlock11 = new TextBlock();
        _textBlock11._set_property_value_by_name("Text", "Drag-drop between lists");
        _textBlock11._set_property_value_by_name("FontSize", 15);
        _textBlock11._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock11._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _stackPanel10.AddChild(_textBlock11);
        const _textBlock12 = new TextBlock();
        _textBlock12._set_property_value_by_name("Text", DataContextBinding(_textBlock12, "Status"));
        _textBlock12._set_property_value_by_name("FontSize", 12);
        _textBlock12._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _textBlock12._set_property_value_by_name("Margin", new Thickness(20, 4, 0, 0));
        _stackPanel10.AddChild(_textBlock12);
        _border9.SetChild(_stackPanel10);
        _dockPanel8.AddChild(_border9);
        const _textBlock13 = new TextBlock();
        _textBlock13._set_property_value_by_name(DockPanel, "Dock", "Bottom");
        _textBlock13._set_property_value_by_name("Margin", new Thickness(20, 4, 20, 16));
        _textBlock13._set_property_value_by_name("FontSize", 11);
        _textBlock13._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock13._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
        _textBlock13._set_property_value_by_name("Text", "Drag any item from one list to the other to move it. The framework's IsDraggable + OnDragStart binding starts the drag; a Behavior on each ListBox handles DragOver/Drop and dispatches to VM commands.");
        _dockPanel8.AddChild(_textBlock13);
        const _stackPanel14 = new StackPanel();
        _stackPanel14._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel14._set_property_value_by_name("Margin", new Thickness(20));
        _stackPanel14._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Stretch);
        const _border15 = new Border();
        _border15._set_property_value_by_name("Width", 220);
        _border15._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Stretch);
        _border15._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
        _border15._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border15._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel16 = new DockPanel();
        const _textBlock17 = new TextBlock();
        _textBlock17._set_property_value_by_name(DockPanel, "Dock", "Top");
        _textBlock17._set_property_value_by_name("Text", "Left");
        _textBlock17._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock17._set_property_value_by_name("FontSize", 12);
        _textBlock17._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#374151')));
        _textBlock17._set_property_value_by_name("Margin", new Thickness(10, 8, 8, 4));
        _dockPanel16.AddChild(_textBlock17);
        const _listBox18 = new ListBox();
        _listBox18.Name = "leftList";
        _border7.nameScope.Register("leftList", _listBox18);
        _listBox18._set_property_value_by_name("ItemsSource", DataContextBinding(_listBox18, "LeftItems"));
        _listBox18._set_property_value_by_name("ItemTemplate", Application.current.Resources.Resolve("DragDropItemTemplate"));
        _listBox18._set_property_value_by_name("ItemContainerStyle", Application.current.Resources.Resolve("DragDropItemContainerStyle"));
        _dockPanel16.AddChild(_listBox18);
        _border15.SetChild(_dockPanel16);
        _stackPanel14.AddChild(_border15);
        const _border19 = new Border();
        _border19._set_property_value_by_name("Width", 220);
        _border19._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Stretch);
        _border19._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border19._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel20 = new DockPanel();
        const _textBlock21 = new TextBlock();
        _textBlock21._set_property_value_by_name(DockPanel, "Dock", "Top");
        _textBlock21._set_property_value_by_name("Text", "Right");
        _textBlock21._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock21._set_property_value_by_name("FontSize", 12);
        _textBlock21._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#374151')));
        _textBlock21._set_property_value_by_name("Margin", new Thickness(10, 8, 8, 4));
        _dockPanel20.AddChild(_textBlock21);
        const _listBox22 = new ListBox();
        _listBox22.Name = "rightList";
        _border7.nameScope.Register("rightList", _listBox22);
        _listBox22._set_property_value_by_name("ItemsSource", DataContextBinding(_listBox22, "RightItems"));
        _listBox22._set_property_value_by_name("ItemTemplate", Application.current.Resources.Resolve("DragDropItemTemplate"));
        _listBox22._set_property_value_by_name("ItemContainerStyle", Application.current.Resources.Resolve("DragDropItemContainerStyle"));
        _dockPanel20.AddChild(_listBox22);
        _border19.SetChild(_dockPanel20);
        _stackPanel14.AddChild(_border19);
        _dockPanel8.AddChild(_stackPanel14);
        _border7.SetChild(_dockPanel8);
        return _border7;
    }, "DragDropVM");
    _rd0.Set("DragDropTemplate", _tmpl6);
    return _rd0;
}
