import { Border, ContentPresenter, DataTemplate, DockPanel, ItemsControl, ItemsPanelTemplate, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Application, Color, DataContextBinding, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _textBlock2 = new TextBlock();
        _textBlock2._set_property_value_by_name("Text", DataContextBinding(_textBlock2, "Label"));
        _textBlock2._set_property_value_by_name("Margin", new Thickness(8, 4, 8, 4));
        _textBlock2._set_property_value_by_name("FontSize", 12);
        return _textBlock2;
    }, "ItemVM");
    _rd0.Set("DragDropItemTemplate", _tmpl1);
    const _tmpl3 = new ItemsPanelTemplate(() => {
        const _stackPanel4 = new StackPanel();
        return _stackPanel4;
    });
    _rd0.Set("DragDropItemsPanel", _tmpl3);
    const _setter5 = new Setter(ContentPresenter, "IsDraggable", true);
    const _setter6 = new Setter(ContentPresenter, "OnDragStart", new SetterFactory((_t) => DataContextBinding(_t, "BeginDragData")));
    const _style7 = new Style(ContentPresenter, [_setter5, _setter6], undefined, [], []);
    _rd0.Set("DragDropItemContainerStyle", _style7);
    const _tmpl8 = new DataTemplate((_data) => {
        const _border9 = new Border();
        _border9.SetNameScope(new NameScope());
        _border9._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border9._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border9._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel10 = new DockPanel();
        const _border11 = new Border();
        _border11._set_property_value_by_name(DockPanel, "Dock", "Top");
        _border11._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border11._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _stackPanel12 = new StackPanel();
        _stackPanel12._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _textBlock13 = new TextBlock();
        _textBlock13._set_property_value_by_name("Text", "Drag-drop between lists");
        _textBlock13._set_property_value_by_name("FontSize", 15);
        _textBlock13._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock13._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _stackPanel12.AddChild(_textBlock13);
        const _textBlock14 = new TextBlock();
        _textBlock14._set_property_value_by_name("Text", DataContextBinding(_textBlock14, "Status"));
        _textBlock14._set_property_value_by_name("FontSize", 12);
        _textBlock14._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _textBlock14._set_property_value_by_name("Margin", new Thickness(20, 4, 0, 0));
        _stackPanel12.AddChild(_textBlock14);
        _border11.SetChild(_stackPanel12);
        _dockPanel10.AddChild(_border11);
        const _stackPanel15 = new StackPanel();
        _stackPanel15._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel15._set_property_value_by_name("Margin", new Thickness(20));
        const _border16 = new Border();
        _border16._set_property_value_by_name("Width", 220);
        _border16._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
        _border16._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border16._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _stackPanel17 = new StackPanel();
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", "Left");
        _textBlock18._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock18._set_property_value_by_name("FontSize", 12);
        _textBlock18._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#374151')));
        _textBlock18._set_property_value_by_name("Margin", new Thickness(10, 8, 8, 4));
        _stackPanel17.AddChild(_textBlock18);
        const _itemsControl19 = new ItemsControl();
        _itemsControl19.Name = "leftList";
        _border9.nameScope.Register("leftList", _itemsControl19);
        _itemsControl19._set_property_value_by_name("ItemsSource", DataContextBinding(_itemsControl19, "LeftItems"));
        _itemsControl19._set_property_value_by_name("ItemsPanel", Application.current.Resources.Resolve("DragDropItemsPanel"));
        _itemsControl19._set_property_value_by_name("ItemTemplate", Application.current.Resources.Resolve("DragDropItemTemplate"));
        _itemsControl19._set_property_value_by_name("ItemContainerStyle", Application.current.Resources.Resolve("DragDropItemContainerStyle"));
        _stackPanel17.AddChild(_itemsControl19);
        _border16.SetChild(_stackPanel17);
        _stackPanel15.AddChild(_border16);
        const _border20 = new Border();
        _border20._set_property_value_by_name("Width", 220);
        _border20._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border20._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _stackPanel21 = new StackPanel();
        const _textBlock22 = new TextBlock();
        _textBlock22._set_property_value_by_name("Text", "Right");
        _textBlock22._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock22._set_property_value_by_name("FontSize", 12);
        _textBlock22._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#374151')));
        _textBlock22._set_property_value_by_name("Margin", new Thickness(10, 8, 8, 4));
        _stackPanel21.AddChild(_textBlock22);
        const _itemsControl23 = new ItemsControl();
        _itemsControl23.Name = "rightList";
        _border9.nameScope.Register("rightList", _itemsControl23);
        _itemsControl23._set_property_value_by_name("ItemsSource", DataContextBinding(_itemsControl23, "RightItems"));
        _itemsControl23._set_property_value_by_name("ItemsPanel", Application.current.Resources.Resolve("DragDropItemsPanel"));
        _itemsControl23._set_property_value_by_name("ItemTemplate", Application.current.Resources.Resolve("DragDropItemTemplate"));
        _itemsControl23._set_property_value_by_name("ItemContainerStyle", Application.current.Resources.Resolve("DragDropItemContainerStyle"));
        _stackPanel21.AddChild(_itemsControl23);
        _border20.SetChild(_stackPanel21);
        _stackPanel15.AddChild(_border20);
        _dockPanel10.AddChild(_stackPanel15);
        const _textBlock24 = new TextBlock();
        _textBlock24._set_property_value_by_name("Margin", new Thickness(20, 4, 20, 16));
        _textBlock24._set_property_value_by_name("FontSize", 11);
        _textBlock24._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock24._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
        _textBlock24._set_property_value_by_name("Text", "Drag any item from one list to the other to move it. The framework's IsDraggable + OnDragStart binding starts the drag; a Behavior on each ListBox handles DragOver/Drop and dispatches to VM commands.");
        _dockPanel10.AddChild(_textBlock24);
        _border9.SetChild(_dockPanel10);
        return _border9;
    }, "DragDropVM");
    _rd0.Set("DragDropTemplate", _tmpl8);
    return _rd0;
}
