import { Border, DataTemplate, DockPanel, ListBox, ListBoxItem, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Application, Color, DataContextBinding, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _textBlock2 = new TextBlock();
        _textBlock2._set_property_value_by_name("Text", DataContextBinding(_textBlock2, "Label"));
        _textBlock2._set_property_value_by_name("Padding", new Thickness(8, 4, 8, 4));
        _textBlock2._set_property_value_by_name("FontSize", 12);
        return _textBlock2;
    }, "ItemVM");
    _rd0.Set("DragDropItemTemplate", _tmpl1);
    const _setter3 = new Setter(ListBoxItem, "IsDraggable", true);
    const _setter4 = new Setter(ListBoxItem, "OnDragStart", new SetterFactory((_t) => DataContextBinding(_t, "BeginDragData")));
    const _style5 = new Style(ListBoxItem, [_setter3, _setter4], undefined, [], []);
    _rd0.Set("DragDropItemContainerStyle", _style5);
    const _tmpl6 = new DataTemplate((_data) => {
        const _border7 = new Border();
        _border7.SetNameScope(new NameScope());
        _border7._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border7._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border7._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel8 = new DockPanel();
        const _border9 = new Border();
        _border9._set_property_value_by_name(DockPanel, "Dock", "Top");
        _border9._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border9._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _stackPanel10 = new StackPanel();
        _stackPanel10._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _textBlock11 = new TextBlock();
        _textBlock11._set_property_value_by_name("Text", "Drag-drop between lists");
        _textBlock11._set_property_value_by_name("FontSize", 15);
        _textBlock11._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock11._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _stackPanel10.AddChild(_textBlock11);
        const _textBlock12 = new TextBlock();
        _textBlock12._set_property_value_by_name("Text", DataContextBinding(_textBlock12, "Status"));
        _textBlock12._set_property_value_by_name("FontSize", 12);
        _textBlock12._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _textBlock12._set_property_value_by_name("Margin", new Thickness(20, 4, 0, 0));
        _stackPanel10.AddChild(_textBlock12);
        _border9.SetChild(_stackPanel10);
        _dockPanel8.AddChild(_border9);
        const _stackPanel13 = new StackPanel();
        _stackPanel13._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel13._set_property_value_by_name("Margin", new Thickness(20));
        const _border14 = new Border();
        _border14._set_property_value_by_name("Width", 220);
        _border14._set_property_value_by_name("Margin", new Thickness(0, 0, 16, 0));
        _border14._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border14._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _stackPanel15 = new StackPanel();
        const _textBlock16 = new TextBlock();
        _textBlock16._set_property_value_by_name("Text", "Left");
        _textBlock16._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock16._set_property_value_by_name("FontSize", 12);
        _textBlock16._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#374151')));
        _textBlock16._set_property_value_by_name("Margin", new Thickness(10, 8, 8, 4));
        _stackPanel15.AddChild(_textBlock16);
        const _listBox17 = new ListBox();
        _listBox17.Name = "leftList";
        _border7.nameScope.Register("leftList", _listBox17);
        _listBox17._set_property_value_by_name("ItemsSource", DataContextBinding(_listBox17, "LeftItems"));
        _listBox17._set_property_value_by_name("ItemTemplate", Application.current.Resources.Resolve("DragDropItemTemplate"));
        _listBox17._set_property_value_by_name("ItemContainerStyle", Application.current.Resources.Resolve("DragDropItemContainerStyle"));
        _stackPanel15.AddChild(_listBox17);
        _border14.SetChild(_stackPanel15);
        _stackPanel13.AddChild(_border14);
        const _border18 = new Border();
        _border18._set_property_value_by_name("Width", 220);
        _border18._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border18._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _stackPanel19 = new StackPanel();
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "Right");
        _textBlock20._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock20._set_property_value_by_name("FontSize", 12);
        _textBlock20._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#374151')));
        _textBlock20._set_property_value_by_name("Margin", new Thickness(10, 8, 8, 4));
        _stackPanel19.AddChild(_textBlock20);
        const _listBox21 = new ListBox();
        _listBox21.Name = "rightList";
        _border7.nameScope.Register("rightList", _listBox21);
        _listBox21._set_property_value_by_name("ItemsSource", DataContextBinding(_listBox21, "RightItems"));
        _listBox21._set_property_value_by_name("ItemTemplate", Application.current.Resources.Resolve("DragDropItemTemplate"));
        _listBox21._set_property_value_by_name("ItemContainerStyle", Application.current.Resources.Resolve("DragDropItemContainerStyle"));
        _stackPanel19.AddChild(_listBox21);
        _border18.SetChild(_stackPanel19);
        _stackPanel13.AddChild(_border18);
        _dockPanel8.AddChild(_stackPanel13);
        const _textBlock22 = new TextBlock();
        _textBlock22._set_property_value_by_name("Margin", new Thickness(20, 4, 20, 16));
        _textBlock22._set_property_value_by_name("FontSize", 11);
        _textBlock22._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock22._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
        _textBlock22._set_property_value_by_name("Text", "Drag any item from one list to the other to move it. The framework's IsDraggable + OnDragStart binding starts the drag; a Behavior on each ListBox handles DragOver/Drop and dispatches to VM commands.");
        _dockPanel8.AddChild(_textBlock22);
        _border7.SetChild(_dockPanel8);
        return _border7;
    }, "DragDropVM");
    _rd0.Set("DragDropTemplate", _tmpl6);
    return _rd0;
}
