#!/usr/bin/env node
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, extname, join, relative, resolve } from 'node:path';
import {
    ArcSegment,
    CubicBezierSegment,
    EllipseGeometry,
    LineGeometry,
    LineSegment,
    PathFigure,
    PathGeometry,
    QuadraticBezierSegment,
    RectangleGeometry,
    SweepDirection,
    type Geometry,
    type PathSegment,
} from '../visual-engine/index.js';
import { CURRENT_COLOR, type IconPaint } from '../basic/icon.js';
import { parseSvgIcon } from '../basic/svg-icon-parser.js';

// build-icons — reads every *.svg in <inputDir>, parses with the icon-
// subset parser, and emits a single .mjs module that constructs each icon
// at module-load time and exports a ResourceDictionary keyed by basename.
//
// Usage:
//   npx tsx src/tooling/build-icons.ts <inputDir> <outputFile>
//
// Example:
//   npx tsx src/tooling/build-icons.ts demo/assets/icons demo/assets/icons.mjs
//
// The emitted module:
//   import { ResourceDictionary } from '@visualisation-sub/mural/runtime';
//   import { IconDefinition, CURRENT_COLOR } from '@visualisation-sub/mural/basic';
//   import { Color, Point, … } from '@visualisation-sub/mural/visual-engine';
//   const d = new ResourceDictionary();
//   d.Set('home', new IconDefinition(24, 24, [ /* shapes */ ]));
//   …
//   export default d;
//
// Consumers:
//   import IconsDict from './assets/icons.mjs';
//   Application.current.Resources.AddMergedDictionary(IconsDict);
//   then in markup: `Icon[Source=@home, Foreground=@OnSurface, Width=24, Height=24]`

function main(): void
{
    const args = process.argv.slice(2);
    if (args.length < 2)
    {
        console.error('usage: build-icons <inputDir> <outputFile>');
        process.exit(1);
    }
    const inputDir  = resolve(args[0]!);
    const outputFile = resolve(args[1]!);

    const files = readdirSync(inputDir)
        .filter(f => extname(f).toLowerCase() === '.svg')
        .sort();

    const entries: Array<{ key: string; code: string }> = [];
    for (const file of files)
    {
        const key  = basename(file, extname(file));
        const text = readFileSync(join(inputDir, file), 'utf8');
        try
        {
            const def = parseSvgIcon(text);
            entries.push({ key, code: emitIconDefinition(def) });
        }
        catch (err)
        {
            console.warn(`build-icons: skipping ${file}: ${(err as Error).message}`);
        }
    }

    const banner = `// Generated by build-icons from ${relative(process.cwd(), inputDir)}.\n// Do not edit by hand — re-run \`npm run build:icons\` (or the underlying script).\n`;

    const setStatements = entries
        .map(e => `dict.Set(${JSON.stringify(e.key)}, ${e.code});`)
        .join('\n');

    const source = `${banner}
import { ResourceDictionary } from '@visualisation-sub/mural/runtime';
import { CURRENT_COLOR, IconDefinition } from '@visualisation-sub/mural/basic';
import {
    ArcSegment,
    Color,
    CubicBezierSegment,
    EllipseGeometry,
    LineGeometry,
    LineSegment,
    PathFigure,
    PathGeometry,
    Point,
    QuadraticBezierSegment,
    Rect,
    RectangleGeometry,
    Size,
    SweepDirection,
} from '@visualisation-sub/mural/visual-engine';

const dict = new ResourceDictionary();
${setStatements}
export default dict;
`;

    writeFileSync(outputFile, source, 'utf8');
    console.log(`build-icons: emitted ${entries.length} icon(s) → ${relative(process.cwd(), outputFile)}`);
}

// ── Code emitters ───────────────────────────────────────────────────

function emitIconDefinition(def: { ViewBoxWidth: number; ViewBoxHeight: number; Shapes: readonly { Geometry: Geometry; Fill: IconPaint; Stroke: IconPaint; StrokeWidth: number }[] }): string
{
    const shapes = def.Shapes.map(s =>
        `{ Geometry: ${emitGeometry(s.Geometry)}, Fill: ${emitPaint(s.Fill)}, Stroke: ${emitPaint(s.Stroke)}, StrokeWidth: ${n(s.StrokeWidth)} }`,
    ).join(', ');
    return `new IconDefinition(${n(def.ViewBoxWidth)}, ${n(def.ViewBoxHeight)}, [${shapes}])`;
}

function emitGeometry(g: Geometry): string
{
    if (g instanceof PathGeometry)
    {
        const figures = g.Figures.map(emitFigure).join(', ');
        return `new PathGeometry([${figures}])`;
    }
    if (g instanceof RectangleGeometry)
    {
        return `new RectangleGeometry(new Rect(${n(g.Rect.X)}, ${n(g.Rect.Y)}, ${n(g.Rect.Width)}, ${n(g.Rect.Height)}), ${n(g.RadiusX)}, ${n(g.RadiusY)})`;
    }
    if (g instanceof EllipseGeometry)
    {
        return `new EllipseGeometry(new Point(${n(g.Center.X)}, ${n(g.Center.Y)}), ${n(g.RadiusX)}, ${n(g.RadiusY)})`;
    }
    if (g instanceof LineGeometry)
    {
        return `new LineGeometry(new Point(${n(g.StartPoint.X)}, ${n(g.StartPoint.Y)}), new Point(${n(g.EndPoint.X)}, ${n(g.EndPoint.Y)}))`;
    }
    throw new Error(`build-icons: unsupported geometry type ${g.constructor.name}`);
}

function emitFigure(f: PathFigure): string
{
    const segs = f.Segments.map(emitSegment).join(', ');
    return `new PathFigure(new Point(${n(f.StartPoint.X)}, ${n(f.StartPoint.Y)}), [${segs}], ${f.IsClosed})`;
}

function emitSegment(s: PathSegment): string
{
    if (s instanceof LineSegment)
    {
        return `new LineSegment(new Point(${n(s.Point.X)}, ${n(s.Point.Y)}))`;
    }
    if (s instanceof CubicBezierSegment)
    {
        return `new CubicBezierSegment(new Point(${n(s.Point1.X)}, ${n(s.Point1.Y)}), new Point(${n(s.Point2.X)}, ${n(s.Point2.Y)}), new Point(${n(s.Point3.X)}, ${n(s.Point3.Y)}))`;
    }
    if (s instanceof QuadraticBezierSegment)
    {
        return `new QuadraticBezierSegment(new Point(${n(s.Point1.X)}, ${n(s.Point1.Y)}), new Point(${n(s.Point2.X)}, ${n(s.Point2.Y)}))`;
    }
    if (s instanceof ArcSegment)
    {
        const dir = s.SweepDirection === SweepDirection.Clockwise
            ? 'SweepDirection.Clockwise'
            : 'SweepDirection.Counterclockwise';
        return `new ArcSegment(new Point(${n(s.Point.X)}, ${n(s.Point.Y)}), new Size(${n(s.Size.Width)}, ${n(s.Size.Height)}), ${n(s.RotationAngle)}, ${s.IsLargeArc}, ${dir})`;
    }
    throw new Error(`build-icons: unsupported segment type ${s.constructor.name}`);
}

function emitPaint(p: IconPaint): string
{
    if (p === undefined)      return 'undefined';
    if (p === CURRENT_COLOR)  return 'CURRENT_COLOR';
    return `new Color(${p.R}, ${p.G}, ${p.B}, ${p.A})`;
}

// Format numbers compactly: integers stay integers; floats keep 4
// decimals (avoids JSON-stringify's "1.0000000000000002" artefacts).
function n(x: number): string
{
    if (Number.isInteger(x)) return String(x);
    return Number(x.toFixed(4)).toString();
}

main();
