import { ColorPickerVM } from "./color-picker-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/basic";
import { ColorPicker, ColorPickerVariant } from "@visualisation-sub/mural/framework";
import { DataContextBinding, DynamicResource, NameScope, ResourceDictionary, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_ColorPickerDemo = Symbol("ColorPickerDemo.ctor");
export class ColorPickerDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_ColorPickerDemo) {
            throw new Error("ColorPickerDemo is private — use ColorPickerDemo.Clone()");
        }
    }
    static Clone() {
        const t = new ColorPickerDemo(_gate_ColorPickerDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.SetNameScope(new NameScope());
            _border1.set_property_value(Border.BackgroundKey, DynamicResource(_border1, "Surface"));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.BackgroundKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(20, 14, 20, 14));
            const _stackPanel4 = new StackPanel();
            _stackPanel4.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock5 = new TextBlock();
            _textBlock5.set_property_value(TextBlock.TextKey, "ComboBox-style color picker");
            _textBlock5.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock5.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock5.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock5, "OnPrimary"));
            _stackPanel4.AddChild(_textBlock5);
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "Material 3 palette + HSV sliders + hex round-trip.");
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock6.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock6, "OnPrimary"));
            _textBlock6.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _stackPanel4.AddChild(_textBlock6);
            _border3.SetChild(_stackPanel4);
            _dockPanel2.AddChild(_border3);
            const _textBlock7 = new TextBlock();
            _textBlock7.set_property_value(DockPanel.DockKey, Dock.Bottom);
            _textBlock7.set_property_value(TextBlock.MarginKey, new Thickness(20, 8, 20, 16));
            _textBlock7.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock7.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock7, "OnSurfaceVariant"));
            _textBlock7.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock7.set_property_value(TextBlock.TextKey, "Three HSV pickers above, one RGB+alpha picker below. The RGB popup carries red / green / blue / alpha sliders (0..255). Hex grows to eight digits when alpha < 255. Each picker feeds a preview swatch via SolidColorBrush(Color.FromHex(...)).");
            _dockPanel2.AddChild(_textBlock7);
            const _border8 = new Border();
            _border8.set_property_value(Border.BackgroundKey, DynamicResource(_border8, "SurfaceContainerLow"));
            _border8.set_property_value(Border.PaddingKey, new Thickness(20, 20, 20, 20));
            const _stackPanel9 = new StackPanel();
            _stackPanel9.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _stackPanel10 = new StackPanel();
            _stackPanel10.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel10.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 16));
            const _stackPanel11 = new StackPanel();
            _stackPanel11.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel11.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock12 = new TextBlock();
            _textBlock12.set_property_value(TextBlock.TextKey, "Surface");
            _textBlock12.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock12.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock12.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock12, "OnSurface"));
            _textBlock12.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel11.AddChild(_textBlock12);
            const _colorPicker13 = new ColorPicker();
            _colorPicker13.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker13, "SurfaceHex"));
            _stackPanel11.AddChild(_colorPicker13);
            _stackPanel10.AddChild(_stackPanel11);
            const _border14 = new Border();
            _border14.Name = "SurfacePreview";
            _border14.set_property_value(Border.WidthKey, 80);
            _border14.set_property_value(Border.HeightKey, 40);
            _border14.set_property_value(Border.CornerRadiusKey, 4);
            _border14.set_property_value(Border.VerticalAlignmentKey, VerticalAlignment.Bottom);
            _border14.set_property_value(Border.BorderBrushKey, DynamicResource(_border14, "OutlineVariant"));
            _border14.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _stackPanel10.AddChild(_border14);
            _stackPanel9.AddChild(_stackPanel10);
            const _stackPanel15 = new StackPanel();
            _stackPanel15.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel15.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 16));
            const _stackPanel16 = new StackPanel();
            _stackPanel16.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel16.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "Accent");
            _textBlock17.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock17.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock17.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock17, "OnSurface"));
            _textBlock17.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel16.AddChild(_textBlock17);
            const _colorPicker18 = new ColorPicker();
            _colorPicker18.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker18, "AccentHex"));
            _stackPanel16.AddChild(_colorPicker18);
            _stackPanel15.AddChild(_stackPanel16);
            const _border19 = new Border();
            _border19.Name = "AccentPreview";
            _border19.set_property_value(Border.WidthKey, 80);
            _border19.set_property_value(Border.HeightKey, 40);
            _border19.set_property_value(Border.CornerRadiusKey, 4);
            _border19.set_property_value(Border.VerticalAlignmentKey, VerticalAlignment.Bottom);
            _border19.set_property_value(Border.BorderBrushKey, DynamicResource(_border19, "OutlineVariant"));
            _border19.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _stackPanel15.AddChild(_border19);
            _stackPanel9.AddChild(_stackPanel15);
            const _stackPanel20 = new StackPanel();
            _stackPanel20.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel20.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 16));
            const _stackPanel21 = new StackPanel();
            _stackPanel21.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel21.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock22 = new TextBlock();
            _textBlock22.set_property_value(TextBlock.TextKey, "Ink");
            _textBlock22.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock22.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock22.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock22, "OnSurface"));
            _textBlock22.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel21.AddChild(_textBlock22);
            const _colorPicker23 = new ColorPicker();
            _colorPicker23.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker23, "InkHex"));
            _stackPanel21.AddChild(_colorPicker23);
            _stackPanel20.AddChild(_stackPanel21);
            const _border24 = new Border();
            _border24.Name = "InkPreview";
            _border24.set_property_value(Border.WidthKey, 80);
            _border24.set_property_value(Border.HeightKey, 40);
            _border24.set_property_value(Border.CornerRadiusKey, 4);
            _border24.set_property_value(Border.VerticalAlignmentKey, VerticalAlignment.Bottom);
            _border24.set_property_value(Border.BorderBrushKey, DynamicResource(_border24, "OutlineVariant"));
            _border24.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _stackPanel20.AddChild(_border24);
            _stackPanel9.AddChild(_stackPanel20);
            const _stackPanel25 = new StackPanel();
            _stackPanel25.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _stackPanel26 = new StackPanel();
            _stackPanel26.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel26.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, "Overlay (RGB + alpha)");
            _textBlock27.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock27.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock27.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock27, "OnSurface"));
            _textBlock27.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel26.AddChild(_textBlock27);
            const _colorPicker28 = new ColorPicker();
            _colorPicker28.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker28, "OverlayHex"));
            _colorPicker28.set_property_value(ColorPicker.VariantKey, ColorPickerVariant.RGB);
            _stackPanel26.AddChild(_colorPicker28);
            _stackPanel25.AddChild(_stackPanel26);
            const _border29 = new Border();
            _border29.Name = "OverlayPreview";
            _border29.set_property_value(Border.WidthKey, 80);
            _border29.set_property_value(Border.HeightKey, 40);
            _border29.set_property_value(Border.CornerRadiusKey, 4);
            _border29.set_property_value(Border.VerticalAlignmentKey, VerticalAlignment.Bottom);
            _border29.set_property_value(Border.BorderBrushKey, DynamicResource(_border29, "OutlineVariant"));
            _border29.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _stackPanel25.AddChild(_border29);
            _stackPanel9.AddChild(_stackPanel25);
            _border8.SetChild(_stackPanel9);
            _dockPanel2.AddChild(_border8);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, ColorPickerVM);
        t.Set("ColorPickerTemplate", _tmpl0);
        return t;
    }
    get ColorPickerTemplate() { return this.Resolve("ColorPickerTemplate"); }
    set ColorPickerTemplate(v) { this.Set("ColorPickerTemplate", v); }
}
