import { ColorPickerVM } from "./color-picker-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/basic";
import { ColorPicker, ColorScheme } from "@visualisation-sub/mural/framework";
import { Color, DataContextBinding, DynamicResource, NameScope, ResourceDictionary, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_ColorPickerDemo = Symbol("ColorPickerDemo.ctor");
export class ColorPickerDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_ColorPickerDemo) {
            throw new Error("ColorPickerDemo is private — use ColorPickerDemo.Clone()");
        }
    }
    static Clone() {
        const t = new ColorPickerDemo(_gate_ColorPickerDemo);
        const _colorScheme0 = new ColorScheme();
        _colorScheme0.Name = "Brand";
        _colorScheme0.Colors = [new SolidColorBrush(Color.FromHex('#0F172A')), new SolidColorBrush(Color.FromHex('#2563EB')), new SolidColorBrush(Color.FromHex('#7C3AED')), new SolidColorBrush(Color.FromHex('#DB2777')), new SolidColorBrush(Color.FromHex('#059669')), new SolidColorBrush(Color.FromHex('#EA580C'))];
        t.Set("BrandColors", _colorScheme0);
        const _tmpl1 = new DataTemplate((_data) => {
            let _border2, _border3, _border4, _border5;
            const _border6 = new Border();
            _border6.SetNameScope(new NameScope());
            _border6.set_property_value(Border.BackgroundKey, DynamicResource(_border6, "Surface"));
            const _dockPanel7 = new DockPanel();
            const _border8 = new Border();
            _border8.set_property_value(DockPanel.DockKey, Dock.Top);
            _border8.set_property_value(Border.BackgroundKey, DynamicResource(_border8, "Primary"));
            _border8.set_property_value(Border.PaddingKey, new Thickness(20, 14, 20, 14));
            const _stackPanel9 = new StackPanel();
            _stackPanel9.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock10 = new TextBlock();
            _textBlock10.set_property_value(TextBlock.TextKey, "Office-style color picker");
            _textBlock10.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock10.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock10.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock10, "OnPrimary"));
            _stackPanel9.AddChild(_textBlock10);
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "Theme colors + tints, standard colors, recents, and a More Colors… dialog.");
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock11.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock11, "OnPrimary"));
            _textBlock11.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _stackPanel9.AddChild(_textBlock11);
            _border8.SetChild(_stackPanel9);
            _dockPanel7.AddChild(_border8);
            const _textBlock12 = new TextBlock();
            _textBlock12.set_property_value(DockPanel.DockKey, Dock.Bottom);
            _textBlock12.set_property_value(TextBlock.MarginKey, new Thickness(20, 8, 20, 16));
            _textBlock12.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock12.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock12, "OnSurfaceVariant"));
            _textBlock12.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock12.set_property_value(TextBlock.TextKey, "Each picker drops down the Office menu: a No-Color entry, a Colors: button opening the 21-scheme gallery (Office, Blue Warm, Median, Paper, …), a Theme-Colors grid (base row + lighter/darker tint-shade rows built from the active ColorScheme), a fixed Standard-Colors row, a session Recent-Colors row, and More Colors… which opens the 2D hue/saturation box + brightness rail + R/G/B/A sliders + hex (with OK / Cancel). Each picker feeds a preview swatch via SolidColorBrush(Color.FromHex(...)).");
            _dockPanel7.AddChild(_textBlock12);
            const _border13 = new Border();
            _border13.set_property_value(Border.BackgroundKey, DynamicResource(_border13, "SurfaceContainerLow"));
            _border13.set_property_value(Border.PaddingKey, new Thickness(20, 20, 20, 20));
            const _stackPanel14 = new StackPanel();
            _stackPanel14.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _stackPanel15 = new StackPanel();
            _stackPanel15.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel15.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 16));
            const _stackPanel16 = new StackPanel();
            _stackPanel16.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel16.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "Surface");
            _textBlock17.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock17.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock17.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock17, "OnSurface"));
            _textBlock17.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel16.AddChild(_textBlock17);
            const _colorPicker18 = new ColorPicker();
            _colorPicker18.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker18, "SurfaceHex"));
            _stackPanel16.AddChild(_colorPicker18);
            _stackPanel15.AddChild(_stackPanel16);
            _border2 = new Border();
            _border2.Name = "SurfacePreview";
            _border2.set_property_value(Border.WidthKey, 80);
            _border2.set_property_value(Border.HeightKey, 40);
            _border2.set_property_value(Border.CornerRadiusKey, 4);
            _border2.set_property_value(Border.VerticalAlignmentKey, VerticalAlignment.Bottom);
            _border2.set_property_value(Border.BorderBrushKey, DynamicResource(_border2, "OutlineVariant"));
            _border2.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _stackPanel15.AddChild(_border2);
            _stackPanel14.AddChild(_stackPanel15);
            const _stackPanel19 = new StackPanel();
            _stackPanel19.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel19.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 16));
            const _stackPanel20 = new StackPanel();
            _stackPanel20.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel20.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "Accent");
            _textBlock21.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock21.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock21.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock21, "OnSurface"));
            _textBlock21.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel20.AddChild(_textBlock21);
            const _colorPicker22 = new ColorPicker();
            _colorPicker22.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker22, "AccentHex"));
            _stackPanel20.AddChild(_colorPicker22);
            _stackPanel19.AddChild(_stackPanel20);
            _border3 = new Border();
            _border3.Name = "AccentPreview";
            _border3.set_property_value(Border.WidthKey, 80);
            _border3.set_property_value(Border.HeightKey, 40);
            _border3.set_property_value(Border.CornerRadiusKey, 4);
            _border3.set_property_value(Border.VerticalAlignmentKey, VerticalAlignment.Bottom);
            _border3.set_property_value(Border.BorderBrushKey, DynamicResource(_border3, "OutlineVariant"));
            _border3.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _stackPanel19.AddChild(_border3);
            _stackPanel14.AddChild(_stackPanel19);
            const _stackPanel23 = new StackPanel();
            _stackPanel23.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel23.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 16));
            const _stackPanel24 = new StackPanel();
            _stackPanel24.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel24.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock25 = new TextBlock();
            _textBlock25.set_property_value(TextBlock.TextKey, "Ink");
            _textBlock25.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock25.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock25.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock25, "OnSurface"));
            _textBlock25.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel24.AddChild(_textBlock25);
            const _colorPicker26 = new ColorPicker();
            _colorPicker26.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker26, "InkHex"));
            _stackPanel24.AddChild(_colorPicker26);
            _stackPanel23.AddChild(_stackPanel24);
            _border4 = new Border();
            _border4.Name = "InkPreview";
            _border4.set_property_value(Border.WidthKey, 80);
            _border4.set_property_value(Border.HeightKey, 40);
            _border4.set_property_value(Border.CornerRadiusKey, 4);
            _border4.set_property_value(Border.VerticalAlignmentKey, VerticalAlignment.Bottom);
            _border4.set_property_value(Border.BorderBrushKey, DynamicResource(_border4, "OutlineVariant"));
            _border4.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _stackPanel23.AddChild(_border4);
            _stackPanel14.AddChild(_stackPanel23);
            const _stackPanel27 = new StackPanel();
            _stackPanel27.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _stackPanel28 = new StackPanel();
            _stackPanel28.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel28.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, "Overlay (custom ColorScheme=@BrandColors)");
            _textBlock29.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock29.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock29.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock29, "OnSurface"));
            _textBlock29.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel28.AddChild(_textBlock29);
            const _colorPicker30 = new ColorPicker();
            _colorPicker30.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker30, "OverlayHex"));
            _colorPicker30.set_property_value(ColorPicker.ColorSchemeKey, DynamicResource(_colorPicker30, "BrandColors"));
            _stackPanel28.AddChild(_colorPicker30);
            _stackPanel27.AddChild(_stackPanel28);
            _border5 = new Border();
            _border5.Name = "OverlayPreview";
            _border5.set_property_value(Border.WidthKey, 80);
            _border5.set_property_value(Border.HeightKey, 40);
            _border5.set_property_value(Border.CornerRadiusKey, 4);
            _border5.set_property_value(Border.VerticalAlignmentKey, VerticalAlignment.Bottom);
            _border5.set_property_value(Border.BorderBrushKey, DynamicResource(_border5, "OutlineVariant"));
            _border5.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _stackPanel27.AddChild(_border5);
            _stackPanel14.AddChild(_stackPanel27);
            _border13.SetChild(_stackPanel14);
            _dockPanel7.AddChild(_border13);
            _border6.SetChild(_dockPanel7);
            return _border6;
        }, ColorPickerVM);
        t.Set("ColorPickerTemplate", _tmpl1);
        return t;
    }
    get BrandColors() { return this.Resolve("BrandColors"); }
    set BrandColors(v) { this.Set("BrandColors", v); }
    get ColorPickerTemplate() { return this.Resolve("ColorPickerTemplate"); }
    set ColorPickerTemplate(v) { this.Set("ColorPickerTemplate", v); }
}
