import { CommandsVM, EllipseNodeVM, NoteNodeVM, RectNodeVM } from "./commands-vm.mjs";
import { Border, Canvas, DataTemplate, Dock, DockPanel, Ellipse, ItemsPanelTemplate, Orientation, StackPanel, TargetedSetter, TemplateDataTrigger, TextBlock } from "@visualisation-sub/mural/Basic";
import { DiagramNode } from "@visualisation-sub/mural/framework/diagram/diagram-node.js";
import { Diagram } from "@visualisation-sub/mural/framework/diagram/diagram.js";
import { SelectionMode } from "@visualisation-sub/mural/framework/list/list-box.js";
import { ContextMenu, ContextMenuService, MenuButton, MenuItem, MenuSeparator, ToolBar, ToolBarButton, ToolBarSeparator } from "@visualisation-sub/mural/framework/surface.js";
import { Color, DataContextBinding, DynamicResource, HorizontalAlignment, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_CommandsDemo = Symbol("CommandsDemo.ctor");
export class CommandsDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_CommandsDemo) {
            throw new Error("CommandsDemo is private — use CommandsDemo.Clone()");
        }
    }
    static Clone() {
        const t = new CommandsDemo(_gate_CommandsDemo);
        const _setter0 = new Setter(DiagramNode, "X", new SetterFactory((_t) => DataContextBinding(_t, "X")));
        const _setter1 = new Setter(DiagramNode, "Y", new SetterFactory((_t) => DataContextBinding(_t, "Y")));
        const _style2 = new Style(DiagramNode, [_setter0, _setter1], undefined, [], []);
        t.Set("CommandsNodeStyle", _style2);
        const _tmpl3 = new ItemsPanelTemplate(() => {
            const _canvas4 = new Canvas();
            return _canvas4;
        });
        t.Set("CommandsCanvasPanel", _tmpl3);
        const _setter5 = new Setter(Border, "BorderBrush", new SetterFactory((_t) => DynamicResource(_t, "Primary")));
        const _style6 = new Style(Border, [_setter5], undefined, [], []);
        t.Set("CommandsRectChromeStyle", _style6);
        const _setter7 = new Setter(Border, "BorderBrush", new SolidColorBrush(Color.FromHex('#a16207')));
        const _style8 = new Style(Border, [_setter7], undefined, [], []);
        t.Set("CommandsNoteChromeStyle", _style8);
        const _setter9 = new Setter(Ellipse, "Stroke", new SolidColorBrush(Color.FromHex('#15803d')));
        const _style10 = new Style(Ellipse, [_setter9], undefined, [], []);
        t.Set("CommandsEllipseChromeStyle", _style10);
        const _contextMenu11 = new ContextMenu();
        const _menuItem12 = new MenuItem();
        _menuItem12._set_property_value_by_name("Header", "Cut");
        _menuItem12._set_property_value_by_name("InputGestureText", "Ctrl+X");
        _menuItem12._set_property_value_by_name("Command", DataContextBinding(_menuItem12, "CutCommand"));
        _contextMenu11.AddChild(_menuItem12);
        const _menuItem13 = new MenuItem();
        _menuItem13._set_property_value_by_name("Header", "Copy");
        _menuItem13._set_property_value_by_name("InputGestureText", "Ctrl+C");
        _menuItem13._set_property_value_by_name("Command", DataContextBinding(_menuItem13, "CopyCommand"));
        _contextMenu11.AddChild(_menuItem13);
        const _menuItem14 = new MenuItem();
        _menuItem14._set_property_value_by_name("Header", "Duplicate");
        _menuItem14._set_property_value_by_name("InputGestureText", "Ctrl+D");
        _menuItem14._set_property_value_by_name("Command", DataContextBinding(_menuItem14, "DuplicateCommand"));
        _contextMenu11.AddChild(_menuItem14);
        const _menuSeparator15 = new MenuSeparator();
        _contextMenu11.AddChild(_menuSeparator15);
        const _menuItem16 = new MenuItem();
        _menuItem16._set_property_value_by_name("Header", "Delete");
        _menuItem16._set_property_value_by_name("InputGestureText", "Del");
        _menuItem16._set_property_value_by_name("Command", DataContextBinding(_menuItem16, "DeleteCommand"));
        _contextMenu11.AddChild(_menuItem16);
        t.Set("NodeContextMenu", _contextMenu11);
        const _tmpl17 = (() => {
            const _factory = (_data) => {
                const _border18 = new Border();
                _border18.Name = "chrome";
                _border18._set_property_value_by_name("Style", _style6);
                _border18._set_property_value_by_name("Width", 130);
                _border18._set_property_value_by_name("Height", 60);
                _border18._set_property_value_by_name("Background", DataContextBinding(_border18, "FillBrush"));
                _border18._set_property_value_by_name("BorderThickness", new Thickness(1.5));
                _border18._set_property_value_by_name("CornerRadius", 4);
                _border18._set_property_value_by_name(ContextMenuService, "ContextMenu", DynamicResource(_border18, "NodeContextMenu"));
                const _textBlock19 = new TextBlock();
                _textBlock19._set_property_value_by_name("Text", DataContextBinding(_textBlock19, "LabelText"));
                _textBlock19._set_property_value_by_name("FontSize", 13);
                _textBlock19._set_property_value_by_name("Foreground", DynamicResource(_textBlock19, "OnSurface"));
                _textBlock19._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock19._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _border18.SetChild(_textBlock19);
                return _border18;
            };
            const _tplSet20 = [new TargetedSetter(Border, "BorderBrush", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig21 = new TemplateDataTrigger("IsSelected", true, _tplSet20);
            return new DataTemplate(_factory, RectNodeVM, [], [_tplDataTrig21]);
        })();
        t.Set(RectNodeVM, _tmpl17);
        const _tmpl22 = (() => {
            const _factory = (_data) => {
                const _canvas23 = new Canvas();
                _canvas23.SetNameScope(new NameScope());
                _canvas23._set_property_value_by_name("Width", 130);
                _canvas23._set_property_value_by_name("Height", 60);
                _canvas23._set_property_value_by_name(ContextMenuService, "ContextMenu", DynamicResource(_canvas23, "NodeContextMenu"));
                const _ellipse24 = new Ellipse();
                _ellipse24.Name = "chrome";
                _ellipse24._set_property_value_by_name("Style", _style10);
                _ellipse24._set_property_value_by_name("Width", 130);
                _ellipse24._set_property_value_by_name("Height", 60);
                _ellipse24._set_property_value_by_name("Fill", DataContextBinding(_ellipse24, "FillBrush"));
                _ellipse24._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas23.AddChild(_ellipse24);
                const _textBlock25 = new TextBlock();
                _textBlock25._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock25._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock25._set_property_value_by_name("Width", 130);
                _textBlock25._set_property_value_by_name("Height", 60);
                _textBlock25._set_property_value_by_name("Text", DataContextBinding(_textBlock25, "LabelText"));
                _textBlock25._set_property_value_by_name("FontSize", 13);
                _textBlock25._set_property_value_by_name("Foreground", DynamicResource(_textBlock25, "OnSurface"));
                _textBlock25._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock25._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas23.AddChild(_textBlock25);
                return _canvas23;
            };
            const _tplSet26 = [new TargetedSetter(Ellipse, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig27 = new TemplateDataTrigger("IsSelected", true, _tplSet26);
            return new DataTemplate(_factory, EllipseNodeVM, [], [_tplDataTrig27]);
        })();
        t.Set(EllipseNodeVM, _tmpl22);
        const _tmpl28 = (() => {
            const _factory = (_data) => {
                const _border29 = new Border();
                _border29.Name = "chrome";
                _border29._set_property_value_by_name("Style", _style8);
                _border29._set_property_value_by_name("Width", 130);
                _border29._set_property_value_by_name("Height", 60);
                _border29._set_property_value_by_name("Background", DataContextBinding(_border29, "FillBrush"));
                _border29._set_property_value_by_name("BorderThickness", new Thickness(1.5));
                _border29._set_property_value_by_name("CornerRadius", 2);
                _border29._set_property_value_by_name(ContextMenuService, "ContextMenu", DynamicResource(_border29, "NodeContextMenu"));
                const _textBlock30 = new TextBlock();
                _textBlock30._set_property_value_by_name("Text", DataContextBinding(_textBlock30, "LabelText"));
                _textBlock30._set_property_value_by_name("FontSize", 13);
                _textBlock30._set_property_value_by_name("Foreground", DynamicResource(_textBlock30, "OnSurface"));
                _textBlock30._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock30._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _border29.SetChild(_textBlock30);
                return _border29;
            };
            const _tplSet31 = [new TargetedSetter(Border, "BorderBrush", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig32 = new TemplateDataTrigger("IsSelected", true, _tplSet31);
            return new DataTemplate(_factory, NoteNodeVM, [], [_tplDataTrig32]);
        })();
        t.Set(NoteNodeVM, _tmpl28);
        const _tmpl33 = new DataTemplate((_data) => {
            const _border34 = new Border();
            _border34._set_property_value_by_name("Background", DynamicResource(_border34, "Surface"));
            _border34._set_property_value_by_name("BorderBrush", DynamicResource(_border34, "OutlineVariant"));
            _border34._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel35 = new DockPanel();
            const _border36 = new Border();
            _border36._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border36._set_property_value_by_name("Background", DynamicResource(_border36, "Primary"));
            _border36._set_property_value_by_name("Padding", new Thickness(16, 10, 16, 10));
            const _textBlock37 = new TextBlock();
            _textBlock37._set_property_value_by_name("Text", "ToolBar + Menu + ContextMenu over a Diagram. Select nodes (click / Ctrl-click / marquee) and use the commands.");
            _textBlock37._set_property_value_by_name("FontSize", 14);
            _textBlock37._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock37._set_property_value_by_name("Foreground", DynamicResource(_textBlock37, "OnPrimary"));
            _border36.SetChild(_textBlock37);
            _dockPanel35.AddChild(_border36);
            const _border38 = new Border();
            _border38._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border38._set_property_value_by_name("Background", DynamicResource(_border38, "SurfaceContainerLow"));
            _border38._set_property_value_by_name("BorderBrush", DynamicResource(_border38, "OutlineVariant"));
            _border38._set_property_value_by_name("BorderThickness", new Thickness(0, 0, 0, 1));
            _border38._set_property_value_by_name("Padding", new Thickness(8, 6, 8, 6));
            const _stackPanel39 = new StackPanel();
            _stackPanel39._set_property_value_by_name("Orientation", Orientation.Horizontal);
            const _menuButton40 = new MenuButton();
            _menuButton40._set_property_value_by_name("Header", "☰  File");
            _menuButton40._set_property_value_by_name("Margin", new Thickness(0, 0, 8, 0));
            const _menuItem41 = new MenuItem();
            _menuItem41._set_property_value_by_name("Header", "Save");
            _menuItem41._set_property_value_by_name("InputGestureText", "Ctrl+S");
            _menuItem41._set_property_value_by_name("Command", DataContextBinding(_menuItem41, "SaveCommand"));
            _menuButton40.AddChild(_menuItem41);
            const _menuItem42 = new MenuItem();
            _menuItem42._set_property_value_by_name("Header", "Load");
            _menuItem42._set_property_value_by_name("InputGestureText", "Ctrl+O");
            _menuItem42._set_property_value_by_name("Command", DataContextBinding(_menuItem42, "LoadCommand"));
            _menuButton40.AddChild(_menuItem42);
            const _menuSeparator43 = new MenuSeparator();
            _menuButton40.AddChild(_menuSeparator43);
            const _menuItem44 = new MenuItem();
            _menuItem44._set_property_value_by_name("Header", "Cut");
            _menuItem44._set_property_value_by_name("InputGestureText", "Ctrl+X");
            _menuItem44._set_property_value_by_name("Command", DataContextBinding(_menuItem44, "CutCommand"));
            _menuButton40.AddChild(_menuItem44);
            const _menuItem45 = new MenuItem();
            _menuItem45._set_property_value_by_name("Header", "Copy");
            _menuItem45._set_property_value_by_name("InputGestureText", "Ctrl+C");
            _menuItem45._set_property_value_by_name("Command", DataContextBinding(_menuItem45, "CopyCommand"));
            _menuButton40.AddChild(_menuItem45);
            const _menuItem46 = new MenuItem();
            _menuItem46._set_property_value_by_name("Header", "Paste");
            _menuItem46._set_property_value_by_name("InputGestureText", "Ctrl+V");
            _menuItem46._set_property_value_by_name("Command", DataContextBinding(_menuItem46, "PasteCommand"));
            _menuButton40.AddChild(_menuItem46);
            const _menuItem47 = new MenuItem();
            _menuItem47._set_property_value_by_name("Header", "Delete");
            _menuItem47._set_property_value_by_name("InputGestureText", "Del");
            _menuItem47._set_property_value_by_name("Command", DataContextBinding(_menuItem47, "DeleteCommand"));
            _menuButton40.AddChild(_menuItem47);
            const _menuSeparator48 = new MenuSeparator();
            _menuButton40.AddChild(_menuSeparator48);
            const _menuItem49 = new MenuItem();
            _menuItem49._set_property_value_by_name("Header", "Duplicate");
            _menuItem49._set_property_value_by_name("InputGestureText", "Ctrl+D");
            _menuItem49._set_property_value_by_name("Command", DataContextBinding(_menuItem49, "DuplicateCommand"));
            _menuButton40.AddChild(_menuItem49);
            const _menuItem50 = new MenuItem();
            _menuItem50._set_property_value_by_name("Header", "Select All");
            _menuItem50._set_property_value_by_name("InputGestureText", "Ctrl+A");
            _menuItem50._set_property_value_by_name("Command", DataContextBinding(_menuItem50, "SelectAllCommand"));
            _menuButton40.AddChild(_menuItem50);
            const _menuSeparator51 = new MenuSeparator();
            _menuButton40.AddChild(_menuSeparator51);
            const _menuItem52 = new MenuItem();
            _menuItem52._set_property_value_by_name("Header", "Undo");
            _menuItem52._set_property_value_by_name("InputGestureText", "Ctrl+Z");
            _menuItem52._set_property_value_by_name("Command", DataContextBinding(_menuItem52, "UndoCommand"));
            _menuButton40.AddChild(_menuItem52);
            const _menuItem53 = new MenuItem();
            _menuItem53._set_property_value_by_name("Header", "Redo");
            _menuItem53._set_property_value_by_name("InputGestureText", "Ctrl+Y");
            _menuItem53._set_property_value_by_name("Command", DataContextBinding(_menuItem53, "RedoCommand"));
            _menuButton40.AddChild(_menuItem53);
            _stackPanel39.AddChild(_menuButton40);
            const _textBlock54 = new TextBlock();
            _textBlock54._set_property_value_by_name("Text", DataContextBinding(_textBlock54, "Status"));
            _textBlock54._set_property_value_by_name("FontSize", 12);
            _textBlock54._set_property_value_by_name("Foreground", DynamicResource(_textBlock54, "OnSurface"));
            _textBlock54._set_property_value_by_name("Margin", new Thickness(12, 8, 0, 0));
            _stackPanel39.AddChild(_textBlock54);
            _border38.SetChild(_stackPanel39);
            _dockPanel35.AddChild(_border38);
            const _border55 = new Border();
            _border55._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border55._set_property_value_by_name("Background", DynamicResource(_border55, "Surface"));
            _border55._set_property_value_by_name("BorderBrush", DynamicResource(_border55, "OutlineVariant"));
            _border55._set_property_value_by_name("BorderThickness", new Thickness(0, 0, 0, 1));
            const _toolBar56 = new ToolBar();
            const _toolBarButton57 = new ToolBarButton();
            _toolBarButton57._set_property_value_by_name("Command", DataContextBinding(_toolBarButton57, "SaveCommand"));
            const _textBlock58 = new TextBlock();
            _textBlock58._set_property_value_by_name("Text", "💾");
            _toolBarButton57.Content = _textBlock58;
            _toolBar56.AddChild(_toolBarButton57);
            const _toolBarSeparator59 = new ToolBarSeparator();
            _toolBar56.AddChild(_toolBarSeparator59);
            const _toolBarButton60 = new ToolBarButton();
            _toolBarButton60._set_property_value_by_name("Command", DataContextBinding(_toolBarButton60, "CutCommand"));
            const _textBlock61 = new TextBlock();
            _textBlock61._set_property_value_by_name("Text", "✂");
            _toolBarButton60.Content = _textBlock61;
            _toolBar56.AddChild(_toolBarButton60);
            const _toolBarButton62 = new ToolBarButton();
            _toolBarButton62._set_property_value_by_name("Command", DataContextBinding(_toolBarButton62, "CopyCommand"));
            const _textBlock63 = new TextBlock();
            _textBlock63._set_property_value_by_name("Text", "📋");
            _toolBarButton62.Content = _textBlock63;
            _toolBar56.AddChild(_toolBarButton62);
            const _toolBarButton64 = new ToolBarButton();
            _toolBarButton64._set_property_value_by_name("Command", DataContextBinding(_toolBarButton64, "PasteCommand"));
            const _textBlock65 = new TextBlock();
            _textBlock65._set_property_value_by_name("Text", "📄");
            _toolBarButton64.Content = _textBlock65;
            _toolBar56.AddChild(_toolBarButton64);
            const _toolBarButton66 = new ToolBarButton();
            _toolBarButton66._set_property_value_by_name("Command", DataContextBinding(_toolBarButton66, "DeleteCommand"));
            const _textBlock67 = new TextBlock();
            _textBlock67._set_property_value_by_name("Text", "🗑");
            _toolBarButton66.Content = _textBlock67;
            _toolBar56.AddChild(_toolBarButton66);
            const _toolBarButton68 = new ToolBarButton();
            _toolBarButton68._set_property_value_by_name("Command", DataContextBinding(_toolBarButton68, "DuplicateCommand"));
            const _textBlock69 = new TextBlock();
            _textBlock69._set_property_value_by_name("Text", "⎘");
            _toolBarButton68.Content = _textBlock69;
            _toolBar56.AddChild(_toolBarButton68);
            const _toolBarSeparator70 = new ToolBarSeparator();
            _toolBar56.AddChild(_toolBarSeparator70);
            const _toolBarButton71 = new ToolBarButton();
            _toolBarButton71._set_property_value_by_name("Command", DataContextBinding(_toolBarButton71, "AlignLeftCommand"));
            const _textBlock72 = new TextBlock();
            _textBlock72._set_property_value_by_name("Text", "⬅");
            _toolBarButton71.Content = _textBlock72;
            _toolBar56.AddChild(_toolBarButton71);
            const _toolBarButton73 = new ToolBarButton();
            _toolBarButton73._set_property_value_by_name("Command", DataContextBinding(_toolBarButton73, "AlignCenterCommand"));
            const _textBlock74 = new TextBlock();
            _textBlock74._set_property_value_by_name("Text", "⇔");
            _toolBarButton73.Content = _textBlock74;
            _toolBar56.AddChild(_toolBarButton73);
            const _toolBarButton75 = new ToolBarButton();
            _toolBarButton75._set_property_value_by_name("Command", DataContextBinding(_toolBarButton75, "AlignRightCommand"));
            const _textBlock76 = new TextBlock();
            _textBlock76._set_property_value_by_name("Text", "➡");
            _toolBarButton75.Content = _textBlock76;
            _toolBar56.AddChild(_toolBarButton75);
            const _toolBarSeparator77 = new ToolBarSeparator();
            _toolBar56.AddChild(_toolBarSeparator77);
            const _toolBarButton78 = new ToolBarButton();
            _toolBarButton78._set_property_value_by_name("Command", DataContextBinding(_toolBarButton78, "AlignTopCommand"));
            const _textBlock79 = new TextBlock();
            _textBlock79._set_property_value_by_name("Text", "⬆");
            _toolBarButton78.Content = _textBlock79;
            _toolBar56.AddChild(_toolBarButton78);
            const _toolBarButton80 = new ToolBarButton();
            _toolBarButton80._set_property_value_by_name("Command", DataContextBinding(_toolBarButton80, "AlignMiddleCommand"));
            const _textBlock81 = new TextBlock();
            _textBlock81._set_property_value_by_name("Text", "↕");
            _toolBarButton80.Content = _textBlock81;
            _toolBar56.AddChild(_toolBarButton80);
            const _toolBarButton82 = new ToolBarButton();
            _toolBarButton82._set_property_value_by_name("Command", DataContextBinding(_toolBarButton82, "AlignBottomCommand"));
            const _textBlock83 = new TextBlock();
            _textBlock83._set_property_value_by_name("Text", "⬇");
            _toolBarButton82.Content = _textBlock83;
            _toolBar56.AddChild(_toolBarButton82);
            const _toolBarSeparator84 = new ToolBarSeparator();
            _toolBar56.AddChild(_toolBarSeparator84);
            const _toolBarButton85 = new ToolBarButton();
            _toolBarButton85._set_property_value_by_name("Command", DataContextBinding(_toolBarButton85, "UndoCommand"));
            const _textBlock86 = new TextBlock();
            _textBlock86._set_property_value_by_name("Text", "⤺");
            _toolBarButton85.Content = _textBlock86;
            _toolBar56.AddChild(_toolBarButton85);
            const _toolBarButton87 = new ToolBarButton();
            _toolBarButton87._set_property_value_by_name("Command", DataContextBinding(_toolBarButton87, "RedoCommand"));
            const _textBlock88 = new TextBlock();
            _textBlock88._set_property_value_by_name("Text", "⤻");
            _toolBarButton87.Content = _textBlock88;
            _toolBar56.AddChild(_toolBarButton87);
            _border55.SetChild(_toolBar56);
            _dockPanel35.AddChild(_border55);
            const _border89 = new Border();
            _border89.Name = "surface";
            _border89._set_property_value_by_name("Background", DynamicResource(_border89, "SurfaceContainerLow"));
            const _diagram90 = new Diagram();
            _diagram90.Name = "nodes";
            _diagram90._set_property_value_by_name("ItemsSource", DataContextBinding(_diagram90, "Nodes"));
            _diagram90._set_property_value_by_name("ItemsPanel", _tmpl3);
            _diagram90._set_property_value_by_name("ItemContainerStyle", _style2);
            _diagram90._set_property_value_by_name("SelectionMode", SelectionMode.Extended);
            _diagram90._set_property_value_by_name("AllowMarqueeSelection", true);
            _border89.SetChild(_diagram90);
            _dockPanel35.AddChild(_border89);
            _border34.SetChild(_dockPanel35);
            return _border34;
        }, CommandsVM);
        t.Set("CommandsTemplate", _tmpl33);
        return t;
    }
    get CommandsNodeStyle() { return this.Resolve("CommandsNodeStyle"); }
    set CommandsNodeStyle(v) { this.Set("CommandsNodeStyle", v); }
    get CommandsCanvasPanel() { return this.Resolve("CommandsCanvasPanel"); }
    set CommandsCanvasPanel(v) { this.Set("CommandsCanvasPanel", v); }
    get CommandsRectChromeStyle() { return this.Resolve("CommandsRectChromeStyle"); }
    set CommandsRectChromeStyle(v) { this.Set("CommandsRectChromeStyle", v); }
    get CommandsNoteChromeStyle() { return this.Resolve("CommandsNoteChromeStyle"); }
    set CommandsNoteChromeStyle(v) { this.Set("CommandsNoteChromeStyle", v); }
    get CommandsEllipseChromeStyle() { return this.Resolve("CommandsEllipseChromeStyle"); }
    set CommandsEllipseChromeStyle(v) { this.Set("CommandsEllipseChromeStyle", v); }
    get NodeContextMenu() { return this.Resolve("NodeContextMenu"); }
    set NodeContextMenu(v) { this.Set("NodeContextMenu", v); }
    get CommandsTemplate() { return this.Resolve("CommandsTemplate"); }
    set CommandsTemplate(v) { this.Set("CommandsTemplate", v); }
}
