import { CommandsVM, EllipseFigure, NoteFigure, RectFigure } from "./commands-vm.mjs";
import { Border, Canvas, DataTemplate, Dock, DockPanel, ItemsPanelTemplate, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/basic";
import { Diagram } from "@visualisation-sub/mural/framework/diagram/diagram.js";
import { SelectionMode } from "@visualisation-sub/mural/framework/list/list-box.js";
import { ContextMenu, ContextMenuService, MenuButton, MenuItem, MenuSeparator, ToolBar, ToolBarButton, ToolBarSeparator } from "@visualisation-sub/mural/framework/surface.js";
import { Color, DataContextBinding, DynamicResource, PropertyTrigger, ResourceDictionary, Setter, SetterFactory, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, Pen, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_CommandsDemo = Symbol("CommandsDemo.ctor");
export class CommandsDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_CommandsDemo) {
            throw new Error("CommandsDemo is private — use CommandsDemo.Clone()");
        }
    }
    static Clone() {
        const t = new CommandsDemo(_gate_CommandsDemo);
        const _tmpl0 = new ItemsPanelTemplate(() => {
            const _canvas1 = new Canvas();
            return _canvas1;
        });
        t.Set("CommandsCanvasPanel", _tmpl0);
        const _pen2 = new Pen();
        _pen2.set_property_value(Pen.BrushKey, new SolidColorBrush(Color.FromHex('#f97316')));
        _pen2.set_property_value(Pen.ThicknessKey, 2);
        t.Set("CommandsSelectedPen", _pen2);
        const _contextMenu3 = new ContextMenu();
        const _menuItem4 = new MenuItem();
        _menuItem4.set_property_value(MenuItem.HeaderKey, "Cut");
        _menuItem4.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+X");
        _menuItem4.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem4, "CutCommand"));
        _contextMenu3.AddChild(_menuItem4);
        const _menuItem5 = new MenuItem();
        _menuItem5.set_property_value(MenuItem.HeaderKey, "Copy");
        _menuItem5.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+C");
        _menuItem5.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem5, "CopyCommand"));
        _contextMenu3.AddChild(_menuItem5);
        const _menuItem6 = new MenuItem();
        _menuItem6.set_property_value(MenuItem.HeaderKey, "Duplicate");
        _menuItem6.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+D");
        _menuItem6.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem6, "DuplicateCommand"));
        _contextMenu3.AddChild(_menuItem6);
        const _menuSeparator7 = new MenuSeparator();
        _contextMenu3.AddChild(_menuSeparator7);
        const _menuItem8 = new MenuItem();
        _menuItem8.set_property_value(MenuItem.HeaderKey, "Delete");
        _menuItem8.set_property_value(MenuItem.InputGestureTextKey, "Del");
        _menuItem8.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem8, "DeleteCommand"));
        _contextMenu3.AddChild(_menuItem8);
        t.Set("NodeContextMenu", _contextMenu3);
        const _setter9 = new Setter(ContextMenuService, "ContextMenu", new SetterFactory((_t) => DynamicResource(_t, "NodeContextMenu")));
        const _setter10 = new Setter(RectFigure, "Stroke", new SetterFactory((_t) => DynamicResource(_t, "CommandsSelectedPen")));
        const _sArr11 = [_setter10];
        const _trigger12 = new PropertyTrigger(RectFigure, "IsSelected", true, _sArr11);
        const _style13 = new Style(RectFigure, [_setter9], undefined, [_trigger12], []);
        t.Set(RectFigure, _style13);
        const _setter14 = new Setter(ContextMenuService, "ContextMenu", new SetterFactory((_t) => DynamicResource(_t, "NodeContextMenu")));
        const _setter15 = new Setter(EllipseFigure, "Stroke", new SetterFactory((_t) => DynamicResource(_t, "CommandsSelectedPen")));
        const _sArr16 = [_setter15];
        const _trigger17 = new PropertyTrigger(EllipseFigure, "IsSelected", true, _sArr16);
        const _style18 = new Style(EllipseFigure, [_setter14], undefined, [_trigger17], []);
        t.Set(EllipseFigure, _style18);
        const _setter19 = new Setter(ContextMenuService, "ContextMenu", new SetterFactory((_t) => DynamicResource(_t, "NodeContextMenu")));
        const _setter20 = new Setter(NoteFigure, "Stroke", new SetterFactory((_t) => DynamicResource(_t, "CommandsSelectedPen")));
        const _sArr21 = [_setter20];
        const _trigger22 = new PropertyTrigger(NoteFigure, "IsSelected", true, _sArr21);
        const _style23 = new Style(NoteFigure, [_setter19], undefined, [_trigger22], []);
        t.Set(NoteFigure, _style23);
        const _tmpl24 = new DataTemplate((_data) => {
            let _diagram25;
            const _border26 = new Border();
            _border26.set_property_value(Border.BackgroundKey, DynamicResource(_border26, "Surface"));
            _border26.set_property_value(Border.BorderBrushKey, DynamicResource(_border26, "OutlineVariant"));
            _border26.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _dockPanel27 = new DockPanel();
            const _border28 = new Border();
            _border28.set_property_value(DockPanel.DockKey, Dock.Top);
            _border28.set_property_value(Border.BackgroundKey, DynamicResource(_border28, "Primary"));
            _border28.set_property_value(Border.PaddingKey, new Thickness(16, 10, 16, 10));
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, "ToolBar + Menu + ContextMenu over a Diagram. Select nodes (click / Ctrl-click / marquee) and use the commands.");
            _textBlock29.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock29.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock29.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock29, "OnPrimary"));
            _border28.SetChild(_textBlock29);
            _dockPanel27.AddChild(_border28);
            const _border30 = new Border();
            _border30.set_property_value(DockPanel.DockKey, Dock.Top);
            _border30.set_property_value(Border.BackgroundKey, DynamicResource(_border30, "SurfaceContainerLow"));
            _border30.set_property_value(Border.BorderBrushKey, DynamicResource(_border30, "OutlineVariant"));
            _border30.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 0, 1));
            _border30.set_property_value(Border.PaddingKey, new Thickness(8, 6, 8, 6));
            const _stackPanel31 = new StackPanel();
            _stackPanel31.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _menuButton32 = new MenuButton();
            _menuButton32.set_property_value(MenuButton.HeaderKey, "☰  File");
            _menuButton32.set_property_value(MenuButton.MarginKey, new Thickness(0, 0, 8, 0));
            const _menuItem33 = new MenuItem();
            _menuItem33.set_property_value(MenuItem.HeaderKey, "Save");
            _menuItem33.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+S");
            _menuItem33.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem33, "SaveCommand"));
            _menuButton32.AddChild(_menuItem33);
            const _menuItem34 = new MenuItem();
            _menuItem34.set_property_value(MenuItem.HeaderKey, "Load");
            _menuItem34.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+O");
            _menuItem34.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem34, "LoadCommand"));
            _menuButton32.AddChild(_menuItem34);
            const _menuSeparator35 = new MenuSeparator();
            _menuButton32.AddChild(_menuSeparator35);
            const _menuItem36 = new MenuItem();
            _menuItem36.set_property_value(MenuItem.HeaderKey, "Cut");
            _menuItem36.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+X");
            _menuItem36.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem36, "CutCommand"));
            _menuButton32.AddChild(_menuItem36);
            const _menuItem37 = new MenuItem();
            _menuItem37.set_property_value(MenuItem.HeaderKey, "Copy");
            _menuItem37.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+C");
            _menuItem37.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem37, "CopyCommand"));
            _menuButton32.AddChild(_menuItem37);
            const _menuItem38 = new MenuItem();
            _menuItem38.set_property_value(MenuItem.HeaderKey, "Paste");
            _menuItem38.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+V");
            _menuItem38.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem38, "PasteCommand"));
            _menuButton32.AddChild(_menuItem38);
            const _menuItem39 = new MenuItem();
            _menuItem39.set_property_value(MenuItem.HeaderKey, "Delete");
            _menuItem39.set_property_value(MenuItem.InputGestureTextKey, "Del");
            _menuItem39.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem39, "DeleteCommand"));
            _menuButton32.AddChild(_menuItem39);
            const _menuSeparator40 = new MenuSeparator();
            _menuButton32.AddChild(_menuSeparator40);
            const _menuItem41 = new MenuItem();
            _menuItem41.set_property_value(MenuItem.HeaderKey, "Duplicate");
            _menuItem41.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+D");
            _menuItem41.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem41, "DuplicateCommand"));
            _menuButton32.AddChild(_menuItem41);
            const _menuItem42 = new MenuItem();
            _menuItem42.set_property_value(MenuItem.HeaderKey, "Select All");
            _menuItem42.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+A");
            _menuItem42.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem42, "SelectAllCommand"));
            _menuButton32.AddChild(_menuItem42);
            const _menuSeparator43 = new MenuSeparator();
            _menuButton32.AddChild(_menuSeparator43);
            const _menuItem44 = new MenuItem();
            _menuItem44.set_property_value(MenuItem.HeaderKey, "Undo");
            _menuItem44.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+Z");
            _menuItem44.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem44, "UndoCommand"));
            _menuButton32.AddChild(_menuItem44);
            const _menuItem45 = new MenuItem();
            _menuItem45.set_property_value(MenuItem.HeaderKey, "Redo");
            _menuItem45.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+Y");
            _menuItem45.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem45, "RedoCommand"));
            _menuButton32.AddChild(_menuItem45);
            _stackPanel31.AddChild(_menuButton32);
            const _textBlock46 = new TextBlock();
            _textBlock46.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock46, "Status"));
            _textBlock46.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock46.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock46, "OnSurface"));
            _textBlock46.set_property_value(TextBlock.MarginKey, new Thickness(12, 8, 0, 0));
            _stackPanel31.AddChild(_textBlock46);
            _border30.SetChild(_stackPanel31);
            _dockPanel27.AddChild(_border30);
            const _border47 = new Border();
            _border47.set_property_value(DockPanel.DockKey, Dock.Top);
            _border47.set_property_value(Border.BackgroundKey, DynamicResource(_border47, "Surface"));
            _border47.set_property_value(Border.BorderBrushKey, DynamicResource(_border47, "OutlineVariant"));
            _border47.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 0, 1));
            const _toolBar48 = new ToolBar();
            const _toolBarButton49 = new ToolBarButton();
            _toolBarButton49.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton49, "SaveCommand"));
            const _textBlock50 = new TextBlock();
            _textBlock50.set_property_value(TextBlock.TextKey, "💾");
            _toolBarButton49.Content = _textBlock50;
            _toolBar48.AddChild(_toolBarButton49);
            const _toolBarSeparator51 = new ToolBarSeparator();
            _toolBar48.AddChild(_toolBarSeparator51);
            const _toolBarButton52 = new ToolBarButton();
            _toolBarButton52.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton52, "CutCommand"));
            const _textBlock53 = new TextBlock();
            _textBlock53.set_property_value(TextBlock.TextKey, "✂");
            _toolBarButton52.Content = _textBlock53;
            _toolBar48.AddChild(_toolBarButton52);
            const _toolBarButton54 = new ToolBarButton();
            _toolBarButton54.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton54, "CopyCommand"));
            const _textBlock55 = new TextBlock();
            _textBlock55.set_property_value(TextBlock.TextKey, "📋");
            _toolBarButton54.Content = _textBlock55;
            _toolBar48.AddChild(_toolBarButton54);
            const _toolBarButton56 = new ToolBarButton();
            _toolBarButton56.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton56, "PasteCommand"));
            const _textBlock57 = new TextBlock();
            _textBlock57.set_property_value(TextBlock.TextKey, "📄");
            _toolBarButton56.Content = _textBlock57;
            _toolBar48.AddChild(_toolBarButton56);
            const _toolBarButton58 = new ToolBarButton();
            _toolBarButton58.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton58, "DeleteCommand"));
            const _textBlock59 = new TextBlock();
            _textBlock59.set_property_value(TextBlock.TextKey, "🗑");
            _toolBarButton58.Content = _textBlock59;
            _toolBar48.AddChild(_toolBarButton58);
            const _toolBarButton60 = new ToolBarButton();
            _toolBarButton60.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton60, "DuplicateCommand"));
            const _textBlock61 = new TextBlock();
            _textBlock61.set_property_value(TextBlock.TextKey, "⎘");
            _toolBarButton60.Content = _textBlock61;
            _toolBar48.AddChild(_toolBarButton60);
            const _toolBarSeparator62 = new ToolBarSeparator();
            _toolBar48.AddChild(_toolBarSeparator62);
            const _toolBarButton63 = new ToolBarButton();
            _toolBarButton63.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton63, "AlignLeftCommand"));
            const _textBlock64 = new TextBlock();
            _textBlock64.set_property_value(TextBlock.TextKey, "⬅");
            _toolBarButton63.Content = _textBlock64;
            _toolBar48.AddChild(_toolBarButton63);
            const _toolBarButton65 = new ToolBarButton();
            _toolBarButton65.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton65, "AlignCenterCommand"));
            const _textBlock66 = new TextBlock();
            _textBlock66.set_property_value(TextBlock.TextKey, "⇔");
            _toolBarButton65.Content = _textBlock66;
            _toolBar48.AddChild(_toolBarButton65);
            const _toolBarButton67 = new ToolBarButton();
            _toolBarButton67.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton67, "AlignRightCommand"));
            const _textBlock68 = new TextBlock();
            _textBlock68.set_property_value(TextBlock.TextKey, "➡");
            _toolBarButton67.Content = _textBlock68;
            _toolBar48.AddChild(_toolBarButton67);
            const _toolBarSeparator69 = new ToolBarSeparator();
            _toolBar48.AddChild(_toolBarSeparator69);
            const _toolBarButton70 = new ToolBarButton();
            _toolBarButton70.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton70, "AlignTopCommand"));
            const _textBlock71 = new TextBlock();
            _textBlock71.set_property_value(TextBlock.TextKey, "⬆");
            _toolBarButton70.Content = _textBlock71;
            _toolBar48.AddChild(_toolBarButton70);
            const _toolBarButton72 = new ToolBarButton();
            _toolBarButton72.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton72, "AlignMiddleCommand"));
            const _textBlock73 = new TextBlock();
            _textBlock73.set_property_value(TextBlock.TextKey, "↕");
            _toolBarButton72.Content = _textBlock73;
            _toolBar48.AddChild(_toolBarButton72);
            const _toolBarButton74 = new ToolBarButton();
            _toolBarButton74.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton74, "AlignBottomCommand"));
            const _textBlock75 = new TextBlock();
            _textBlock75.set_property_value(TextBlock.TextKey, "⬇");
            _toolBarButton74.Content = _textBlock75;
            _toolBar48.AddChild(_toolBarButton74);
            const _toolBarSeparator76 = new ToolBarSeparator();
            _toolBar48.AddChild(_toolBarSeparator76);
            const _toolBarButton77 = new ToolBarButton();
            _toolBarButton77.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton77, "UndoCommand"));
            const _textBlock78 = new TextBlock();
            _textBlock78.set_property_value(TextBlock.TextKey, "⤺");
            _toolBarButton77.Content = _textBlock78;
            _toolBar48.AddChild(_toolBarButton77);
            const _toolBarButton79 = new ToolBarButton();
            _toolBarButton79.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton79, "RedoCommand"));
            const _textBlock80 = new TextBlock();
            _textBlock80.set_property_value(TextBlock.TextKey, "⤻");
            _toolBarButton79.Content = _textBlock80;
            _toolBar48.AddChild(_toolBarButton79);
            _border47.SetChild(_toolBar48);
            _dockPanel27.AddChild(_border47);
            _diagram25 = new Diagram();
            _diagram25.Name = "nodes";
            _diagram25.set_property_value(Diagram.ItemsSourceKey, DataContextBinding(_diagram25, "Nodes"));
            _diagram25.set_property_value(Diagram.ItemsPanelKey, _tmpl0);
            _diagram25.set_property_value(Diagram.SelectionModeKey, SelectionMode.Extended);
            _diagram25.set_property_value(Diagram.AllowMarqueeSelectionKey, true);
            _diagram25.set_property_value(Diagram.ReflectSelectionToItemsKey, true);
            _diagram25.set_property_value(Diagram.FocusableKey, true);
            _dockPanel27.AddChild(_diagram25);
            _border26.SetChild(_dockPanel27);
            return _border26;
        }, CommandsVM);
        t.Set("CommandsTemplate", _tmpl24);
        return t;
    }
    get CommandsCanvasPanel() { return this.Resolve("CommandsCanvasPanel"); }
    set CommandsCanvasPanel(v) { this.Set("CommandsCanvasPanel", v); }
    get CommandsSelectedPen() { return this.Resolve("CommandsSelectedPen"); }
    set CommandsSelectedPen(v) { this.Set("CommandsSelectedPen", v); }
    get NodeContextMenu() { return this.Resolve("NodeContextMenu"); }
    set NodeContextMenu(v) { this.Set("NodeContextMenu", v); }
    get CommandsTemplate() { return this.Resolve("CommandsTemplate"); }
    set CommandsTemplate(v) { this.Set("CommandsTemplate", v); }
}
