import { CommandsVM, EllipseFigure, NoteFigure, RectFigure } from "./commands-vm.mjs";
import { Border, Canvas, DataTemplate, Dock, DockPanel, ItemsPanelTemplate, Orientation, StackPanel, TargetedSetter, TemplateDataTrigger, TextBlock } from "@visualisation-sub/mural/basic";
import { Diagram } from "@visualisation-sub/mural/framework/diagram/diagram.js";
import { SelectionMode } from "@visualisation-sub/mural/framework/list/list-box.js";
import { ContextMenu, ContextMenuService, MenuButton, MenuItem, MenuSeparator, Ribbon, RibbonButton, RibbonContextualGroup, RibbonGroup, RibbonSmallButtonColumn, RibbonTab, ToolBar, ToolBarButton, ToolBarSeparator } from "@visualisation-sub/mural/framework/surface.js";
import { Checkbox } from "@visualisation-sub/mural/framework/toggles/checkbox.js";
import { Color, DataContextBinding, DynamicResource, PropertyTrigger, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment, Visibility } from "@visualisation-sub/mural/runtime";
import { FontWeight, Pen, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_CommandsDemo = Symbol("CommandsDemo.ctor");
export class CommandsDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_CommandsDemo) {
            throw new Error("CommandsDemo is private — use CommandsDemo.Clone()");
        }
    }
    static Clone() {
        const t = new CommandsDemo(_gate_CommandsDemo);
        const _tmpl0 = new ItemsPanelTemplate(() => {
            const _canvas1 = new Canvas();
            return _canvas1;
        });
        t.Set("CommandsCanvasPanel", _tmpl0);
        const _pen2 = new Pen();
        _pen2.set_property_value(Pen.BrushKey, new SolidColorBrush(Color.FromHex('#f97316')));
        _pen2.set_property_value(Pen.ThicknessKey, 2);
        t.Set("CommandsSelectedPen", _pen2);
        const _contextMenu3 = new ContextMenu();
        const _menuItem4 = new MenuItem();
        _menuItem4.set_property_value(MenuItem.HeaderKey, "Cut");
        _menuItem4.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+X");
        _menuItem4.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem4, "CutCommand"));
        _contextMenu3.AddChild(_menuItem4);
        const _menuItem5 = new MenuItem();
        _menuItem5.set_property_value(MenuItem.HeaderKey, "Copy");
        _menuItem5.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+C");
        _menuItem5.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem5, "CopyCommand"));
        _contextMenu3.AddChild(_menuItem5);
        const _menuItem6 = new MenuItem();
        _menuItem6.set_property_value(MenuItem.HeaderKey, "Duplicate");
        _menuItem6.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+D");
        _menuItem6.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem6, "DuplicateCommand"));
        _contextMenu3.AddChild(_menuItem6);
        const _menuSeparator7 = new MenuSeparator();
        _contextMenu3.AddChild(_menuSeparator7);
        const _menuItem8 = new MenuItem();
        _menuItem8.set_property_value(MenuItem.HeaderKey, "Delete");
        _menuItem8.set_property_value(MenuItem.InputGestureTextKey, "Del");
        _menuItem8.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem8, "DeleteCommand"));
        _contextMenu3.AddChild(_menuItem8);
        t.Set("NodeContextMenu", _contextMenu3);
        const _setter9 = new Setter(ContextMenuService, "ContextMenu", new SetterFactory((_t) => DynamicResource(_t, "NodeContextMenu")));
        const _setter10 = new Setter(RectFigure, "Stroke", new SetterFactory((_t) => DynamicResource(_t, "CommandsSelectedPen")));
        const _sArr11 = [_setter10];
        const _trigger12 = new PropertyTrigger(RectFigure, "IsSelected", true, _sArr11);
        const _style13 = new Style(RectFigure, [_setter9], undefined, [_trigger12], []);
        t.Set(RectFigure, _style13);
        const _setter14 = new Setter(ContextMenuService, "ContextMenu", new SetterFactory((_t) => DynamicResource(_t, "NodeContextMenu")));
        const _setter15 = new Setter(EllipseFigure, "Stroke", new SetterFactory((_t) => DynamicResource(_t, "CommandsSelectedPen")));
        const _sArr16 = [_setter15];
        const _trigger17 = new PropertyTrigger(EllipseFigure, "IsSelected", true, _sArr16);
        const _style18 = new Style(EllipseFigure, [_setter14], undefined, [_trigger17], []);
        t.Set(EllipseFigure, _style18);
        const _setter19 = new Setter(ContextMenuService, "ContextMenu", new SetterFactory((_t) => DynamicResource(_t, "NodeContextMenu")));
        const _setter20 = new Setter(NoteFigure, "Stroke", new SetterFactory((_t) => DynamicResource(_t, "CommandsSelectedPen")));
        const _sArr21 = [_setter20];
        const _trigger22 = new PropertyTrigger(NoteFigure, "IsSelected", true, _sArr21);
        const _style23 = new Style(NoteFigure, [_setter19], undefined, [_trigger22], []);
        t.Set(NoteFigure, _style23);
        const _tmpl24 = (() => {
            const _factory = (_data) => {
                let _stackPanel25, _border26, _diagram27;
                const _border28 = new Border();
                _border28.set_property_value(Border.BackgroundKey, DynamicResource(_border28, "Surface"));
                _border28.set_property_value(Border.BorderBrushKey, DynamicResource(_border28, "OutlineVariant"));
                _border28.set_property_value(Border.BorderThicknessKey, new Thickness(1));
                const _dockPanel29 = new DockPanel();
                const _border30 = new Border();
                _border30.set_property_value(DockPanel.DockKey, Dock.Top);
                _border30.set_property_value(Border.BackgroundKey, DynamicResource(_border30, "Primary"));
                _border30.set_property_value(Border.PaddingKey, new Thickness(16, 10, 16, 10));
                const _dockPanel31 = new DockPanel();
                _dockPanel31.set_property_value(DockPanel.LastChildFillKey, true);
                const _checkbox32 = new Checkbox();
                _checkbox32.set_property_value(DockPanel.DockKey, Dock.Right);
                _checkbox32.set_property_value(Checkbox.ContentKey, "Ribbon mode");
                _checkbox32.set_property_value(Checkbox.IsCheckedKey, DataContextBinding(_checkbox32, "IsRibbonMode"));
                _dockPanel31.AddChild(_checkbox32);
                const _textBlock33 = new TextBlock();
                _textBlock33.set_property_value(TextBlock.TextKey, "Menu + ToolBar + ContextMenu (Classic) or a tabbed Ribbon over one shared ICommand catalog. Select nodes to reveal the contextual Format tab.");
                _textBlock33.set_property_value(TextBlock.FontSizeKey, 14);
                _textBlock33.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
                _textBlock33.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock33, "OnPrimary"));
                _textBlock33.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
                _dockPanel31.AddChild(_textBlock33);
                _border30.SetChild(_dockPanel31);
                _dockPanel29.AddChild(_border30);
                _stackPanel25 = new StackPanel();
                _stackPanel25.Name = "ClassicChrome";
                _stackPanel25.set_property_value(DockPanel.DockKey, Dock.Top);
                _stackPanel25.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
                const _border34 = new Border();
                _border34.set_property_value(Border.BackgroundKey, DynamicResource(_border34, "SurfaceContainerLow"));
                _border34.set_property_value(Border.BorderBrushKey, DynamicResource(_border34, "OutlineVariant"));
                _border34.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 0, 1));
                _border34.set_property_value(Border.PaddingKey, new Thickness(8, 6, 8, 6));
                const _stackPanel35 = new StackPanel();
                _stackPanel35.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
                const _menuButton36 = new MenuButton();
                _menuButton36.set_property_value(MenuButton.HeaderKey, "☰  File");
                _menuButton36.set_property_value(MenuButton.MarginKey, new Thickness(0, 0, 8, 0));
                const _menuItem37 = new MenuItem();
                _menuItem37.set_property_value(MenuItem.HeaderKey, "Save");
                _menuItem37.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+S");
                _menuItem37.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem37, "SaveCommand"));
                _menuButton36.AddChild(_menuItem37);
                const _menuItem38 = new MenuItem();
                _menuItem38.set_property_value(MenuItem.HeaderKey, "Load");
                _menuItem38.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+O");
                _menuItem38.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem38, "LoadCommand"));
                _menuButton36.AddChild(_menuItem38);
                const _menuSeparator39 = new MenuSeparator();
                _menuButton36.AddChild(_menuSeparator39);
                const _menuItem40 = new MenuItem();
                _menuItem40.set_property_value(MenuItem.HeaderKey, "Cut");
                _menuItem40.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+X");
                _menuItem40.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem40, "CutCommand"));
                _menuButton36.AddChild(_menuItem40);
                const _menuItem41 = new MenuItem();
                _menuItem41.set_property_value(MenuItem.HeaderKey, "Copy");
                _menuItem41.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+C");
                _menuItem41.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem41, "CopyCommand"));
                _menuButton36.AddChild(_menuItem41);
                const _menuItem42 = new MenuItem();
                _menuItem42.set_property_value(MenuItem.HeaderKey, "Paste");
                _menuItem42.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+V");
                _menuItem42.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem42, "PasteCommand"));
                _menuButton36.AddChild(_menuItem42);
                const _menuItem43 = new MenuItem();
                _menuItem43.set_property_value(MenuItem.HeaderKey, "Delete");
                _menuItem43.set_property_value(MenuItem.InputGestureTextKey, "Del");
                _menuItem43.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem43, "DeleteCommand"));
                _menuButton36.AddChild(_menuItem43);
                const _menuSeparator44 = new MenuSeparator();
                _menuButton36.AddChild(_menuSeparator44);
                const _menuItem45 = new MenuItem();
                _menuItem45.set_property_value(MenuItem.HeaderKey, "Duplicate");
                _menuItem45.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+D");
                _menuItem45.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem45, "DuplicateCommand"));
                _menuButton36.AddChild(_menuItem45);
                const _menuItem46 = new MenuItem();
                _menuItem46.set_property_value(MenuItem.HeaderKey, "Select All");
                _menuItem46.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+A");
                _menuItem46.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem46, "SelectAllCommand"));
                _menuButton36.AddChild(_menuItem46);
                const _menuSeparator47 = new MenuSeparator();
                _menuButton36.AddChild(_menuSeparator47);
                const _menuItem48 = new MenuItem();
                _menuItem48.set_property_value(MenuItem.HeaderKey, "Undo");
                _menuItem48.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+Z");
                _menuItem48.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem48, "UndoCommand"));
                _menuButton36.AddChild(_menuItem48);
                const _menuItem49 = new MenuItem();
                _menuItem49.set_property_value(MenuItem.HeaderKey, "Redo");
                _menuItem49.set_property_value(MenuItem.InputGestureTextKey, "Ctrl+Y");
                _menuItem49.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem49, "RedoCommand"));
                _menuButton36.AddChild(_menuItem49);
                _stackPanel35.AddChild(_menuButton36);
                const _textBlock50 = new TextBlock();
                _textBlock50.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock50, "Status"));
                _textBlock50.set_property_value(TextBlock.FontSizeKey, 12);
                _textBlock50.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock50, "OnSurface"));
                _textBlock50.set_property_value(TextBlock.MarginKey, new Thickness(12, 8, 0, 0));
                _stackPanel35.AddChild(_textBlock50);
                _border34.SetChild(_stackPanel35);
                _stackPanel25.AddChild(_border34);
                const _border51 = new Border();
                _border51.set_property_value(DockPanel.DockKey, Dock.Top);
                _border51.set_property_value(Border.BackgroundKey, DynamicResource(_border51, "Surface"));
                _border51.set_property_value(Border.BorderBrushKey, DynamicResource(_border51, "OutlineVariant"));
                _border51.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 0, 1));
                const _toolBar52 = new ToolBar();
                const _toolBarButton53 = new ToolBarButton();
                _toolBarButton53.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton53, "SaveCommand"));
                const _textBlock54 = new TextBlock();
                _textBlock54.set_property_value(TextBlock.TextKey, "💾");
                _toolBarButton53.Content = _textBlock54;
                _toolBar52.AddChild(_toolBarButton53);
                const _toolBarSeparator55 = new ToolBarSeparator();
                _toolBar52.AddChild(_toolBarSeparator55);
                const _toolBarButton56 = new ToolBarButton();
                _toolBarButton56.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton56, "CutCommand"));
                const _textBlock57 = new TextBlock();
                _textBlock57.set_property_value(TextBlock.TextKey, "✂");
                _toolBarButton56.Content = _textBlock57;
                _toolBar52.AddChild(_toolBarButton56);
                const _toolBarButton58 = new ToolBarButton();
                _toolBarButton58.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton58, "CopyCommand"));
                const _textBlock59 = new TextBlock();
                _textBlock59.set_property_value(TextBlock.TextKey, "📋");
                _toolBarButton58.Content = _textBlock59;
                _toolBar52.AddChild(_toolBarButton58);
                const _toolBarButton60 = new ToolBarButton();
                _toolBarButton60.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton60, "PasteCommand"));
                const _textBlock61 = new TextBlock();
                _textBlock61.set_property_value(TextBlock.TextKey, "📄");
                _toolBarButton60.Content = _textBlock61;
                _toolBar52.AddChild(_toolBarButton60);
                const _toolBarButton62 = new ToolBarButton();
                _toolBarButton62.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton62, "DeleteCommand"));
                const _textBlock63 = new TextBlock();
                _textBlock63.set_property_value(TextBlock.TextKey, "🗑");
                _toolBarButton62.Content = _textBlock63;
                _toolBar52.AddChild(_toolBarButton62);
                const _toolBarButton64 = new ToolBarButton();
                _toolBarButton64.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton64, "DuplicateCommand"));
                const _textBlock65 = new TextBlock();
                _textBlock65.set_property_value(TextBlock.TextKey, "⎘");
                _toolBarButton64.Content = _textBlock65;
                _toolBar52.AddChild(_toolBarButton64);
                const _toolBarSeparator66 = new ToolBarSeparator();
                _toolBar52.AddChild(_toolBarSeparator66);
                const _toolBarButton67 = new ToolBarButton();
                _toolBarButton67.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton67, "AlignLeftCommand"));
                const _textBlock68 = new TextBlock();
                _textBlock68.set_property_value(TextBlock.TextKey, "⬅");
                _toolBarButton67.Content = _textBlock68;
                _toolBar52.AddChild(_toolBarButton67);
                const _toolBarButton69 = new ToolBarButton();
                _toolBarButton69.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton69, "AlignCenterCommand"));
                const _textBlock70 = new TextBlock();
                _textBlock70.set_property_value(TextBlock.TextKey, "⇔");
                _toolBarButton69.Content = _textBlock70;
                _toolBar52.AddChild(_toolBarButton69);
                const _toolBarButton71 = new ToolBarButton();
                _toolBarButton71.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton71, "AlignRightCommand"));
                const _textBlock72 = new TextBlock();
                _textBlock72.set_property_value(TextBlock.TextKey, "➡");
                _toolBarButton71.Content = _textBlock72;
                _toolBar52.AddChild(_toolBarButton71);
                const _toolBarSeparator73 = new ToolBarSeparator();
                _toolBar52.AddChild(_toolBarSeparator73);
                const _toolBarButton74 = new ToolBarButton();
                _toolBarButton74.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton74, "AlignTopCommand"));
                const _textBlock75 = new TextBlock();
                _textBlock75.set_property_value(TextBlock.TextKey, "⬆");
                _toolBarButton74.Content = _textBlock75;
                _toolBar52.AddChild(_toolBarButton74);
                const _toolBarButton76 = new ToolBarButton();
                _toolBarButton76.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton76, "AlignMiddleCommand"));
                const _textBlock77 = new TextBlock();
                _textBlock77.set_property_value(TextBlock.TextKey, "↕");
                _toolBarButton76.Content = _textBlock77;
                _toolBar52.AddChild(_toolBarButton76);
                const _toolBarButton78 = new ToolBarButton();
                _toolBarButton78.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton78, "AlignBottomCommand"));
                const _textBlock79 = new TextBlock();
                _textBlock79.set_property_value(TextBlock.TextKey, "⬇");
                _toolBarButton78.Content = _textBlock79;
                _toolBar52.AddChild(_toolBarButton78);
                const _toolBarSeparator80 = new ToolBarSeparator();
                _toolBar52.AddChild(_toolBarSeparator80);
                const _toolBarButton81 = new ToolBarButton();
                _toolBarButton81.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton81, "UndoCommand"));
                const _textBlock82 = new TextBlock();
                _textBlock82.set_property_value(TextBlock.TextKey, "⤺");
                _toolBarButton81.Content = _textBlock82;
                _toolBar52.AddChild(_toolBarButton81);
                const _toolBarButton83 = new ToolBarButton();
                _toolBarButton83.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton83, "RedoCommand"));
                const _textBlock84 = new TextBlock();
                _textBlock84.set_property_value(TextBlock.TextKey, "⤻");
                _toolBarButton83.Content = _textBlock84;
                _toolBar52.AddChild(_toolBarButton83);
                _border51.SetChild(_toolBar52);
                _stackPanel25.AddChild(_border51);
                _dockPanel29.AddChild(_stackPanel25);
                _border26 = new Border();
                _border26.Name = "RibbonChrome";
                _border26.set_property_value(DockPanel.DockKey, Dock.Top);
                _border26.set_property_value(Border.VisibilityKey, Visibility.Collapsed);
                const _ribbon85 = new Ribbon();
                const _ribbonTab86 = new RibbonTab();
                _ribbonTab86.set_property_value(RibbonTab.HeaderKey, "Home");
                const _ribbonGroup87 = new RibbonGroup();
                _ribbonGroup87.set_property_value(RibbonGroup.HeaderKey, "Clipboard");
                const _ribbonButton88 = new RibbonButton();
                _ribbonButton88.set_property_value(RibbonButton.TextKey, "✂ Cut");
                _ribbonButton88.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton88, "CutCommand"));
                _ribbonGroup87.AddChild(_ribbonButton88);
                const _ribbonButton89 = new RibbonButton();
                _ribbonButton89.set_property_value(RibbonButton.TextKey, "📋 Copy");
                _ribbonButton89.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton89, "CopyCommand"));
                _ribbonGroup87.AddChild(_ribbonButton89);
                const _ribbonButton90 = new RibbonButton();
                _ribbonButton90.set_property_value(RibbonButton.TextKey, "📄 Paste");
                _ribbonButton90.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton90, "PasteCommand"));
                _ribbonGroup87.AddChild(_ribbonButton90);
                _ribbonTab86.AddChild(_ribbonGroup87);
                const _ribbonGroup91 = new RibbonGroup();
                _ribbonGroup91.set_property_value(RibbonGroup.HeaderKey, "File");
                _ribbonGroup91.set_property_value(RibbonGroup.LaunchCommandKey, DataContextBinding(_ribbonGroup91, "SaveCommand"));
                const _ribbonButton92 = new RibbonButton();
                _ribbonButton92.set_property_value(RibbonButton.TextKey, "💾 Save");
                _ribbonButton92.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton92, "SaveCommand"));
                _ribbonGroup91.AddChild(_ribbonButton92);
                const _ribbonButton93 = new RibbonButton();
                _ribbonButton93.set_property_value(RibbonButton.TextKey, "📂 Load");
                _ribbonButton93.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton93, "LoadCommand"));
                _ribbonGroup91.AddChild(_ribbonButton93);
                _ribbonTab86.AddChild(_ribbonGroup91);
                _ribbon85.AddChild(_ribbonTab86);
                const _ribbonTab94 = new RibbonTab();
                _ribbonTab94.set_property_value(RibbonTab.HeaderKey, "Insert");
                const _ribbonGroup95 = new RibbonGroup();
                _ribbonGroup95.set_property_value(RibbonGroup.HeaderKey, "Nodes");
                const _ribbonButton96 = new RibbonButton();
                _ribbonButton96.set_property_value(RibbonButton.TextKey, "⎘ Duplicate");
                _ribbonButton96.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton96, "DuplicateCommand"));
                _ribbonGroup95.AddChild(_ribbonButton96);
                const _ribbonButton97 = new RibbonButton();
                _ribbonButton97.set_property_value(RibbonButton.TextKey, "Select All");
                _ribbonButton97.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton97, "SelectAllCommand"));
                _ribbonGroup95.AddChild(_ribbonButton97);
                _ribbonTab94.AddChild(_ribbonGroup95);
                _ribbon85.AddChild(_ribbonTab94);
                const _ribbonTab98 = new RibbonTab();
                _ribbonTab98.set_property_value(RibbonTab.HeaderKey, "View");
                const _ribbonGroup99 = new RibbonGroup();
                _ribbonGroup99.set_property_value(RibbonGroup.HeaderKey, "History");
                const _ribbonButton100 = new RibbonButton();
                _ribbonButton100.set_property_value(RibbonButton.TextKey, "↶ Undo");
                _ribbonButton100.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton100, "UndoCommand"));
                _ribbonGroup99.AddChild(_ribbonButton100);
                const _ribbonButton101 = new RibbonButton();
                _ribbonButton101.set_property_value(RibbonButton.TextKey, "↷ Redo");
                _ribbonButton101.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton101, "RedoCommand"));
                _ribbonGroup99.AddChild(_ribbonButton101);
                _ribbonTab98.AddChild(_ribbonGroup99);
                _ribbon85.AddChild(_ribbonTab98);
                const _ribbonContextualGroup102 = new RibbonContextualGroup();
                _ribbonContextualGroup102.set_property_value(RibbonContextualGroup.HeaderKey, "Drawing Tools");
                _ribbonContextualGroup102.set_property_value(RibbonContextualGroup.ColorKey, new SolidColorBrush(Color.FromHex('#f97316')));
                _ribbonContextualGroup102.set_property_value(RibbonContextualGroup.IsActiveKey, DataContextBinding(_ribbonContextualGroup102, "HasSelection"));
                const _ribbonTab103 = new RibbonTab();
                _ribbonTab103.set_property_value(RibbonTab.HeaderKey, "Format");
                const _ribbonGroup104 = new RibbonGroup();
                _ribbonGroup104.set_property_value(RibbonGroup.HeaderKey, "Edit");
                const _ribbonButton105 = new RibbonButton();
                _ribbonButton105.set_property_value(RibbonButton.TextKey, "🗑 Delete");
                _ribbonButton105.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton105, "DeleteCommand"));
                _ribbonGroup104.AddChild(_ribbonButton105);
                const _ribbonButton106 = new RibbonButton();
                _ribbonButton106.set_property_value(RibbonButton.TextKey, "⎘ Duplicate");
                _ribbonButton106.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton106, "DuplicateCommand"));
                _ribbonGroup104.AddChild(_ribbonButton106);
                _ribbonTab103.AddChild(_ribbonGroup104);
                const _ribbonGroup107 = new RibbonGroup();
                _ribbonGroup107.set_property_value(RibbonGroup.HeaderKey, "Z-order");
                const _ribbonButton108 = new RibbonButton();
                _ribbonButton108.set_property_value(RibbonButton.TextKey, "Bring Front");
                _ribbonButton108.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton108, "BringFrontCommand"));
                _ribbonGroup107.AddChild(_ribbonButton108);
                const _ribbonButton109 = new RibbonButton();
                _ribbonButton109.set_property_value(RibbonButton.TextKey, "Send Back");
                _ribbonButton109.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton109, "SendBackCommand"));
                _ribbonGroup107.AddChild(_ribbonButton109);
                _ribbonTab103.AddChild(_ribbonGroup107);
                const _ribbonGroup110 = new RibbonGroup();
                _ribbonGroup110.set_property_value(RibbonGroup.HeaderKey, "Align");
                _ribbonGroup110.set_property_value(RibbonGroup.LaunchCommandKey, DataContextBinding(_ribbonGroup110, "AlignLeftCommand"));
                const _ribbonSmallButtonColumn111 = new RibbonSmallButtonColumn();
                const _ribbonButton112 = new RibbonButton();
                _ribbonButton112.set_property_value(RibbonButton.TextKey, "⬅ Left");
                _ribbonButton112.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton112, "AlignLeftCommand"));
                _ribbonSmallButtonColumn111.AddChild(_ribbonButton112);
                const _ribbonButton113 = new RibbonButton();
                _ribbonButton113.set_property_value(RibbonButton.TextKey, "⇔ Center");
                _ribbonButton113.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton113, "AlignCenterCommand"));
                _ribbonSmallButtonColumn111.AddChild(_ribbonButton113);
                const _ribbonButton114 = new RibbonButton();
                _ribbonButton114.set_property_value(RibbonButton.TextKey, "➡ Right");
                _ribbonButton114.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton114, "AlignRightCommand"));
                _ribbonSmallButtonColumn111.AddChild(_ribbonButton114);
                _ribbonGroup110.AddChild(_ribbonSmallButtonColumn111);
                const _ribbonSmallButtonColumn115 = new RibbonSmallButtonColumn();
                const _ribbonButton116 = new RibbonButton();
                _ribbonButton116.set_property_value(RibbonButton.TextKey, "⬆ Top");
                _ribbonButton116.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton116, "AlignTopCommand"));
                _ribbonSmallButtonColumn115.AddChild(_ribbonButton116);
                const _ribbonButton117 = new RibbonButton();
                _ribbonButton117.set_property_value(RibbonButton.TextKey, "↕ Middle");
                _ribbonButton117.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton117, "AlignMiddleCommand"));
                _ribbonSmallButtonColumn115.AddChild(_ribbonButton117);
                const _ribbonButton118 = new RibbonButton();
                _ribbonButton118.set_property_value(RibbonButton.TextKey, "⬇ Bottom");
                _ribbonButton118.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton118, "AlignBottomCommand"));
                _ribbonSmallButtonColumn115.AddChild(_ribbonButton118);
                _ribbonGroup110.AddChild(_ribbonSmallButtonColumn115);
                _ribbonTab103.AddChild(_ribbonGroup110);
                _ribbonContextualGroup102.AddChild(_ribbonTab103);
                _ribbon85.ContextualGroups.Add(_ribbonContextualGroup102);
                const _ribbonButton119 = new RibbonButton();
                _ribbonButton119.set_property_value(RibbonButton.TextKey, "💾");
                _ribbonButton119.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton119, "SaveCommand"));
                _ribbon85.QuickAccessItems.Add(_ribbonButton119);
                const _ribbonButton120 = new RibbonButton();
                _ribbonButton120.set_property_value(RibbonButton.TextKey, "↶");
                _ribbonButton120.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton120, "UndoCommand"));
                _ribbon85.QuickAccessItems.Add(_ribbonButton120);
                const _ribbonButton121 = new RibbonButton();
                _ribbonButton121.set_property_value(RibbonButton.TextKey, "↷");
                _ribbonButton121.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton121, "RedoCommand"));
                _ribbon85.QuickAccessItems.Add(_ribbonButton121);
                _border26.SetChild(_ribbon85);
                _dockPanel29.AddChild(_border26);
                _diagram27 = new Diagram();
                _diagram27.Name = "nodes";
                _diagram27.set_property_value(Diagram.ItemsSourceKey, DataContextBinding(_diagram27, "Nodes"));
                _diagram27.set_property_value(Diagram.ItemsPanelKey, _tmpl0);
                _diagram27.set_property_value(Diagram.SelectionModeKey, SelectionMode.Extended);
                _diagram27.set_property_value(Diagram.AllowMarqueeSelectionKey, true);
                _diagram27.set_property_value(Diagram.ReflectSelectionToItemsKey, true);
                _diagram27.set_property_value(Diagram.FocusableKey, true);
                _dockPanel29.AddChild(_diagram27);
                _border28.SetChild(_dockPanel29);
                return _border28;
            };
            const _tplSet122 = [new TargetedSetter(StackPanel, "Visibility", Visibility.Collapsed, "ClassicChrome"), new TargetedSetter(Border, "Visibility", Visibility.Visible, "RibbonChrome")];
            const _tplDataTrig123 = new TemplateDataTrigger("IsRibbonMode", true, _tplSet122);
            return new DataTemplate(_factory, CommandsVM, [], [_tplDataTrig123]);
        })();
        t.Set("CommandsTemplate", _tmpl24);
        return t;
    }
    get CommandsCanvasPanel() { return this.Resolve("CommandsCanvasPanel"); }
    set CommandsCanvasPanel(v) { this.Set("CommandsCanvasPanel", v); }
    get CommandsSelectedPen() { return this.Resolve("CommandsSelectedPen"); }
    set CommandsSelectedPen(v) { this.Set("CommandsSelectedPen", v); }
    get NodeContextMenu() { return this.Resolve("NodeContextMenu"); }
    set NodeContextMenu(v) { this.Set("NodeContextMenu", v); }
    get CommandsTemplate() { return this.Resolve("CommandsTemplate"); }
    set CommandsTemplate(v) { this.Set("CommandsTemplate", v); }
}
