import { ToggleButtonVM } from "./toggle-button-vm.mjs";
import { Border, ContentPresenter, ControlTemplate, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TargetedSetter, TemplatePropertyTrigger, TextBlock } from "@visualisation-sub/mural/Basic";
import { ToggleButton } from "@visualisation-sub/mural/framework/toggle-button.js";
import { DataContextBinding, DynamicResource, ResourceDictionary, Setter, SetterFactory, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontStyle, FontWeight } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = (() => {
        const _factory = (_templatedParent) => {
            const _border2 = new Border();
            _border2.Name = "PART_Border";
            _border2._set_property_value_by_name("BorderBrush", DynamicResource(_border2, "Outline"));
            _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
            _border2._set_property_value_by_name("CornerRadius", DynamicResource(_border2, "ShapeSmall"));
            _border2._set_property_value_by_name("Padding", new Thickness(16, 8, 16, 8));
            const _contentPresenter3 = new ContentPresenter();
            _border2.SetChild(_contentPresenter3);
            return _border2;
        };
        const _tplSet4 = [new TargetedSetter(Border, "Background", new SetterFactory((_t) => DynamicResource(_t, "Primary")), "PART_Border"), new TargetedSetter(Border, "BorderBrush", new SetterFactory((_t) => DynamicResource(_t, "PrimaryPress")), "PART_Border")];
        const _tplTrig5 = new TemplatePropertyTrigger(ToggleButton, "IsChecked", true, _tplSet4);
        return new ControlTemplate(_factory, [_tplTrig5]);
    })();
    _rd0.Set("ToggleChromeTemplate", _tmpl1);
    const _setter6 = new Setter(ToggleButton, "Template", _tmpl1);
    const _style7 = new Style(ToggleButton, [_setter6], undefined, [], []);
    _rd0.Set("StyleToggle", _style7);
    const _tmpl8 = new DataTemplate((_data) => {
        const _border9 = new Border();
        _border9._set_property_value_by_name("Background", DynamicResource(_border9, "Surface"));
        _border9._set_property_value_by_name("BorderBrush", DynamicResource(_border9, "OutlineVariant"));
        _border9._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel10 = new DockPanel();
        const _border11 = new Border();
        _border11._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border11._set_property_value_by_name("Background", DynamicResource(_border11, "Primary"));
        _border11._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock12 = new TextBlock();
        _textBlock12._set_property_value_by_name("Text", "ToggleButton — IsChecked flips on click; TwoWay binding keeps the VM in sync.");
        _textBlock12._set_property_value_by_name("FontSize", 15);
        _textBlock12._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock12._set_property_value_by_name("Foreground", DynamicResource(_textBlock12, "OnPrimary"));
        _border11.SetChild(_textBlock12);
        _dockPanel10.AddChild(_border11);
        const _stackPanel13 = new StackPanel();
        _stackPanel13._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel13._set_property_value_by_name("Margin", new Thickness(16, 16, 16, 16));
        const _stackPanel14 = new StackPanel();
        _stackPanel14._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel14._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
        const _toggleButton15 = new ToggleButton();
        _toggleButton15._set_property_value_by_name("Style", _style7);
        _toggleButton15._set_property_value_by_name("IsChecked", DataContextBinding(_toggleButton15, "IsBold"));
        _toggleButton15._set_property_value_by_name("Margin", new Thickness(0, 0, 8, 0));
        const _textBlock16 = new TextBlock();
        _textBlock16._set_property_value_by_name("Text", "B");
        _textBlock16._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock16._set_property_value_by_name("Foreground", DynamicResource(_textBlock16, "OnSurface"));
        _toggleButton15.Content = _textBlock16;
        _stackPanel14.AddChild(_toggleButton15);
        const _toggleButton17 = new ToggleButton();
        _toggleButton17._set_property_value_by_name("Style", _style7);
        _toggleButton17._set_property_value_by_name("IsChecked", DataContextBinding(_toggleButton17, "IsItalic"));
        _toggleButton17._set_property_value_by_name("Margin", new Thickness(0, 0, 8, 0));
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", "I");
        _textBlock18._set_property_value_by_name("FontStyle", FontStyle.Italic);
        _textBlock18._set_property_value_by_name("Foreground", DynamicResource(_textBlock18, "OnSurface"));
        _toggleButton17.Content = _textBlock18;
        _stackPanel14.AddChild(_toggleButton17);
        const _toggleButton19 = new ToggleButton();
        _toggleButton19._set_property_value_by_name("Style", _style7);
        _toggleButton19._set_property_value_by_name("IsChecked", DataContextBinding(_toggleButton19, "IsUnderline"));
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "U");
        _textBlock20._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock20._set_property_value_by_name("Foreground", DynamicResource(_textBlock20, "OnSurface"));
        _toggleButton19.Content = _textBlock20;
        _stackPanel14.AddChild(_toggleButton19);
        _stackPanel13.AddChild(_stackPanel14);
        const _border21 = new Border();
        _border21._set_property_value_by_name("Background", DynamicResource(_border21, "SurfaceContainerLow"));
        _border21._set_property_value_by_name("Padding", new Thickness(12, 12, 12, 12));
        _border21._set_property_value_by_name("BorderBrush", DynamicResource(_border21, "Outline"));
        _border21._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _stackPanel22 = new StackPanel();
        _stackPanel22._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _textBlock23 = new TextBlock();
        _textBlock23._set_property_value_by_name("Text", DataContextBinding(_textBlock23, "PreviewText"));
        _textBlock23._set_property_value_by_name("FontSize", 16);
        _textBlock23._set_property_value_by_name("Foreground", DynamicResource(_textBlock23, "OnSurface"));
        _stackPanel22.AddChild(_textBlock23);
        const _textBlock24 = new TextBlock();
        _textBlock24._set_property_value_by_name("Text", "(Bold / Italic / Underline DPs above drive this preview's chrome via TwoWay bindings.)");
        _textBlock24._set_property_value_by_name("FontSize", 11);
        _textBlock24._set_property_value_by_name("Foreground", DynamicResource(_textBlock24, "OnSurfaceVariant"));
        _textBlock24._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel22.AddChild(_textBlock24);
        _border21.SetChild(_stackPanel22);
        _stackPanel13.AddChild(_border21);
        _dockPanel10.AddChild(_stackPanel13);
        _border9.SetChild(_dockPanel10);
        return _border9;
    }, ToggleButtonVM);
    _rd0.Set("ToggleButtonTemplate", _tmpl8);
    return _rd0;
}
