import { ToggleButtonVM } from "./toggle-button-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Basic";
import { ToggleButton } from "@visualisation-sub/mural/framework/toggle-button.js";
import { Color, DataContextBinding, DynamicResource, PropertyTrigger, ResourceDictionary, Setter, SetterFactory, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontStyle, FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _setter1 = new Setter(ToggleButton, "Background", new SetterFactory((_t) => DynamicResource(_t, "Surface")));
    const _setter2 = new Setter(ToggleButton, "BorderBrush", new SolidColorBrush(Color.FromHex('#c4c4c4')));
    const _setter3 = new Setter(ToggleButton, "BorderThickness", new Thickness(1));
    const _setter4 = new Setter(ToggleButton, "Padding", new Thickness(16, 8, 16, 8));
    const _setter5 = new Setter(ToggleButton, "Background", new SetterFactory((_t) => DynamicResource(_t, "Primary")));
    const _setter6 = new Setter(ToggleButton, "BorderBrush", new SolidColorBrush(Color.FromHex('#0d47a1')));
    const _sArr7 = [_setter5, _setter6];
    const _trigger8 = new PropertyTrigger(ToggleButton, "IsChecked", true, _sArr7);
    const _style9 = new Style(ToggleButton, [_setter1, _setter2, _setter3, _setter4], undefined, [_trigger8], []);
    _rd0.Set("StyleToggle", _style9);
    const _tmpl10 = new DataTemplate((_data) => {
        const _border11 = new Border();
        _border11._set_property_value_by_name("Background", DynamicResource(_border11, "Surface"));
        _border11._set_property_value_by_name("BorderBrush", DynamicResource(_border11, "OutlineVariant"));
        _border11._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel12 = new DockPanel();
        const _border13 = new Border();
        _border13._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border13._set_property_value_by_name("Background", DynamicResource(_border13, "Primary"));
        _border13._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock14 = new TextBlock();
        _textBlock14._set_property_value_by_name("Text", "ToggleButton — IsChecked flips on click; TwoWay binding keeps the VM in sync.");
        _textBlock14._set_property_value_by_name("FontSize", 15);
        _textBlock14._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock14._set_property_value_by_name("Foreground", DynamicResource(_textBlock14, "Surface"));
        _border13.SetChild(_textBlock14);
        _dockPanel12.AddChild(_border13);
        const _stackPanel15 = new StackPanel();
        _stackPanel15._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel15._set_property_value_by_name("Margin", new Thickness(16, 16, 16, 16));
        const _stackPanel16 = new StackPanel();
        _stackPanel16._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel16._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
        const _toggleButton17 = new ToggleButton();
        _toggleButton17._set_property_value_by_name("Style", _style9);
        _toggleButton17._set_property_value_by_name("IsChecked", DataContextBinding(_toggleButton17, "IsBold"));
        _toggleButton17._set_property_value_by_name("Margin", new Thickness(0, 0, 8, 0));
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", "B");
        _textBlock18._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock18._set_property_value_by_name("Foreground", DynamicResource(_textBlock18, "OnSurface"));
        _toggleButton17.Content = _textBlock18;
        _stackPanel16.AddChild(_toggleButton17);
        const _toggleButton19 = new ToggleButton();
        _toggleButton19._set_property_value_by_name("Style", _style9);
        _toggleButton19._set_property_value_by_name("IsChecked", DataContextBinding(_toggleButton19, "IsItalic"));
        _toggleButton19._set_property_value_by_name("Margin", new Thickness(0, 0, 8, 0));
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "I");
        _textBlock20._set_property_value_by_name("FontStyle", FontStyle.Italic);
        _textBlock20._set_property_value_by_name("Foreground", DynamicResource(_textBlock20, "OnSurface"));
        _toggleButton19.Content = _textBlock20;
        _stackPanel16.AddChild(_toggleButton19);
        const _toggleButton21 = new ToggleButton();
        _toggleButton21._set_property_value_by_name("Style", _style9);
        _toggleButton21._set_property_value_by_name("IsChecked", DataContextBinding(_toggleButton21, "IsUnderline"));
        const _textBlock22 = new TextBlock();
        _textBlock22._set_property_value_by_name("Text", "U");
        _textBlock22._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock22._set_property_value_by_name("Foreground", DynamicResource(_textBlock22, "OnSurface"));
        _toggleButton21.Content = _textBlock22;
        _stackPanel16.AddChild(_toggleButton21);
        _stackPanel15.AddChild(_stackPanel16);
        const _border23 = new Border();
        _border23._set_property_value_by_name("Background", DynamicResource(_border23, "SurfaceContainerLow"));
        _border23._set_property_value_by_name("Padding", new Thickness(12, 12, 12, 12));
        _border23._set_property_value_by_name("BorderBrush", DynamicResource(_border23, "Outline"));
        _border23._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _stackPanel24 = new StackPanel();
        _stackPanel24._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _textBlock25 = new TextBlock();
        _textBlock25._set_property_value_by_name("Text", DataContextBinding(_textBlock25, "PreviewText"));
        _textBlock25._set_property_value_by_name("FontSize", 16);
        _textBlock25._set_property_value_by_name("Foreground", DynamicResource(_textBlock25, "OnSurface"));
        _stackPanel24.AddChild(_textBlock25);
        const _textBlock26 = new TextBlock();
        _textBlock26._set_property_value_by_name("Text", "(Bold / Italic / Underline DPs above drive this preview's chrome via TwoWay bindings.)");
        _textBlock26._set_property_value_by_name("FontSize", 11);
        _textBlock26._set_property_value_by_name("Foreground", DynamicResource(_textBlock26, "OnSurfaceVariant"));
        _textBlock26._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel24.AddChild(_textBlock26);
        _border23.SetChild(_stackPanel24);
        _stackPanel15.AddChild(_border23);
        _dockPanel12.AddChild(_stackPanel15);
        _border11.SetChild(_dockPanel12);
        return _border11;
    }, ToggleButtonVM);
    _rd0.Set("ToggleButtonTemplate", _tmpl10);
    return _rd0;
}
