#!/usr/bin/env python3
"""
Model Compiler — modeling_engine/Compiler/model_compiler.py

Resolves library imports transitively from the toolchain's `technology_library/`,
inlines resolved category and technology symbols, validates, builds a unified
typed `connectors:` block, and writes the compiled YAML.

Component IDs are globally unique. Authoring: dict form (YAML key is the id)
or list form (each entry is an object; `id:` optional, autogenerated from
`label` + `category` via slugification when missing).

Connector entries in the source `connectors:` block accept three shapes:
  - object form:  { from, to, type, ... }
  - pair form:    [a, b]   (shorthand for type: calls)
  - natural form: "X is enabled by Y"   (and other verb phrases)

Usage:
    # explicit source + output (preferred — used by toolchain/build.py):
    python3 modeling_engine/Compiler/model_compiler.py <source.arch.yaml> --output <out.compiled.yaml>

    # legacy convention (project-dir; resolves source under the dir, writes
    # output to <project>/output/<source>.compiled.yaml):
    python3 modeling_engine/Compiler/model_compiler.py <project-dir>
"""

from __future__ import annotations
import argparse
import re
import sys
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent.parent
LIB_ROOT = ROOT / "technology_library"

ARROW = "→"
CONNECTOR_TYPES = {"calls", "event", "consumes", "available-through", "enabled-by", "hosted-by"}
STEP_KIND_RE = re.compile(r"^\[\s*([a-z\-]+)\s*\]\s*")
SLUG_NON_ALNUM = re.compile(r"[^a-z0-9]+")

# Natural-language connector phrasings. Patterns are tried in order; longer
# multi-word phrases come first so they're not shadowed by shorter ones.
NATURAL_PATTERNS = [
    (re.compile(r"^(\S+)\s+is\s+available\s+through\s+(\S+)$", re.I), "available-through"),
    (re.compile(r"^(\S+)\s+is\s+enabled\s+by\s+(\S+)$",        re.I), "enabled-by"),
    (re.compile(r"^(\S+)\s+is\s+hosted\s+by\s+(\S+)$",         re.I), "hosted-by"),
    (re.compile(r"^(\S+)\s+sends\s+event\s+to\s+(\S+)$",       re.I), "event"),
    (re.compile(r"^(\S+)\s+publishes\s+to\s+(\S+)$",           re.I), "event"),
    (re.compile(r"^(\S+)\s+emits\s+to\s+(\S+)$",               re.I), "event"),
    (re.compile(r"^(\S+)\s+consumes\s+(\S+)$",                 re.I), "consumes"),
    (re.compile(r"^(\S+)\s+invokes\s+(\S+)$",                  re.I), "calls"),
    (re.compile(r"^(\S+)\s+calls\s+(\S+)$",                    re.I), "calls"),
]


def parse_natural_connector(s):
    s = s.strip()
    for rx, ctype in NATURAL_PATTERNS:
        m = rx.match(s)
        if m:
            return m.group(1), ctype, m.group(2)
    return None


def slugify(label, category=None):
    if isinstance(label, list):
        text = " ".join(str(p) for p in label)
    else:
        text = str(label)
    label_parts = [p for p in SLUG_NON_ALNUM.sub("-", text.lower()).strip("-").split("-") if p]
    if not category:
        return "-".join(label_parts)
    cat_parts = [p for p in str(category).lower().split("-") if p]
    seen = set(label_parts)
    merged = list(label_parts)
    for p in cat_parts:
        if p not in seen:
            merged.append(p)
            seen.add(p)
    return "-".join(merged)


def normalize_components(loc, comps, issues):
    def err(c, m): issues.append(("error", c, m))
    out = {}
    if comps is None:
        return out
    if isinstance(comps, dict):
        for cid, cdef in comps.items():
            if cid in out:
                err(f"components:{loc}:{cid}", "duplicate component id")
            out[cid] = cdef
        return out
    if isinstance(comps, list):
        for i, cdef in enumerate(comps):
            if not isinstance(cdef, dict):
                err(f"components:{loc}[{i}]", "entry must be an object")
                continue
            cid = cdef.get("id")
            if not cid:
                label = cdef.get("label")
                if label is None:
                    err(f"components:{loc}[{i}]", "no id and no label - cannot autogenerate id")
                    continue
                cid = slugify(label, cdef.get("category"))
                if not cid:
                    err(f"components:{loc}[{i}]", f"could not autogenerate valid id from label={label!r}")
                    continue
            if cid in out:
                err(f"components:{loc}:{cid}", "duplicate id (autogen collision?)")
            out[cid] = cdef
        return out
    err(f"components:{loc}", f"components must be dict or list, got {type(comps).__name__}")
    return out


def load_yaml(path):
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def resolve_imports(arch):
    categories, technologies, visited, in_progress = {}, {}, [], set()

    def visit(name):
        if name in visited:
            return
        if name in in_progress:
            raise RuntimeError(f"import cycle through library '{name}'")
        in_progress.add(name)
        lib_path = LIB_ROOT / name / "index.yaml"
        if not lib_path.exists():
            raise FileNotFoundError(f"library '{name}' not found at {lib_path}")
        lib = load_yaml(lib_path)
        for sub in lib.get("imports") or []:
            visit(sub)
        for cid, e in (lib.get("categories") or {}).items():
            categories.setdefault(cid, e)
        for tid, e in (lib.get("technologies") or {}).items():
            technologies.setdefault(tid, e)
        in_progress.discard(name)
        visited.append(name)

    for lib in arch.get("imports") or []:
        visit(lib)
    for cid, e in (arch.get("categories") or {}).items():
        categories[cid] = e
    for tid, e in (arch.get("custom-technologies") or {}).items():
        technologies[tid] = e
    return categories, technologies, visited


def parse_step(step):
    if ARROW not in step:
        return None
    src, rest = step.split(ARROW, 1)
    src = src.strip()
    rest = rest.lstrip()
    m = STEP_KIND_RE.match(rest)
    if m:
        return src, m.group(1), rest[m.end():].strip()
    return src, "calls", rest.strip()


def resolve_endpoint(ref, locations, actors, block_ids, components_by_id):
    ref = ref.strip()
    if ":" in ref:
        return False, "qualified `<location>:<id>` form is not supported (component IDs are globally unique)"
    if ref in actors:
        return True, "actor"
    if ref in block_ids:
        return True, "block"
    if ref in locations:
        return True, "location"
    if ref in components_by_id:
        return True, "component"
    return False, "ref matches no actor, block, location, or component"


EXPECTED_META_MODEL = "enterprise-architecture"


def validate(arch, categories, technologies):
    issues = []
    def err(c, m): issues.append(("error", c, m))
    def warn(c, m): issues.append(("warning", c, m))

    # Optional `meta.meta-model:` self-identifier. When set it must match
    # this compiler — same belt-and-braces check as the BPMN compiler does
    # for `bpmn`. Catches a `.arch.yaml` that came from the wrong template
    # or was renamed from another meta-model.
    meta = arch.get("meta") or {}
    declared_mm = meta.get("meta-model")
    if declared_mm is not None and declared_mm != EXPECTED_META_MODEL:
        err("meta:meta-model",
            f"declared meta-model '{declared_mm}' doesn't match the "
            f"architecture compiler (expected '{EXPECTED_META_MODEL}'). "
            f"Either fix the declaration or run this file through the "
            f"right compiler.")

    locations = set((arch.get("locations") or {}).keys())
    actors = set((arch.get("actors") or {}).keys())
    blocks = arch.get("blocks") or {}
    block_ids = set(blocks.keys())
    components_by_id = {}

    def add_component(cid, cdef, owner, location, ctx):
        if cid in components_by_id:
            other = components_by_id[cid]
            origin = ("block " + other[1]) if other[1] else ("location " + other[2])
            err(ctx, f"duplicate component id '{cid}' (also defined at {origin})")
            return
        if cid in actors:
            err(ctx, f"id '{cid}' collides with actor")
        if cid in block_ids:
            err(ctx, f"id '{cid}' collides with block")
        if cid in locations:
            err(ctx, f"id '{cid}' collides with location")
        components_by_id[cid] = (cdef, owner, location)

    for loc, comps in (arch.get("components") or {}).items():
        if loc not in locations:
            err(f"components:{loc}", f"location '{loc}' not declared")
            continue
        for cid, cdef in normalize_components(loc, comps, issues).items():
            add_component(cid, cdef, None, loc, f"components:{loc}:{cid}")

    for bid, bdef in blocks.items():
        bloc = bdef.get("in")
        if bloc not in locations:
            err(f"blocks:{bid}", f"in: '{bloc}' is not a declared location")
            continue
        for cid, cdef in normalize_components(f"blocks:{bid}", bdef.get("components"), issues).items():
            add_component(cid, cdef, bid, bloc, f"blocks:{bid}:components:{cid}")

    for cid, (entry, owner, loc) in components_by_id.items():
        ctx = f"blocks:{owner}:components:{cid}" if owner else f"components:{loc}:{cid}"
        cat = entry.get("category")
        if not cat:
            err(ctx, "missing category:")
        elif cat not in categories:
            err(ctx, f"category '{cat}' not in resolved registry")
        impl_by = entry.get("implemented-by") or []
        if not impl_by:
            warn(ctx, "no implemented-by - component has no technology binding")
        for tid in impl_by:
            if tid not in technologies:
                err(ctx, f"implemented-by '{tid}' not in resolved registry")
                continue
            tech = technologies[tid]
            avail = tech.get("available-in") or []
            if loc not in avail:
                err(ctx, f"location '{loc}' not in {tid}.available-in={avail}")
            applic = tech.get("applicable-to") or []
            if cat and cat not in applic:
                err(ctx, f"category '{cat}' not in {tid}.applicable-to={applic}")
        for old in ("enabled-by", "hosted-by", "consumes", "available-through"):
            if old in entry:
                err(ctx, f"'{old}' is not a component property - express as a connector entry")

    return issues, components_by_id, locations, actors, block_ids


def _normalize_sequence_entry(entry):
    """A sequence list entry can be either the wrapped form
    `{ sequence: { Title, Entry Point, steps } }` or the bare form
    `{ Title, Entry Point, steps }`. Lower-snake-case keys (`title`,
    `entry-point`) are also accepted. Returns the inner dict or None."""
    if not isinstance(entry, dict):
        return None
    inner = entry.get("sequence") if "sequence" in entry else entry
    return inner if isinstance(inner, dict) else None


def _sequence_field(seq, *keys):
    """Read a per-sequence field, accepting the casing/spacing the user
    authored and the lower-snake-case alternates."""
    for k in keys:
        if k in seq:
            return seq[k]
    return None


def _slug_sequence_id(title, fallback_idx):
    """Stable per-scenario identifier for a sequence — used for connector
    metadata so consumers (viewer, slides) can group connectors by sequence
    without reading the title back. Falls back to `seq-<idx>` for untitled
    sequences."""
    if isinstance(title, str) and title.strip():
        slug = SLUG_NON_ALNUM.sub("-", title.lower()).strip("-")
        if slug:
            return slug
    return f"seq-{fallback_idx + 1}"


def build_connectors(arch, issues, locations, actors, block_ids, components_by_id):
    def err(c, m): issues.append(("error", c, m))
    out = []

    for sid, sdef in (arch.get("scenarios") or {}).items():
        sequences = sdef.get("sequences") if isinstance(sdef, dict) else None
        if not sequences:
            err(f"scenarios:{sid}", "no sequences declared (expected `sequences:` list)")
            continue
        if not isinstance(sequences, list):
            err(f"scenarios:{sid}:sequences",
                f"must be a list, got {type(sequences).__name__}")
            continue

        seen_seq_ids = {}
        for j, raw_seq in enumerate(sequences):
            sctx = f"scenarios:{sid}:sequences[{j}]"
            seq = _normalize_sequence_entry(raw_seq)
            if seq is None:
                err(sctx, f"sequence entry must be an object (or `sequence:` wrapper), got {raw_seq!r}")
                continue

            title       = _sequence_field(seq, "Title", "title")
            entry_point = _sequence_field(seq, "Entry Point", "entry-point", "entryPoint")
            steps       = _sequence_field(seq, "steps")

            seq_id = _slug_sequence_id(title, j)
            # Disambiguate slug collisions within the same scenario.
            if seq_id in seen_seq_ids:
                seen_seq_ids[seq_id] += 1
                seq_id = f"{seq_id}-{seen_seq_ids[seq_id]}"
            else:
                seen_seq_ids[seq_id] = 1

            if entry_point is None:
                err(sctx, "missing `Entry Point:`")
            elif isinstance(entry_point, str):
                ok, why = resolve_endpoint(entry_point, locations, actors, block_ids, components_by_id)
                if not ok:
                    err(sctx + ":Entry Point", f"'{entry_point}': {why}")
            else:
                err(sctx + ":Entry Point", f"must be a bare id string, got {entry_point!r}")

            if steps is None:
                err(sctx, "missing `steps:`")
                continue
            if not isinstance(steps, list):
                err(sctx + ":steps", f"must be a list, got {type(steps).__name__}")
                continue

            for i, step in enumerate(steps):
                ictx = f"{sctx}:steps[{i}]"
                if not isinstance(step, str):
                    err(ictx, f"step is not a string: {step!r}")
                    continue
                parsed = parse_step(step)
                if parsed is None:
                    err(ictx, f"step missing arrow: {step!r}")
                    continue
                src, kind, dst = parsed
                if kind not in CONNECTOR_TYPES:
                    err(ictx, f"unknown connector type '{kind}'")
                    continue
                for endpoint, lbl in ((src, "src"), (dst, "dst")):
                    ok, why = resolve_endpoint(endpoint, locations, actors, block_ids, components_by_id)
                    if not ok:
                        err(ictx, f"{lbl} '{endpoint}': {why}")
                out.append({"from": src, "to": dst, "type": kind,
                            "source": "scenario-step",
                            "scenario": sid, "sequence": seq_id, "step": i})

    for i, entry in enumerate(arch.get("connectors") or []):
        ictx = f"connectors[{i}]"
        if isinstance(entry, list):
            if len(entry) != 2:
                err(ictx, f"pair shorthand expects [src, dst], got {entry!r}")
                continue
            src, dst, ctype, extra = entry[0], entry[1], "calls", {}
        elif isinstance(entry, dict):
            src = entry.get("from")
            dst = entry.get("to")
            ctype = entry.get("type", "calls")
            if src is None or dst is None:
                err(ictx, "object form requires `from:` and `to:`")
                continue
            extra = {k: v for k, v in entry.items() if k not in ("from", "to", "type")}
        elif isinstance(entry, str):
            parsed = parse_natural_connector(entry)
            if parsed is None:
                err(ictx, f"could not parse natural-language connector: {entry!r}")
                continue
            src, ctype, dst = parsed
            extra = {"natural": entry}
        else:
            err(ictx, f"entry must be pair, object, or string, got {type(entry).__name__}")
            continue
        if ctype not in CONNECTOR_TYPES:
            err(ictx, f"unknown connector type '{ctype}'")
            continue
        if not isinstance(src, str) or not isinstance(dst, str):
            err(ictx, "endpoints must be strings")
            continue
        for endpoint, lbl in ((src, "from"), (dst, "to")):
            ok, why = resolve_endpoint(endpoint, locations, actors, block_ids, components_by_id)
            if not ok:
                err(ictx, f"{lbl} '{endpoint}': {why}")
        rec = {"from": src, "to": dst, "type": ctype, "source": "connectors"}
        rec.update(extra)
        out.append(rec)

    return out


def smell_check(connectors, issues):
    standalone_calls = [c for c in connectors if c["type"] == "calls" and c["source"] == "connectors"]
    if len(standalone_calls) >= 5:
        issues.append(("warning", "connectors",
                       f"{len(standalone_calls)} standalone `calls` entries - design smell"))


def build_compiled(arch, categories, technologies, connectors):
    out = {}
    if "meta" in arch:
        out["meta"] = arch["meta"]
    for k in ("locations", "actors"):
        if k in arch:
            out[k] = arch[k]
    out["categories"] = categories
    out["technologies"] = technologies
    if "scenarios" in arch:
        out["scenarios"] = arch["scenarios"]
    def with_explicit_id(comps_dict):
        return {cid: {"id": cid, **{k: v for k, v in cdef.items() if k != "id"}}
                for cid, cdef in comps_dict.items()}
    if "blocks" in arch:
        blocks_out = {}
        for bid, bdef in (arch["blocks"] or {}).items():
            bdef_out = dict(bdef)
            normalised = normalize_components(f"blocks:{bid}", bdef.get("components"), [])
            bdef_out["components"] = with_explicit_id(normalised)
            blocks_out[bid] = bdef_out
        out["blocks"] = blocks_out
    if "components" in arch:
        comps_out = {}
        for loc, comps in (arch["components"] or {}).items():
            comps_out[loc] = with_explicit_id(normalize_components(loc, comps, []))
        out["components"] = comps_out
    out["connectors"] = connectors
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("source",
                        help="Path to <model>.arch.yaml or to a project directory "
                             "(legacy form — the source is resolved as <dir>/<dir>.arch.yaml).")
    parser.add_argument("--output",
                        help="Path to write the compiled YAML. Default for the legacy "
                             "form is <project>/output/<source-stem>.compiled.yaml; "
                             "with an explicit source file, --output is required unless "
                             "the file lives next to a sibling `output/` directory.")
    args = parser.parse_args()

    src_arg = Path(args.source).resolve()
    if src_arg.is_dir():
        project = src_arg
        source  = project / f"{project.name}.arch.yaml"
    else:
        source  = src_arg
        project = source.parent
    if not source.exists():
        print(f"ERROR: source not found at {source}", file=sys.stderr)
        return 2
    output = (Path(args.output).resolve() if args.output
              else project / "output" / f"{source.stem}.compiled.yaml")

    arch = load_yaml(source)
    try:
        categories, technologies, libs = resolve_imports(arch)
    except (FileNotFoundError, RuntimeError) as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    issues, components_by_id, locations, actors, block_ids = validate(arch, categories, technologies)
    connectors = build_connectors(arch, issues, locations, actors, block_ids, components_by_id)
    smell_check(connectors, issues)

    compiled = build_compiled(arch, categories, technologies, connectors)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w", encoding="utf-8") as f:
        f.write("# Compiled architecture - generated by model_compiler.py. Do not edit by hand.\n")
        f.write(f"# Project:          {project.name}\n")
        f.write(f"# Source:           {source.name}\n")
        f.write(f"# Imports resolved: {', '.join(libs)}\n")
        f.write(f"# Categories:       {len(categories)} resolved\n")
        f.write(f"# Technologies:     {len(technologies)} resolved\n")
        f.write(f"# Components:       {len(components_by_id)} (globally unique)\n")
        f.write(f"# Connectors:       {len(connectors)} unified\n\n")
        yaml.safe_dump(compiled, f, sort_keys=False, default_flow_style=False,
                       allow_unicode=True, width=120)

    errors = [i for i in issues if i[0] == "error"]
    warnings = [i for i in issues if i[0] == "warning"]
    for sev, ctx, msg in issues:
        marker = "E" if sev == "error" else "W"
        print(f"  [{marker}] {ctx}: {msg}")
    if issues:
        print()
    try:
        wrote = output.relative_to(Path.cwd())
    except ValueError:
        wrote = output
    print(f"Wrote: {wrote}")
    print(f"Imports: {' -> '.join(libs)}")
    print(f"Categories: {len(categories)}    Technologies: {len(technologies)}    Components: {len(components_by_id)}    Connectors: {len(connectors)}")
    print(f"Errors: {len(errors)}    Warnings: {len(warnings)}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
