import { Border, Button, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { Application, BeginStoryboardAction, Color, DoubleAnimation, EventTrigger, NameScope, Storyboard, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#e2e8f0')));
    _rd1.Set("primary", new SolidColorBrush(Color.FromHex('#1976d2')));
    _rd1.Set("primInk", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("hint", new SolidColorBrush(Color.FromHex('#6b7280')));
    const _act3 = new BeginStoryboardAction((_target) => {
        const _sb2 = new Storyboard();
        _sb2.Add(_target, "Width", new DoubleAnimation({ From: 80, To: 240, Duration: 400 }));
        return _sb2;
    });
    const _evt4 = new EventTrigger("Click", [_act3]);
    const _style5 = new Style(Button, [], undefined, [], [], [_evt4]);
    _rd1.Set(Button, _style5);
    const _border6 = new Border();
    _border6.SetNameScope(new NameScope());
    _border6.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border6.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border6.set_property_value("BorderThickness", new Thickness(1));
    const _dockPanel7 = new DockPanel();
    const _border8 = new Border();
    _border8.set_property_value(DockPanel, "Dock", "Top");
    _border8.set_property_value("Background", Application.current.Resources.Resolve("primary"));
    _border8.set_property_value("Padding", new Thickness(16, 12, 16, 12));
    const _textBlock9 = new TextBlock();
    _textBlock9.set_property_value("Text", "Declarative animation — on Click { BeginStoryboard { ... } }");
    _textBlock9.set_property_value("FontSize", 15);
    _textBlock9.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock9.set_property_value("Foreground", Application.current.Resources.Resolve("primInk"));
    _border8.SetChild(_textBlock9);
    _dockPanel7.AddChild(_border8);
    const _stackPanel10 = new StackPanel();
    _stackPanel10.set_property_value("Orientation", Orientation.Vertical);
    _stackPanel10.set_property_value("Margin", new Thickness(20, 24, 20, 20));
    const _textBlock11 = new TextBlock();
    _textBlock11.set_property_value("Text", "Click any Button. The style's EventTrigger animates the Button's own Width from 80 to 240 over 400 ms — no host-side handler wired.");
    _textBlock11.set_property_value("FontSize", 12);
    _textBlock11.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock11.set_property_value("Margin", new Thickness(0, 0, 0, 16));
    _stackPanel10.AddChild(_textBlock11);
    const _stackPanel12 = new StackPanel();
    _stackPanel12.set_property_value("Orientation", Orientation.Vertical);
    const _button13 = new Button();
    _button13.set_property_value("Width", 80);
    _button13.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    const _textBlock14 = new TextBlock();
    _textBlock14.set_property_value("Text", "Slide A");
    _button13.Content = _textBlock14;
    _stackPanel12.AddChild(_button13);
    const _button15 = new Button();
    _button15.set_property_value("Width", 80);
    _button15.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    const _textBlock16 = new TextBlock();
    _textBlock16.set_property_value("Text", "Slide B");
    _button15.Content = _textBlock16;
    _stackPanel12.AddChild(_button15);
    const _button17 = new Button();
    _button17.set_property_value("Width", 80);
    _button17.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    const _textBlock18 = new TextBlock();
    _textBlock18.set_property_value("Text", "Slide C");
    _button17.Content = _textBlock18;
    _stackPanel12.AddChild(_button17);
    _stackPanel10.AddChild(_stackPanel12);
    const _textBlock19 = new TextBlock();
    _textBlock19.set_property_value("Text", "Each Button carries its own animation instance — clicking them simultaneously plays independent storyboards (each baseline-captures From=80 at fire time).");
    _textBlock19.set_property_value("FontSize", 11);
    _textBlock19.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock19.set_property_value("Margin", new Thickness(0, 16, 0, 0));
    _stackPanel10.AddChild(_textBlock19);
    _dockPanel7.AddChild(_stackPanel10);
    _border6.SetChild(_dockPanel7);
    _rd1.Root = _border6;
    return _app0;
})();
