import { Border, Button, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { Application, BeginStoryboardAction, Color, DoubleAnimation, EventTrigger, NameScope, PropertyTrigger, Storyboard, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#e2e8f0')));
    _rd1.Set("primary", new SolidColorBrush(Color.FromHex('#1976d2')));
    _rd1.Set("primInk", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("hint", new SolidColorBrush(Color.FromHex('#6b7280')));
    _rd1.Set("accent", new SolidColorBrush(Color.FromHex('#ff9800')));
    const _act3 = new BeginStoryboardAction((_target) => {
        const _sb2 = new Storyboard();
        _sb2.Add(_target, "Width", new DoubleAnimation({ From: 60, To: 140, Duration: 500 }));
        return _sb2;
    });
    const _evt4 = new EventTrigger("Loaded", [_act3]);
    const _act6 = new BeginStoryboardAction((_target) => {
        const _sb5 = new Storyboard();
        _sb5.Add((_target.FindName("banner") ?? _target), "Width", new DoubleAnimation({ From: 80, To: 320, Duration: 500 }));
        return _sb5;
    });
    const _evt7 = new EventTrigger("Click", [_act6]);
    const _act9 = new BeginStoryboardAction((_target) => {
        const _sb8 = new Storyboard();
        _sb8.Add(_target, "Height", new DoubleAnimation({ To: 36, Duration: 180 }));
        return _sb8;
    });
    const _act11 = new BeginStoryboardAction((_target) => {
        const _sb10 = new Storyboard();
        _sb10.Add(_target, "Height", new DoubleAnimation({ To: 28, Duration: 180 }));
        return _sb10;
    });
    const _sArr12 = [];
    const _enter13 = [_act9];
    const _exit14 = [_act11];
    const _trigger15 = new PropertyTrigger(Button, "IsMouseOver", true, _sArr12, _enter13, _exit14);
    const _style16 = new Style(Button, [], undefined, [_trigger15], [], [_evt4, _evt7]);
    _rd1.Set(Button, _style16);
    const _border17 = new Border();
    _border17.SetNameScope(new NameScope());
    _border17.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border17.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border17.set_property_value("BorderThickness", new Thickness(1));
    const _dockPanel18 = new DockPanel();
    const _border19 = new Border();
    _border19.set_property_value(DockPanel, "Dock", "Top");
    _border19.set_property_value("Background", Application.current.Resources.Resolve("primary"));
    _border19.set_property_value("Padding", new Thickness(16, 12, 16, 12));
    const _textBlock20 = new TextBlock();
    _textBlock20.set_property_value("Text", "Trigger actions — enter/exit, Loaded, TargetName");
    _textBlock20.set_property_value("FontSize", 15);
    _textBlock20.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock20.set_property_value("Foreground", Application.current.Resources.Resolve("primInk"));
    _border19.SetChild(_textBlock20);
    _dockPanel18.AddChild(_border19);
    const _stackPanel21 = new StackPanel();
    _stackPanel21.set_property_value("Orientation", Orientation.Vertical);
    _stackPanel21.set_property_value("Margin", new Thickness(20, 24, 20, 20));
    const _stackPanel22 = new StackPanel();
    _stackPanel22.set_property_value("Orientation", Orientation.Vertical);
    _stackPanel22.set_property_value("Margin", new Thickness(0, 0, 0, 28));
    const _textBlock23 = new TextBlock();
    _textBlock23.set_property_value("Text", "Hover an entry — `when(IsMouseOver) { on enter / on exit }` drives Height.");
    _textBlock23.set_property_value("FontSize", 12);
    _textBlock23.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock23.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    _stackPanel22.AddChild(_textBlock23);
    const _stackPanel24 = new StackPanel();
    _stackPanel24.set_property_value("Orientation", Orientation.Vertical);
    const _button25 = new Button();
    _button25.set_property_value("Height", 28);
    _button25.set_property_value("Margin", new Thickness(0, 0, 0, 6));
    const _textBlock26 = new TextBlock();
    _textBlock26.set_property_value("Text", "Hover me");
    _button25.Content = _textBlock26;
    _stackPanel24.AddChild(_button25);
    const _button27 = new Button();
    _button27.set_property_value("Height", 28);
    _button27.set_property_value("Margin", new Thickness(0, 0, 0, 6));
    const _textBlock28 = new TextBlock();
    _textBlock28.set_property_value("Text", "Hover me too");
    _button27.Content = _textBlock28;
    _stackPanel24.AddChild(_button27);
    const _button29 = new Button();
    _button29.set_property_value("Height", 28);
    _button29.set_property_value("Margin", new Thickness(0, 0, 0, 6));
    const _textBlock30 = new TextBlock();
    _textBlock30.set_property_value("Text", "And me");
    _button29.Content = _textBlock30;
    _stackPanel24.AddChild(_button29);
    _stackPanel22.AddChild(_stackPanel24);
    const _textBlock31 = new TextBlock();
    _textBlock31.set_property_value("Text", "On first mount the same buttons run the Loaded storyboard — Width grows from 60 to 140.");
    _textBlock31.set_property_value("FontSize", 11);
    _textBlock31.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock31.set_property_value("Margin", new Thickness(0, 12, 0, 0));
    _stackPanel22.AddChild(_textBlock31);
    _stackPanel21.AddChild(_stackPanel22);
    const _stackPanel32 = new StackPanel();
    _stackPanel32.set_property_value("Orientation", Orientation.Vertical);
    const _textBlock33 = new TextBlock();
    _textBlock33.set_property_value("Text", "`TargetName=banner` redirects the storyboard target to the named sibling Border.");
    _textBlock33.set_property_value("FontSize", 12);
    _textBlock33.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock33.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    _stackPanel32.AddChild(_textBlock33);
    const _button34 = new Button();
    _button34.Name = "bannerBtn";
    _border17.nameScope.Register("bannerBtn", _button34);
    _button34.set_property_value("Width", 200);
    _button34.set_property_value("Height", 28);
    _button34.set_property_value("Margin", new Thickness(0, 0, 0, 12));
    const _textBlock35 = new TextBlock();
    _textBlock35.set_property_value("Text", "Animate banner");
    _button34.Content = _textBlock35;
    _stackPanel32.AddChild(_button34);
    const _border36 = new Border();
    _border36.Name = "banner";
    _border17.nameScope.Register("banner", _border36);
    _border36.set_property_value("Background", Application.current.Resources.Resolve("accent"));
    _border36.set_property_value("Width", 80);
    _border36.set_property_value("Height", 20);
    _border36.set_property_value("CornerRadius", 4);
    _stackPanel32.AddChild(_border36);
    _stackPanel21.AddChild(_stackPanel32);
    _dockPanel18.AddChild(_stackPanel21);
    _border17.SetChild(_dockPanel18);
    _rd1.Root = _border17;
    return _app0;
})();
