import { Border, Button, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { Application, BeginStoryboardAction, Color, DoubleAnimation, EventTrigger, NameScope, PauseStoryboardAction, PropertyTrigger, ResumeStoryboardAction, StopStoryboardAction, Storyboard, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#e2e8f0')));
    _rd1.Set("primary", new SolidColorBrush(Color.FromHex('#1976d2')));
    _rd1.Set("primInk", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("hint", new SolidColorBrush(Color.FromHex('#6b7280')));
    const _act3 = new BeginStoryboardAction((_target) => {
        const _sb2 = new Storyboard();
        _sb2.Add(_target, "Width", new DoubleAnimation({ From: 80, To: 240, Duration: 800, AutoReverse: true, RepeatBehavior: Infinity }));
        return _sb2;
    }, "loop");
    const _evt4 = new EventTrigger("Loaded", [_act3]);
    const _act5 = new PauseStoryboardAction("loop");
    const _act6 = new ResumeStoryboardAction("loop");
    const _sArr7 = [];
    const _enter8 = [_act5];
    const _exit9 = [_act6];
    const _trigger10 = new PropertyTrigger(Button, "IsMouseOver", true, _sArr7, _enter8, _exit9);
    const _act11 = new StopStoryboardAction("loop");
    const _evt12 = new EventTrigger("Click", [_act11]);
    const _style13 = new Style(Button, [], undefined, [_trigger10], [], [_evt4, _evt12]);
    _rd1.Set(Button, _style13);
    const _border14 = new Border();
    _border14.SetNameScope(new NameScope());
    _border14.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border14.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border14.set_property_value("BorderThickness", new Thickness(1));
    const _dockPanel15 = new DockPanel();
    const _border16 = new Border();
    _border16.set_property_value(DockPanel, "Dock", "Top");
    _border16.set_property_value("Background", Application.current.Resources.Resolve("primary"));
    _border16.set_property_value("Padding", new Thickness(16, 12, 16, 12));
    const _textBlock17 = new TextBlock();
    _textBlock17.set_property_value("Text", "Named storyboards — Begin / Pause / Resume / Stop");
    _textBlock17.set_property_value("FontSize", 15);
    _textBlock17.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock17.set_property_value("Foreground", Application.current.Resources.Resolve("primInk"));
    _border16.SetChild(_textBlock17);
    _dockPanel15.AddChild(_border16);
    const _stackPanel18 = new StackPanel();
    _stackPanel18.set_property_value("Orientation", Orientation.Vertical);
    _stackPanel18.set_property_value("Margin", new Thickness(20, 24, 20, 20));
    const _textBlock19 = new TextBlock();
    _textBlock19.set_property_value("Text", "Each button starts a looping Width animation on Loaded. Hover pauses; un-hover resumes; click stops for good.");
    _textBlock19.set_property_value("FontSize", 12);
    _textBlock19.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock19.set_property_value("Margin", new Thickness(0, 0, 0, 16));
    _stackPanel18.AddChild(_textBlock19);
    const _stackPanel20 = new StackPanel();
    _stackPanel20.set_property_value("Orientation", Orientation.Vertical);
    const _button21 = new Button();
    _button21.set_property_value("Height", 28);
    _button21.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    const _textBlock22 = new TextBlock();
    _textBlock22.set_property_value("Text", "Loop A");
    _button21.Content = _textBlock22;
    _stackPanel20.AddChild(_button21);
    const _button23 = new Button();
    _button23.set_property_value("Height", 28);
    _button23.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    const _textBlock24 = new TextBlock();
    _textBlock24.set_property_value("Text", "Loop B");
    _button23.Content = _textBlock24;
    _stackPanel20.AddChild(_button23);
    const _button25 = new Button();
    _button25.set_property_value("Height", 28);
    _button25.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    const _textBlock26 = new TextBlock();
    _textBlock26.set_property_value("Text", "Loop C");
    _button25.Content = _textBlock26;
    _stackPanel20.AddChild(_button25);
    _stackPanel18.AddChild(_stackPanel20);
    const _textBlock27 = new TextBlock();
    _textBlock27.set_property_value("Text", "The named registry is per-Visual — pausing Loop A doesn't pause Loop B or C.");
    _textBlock27.set_property_value("FontSize", 11);
    _textBlock27.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock27.set_property_value("Margin", new Thickness(0, 16, 0, 0));
    _stackPanel18.AddChild(_textBlock27);
    _dockPanel15.AddChild(_stackPanel18);
    _border14.SetChild(_dockPanel15);
    _rd1.Root = _border14;
    return _app0;
})();
