import { Border, Button, Canvas, ComboBox, TextBlock, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Application, Color, DataContextBinding, MultiBinding, NameScope, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("ink", new SolidColorBrush(Color.FromHex('#1f2937')));
    _rd1.Set("hint", new SolidColorBrush(Color.FromHex('#6b7280')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#e2e8f0')));
    _rd1.Set("accent", new SolidColorBrush(Color.FromHex('#1976d2')));
    const _border2 = new Border();
    _border2.SetNameScope(new NameScope());
    _border2.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border2.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border2.set_property_value("BorderThickness", new Thickness(1));
    const _canvas3 = new Canvas();
    const _textBlock4 = new TextBlock();
    _textBlock4.set_property_value(Canvas, "Left", 24);
    _textBlock4.set_property_value(Canvas, "Top", 20);
    _textBlock4.set_property_value("FontSize", 14);
    _textBlock4.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock4.set_property_value("Text", "Counter:");
    _canvas3.AddChild(_textBlock4);
    const _textBlock5 = new TextBlock();
    _textBlock5.set_property_value(Canvas, "Left", 24);
    _textBlock5.set_property_value(Canvas, "Top", 40);
    _textBlock5.set_property_value("FontSize", 42);
    _textBlock5.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock5.set_property_value("Foreground", Application.current.Resources.Resolve("accent"));
    _textBlock5.set_property_value("Text", MultiBinding(_textBlock5, ["Count"], (_p0) => ( String(_p0) )));
    _canvas3.AddChild(_textBlock5);
    const _textBlock6 = new TextBlock();
    _textBlock6.set_property_value(Canvas, "Left", 170);
    _textBlock6.set_property_value(Canvas, "Top", 124);
    _textBlock6.set_property_value("FontSize", 12);
    _textBlock6.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock6.set_property_value("Text", "Step:");
    _canvas3.AddChild(_textBlock6);
    const _comboBox7 = new ComboBox();
    _comboBox7.set_property_value(Canvas, "Left", 170);
    _comboBox7.set_property_value(Canvas, "Top", 140);
    _comboBox7.set_property_value("Width", 164);
    _comboBox7.set_property_value("Items", DataContextBinding(_comboBox7, "Steps"));
    _comboBox7.set_property_value("SelectedItem", DataContextBinding(_comboBox7, "Step"));
    _canvas3.AddChild(_comboBox7);
    const _button8 = new Button();
    _button8.set_property_value(Canvas, "Left", 24);
    _button8.set_property_value(Canvas, "Top", 140);
    _button8.set_property_value("Width", 80);
    _button8.set_property_value("Command", DataContextBinding(_button8, "Increment"));
    const _textBlock9 = new TextBlock();
    _textBlock9.set_property_value("Text", "+ Step");
    _button8.Content = _textBlock9;
    _canvas3.AddChild(_button8);
    const _button10 = new Button();
    _button10.set_property_value(Canvas, "Left", 24);
    _button10.set_property_value(Canvas, "Top", 190);
    _button10.set_property_value("Width", 80);
    _button10.set_property_value("Command", DataContextBinding(_button10, "Reset"));
    const _textBlock11 = new TextBlock();
    _textBlock11.set_property_value("Text", "Reset");
    _button10.Content = _textBlock11;
    _canvas3.AddChild(_button10);
    const _textBlock12 = new TextBlock();
    _textBlock12.set_property_value(Canvas, "Left", 24);
    _textBlock12.set_property_value(Canvas, "Top", 232);
    _textBlock12.set_property_value("Width", 312);
    _textBlock12.set_property_value("FontSize", 12);
    _textBlock12.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock12.set_property_value("TextWrapping", TextWrapping.Wrap);
    _textBlock12.set_property_value("Text", "The ComboBox sets Step. Increment adds Step to Count and stops at 10. Reset always works.");
    _canvas3.AddChild(_textBlock12);
    _border2.SetChild(_canvas3);
    _rd1.Root = _border2;
    return _app0;
})();
