import { Border, Button, Canvas, ComboBox, TextBlock, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Application, Color, DataContextBinding, MultiBinding, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("ink", new SolidColorBrush(Color.FromHex('#1f2937')));
    _rd1.Set("hint", new SolidColorBrush(Color.FromHex('#6b7280')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#e2e8f0')));
    _rd1.Set("accent", new SolidColorBrush(Color.FromHex('#1976d2')));
    const _canvas2 = new Canvas();
    const _border3 = new Border();
    _border3.set_property_value(Canvas, "Left", 50);
    _border3.set_property_value(Canvas, "Top", 40);
    _border3.set_property_value("Width", 360);
    _border3.set_property_value("Height", 280);
    _border3.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border3.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border3.set_property_value("BorderThickness", new Thickness(1));
    _border3.set_property_value("CornerRadius", 8);
    const _canvas4 = new Canvas();
    const _textBlock5 = new TextBlock();
    _textBlock5.set_property_value(Canvas, "Left", 24);
    _textBlock5.set_property_value(Canvas, "Top", 20);
    _textBlock5.set_property_value("FontSize", 14);
    _textBlock5.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock5.set_property_value("Text", "Counter:");
    _canvas4.AddChild(_textBlock5);
    const _textBlock6 = new TextBlock();
    _textBlock6.set_property_value(Canvas, "Left", 24);
    _textBlock6.set_property_value(Canvas, "Top", 40);
    _textBlock6.set_property_value("FontSize", 42);
    _textBlock6.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock6.set_property_value("Foreground", Application.current.Resources.Resolve("accent"));
    _textBlock6.set_property_value("Text", MultiBinding(_textBlock6, ["Count"], (_p0) => ( String(_p0) )));
    _canvas4.AddChild(_textBlock6);
    const _textBlock7 = new TextBlock();
    _textBlock7.set_property_value(Canvas, "Left", 170);
    _textBlock7.set_property_value(Canvas, "Top", 124);
    _textBlock7.set_property_value("FontSize", 12);
    _textBlock7.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock7.set_property_value("Text", "Step:");
    _canvas4.AddChild(_textBlock7);
    const _comboBox8 = new ComboBox();
    _comboBox8.set_property_value(Canvas, "Left", 170);
    _comboBox8.set_property_value(Canvas, "Top", 140);
    _comboBox8.set_property_value("Width", 164);
    _comboBox8.set_property_value("Items", DataContextBinding(_comboBox8, "Steps"));
    _comboBox8.set_property_value("SelectedItem", DataContextBinding(_comboBox8, "Step"));
    _canvas4.AddChild(_comboBox8);
    const _button9 = new Button();
    _button9.set_property_value(Canvas, "Left", 24);
    _button9.set_property_value(Canvas, "Top", 140);
    _button9.set_property_value("Width", 80);
    _button9.set_property_value("Command", DataContextBinding(_button9, "Increment"));
    const _textBlock10 = new TextBlock();
    _textBlock10.set_property_value("Text", "+ Step");
    _button9.Content = _textBlock10;
    _canvas4.AddChild(_button9);
    const _button11 = new Button();
    _button11.set_property_value(Canvas, "Left", 24);
    _button11.set_property_value(Canvas, "Top", 190);
    _button11.set_property_value("Width", 80);
    _button11.set_property_value("Command", DataContextBinding(_button11, "Reset"));
    const _textBlock12 = new TextBlock();
    _textBlock12.set_property_value("Text", "Reset");
    _button11.Content = _textBlock12;
    _canvas4.AddChild(_button11);
    const _textBlock13 = new TextBlock();
    _textBlock13.set_property_value(Canvas, "Left", 24);
    _textBlock13.set_property_value(Canvas, "Top", 232);
    _textBlock13.set_property_value("Width", 312);
    _textBlock13.set_property_value("FontSize", 12);
    _textBlock13.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock13.set_property_value("TextWrapping", TextWrapping.Wrap);
    _textBlock13.set_property_value("Text", "The ComboBox sets Step. Increment adds Step to Count and stops at 10. Reset always works.");
    _canvas4.AddChild(_textBlock13);
    _border3.SetChild(_canvas4);
    _canvas2.AddChild(_border3);
    _rd1.Root = _canvas2;
    return _app0;
})();
