import { Border, Canvas, TextBlock } from "@visualisation-sub/mural/Controls";
import { Application, Color, Setter, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("primary", new SolidColorBrush(Color.FromHex('#4caf50')));
    _rd1.Set("primary:dark", new SolidColorBrush(Color.FromHex('#1b5e20')));
    _rd1.Set("danger", new SolidColorBrush(Color.FromHex('#d32f2f')));
    _rd1.Set("danger:dark", new SolidColorBrush(Color.FromHex('#7f0000')));
    _rd1.Set("on:white", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("ink", new SolidColorBrush(Color.FromHex('#1f2937')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#d1d5db')));
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    const _setter2 = new Setter(Border, "BorderThickness", new Thickness(1));
    const _setter3 = new Setter(Border, "CornerRadius", new Thickness(6));
    const _style4 = new Style(Border, [_setter2, _setter3], undefined, [], []);
    _rd1.Set(Border, _style4);
    const _canvas5 = new Canvas();
    const _border6 = new Border();
    _border6.set_property_value(Canvas, "Left", 20);
    _border6.set_property_value(Canvas, "Top", 20);
    _border6.set_property_value("Width", 200);
    _border6.set_property_value("Height", 80);
    _border6.set_property_value("Background", Application.current.Resources.Resolve("primary"));
    _border6.set_property_value("BorderBrush", Application.current.Resources.Resolve("primary:dark"));
    _border6.set_property_value("BorderThickness", new Thickness(2));
    _border6.set_property_value("CornerRadius", new Thickness(8));
    _border6.set_property_value("Padding", new Thickness(16));
    const _textBlock7 = new TextBlock();
    _textBlock7.set_property_value("Text", "Hello mural");
    _textBlock7.set_property_value("FontSize", 20);
    _textBlock7.set_property_value("Foreground", Application.current.Resources.Resolve("on:white"));
    _border6.SetChild(_textBlock7);
    _canvas5.AddChild(_border6);
    const _border8 = new Border();
    _border8.set_property_value(Canvas, "Left", 240);
    _border8.set_property_value(Canvas, "Top", 20);
    _border8.set_property_value("Width", 200);
    _border8.set_property_value("Height", 80);
    _border8.set_property_value("Background", Application.current.Resources.Resolve("danger"));
    _border8.set_property_value("BorderBrush", Application.current.Resources.Resolve("danger:dark"));
    _border8.set_property_value("BorderThickness", new Thickness(2));
    _border8.set_property_value("CornerRadius", new Thickness(8));
    _border8.set_property_value("Padding", new Thickness(16));
    const _textBlock9 = new TextBlock();
    _textBlock9.set_property_value("Text", "Danger zone");
    _textBlock9.set_property_value("FontSize", 20);
    _textBlock9.set_property_value("Foreground", Application.current.Resources.Resolve("on:white"));
    _border8.SetChild(_textBlock9);
    _canvas5.AddChild(_border8);
    const _border10 = new Border();
    _border10.set_property_value(Canvas, "Left", 20);
    _border10.set_property_value(Canvas, "Top", 140);
    _border10.set_property_value("Width", 420);
    _border10.set_property_value("Height", 160);
    _border10.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border10.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border10.set_property_value("Padding", new Thickness(20));
    const _textBlock11 = new TextBlock();
    _textBlock11.set_property_value("Text", "Compiled from .mu source. Runtime parser used here so you can edit and reload.");
    _textBlock11.set_property_value("FontSize", 14);
    _textBlock11.set_property_value("Foreground", Application.current.Resources.Resolve("ink"));
    _border10.SetChild(_textBlock11);
    _canvas5.AddChild(_border10);
    _rd1.Root = _canvas5;
    return _app0;
})();
