import { Border, Canvas, TextBlock, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Application, Color, PropertyTrigger, Setter, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("primary", new SolidColorBrush(Color.FromHex('#4caf50')));
    _rd1.Set("primary:light", new SolidColorBrush(Color.FromHex('#66bb6a')));
    _rd1.Set("primary:dark", new SolidColorBrush(Color.FromHex('#2e7d32')));
    _rd1.Set("primary:edge", new SolidColorBrush(Color.FromHex('#1b5e20')));
    _rd1.Set("danger", new SolidColorBrush(Color.FromHex('#d32f2f')));
    _rd1.Set("danger:light", new SolidColorBrush(Color.FromHex('#ef5350')));
    _rd1.Set("danger:dark", new SolidColorBrush(Color.FromHex('#b71c1c')));
    _rd1.Set("danger:edge", new SolidColorBrush(Color.FromHex('#7f0000')));
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("paper:hover", new SolidColorBrush(Color.FromHex('#f5f5f5')));
    _rd1.Set("paper:press", new SolidColorBrush(Color.FromHex('#e0e0e0')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#d1d5db')));
    _rd1.Set("on:white", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("ink", new SolidColorBrush(Color.FromHex('#1f2937')));
    const _setter2 = new Setter(Border, "Background", Application.current.Resources.Resolve("primary"));
    const _setter3 = new Setter(Border, "BorderBrush", Application.current.Resources.Resolve("primary:edge"));
    const _setter4 = new Setter(Border, "BorderThickness", new Thickness(2));
    const _setter5 = new Setter(Border, "CornerRadius", new Thickness(8));
    const _setter6 = new Setter(Border, "Padding", new Thickness(16));
    const _setter7 = new Setter(Border, "Background", Application.current.Resources.Resolve("primary:light"));
    const _setter8 = new Setter(Border, "BorderThickness", new Thickness(3));
    const _sArr9 = [_setter7, _setter8];
    const _trigger10 = new PropertyTrigger(Border, "IsMouseOver", true, _sArr9);
    const _setter11 = new Setter(Border, "Background", Application.current.Resources.Resolve("primary:dark"));
    const _setter12 = new Setter(Border, "BorderThickness", new Thickness(4));
    const _sArr13 = [_setter11, _setter12];
    const _trigger14 = new PropertyTrigger(Border, "IsPressed", true, _sArr13);
    const _style15 = new Style(Border, [_setter2, _setter3, _setter4, _setter5, _setter6], undefined, [_trigger10, _trigger14], []);
    _rd1.Set("PrimaryCard", _style15);
    const _setter16 = new Setter(Border, "Background", Application.current.Resources.Resolve("danger"));
    const _setter17 = new Setter(Border, "BorderBrush", Application.current.Resources.Resolve("danger:edge"));
    const _setter18 = new Setter(Border, "BorderThickness", new Thickness(2));
    const _setter19 = new Setter(Border, "CornerRadius", new Thickness(8));
    const _setter20 = new Setter(Border, "Padding", new Thickness(16));
    const _setter21 = new Setter(Border, "Background", Application.current.Resources.Resolve("danger:light"));
    const _setter22 = new Setter(Border, "BorderThickness", new Thickness(3));
    const _sArr23 = [_setter21, _setter22];
    const _trigger24 = new PropertyTrigger(Border, "IsMouseOver", true, _sArr23);
    const _setter25 = new Setter(Border, "Background", Application.current.Resources.Resolve("danger:dark"));
    const _setter26 = new Setter(Border, "BorderThickness", new Thickness(4));
    const _sArr27 = [_setter25, _setter26];
    const _trigger28 = new PropertyTrigger(Border, "IsPressed", true, _sArr27);
    const _style29 = new Style(Border, [_setter16, _setter17, _setter18, _setter19, _setter20], undefined, [_trigger24, _trigger28], []);
    _rd1.Set("DangerCard", _style29);
    const _setter30 = new Setter(Border, "Background", Application.current.Resources.Resolve("paper"));
    const _setter31 = new Setter(Border, "BorderBrush", Application.current.Resources.Resolve("hairline"));
    const _setter32 = new Setter(Border, "BorderThickness", new Thickness(1));
    const _setter33 = new Setter(Border, "CornerRadius", new Thickness(6));
    const _setter34 = new Setter(Border, "Padding", new Thickness(20));
    const _setter35 = new Setter(Border, "Background", Application.current.Resources.Resolve("paper:hover"));
    const _setter36 = new Setter(Border, "BorderThickness", new Thickness(2));
    const _sArr37 = [_setter35, _setter36];
    const _trigger38 = new PropertyTrigger(Border, "IsMouseOver", true, _sArr37);
    const _setter39 = new Setter(Border, "Background", Application.current.Resources.Resolve("paper:press"));
    const _setter40 = new Setter(Border, "BorderThickness", new Thickness(3));
    const _sArr41 = [_setter39, _setter40];
    const _trigger42 = new PropertyTrigger(Border, "IsPressed", true, _sArr41);
    const _style43 = new Style(Border, [_setter30, _setter31, _setter32, _setter33, _setter34], undefined, [_trigger38, _trigger42], []);
    _rd1.Set("PaperCard", _style43);
    const _canvas44 = new Canvas();
    const _border45 = new Border();
    _border45.set_property_value("Style", Application.current.Resources.Resolve("PrimaryCard"));
    _border45.set_property_value(Canvas, "Left", 20);
    _border45.set_property_value(Canvas, "Top", 20);
    _border45.set_property_value("Width", 200);
    _border45.set_property_value("Height", 80);
    const _textBlock46 = new TextBlock();
    _textBlock46.set_property_value("Text", "Hello mural");
    _textBlock46.set_property_value("FontSize", 20);
    _textBlock46.set_property_value("Foreground", Application.current.Resources.Resolve("on:white"));
    _border45.SetChild(_textBlock46);
    _canvas44.AddChild(_border45);
    const _border47 = new Border();
    _border47.set_property_value("Style", Application.current.Resources.Resolve("DangerCard"));
    _border47.set_property_value(Canvas, "Left", 240);
    _border47.set_property_value(Canvas, "Top", 20);
    _border47.set_property_value("Width", 200);
    _border47.set_property_value("Height", 80);
    const _textBlock48 = new TextBlock();
    _textBlock48.set_property_value("Text", "Danger zone");
    _textBlock48.set_property_value("FontSize", 20);
    _textBlock48.set_property_value("Foreground", Application.current.Resources.Resolve("on:white"));
    _border47.SetChild(_textBlock48);
    _canvas44.AddChild(_border47);
    const _border49 = new Border();
    _border49.set_property_value("Style", Application.current.Resources.Resolve("PaperCard"));
    _border49.set_property_value(Canvas, "Left", 20);
    _border49.set_property_value(Canvas, "Top", 140);
    _border49.set_property_value("Width", 420);
    _border49.set_property_value("Height", 160);
    const _textBlock50 = new TextBlock();
    _textBlock50.set_property_value("Text", "Hover over the cards above to see Style triggers fire on IsMouseOver. Press and hold to see the IsPressed trigger lock in.");
    _textBlock50.set_property_value("FontSize", 14);
    _textBlock50.set_property_value("TextWrapping", TextWrapping.Wrap);
    _textBlock50.set_property_value("Foreground", Application.current.Resources.Resolve("ink"));
    _border49.SetChild(_textBlock50);
    _canvas44.AddChild(_border49);
    _rd1.Root = _canvas44;
    return _app0;
})();
