import { Border, Canvas, DockPanel, ItemsControl, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Application, Color, NameScope, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("ink", new SolidColorBrush(Color.FromHex('#1f2937')));
    _rd1.Set("hint", new SolidColorBrush(Color.FromHex('#6b7280')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#e2e8f0')));
    _rd1.Set("primary", new SolidColorBrush(Color.FromHex('#1976d2')));
    _rd1.Set("primaryInk", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("grid", new SolidColorBrush(Color.FromHex('#f1f5f9')));
    _rd1.Set("tile", new SolidColorBrush(Color.FromHex('#f8fafc')));
    _rd1.Set("tileHover", new SolidColorBrush(Color.FromHex('#eef2f7')));
    const _border2 = new Border();
    _border2.SetNameScope(new NameScope());
    _border2.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border2.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border2.set_property_value("BorderThickness", new Thickness(1));
    const _dockPanel3 = new DockPanel();
    const _border4 = new Border();
    _border4.set_property_value(DockPanel, "Dock", "Top");
    _border4.set_property_value("Height", 44);
    _border4.set_property_value("Background", Application.current.Resources.Resolve("primary"));
    const _stackPanel5 = new StackPanel();
    _stackPanel5.set_property_value("Orientation", Orientation.Horizontal);
    _stackPanel5.set_property_value("Margin", new Thickness(16, 10, 0, 0));
    const _textBlock6 = new TextBlock();
    _textBlock6.set_property_value("Text", "Diagrammer");
    _textBlock6.set_property_value("FontSize", 15);
    _textBlock6.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock6.set_property_value("Foreground", Application.current.Resources.Resolve("primaryInk"));
    _stackPanel5.AddChild(_textBlock6);
    const _textBlock7 = new TextBlock();
    _textBlock7.Name = "status";
    _border2.nameScope.Register("status", _textBlock7);
    _textBlock7.set_property_value("Text", "drag a shape from the toolbox →");
    _textBlock7.set_property_value("FontSize", 12);
    _textBlock7.set_property_value("Foreground", Application.current.Resources.Resolve("primaryInk"));
    _textBlock7.set_property_value("Margin", new Thickness(20, 3, 0, 0));
    _stackPanel5.AddChild(_textBlock7);
    _border4.SetChild(_stackPanel5);
    _dockPanel3.AddChild(_border4);
    const _border8 = new Border();
    _border8.set_property_value(DockPanel, "Dock", "Left");
    _border8.set_property_value("Width", 140);
    _border8.set_property_value("Background", Application.current.Resources.Resolve("tile"));
    _border8.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border8.set_property_value("BorderThickness", new Thickness(0, 0, 1, 0));
    _border8.set_property_value("Padding", new Thickness(12));
    const _stackPanel9 = new StackPanel();
    const _textBlock10 = new TextBlock();
    _textBlock10.set_property_value("Text", "Shapes");
    _textBlock10.set_property_value("FontSize", 11);
    _textBlock10.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock10.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock10.set_property_value("Margin", new Thickness(2, 0, 0, 8));
    _stackPanel9.AddChild(_textBlock10);
    const _itemsControl11 = new ItemsControl();
    _itemsControl11.Name = "toolbox";
    _border2.nameScope.Register("toolbox", _itemsControl11);
    _stackPanel9.AddChild(_itemsControl11);
    const _textBlock12 = new TextBlock();
    _textBlock12.set_property_value("Text", "Drag onto the canvas. Click a\n                                        node to select it; drag to move.\n                                        Hover to reveal connection ports\n                                        — drag a port to another node to\n                                        wire them.");
    _textBlock12.set_property_value("TextWrapping", TextWrapping.Wrap);
    _textBlock12.set_property_value("FontSize", 10);
    _textBlock12.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock12.set_property_value("Margin", new Thickness(2, 16, 2, 0));
    _stackPanel9.AddChild(_textBlock12);
    _border8.SetChild(_stackPanel9);
    _dockPanel3.AddChild(_border8);
    const _border13 = new Border();
    _border13.Name = "surface";
    _border2.nameScope.Register("surface", _border13);
    _border13.set_property_value("Background", Application.current.Resources.Resolve("grid"));
    const _canvas14 = new Canvas();
    _canvas14.Name = "canvas";
    _border2.nameScope.Register("canvas", _canvas14);
    _border13.SetChild(_canvas14);
    _dockPanel3.AddChild(_border13);
    _border2.SetChild(_dockPanel3);
    _rd1.Root = _border2;
    return _app0;
})();
