import { Border, DockPanel, ListBox, ListBoxItem, Orientation, SelectionMode, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { Application, Color, NameScope, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#e2e8f0')));
    _rd1.Set("primary", new SolidColorBrush(Color.FromHex('#1976d2')));
    _rd1.Set("primInk", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("divider", new SolidColorBrush(Color.FromHex('#e0e0e0')));
    const _border2 = new Border();
    _border2.SetNameScope(new NameScope());
    _border2.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border2.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border2.set_property_value("BorderThickness", new Thickness(1));
    const _dockPanel3 = new DockPanel();
    const _border4 = new Border();
    _border4.set_property_value(DockPanel, "Dock", "Top");
    _border4.set_property_value("Background", Application.current.Resources.Resolve("primary"));
    _border4.set_property_value("Padding", new Thickness(16, 12, 16, 12));
    const _textBlock5 = new TextBlock();
    _textBlock5.set_property_value("Text", "ListBox demo — declarative vs. Items");
    _textBlock5.set_property_value("FontSize", 15);
    _textBlock5.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock5.set_property_value("Foreground", Application.current.Resources.Resolve("primInk"));
    _border4.SetChild(_textBlock5);
    _dockPanel3.AddChild(_border4);
    const _stackPanel6 = new StackPanel();
    _stackPanel6.set_property_value("Orientation", Orientation.Horizontal);
    const _stackPanel7 = new StackPanel();
    _stackPanel7.set_property_value("Orientation", Orientation.Vertical);
    _stackPanel7.set_property_value("Width", 240);
    _stackPanel7.set_property_value("Margin", new Thickness(12, 12, 6, 12));
    const _textBlock8 = new TextBlock();
    _textBlock8.set_property_value("Text", "Declarative");
    _textBlock8.set_property_value("FontSize", 12);
    _textBlock8.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock8.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    _stackPanel7.AddChild(_textBlock8);
    const _listBox9 = new ListBox();
    _listBox9.Name = "declarative";
    _border2.nameScope.Register("declarative", _listBox9);
    _listBox9.set_property_value("SelectionMode", SelectionMode.Extended);
    const _listBoxItem10 = new ListBoxItem();
    const _textBlock11 = new TextBlock();
    _textBlock11.set_property_value("Text", "Apples");
    _listBoxItem10.Content = _textBlock11;
    _listBox9.AddChild(_listBoxItem10);
    const _listBoxItem12 = new ListBoxItem();
    const _textBlock13 = new TextBlock();
    _textBlock13.set_property_value("Text", "Bananas");
    _listBoxItem12.Content = _textBlock13;
    _listBox9.AddChild(_listBoxItem12);
    const _listBoxItem14 = new ListBoxItem();
    const _textBlock15 = new TextBlock();
    _textBlock15.set_property_value("Text", "Cherries");
    _listBoxItem14.Content = _textBlock15;
    _listBox9.AddChild(_listBoxItem14);
    const _listBoxItem16 = new ListBoxItem();
    const _textBlock17 = new TextBlock();
    _textBlock17.set_property_value("Text", "Durian");
    _listBoxItem16.Content = _textBlock17;
    _listBox9.AddChild(_listBoxItem16);
    const _listBoxItem18 = new ListBoxItem();
    const _textBlock19 = new TextBlock();
    _textBlock19.set_property_value("Text", "Elderberry");
    _listBoxItem18.Content = _textBlock19;
    _listBox9.AddChild(_listBoxItem18);
    const _listBoxItem20 = new ListBoxItem();
    const _textBlock21 = new TextBlock();
    _textBlock21.set_property_value("Text", "Fig");
    _listBoxItem20.Content = _textBlock21;
    _listBox9.AddChild(_listBoxItem20);
    _stackPanel7.AddChild(_listBox9);
    _stackPanel6.AddChild(_stackPanel7);
    const _border22 = new Border();
    _border22.set_property_value("Width", 1);
    _border22.set_property_value("Background", Application.current.Resources.Resolve("divider"));
    _border22.set_property_value("Margin", new Thickness(0, 12, 0, 12));
    _stackPanel6.AddChild(_border22);
    const _stackPanel23 = new StackPanel();
    _stackPanel23.set_property_value("Orientation", Orientation.Vertical);
    _stackPanel23.set_property_value("Width", 240);
    _stackPanel23.set_property_value("Margin", new Thickness(6, 12, 12, 12));
    const _textBlock24 = new TextBlock();
    _textBlock24.set_property_value("Text", "Items=[…] convenience");
    _textBlock24.set_property_value("FontSize", 12);
    _textBlock24.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock24.set_property_value("Margin", new Thickness(0, 0, 0, 8));
    _stackPanel23.AddChild(_textBlock24);
    const _listBox25 = new ListBox();
    _listBox25.Name = "items";
    _border2.nameScope.Register("items", _listBox25);
    _listBox25.set_property_value("Items", ["Red", "Green", "Blue", "Yellow", "Magenta", "Cyan"]);
    _stackPanel23.AddChild(_listBox25);
    _stackPanel6.AddChild(_stackPanel23);
    _dockPanel3.AddChild(_stackPanel6);
    _border2.SetChild(_dockPanel3);
    _rd1.Root = _border2;
    return _app0;
})();
