import { Border, DockPanel, Orientation, StackPanel, TextBlock, TextBox, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Application, Color, NameScope, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#e2e8f0')));
    _rd1.Set("primary", new SolidColorBrush(Color.FromHex('#1976d2')));
    _rd1.Set("primInk", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("hint", new SolidColorBrush(Color.FromHex('#6b7280')));
    const _border2 = new Border();
    _border2.SetNameScope(new NameScope());
    _border2.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border2.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border2.set_property_value("BorderThickness", new Thickness(1));
    const _dockPanel3 = new DockPanel();
    const _border4 = new Border();
    _border4.set_property_value(DockPanel, "Dock", "Top");
    _border4.set_property_value("Background", Application.current.Resources.Resolve("primary"));
    _border4.set_property_value("Padding", new Thickness(16, 12, 16, 12));
    const _textBlock5 = new TextBlock();
    _textBlock5.set_property_value("Text", "TextBox demo — single-line + multi-line");
    _textBlock5.set_property_value("FontSize", 15);
    _textBlock5.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock5.set_property_value("Foreground", Application.current.Resources.Resolve("primInk"));
    _border4.SetChild(_textBlock5);
    _dockPanel3.AddChild(_border4);
    const _stackPanel6 = new StackPanel();
    _stackPanel6.set_property_value("Orientation", Orientation.Horizontal);
    const _stackPanel7 = new StackPanel();
    _stackPanel7.set_property_value("Orientation", Orientation.Vertical);
    _stackPanel7.set_property_value("Width", 300);
    _stackPanel7.set_property_value("Margin", new Thickness(16, 16, 8, 16));
    const _textBlock8 = new TextBlock();
    _textBlock8.set_property_value("Text", "Single-line:");
    _textBlock8.set_property_value("FontSize", 12);
    _textBlock8.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock8.set_property_value("Margin", new Thickness(0, 0, 0, 6));
    _stackPanel7.AddChild(_textBlock8);
    const _textBox9 = new TextBox();
    _textBox9.Name = "nameField";
    _border2.nameScope.Register("nameField", _textBox9);
    _textBox9.set_property_value("Width", 260);
    _textBox9.set_property_value("Text", "This is a single-line TextBox whose content overflows the field width.");
    _stackPanel7.AddChild(_textBox9);
    const _textBlock10 = new TextBlock();
    _textBlock10.set_property_value("Text", "No scrollbar. Type / Home / End — text follows the caret.");
    _textBlock10.set_property_value("FontSize", 11);
    _textBlock10.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock10.set_property_value("Margin", new Thickness(0, 8, 0, 0));
    _stackPanel7.AddChild(_textBlock10);
    _stackPanel6.AddChild(_stackPanel7);
    const _stackPanel11 = new StackPanel();
    _stackPanel11.set_property_value("Orientation", Orientation.Vertical);
    _stackPanel11.set_property_value("Width", 300);
    _stackPanel11.set_property_value("Margin", new Thickness(8, 16, 8, 16));
    const _textBlock12 = new TextBlock();
    _textBlock12.set_property_value("Text", "Multi-line — Wrap:");
    _textBlock12.set_property_value("FontSize", 12);
    _textBlock12.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock12.set_property_value("Margin", new Thickness(0, 0, 0, 6));
    _stackPanel11.AddChild(_textBlock12);
    const _textBox13 = new TextBox();
    _textBox13.Name = "wrapField";
    _border2.nameScope.Register("wrapField", _textBox13);
    _textBox13.set_property_value("Width", 280);
    _textBox13.set_property_value("Height", 160);
    _textBox13.set_property_value("AcceptsReturn", true);
    _textBox13.set_property_value("Text", "Default wrap mode: this paragraph is long enough that it should break across several visual lines at word boundaries. ArrowDown moves down visual rows.\nA hard newline starts a new logical line that also wraps on overflow.");
    _stackPanel11.AddChild(_textBox13);
    const _textBlock14 = new TextBlock();
    _textBlock14.set_property_value("Text", "Word-wrap. Resize the column to see lines re-flow.");
    _textBlock14.set_property_value("FontSize", 11);
    _textBlock14.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock14.set_property_value("Margin", new Thickness(0, 8, 0, 0));
    _stackPanel11.AddChild(_textBlock14);
    _stackPanel6.AddChild(_stackPanel11);
    const _stackPanel15 = new StackPanel();
    _stackPanel15.set_property_value("Orientation", Orientation.Vertical);
    _stackPanel15.set_property_value("Width", 300);
    _stackPanel15.set_property_value("Margin", new Thickness(8, 16, 16, 16));
    const _textBlock16 = new TextBlock();
    _textBlock16.set_property_value("Text", "Multi-line — NoWrap:");
    _textBlock16.set_property_value("FontSize", 12);
    _textBlock16.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock16.set_property_value("Margin", new Thickness(0, 0, 0, 6));
    _stackPanel15.AddChild(_textBlock16);
    const _textBox17 = new TextBox();
    _textBox17.Name = "codeField";
    _border2.nameScope.Register("codeField", _textBox17);
    _textBox17.set_property_value("Width", 280);
    _textBox17.set_property_value("Height", 160);
    _textBox17.set_property_value("AcceptsReturn", true);
    _textBox17.set_property_value("AcceptsTab", true);
    _textBox17.set_property_value("TextWrapping", TextWrapping.NoWrap);
    _textBox17.set_property_value("Text", "function example() {\n    const longLineThatWillNotWrap = 'extends past the viewport horizontally';\n    return longLineThatWillNotWrap;\n}");
    _stackPanel15.AddChild(_textBox17);
    const _textBlock18 = new TextBlock();
    _textBlock18.set_property_value("Text", "Both axes scroll; lines never break.");
    _textBlock18.set_property_value("FontSize", 11);
    _textBlock18.set_property_value("Foreground", Application.current.Resources.Resolve("hint"));
    _textBlock18.set_property_value("Margin", new Thickness(0, 8, 0, 0));
    _stackPanel15.AddChild(_textBlock18);
    _stackPanel6.AddChild(_stackPanel15);
    _dockPanel3.AddChild(_stackPanel6);
    _border2.SetChild(_dockPanel3);
    _rd1.Root = _border2;
    return _app0;
})();
