import { Border, DockPanel, TextBlock, TreeView, TreeViewItem } from "@visualisation-sub/mural/Controls";
import { Application, Color, NameScope, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export const app = (() => {
    const _app0 = new Application();
    const _rd1 = _app0.Resources;
    _rd1.Set("paper", new SolidColorBrush(Color.FromHex('#ffffff')));
    _rd1.Set("ink", new SolidColorBrush(Color.FromHex('#1f2937')));
    _rd1.Set("hint", new SolidColorBrush(Color.FromHex('#6b7280')));
    _rd1.Set("hairline", new SolidColorBrush(Color.FromHex('#e2e8f0')));
    _rd1.Set("primary", new SolidColorBrush(Color.FromHex('#1976d2')));
    _rd1.Set("primInk", new SolidColorBrush(Color.FromHex('#ffffff')));
    const _border2 = new Border();
    _border2.SetNameScope(new NameScope());
    _border2.set_property_value("Background", Application.current.Resources.Resolve("paper"));
    _border2.set_property_value("BorderBrush", Application.current.Resources.Resolve("hairline"));
    _border2.set_property_value("BorderThickness", new Thickness(1));
    const _dockPanel3 = new DockPanel();
    const _border4 = new Border();
    _border4.set_property_value(DockPanel, "Dock", "Top");
    _border4.set_property_value("Background", Application.current.Resources.Resolve("primary"));
    _border4.set_property_value("Padding", new Thickness(16, 12, 16, 12));
    const _textBlock5 = new TextBlock();
    _textBlock5.set_property_value("Text", "Project explorer");
    _textBlock5.set_property_value("FontSize", 15);
    _textBlock5.set_property_value("FontWeight", FontWeight.Bold);
    _textBlock5.set_property_value("Foreground", Application.current.Resources.Resolve("primInk"));
    _border4.SetChild(_textBlock5);
    _dockPanel3.AddChild(_border4);
    const _treeView6 = new TreeView();
    _treeView6.set_property_value("Indent", 18);
    _treeView6.set_property_value("Margin", new Thickness(8, 8, 8, 8));
    const _treeViewItem7 = new TreeViewItem();
    _treeViewItem7.set_property_value("Header", "src/");
    _treeViewItem7.set_property_value("IsExpanded", true);
    const _treeViewItem8 = new TreeViewItem();
    _treeViewItem8.set_property_value("Header", "runtime/");
    _treeViewItem8.set_property_value("IsExpanded", true);
    const _treeViewItem9 = new TreeViewItem();
    _treeViewItem9.set_property_value("Header", "visual.ts");
    _treeViewItem8.AddChild(_treeViewItem9);
    const _treeViewItem10 = new TreeViewItem();
    _treeViewItem10.set_property_value("Header", "model.ts");
    _treeViewItem8.AddChild(_treeViewItem10);
    const _treeViewItem11 = new TreeViewItem();
    _treeViewItem11.set_property_value("Header", "routed-event.ts");
    _treeViewItem8.AddChild(_treeViewItem11);
    const _treeViewItem12 = new TreeViewItem();
    _treeViewItem12.set_property_value("Header", "input-manager.ts");
    _treeViewItem8.AddChild(_treeViewItem12);
    _treeViewItem7.AddChild(_treeViewItem8);
    const _treeViewItem13 = new TreeViewItem();
    _treeViewItem13.set_property_value("Header", "visual-engine/");
    const _treeViewItem14 = new TreeViewItem();
    _treeViewItem14.set_property_value("Header", "presentation-target.ts");
    _treeViewItem13.AddChild(_treeViewItem14);
    const _treeViewItem15 = new TreeViewItem();
    _treeViewItem15.set_property_value("Header", "svg-renderer.ts");
    _treeViewItem13.AddChild(_treeViewItem15);
    const _treeViewItem16 = new TreeViewItem();
    _treeViewItem16.set_property_value("Header", "overlay-layer.ts");
    _treeViewItem13.AddChild(_treeViewItem16);
    const _treeViewItem17 = new TreeViewItem();
    _treeViewItem17.set_property_value("Header", "targets/");
    const _treeViewItem18 = new TreeViewItem();
    _treeViewItem18.set_property_value("Header", "html-target.ts");
    _treeViewItem17.AddChild(_treeViewItem18);
    const _treeViewItem19 = new TreeViewItem();
    _treeViewItem19.set_property_value("Header", "headless-target.ts");
    _treeViewItem17.AddChild(_treeViewItem19);
    const _treeViewItem20 = new TreeViewItem();
    _treeViewItem20.set_property_value("Header", "file-target.ts");
    _treeViewItem17.AddChild(_treeViewItem20);
    _treeViewItem13.AddChild(_treeViewItem17);
    _treeViewItem7.AddChild(_treeViewItem13);
    const _treeViewItem21 = new TreeViewItem();
    _treeViewItem21.set_property_value("Header", "Controls/");
    _treeViewItem21.set_property_value("IsExpanded", true);
    const _treeViewItem22 = new TreeViewItem();
    _treeViewItem22.set_property_value("Header", "border.ts");
    _treeViewItem21.AddChild(_treeViewItem22);
    const _treeViewItem23 = new TreeViewItem();
    _treeViewItem23.set_property_value("Header", "button.ts");
    _treeViewItem21.AddChild(_treeViewItem23);
    const _treeViewItem24 = new TreeViewItem();
    _treeViewItem24.set_property_value("Header", "combo-box.ts");
    _treeViewItem21.AddChild(_treeViewItem24);
    const _treeViewItem25 = new TreeViewItem();
    _treeViewItem25.set_property_value("Header", "dock-panel.ts");
    _treeViewItem21.AddChild(_treeViewItem25);
    const _treeViewItem26 = new TreeViewItem();
    _treeViewItem26.set_property_value("Header", "drawer.ts");
    _treeViewItem21.AddChild(_treeViewItem26);
    const _treeViewItem27 = new TreeViewItem();
    _treeViewItem27.set_property_value("Header", "tree-view.ts");
    _treeViewItem21.AddChild(_treeViewItem27);
    _treeViewItem7.AddChild(_treeViewItem21);
    _treeView6.AddChild(_treeViewItem7);
    const _treeViewItem28 = new TreeViewItem();
    _treeViewItem28.set_property_value("Header", "demo/");
    const _treeViewItem29 = new TreeViewItem();
    _treeViewItem29.set_property_value("Header", "counter.mu");
    _treeViewItem28.AddChild(_treeViewItem29);
    const _treeViewItem30 = new TreeViewItem();
    _treeViewItem30.set_property_value("Header", "drawer.mu");
    _treeViewItem28.AddChild(_treeViewItem30);
    const _treeViewItem31 = new TreeViewItem();
    _treeViewItem31.set_property_value("Header", "tree-view.mu");
    _treeViewItem28.AddChild(_treeViewItem31);
    _treeView6.AddChild(_treeViewItem28);
    _dockPanel3.AddChild(_treeView6);
    _border2.SetChild(_dockPanel3);
    _rd1.Root = _border2;
    return _app0;
})();
