import { ToolBarVM } from "./tool-bar-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Basic";
import { ToolBar, ToolBarButton, ToolBarSeparator } from "@visualisation-sub/mural/framework/surface.js";
import { ToggleButton } from "@visualisation-sub/mural/framework/toggle-button.js";
import { Color, DataContextBinding, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border4._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border4._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name("Text", "ToolBar — Button rows, separators, and command binding.");
        _textBlock5._set_property_value_by_name("FontSize", 15);
        _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock5._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel6._set_property_value_by_name("Margin", new Thickness(16, 16, 16, 16));
        const _textBlock7 = new TextBlock();
        _textBlock7._set_property_value_by_name("Text", "A row of command buttons separated into groups:");
        _textBlock7._set_property_value_by_name("FontSize", 12);
        _textBlock7._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock7._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel6.AddChild(_textBlock7);
        const _toolBar8 = new ToolBar();
        const _toolBarButton9 = new ToolBarButton();
        _toolBarButton9._set_property_value_by_name("Command", DataContextBinding(_toolBarButton9, "SaveCommand"));
        const _textBlock10 = new TextBlock();
        _textBlock10._set_property_value_by_name("Text", "💾");
        _toolBarButton9.Content = _textBlock10;
        _toolBar8.AddChild(_toolBarButton9);
        const _toolBarSeparator11 = new ToolBarSeparator();
        _toolBar8.AddChild(_toolBarSeparator11);
        const _toolBarButton12 = new ToolBarButton();
        _toolBarButton12._set_property_value_by_name("Command", DataContextBinding(_toolBarButton12, "CutCommand"));
        const _textBlock13 = new TextBlock();
        _textBlock13._set_property_value_by_name("Text", "✂");
        _toolBarButton12.Content = _textBlock13;
        _toolBar8.AddChild(_toolBarButton12);
        const _toolBarButton14 = new ToolBarButton();
        _toolBarButton14._set_property_value_by_name("Command", DataContextBinding(_toolBarButton14, "CopyCommand"));
        const _textBlock15 = new TextBlock();
        _textBlock15._set_property_value_by_name("Text", "📋");
        _toolBarButton14.Content = _textBlock15;
        _toolBar8.AddChild(_toolBarButton14);
        const _toolBarButton16 = new ToolBarButton();
        _toolBarButton16._set_property_value_by_name("Command", DataContextBinding(_toolBarButton16, "DeleteCommand"));
        const _textBlock17 = new TextBlock();
        _textBlock17._set_property_value_by_name("Text", "🗑");
        _toolBarButton16.Content = _textBlock17;
        _toolBar8.AddChild(_toolBarButton16);
        _stackPanel6.AddChild(_toolBar8);
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", DataContextBinding(_textBlock18, "Status"));
        _textBlock18._set_property_value_by_name("FontSize", 13);
        _textBlock18._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#1f2937')));
        _textBlock18._set_property_value_by_name("Margin", new Thickness(0, 16, 0, 4));
        _stackPanel6.AddChild(_textBlock18);
        const _stackPanel19 = new StackPanel();
        _stackPanel19._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel19._set_property_value_by_name("Margin", new Thickness(0, 8, 0, 0));
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "Selection state:");
        _textBlock20._set_property_value_by_name("FontSize", 12);
        _textBlock20._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock20._set_property_value_by_name("Margin", new Thickness(0, 8, 8, 0));
        _stackPanel19.AddChild(_textBlock20);
        const _toggleButton21 = new ToggleButton();
        _toggleButton21._set_property_value_by_name("IsChecked", DataContextBinding(_toggleButton21, "HasSelection"));
        _toggleButton21._set_property_value_by_name("Command", DataContextBinding(_toggleButton21, "ToggleSelectionCommand"));
        const _textBlock22 = new TextBlock();
        _textBlock22._set_property_value_by_name("Text", "HasSelection");
        _toggleButton21.Content = _textBlock22;
        _stackPanel19.AddChild(_toggleButton21);
        const _textBlock23 = new TextBlock();
        _textBlock23._set_property_value_by_name("Text", "  (Delete is selection-gated — toggle to ungate.)");
        _textBlock23._set_property_value_by_name("FontSize", 11);
        _textBlock23._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock23._set_property_value_by_name("Margin", new Thickness(8, 8, 0, 0));
        _stackPanel19.AddChild(_textBlock23);
        _stackPanel6.AddChild(_stackPanel19);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, ToolBarVM);
    _rd0.Set("ToolBarTemplate", _tmpl1);
    return _rd0;
}
