import { CardVM } from "./card-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock, TextWrapping } from "@pragmatic-tech-ai/mural/basic";
import { Button, ButtonVariant } from "@pragmatic-tech-ai/mural/framework/buttons/button.js";
import { Card } from "@pragmatic-tech-ai/mural/framework/surfaces/card.js";
import { DataContextBinding, DynamicResource, HorizontalAlignment, ResourceDictionary, Thickness } from "@pragmatic-tech-ai/mural/runtime";
import { FontWeight, Pen } from "@pragmatic-tech-ai/mural/visual-engine";


const _gate_CardDemo = Symbol("CardDemo.ctor");
export class CardDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_CardDemo) {
            throw new Error("CardDemo is private — use CardDemo.Clone()");
        }
    }
    static Clone() {
        const t = new CardDemo(_gate_CardDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.set_property_value(Border.FillKey, DynamicResource(_border1, "Surface"));
            _border1.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.FillKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4.set_property_value(TextBlock.TextKey, "Card — M3's content container. Three variants vary container colour, border, and resting elevation.");
            _textBlock4.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock4.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock4.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel5.set_property_value(StackPanel.MarginKey, new Thickness(24, 24, 24, 24));
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "Card — Variant: Filled / Elevated / Outlined");
            _textBlock6.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock6.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock6, "OnSurface"));
            _textBlock6.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 16));
            _stackPanel5.AddChild(_textBlock6);
            const _stackPanel7 = new StackPanel();
            _stackPanel7.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel7.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 16));
            const _card8 = new Card();
            _card8.set_property_value(Card.VariantKey, ButtonVariant.Filled);
            _card8.set_property_value(Card.WidthKey, 240);
            _card8.set_property_value(Card.MarginKey, new Thickness(0, 0, 24, 0));
            const _stackPanel9 = new StackPanel();
            _stackPanel9.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock10 = new TextBlock();
            _textBlock10.set_property_value(TextBlock.TextKey, "Filled");
            _textBlock10.set_property_value(TextBlock.FontFamilyKey, DynamicResource(_textBlock10, "TitleMediumFont"));
            _textBlock10.set_property_value(TextBlock.FontWeightKey, DynamicResource(_textBlock10, "TitleMediumWeight"));
            _textBlock10.set_property_value(TextBlock.FontSizeKey, DynamicResource(_textBlock10, "TitleMediumSize"));
            _textBlock10.set_property_value(TextBlock.LineHeightKey, DynamicResource(_textBlock10, "TitleMediumLineHeight"));
            _textBlock10.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock10, "OnSurface"));
            _textBlock10.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel9.AddChild(_textBlock10);
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "SurfaceContainerHighest base, no border, no resting elevation. Hover bumps to Level1.");
            _textBlock11.set_property_value(TextBlock.FontFamilyKey, DynamicResource(_textBlock11, "BodyMediumFont"));
            _textBlock11.set_property_value(TextBlock.FontSizeKey, DynamicResource(_textBlock11, "BodyMediumSize"));
            _textBlock11.set_property_value(TextBlock.LineHeightKey, DynamicResource(_textBlock11, "BodyMediumLineHeight"));
            _textBlock11.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock11, "OnSurfaceVariant"));
            _textBlock11.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock11.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 16));
            _stackPanel9.AddChild(_textBlock11);
            const _button12 = new Button();
            _button12.set_property_value(Button.VariantKey, ButtonVariant.Text);
            _button12.set_property_value(Button.CommandKey, DataContextBinding(_button12, "FilledActionCommand"));
            _button12.set_property_value(Button.HorizontalAlignmentKey, HorizontalAlignment.Left);
            const _textBlock13 = new TextBlock();
            _textBlock13.set_property_value(TextBlock.TextKey, "Action");
            _button12.Content = _textBlock13;
            _stackPanel9.AddChild(_button12);
            _card8.Content = _stackPanel9;
            _stackPanel7.AddChild(_card8);
            const _card14 = new Card();
            _card14.set_property_value(Card.VariantKey, ButtonVariant.Elevated);
            _card14.set_property_value(Card.WidthKey, 240);
            _card14.set_property_value(Card.MarginKey, new Thickness(0, 0, 24, 0));
            const _stackPanel15 = new StackPanel();
            _stackPanel15.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock16 = new TextBlock();
            _textBlock16.set_property_value(TextBlock.TextKey, "Elevated");
            _textBlock16.set_property_value(TextBlock.FontFamilyKey, DynamicResource(_textBlock16, "TitleMediumFont"));
            _textBlock16.set_property_value(TextBlock.FontWeightKey, DynamicResource(_textBlock16, "TitleMediumWeight"));
            _textBlock16.set_property_value(TextBlock.FontSizeKey, DynamicResource(_textBlock16, "TitleMediumSize"));
            _textBlock16.set_property_value(TextBlock.LineHeightKey, DynamicResource(_textBlock16, "TitleMediumLineHeight"));
            _textBlock16.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock16, "OnSurface"));
            _textBlock16.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel15.AddChild(_textBlock16);
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "SurfaceContainerLow base, no border, resting ElevationLevel1. Hover bumps to Level2.");
            _textBlock17.set_property_value(TextBlock.FontFamilyKey, DynamicResource(_textBlock17, "BodyMediumFont"));
            _textBlock17.set_property_value(TextBlock.FontSizeKey, DynamicResource(_textBlock17, "BodyMediumSize"));
            _textBlock17.set_property_value(TextBlock.LineHeightKey, DynamicResource(_textBlock17, "BodyMediumLineHeight"));
            _textBlock17.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock17, "OnSurfaceVariant"));
            _textBlock17.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock17.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 16));
            _stackPanel15.AddChild(_textBlock17);
            const _button18 = new Button();
            _button18.set_property_value(Button.VariantKey, ButtonVariant.Text);
            _button18.set_property_value(Button.CommandKey, DataContextBinding(_button18, "ElevatedActionCommand"));
            _button18.set_property_value(Button.HorizontalAlignmentKey, HorizontalAlignment.Left);
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "Action");
            _button18.Content = _textBlock19;
            _stackPanel15.AddChild(_button18);
            _card14.Content = _stackPanel15;
            _stackPanel7.AddChild(_card14);
            const _card20 = new Card();
            _card20.set_property_value(Card.VariantKey, ButtonVariant.Outlined);
            _card20.set_property_value(Card.WidthKey, 240);
            const _stackPanel21 = new StackPanel();
            _stackPanel21.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock22 = new TextBlock();
            _textBlock22.set_property_value(TextBlock.TextKey, "Outlined");
            _textBlock22.set_property_value(TextBlock.FontFamilyKey, DynamicResource(_textBlock22, "TitleMediumFont"));
            _textBlock22.set_property_value(TextBlock.FontWeightKey, DynamicResource(_textBlock22, "TitleMediumWeight"));
            _textBlock22.set_property_value(TextBlock.FontSizeKey, DynamicResource(_textBlock22, "TitleMediumSize"));
            _textBlock22.set_property_value(TextBlock.LineHeightKey, DynamicResource(_textBlock22, "TitleMediumLineHeight"));
            _textBlock22.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock22, "OnSurface"));
            _textBlock22.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel21.AddChild(_textBlock22);
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, "Surface base, 1-DIP Outline border, no resting elevation. Hover bumps to Level1.");
            _textBlock23.set_property_value(TextBlock.FontFamilyKey, DynamicResource(_textBlock23, "BodyMediumFont"));
            _textBlock23.set_property_value(TextBlock.FontSizeKey, DynamicResource(_textBlock23, "BodyMediumSize"));
            _textBlock23.set_property_value(TextBlock.LineHeightKey, DynamicResource(_textBlock23, "BodyMediumLineHeight"));
            _textBlock23.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock23, "OnSurfaceVariant"));
            _textBlock23.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock23.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 16));
            _stackPanel21.AddChild(_textBlock23);
            const _button24 = new Button();
            _button24.set_property_value(Button.VariantKey, ButtonVariant.Text);
            _button24.set_property_value(Button.CommandKey, DataContextBinding(_button24, "OutlinedActionCommand"));
            _button24.set_property_value(Button.HorizontalAlignmentKey, HorizontalAlignment.Left);
            const _textBlock25 = new TextBlock();
            _textBlock25.set_property_value(TextBlock.TextKey, "Action");
            _button24.Content = _textBlock25;
            _stackPanel21.AddChild(_button24);
            _card20.Content = _stackPanel21;
            _stackPanel7.AddChild(_card20);
            _stackPanel5.AddChild(_stackPanel7);
            const _stackPanel26 = new StackPanel();
            _stackPanel26.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, "Actions — Filled: ");
            _textBlock27.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock27.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock27, "OnSurfaceVariant"));
            _stackPanel26.AddChild(_textBlock27);
            const _textBlock28 = new TextBlock();
            _textBlock28.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock28, "FilledActions"));
            _textBlock28.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock28.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock28.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock28, "OnSurface"));
            _stackPanel26.AddChild(_textBlock28);
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, "  Elevated: ");
            _textBlock29.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock29.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock29, "OnSurfaceVariant"));
            _stackPanel26.AddChild(_textBlock29);
            const _textBlock30 = new TextBlock();
            _textBlock30.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock30, "ElevatedActions"));
            _textBlock30.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock30.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock30.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock30, "OnSurface"));
            _stackPanel26.AddChild(_textBlock30);
            const _textBlock31 = new TextBlock();
            _textBlock31.set_property_value(TextBlock.TextKey, "  Outlined: ");
            _textBlock31.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock31.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock31, "OnSurfaceVariant"));
            _stackPanel26.AddChild(_textBlock31);
            const _textBlock32 = new TextBlock();
            _textBlock32.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock32, "OutlinedActions"));
            _textBlock32.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock32.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock32.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock32, "OnSurface"));
            _stackPanel26.AddChild(_textBlock32);
            _stackPanel5.AddChild(_stackPanel26);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, CardVM);
        t.Set(CardVM, _tmpl0);
        return t;
    }
}
