import { CardVM } from "./card-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/basic";
import { Button, ButtonVariant } from "@visualisation-sub/mural/framework/button.js";
import { Card } from "@visualisation-sub/mural/framework/card.js";
import { DataContextBinding, DynamicResource, HorizontalAlignment, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_CardDemo = Symbol("CardDemo.ctor");
export class CardDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_CardDemo) {
            throw new Error("CardDemo is private — use CardDemo.Clone()");
        }
    }
    static Clone() {
        const t = new CardDemo(_gate_CardDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1._set_property_value_by_name("Background", DynamicResource(_border1, "Surface"));
            _border1._set_property_value_by_name("BorderBrush", DynamicResource(_border1, "OutlineVariant"));
            _border1._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border3._set_property_value_by_name("Background", DynamicResource(_border3, "Primary"));
            _border3._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4._set_property_value_by_name("Text", "Card — M3's content container. Three variants vary container colour, border, and resting elevation.");
            _textBlock4._set_property_value_by_name("FontSize", 15);
            _textBlock4._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock4._set_property_value_by_name("Foreground", DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel5._set_property_value_by_name("Margin", new Thickness(24, 24, 24, 24));
            const _textBlock6 = new TextBlock();
            _textBlock6._set_property_value_by_name("Text", "Card — Variant: Filled / Elevated / Outlined");
            _textBlock6._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock6._set_property_value_by_name("FontSize", 14);
            _textBlock6._set_property_value_by_name("Foreground", DynamicResource(_textBlock6, "OnSurface"));
            _textBlock6._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
            _stackPanel5.AddChild(_textBlock6);
            const _stackPanel7 = new StackPanel();
            _stackPanel7._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel7._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
            const _card8 = new Card();
            _card8._set_property_value_by_name("Variant", ButtonVariant.Filled);
            _card8._set_property_value_by_name("Width", 240);
            _card8._set_property_value_by_name("Margin", new Thickness(0, 0, 24, 0));
            const _stackPanel9 = new StackPanel();
            _stackPanel9._set_property_value_by_name("Orientation", Orientation.Vertical);
            const _textBlock10 = new TextBlock();
            _textBlock10._set_property_value_by_name("Text", "Filled");
            _textBlock10._set_property_value_by_name("FontFamily", DynamicResource(_textBlock10, "TitleMediumFont"));
            _textBlock10._set_property_value_by_name("FontWeight", DynamicResource(_textBlock10, "TitleMediumWeight"));
            _textBlock10._set_property_value_by_name("FontSize", DynamicResource(_textBlock10, "TitleMediumSize"));
            _textBlock10._set_property_value_by_name("LineHeight", DynamicResource(_textBlock10, "TitleMediumLineHeight"));
            _textBlock10._set_property_value_by_name("Foreground", DynamicResource(_textBlock10, "OnSurface"));
            _textBlock10._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            _stackPanel9.AddChild(_textBlock10);
            const _textBlock11 = new TextBlock();
            _textBlock11._set_property_value_by_name("Text", "SurfaceContainerHighest base, no border, no resting elevation. Hover bumps to Level1.");
            _textBlock11._set_property_value_by_name("FontFamily", DynamicResource(_textBlock11, "BodyMediumFont"));
            _textBlock11._set_property_value_by_name("FontSize", DynamicResource(_textBlock11, "BodyMediumSize"));
            _textBlock11._set_property_value_by_name("LineHeight", DynamicResource(_textBlock11, "BodyMediumLineHeight"));
            _textBlock11._set_property_value_by_name("Foreground", DynamicResource(_textBlock11, "OnSurfaceVariant"));
            _textBlock11._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
            _textBlock11._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
            _stackPanel9.AddChild(_textBlock11);
            const _button12 = new Button();
            _button12._set_property_value_by_name("Variant", ButtonVariant.Text);
            _button12._set_property_value_by_name("Command", DataContextBinding(_button12, "FilledActionCommand"));
            _button12._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Left);
            const _textBlock13 = new TextBlock();
            _textBlock13._set_property_value_by_name("Text", "Action");
            _button12.Content = _textBlock13;
            _stackPanel9.AddChild(_button12);
            _card8.Content = _stackPanel9;
            _stackPanel7.AddChild(_card8);
            const _card14 = new Card();
            _card14._set_property_value_by_name("Variant", ButtonVariant.Elevated);
            _card14._set_property_value_by_name("Width", 240);
            _card14._set_property_value_by_name("Margin", new Thickness(0, 0, 24, 0));
            const _stackPanel15 = new StackPanel();
            _stackPanel15._set_property_value_by_name("Orientation", Orientation.Vertical);
            const _textBlock16 = new TextBlock();
            _textBlock16._set_property_value_by_name("Text", "Elevated");
            _textBlock16._set_property_value_by_name("FontFamily", DynamicResource(_textBlock16, "TitleMediumFont"));
            _textBlock16._set_property_value_by_name("FontWeight", DynamicResource(_textBlock16, "TitleMediumWeight"));
            _textBlock16._set_property_value_by_name("FontSize", DynamicResource(_textBlock16, "TitleMediumSize"));
            _textBlock16._set_property_value_by_name("LineHeight", DynamicResource(_textBlock16, "TitleMediumLineHeight"));
            _textBlock16._set_property_value_by_name("Foreground", DynamicResource(_textBlock16, "OnSurface"));
            _textBlock16._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            _stackPanel15.AddChild(_textBlock16);
            const _textBlock17 = new TextBlock();
            _textBlock17._set_property_value_by_name("Text", "SurfaceContainerLow base, no border, resting ElevationLevel1. Hover bumps to Level2.");
            _textBlock17._set_property_value_by_name("FontFamily", DynamicResource(_textBlock17, "BodyMediumFont"));
            _textBlock17._set_property_value_by_name("FontSize", DynamicResource(_textBlock17, "BodyMediumSize"));
            _textBlock17._set_property_value_by_name("LineHeight", DynamicResource(_textBlock17, "BodyMediumLineHeight"));
            _textBlock17._set_property_value_by_name("Foreground", DynamicResource(_textBlock17, "OnSurfaceVariant"));
            _textBlock17._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
            _textBlock17._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
            _stackPanel15.AddChild(_textBlock17);
            const _button18 = new Button();
            _button18._set_property_value_by_name("Variant", ButtonVariant.Text);
            _button18._set_property_value_by_name("Command", DataContextBinding(_button18, "ElevatedActionCommand"));
            _button18._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Left);
            const _textBlock19 = new TextBlock();
            _textBlock19._set_property_value_by_name("Text", "Action");
            _button18.Content = _textBlock19;
            _stackPanel15.AddChild(_button18);
            _card14.Content = _stackPanel15;
            _stackPanel7.AddChild(_card14);
            const _card20 = new Card();
            _card20._set_property_value_by_name("Variant", ButtonVariant.Outlined);
            _card20._set_property_value_by_name("Width", 240);
            const _stackPanel21 = new StackPanel();
            _stackPanel21._set_property_value_by_name("Orientation", Orientation.Vertical);
            const _textBlock22 = new TextBlock();
            _textBlock22._set_property_value_by_name("Text", "Outlined");
            _textBlock22._set_property_value_by_name("FontFamily", DynamicResource(_textBlock22, "TitleMediumFont"));
            _textBlock22._set_property_value_by_name("FontWeight", DynamicResource(_textBlock22, "TitleMediumWeight"));
            _textBlock22._set_property_value_by_name("FontSize", DynamicResource(_textBlock22, "TitleMediumSize"));
            _textBlock22._set_property_value_by_name("LineHeight", DynamicResource(_textBlock22, "TitleMediumLineHeight"));
            _textBlock22._set_property_value_by_name("Foreground", DynamicResource(_textBlock22, "OnSurface"));
            _textBlock22._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            _stackPanel21.AddChild(_textBlock22);
            const _textBlock23 = new TextBlock();
            _textBlock23._set_property_value_by_name("Text", "Surface base, 1-DIP Outline border, no resting elevation. Hover bumps to Level1.");
            _textBlock23._set_property_value_by_name("FontFamily", DynamicResource(_textBlock23, "BodyMediumFont"));
            _textBlock23._set_property_value_by_name("FontSize", DynamicResource(_textBlock23, "BodyMediumSize"));
            _textBlock23._set_property_value_by_name("LineHeight", DynamicResource(_textBlock23, "BodyMediumLineHeight"));
            _textBlock23._set_property_value_by_name("Foreground", DynamicResource(_textBlock23, "OnSurfaceVariant"));
            _textBlock23._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
            _textBlock23._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
            _stackPanel21.AddChild(_textBlock23);
            const _button24 = new Button();
            _button24._set_property_value_by_name("Variant", ButtonVariant.Text);
            _button24._set_property_value_by_name("Command", DataContextBinding(_button24, "OutlinedActionCommand"));
            _button24._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Left);
            const _textBlock25 = new TextBlock();
            _textBlock25._set_property_value_by_name("Text", "Action");
            _button24.Content = _textBlock25;
            _stackPanel21.AddChild(_button24);
            _card20.Content = _stackPanel21;
            _stackPanel7.AddChild(_card20);
            _stackPanel5.AddChild(_stackPanel7);
            const _stackPanel26 = new StackPanel();
            _stackPanel26._set_property_value_by_name("Orientation", Orientation.Horizontal);
            const _textBlock27 = new TextBlock();
            _textBlock27._set_property_value_by_name("Text", "Actions — Filled: ");
            _textBlock27._set_property_value_by_name("FontSize", 12);
            _textBlock27._set_property_value_by_name("Foreground", DynamicResource(_textBlock27, "OnSurfaceVariant"));
            _stackPanel26.AddChild(_textBlock27);
            const _textBlock28 = new TextBlock();
            _textBlock28._set_property_value_by_name("Text", DataContextBinding(_textBlock28, "FilledActions"));
            _textBlock28._set_property_value_by_name("FontSize", 12);
            _textBlock28._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock28._set_property_value_by_name("Foreground", DynamicResource(_textBlock28, "OnSurface"));
            _stackPanel26.AddChild(_textBlock28);
            const _textBlock29 = new TextBlock();
            _textBlock29._set_property_value_by_name("Text", "  Elevated: ");
            _textBlock29._set_property_value_by_name("FontSize", 12);
            _textBlock29._set_property_value_by_name("Foreground", DynamicResource(_textBlock29, "OnSurfaceVariant"));
            _stackPanel26.AddChild(_textBlock29);
            const _textBlock30 = new TextBlock();
            _textBlock30._set_property_value_by_name("Text", DataContextBinding(_textBlock30, "ElevatedActions"));
            _textBlock30._set_property_value_by_name("FontSize", 12);
            _textBlock30._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock30._set_property_value_by_name("Foreground", DynamicResource(_textBlock30, "OnSurface"));
            _stackPanel26.AddChild(_textBlock30);
            const _textBlock31 = new TextBlock();
            _textBlock31._set_property_value_by_name("Text", "  Outlined: ");
            _textBlock31._set_property_value_by_name("FontSize", 12);
            _textBlock31._set_property_value_by_name("Foreground", DynamicResource(_textBlock31, "OnSurfaceVariant"));
            _stackPanel26.AddChild(_textBlock31);
            const _textBlock32 = new TextBlock();
            _textBlock32._set_property_value_by_name("Text", DataContextBinding(_textBlock32, "OutlinedActions"));
            _textBlock32._set_property_value_by_name("FontSize", 12);
            _textBlock32._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock32._set_property_value_by_name("Foreground", DynamicResource(_textBlock32, "OnSurface"));
            _stackPanel26.AddChild(_textBlock32);
            _stackPanel5.AddChild(_stackPanel26);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, CardVM);
        t.Set("CardTemplate", _tmpl0);
        return t;
    }
    get CardTemplate() { return this.Resolve("CardTemplate"); }
    set CardTemplate(v) { this.Set("CardTemplate", v); }
}
