import { Border, Button, DataTemplate, DockPanel, ListBox, ListBoxItem, Orientation, SelectionMode, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { Color, NameScope, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2.SetNameScope(new NameScope());
        _border2._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4._set_property_value_by_name(DockPanel, "Dock", "Top");
        _border4._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border4._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock5 = new TextBlock();
        _textBlock5._set_property_value_by_name("Text", "ListBox demo — declarative vs. Items");
        _textBlock5._set_property_value_by_name("FontSize", 15);
        _textBlock5._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock5._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border4.SetChild(_textBlock5);
        _dockPanel3.AddChild(_border4);
        const _stackPanel6 = new StackPanel();
        _stackPanel6._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _stackPanel7 = new StackPanel();
        _stackPanel7._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel7._set_property_value_by_name("Width", 240);
        _stackPanel7._set_property_value_by_name("Margin", new Thickness(12, 12, 6, 12));
        const _textBlock8 = new TextBlock();
        _textBlock8._set_property_value_by_name("Text", "Declarative");
        _textBlock8._set_property_value_by_name("FontSize", 12);
        _textBlock8._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock8._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel7.AddChild(_textBlock8);
        const _listBox9 = new ListBox();
        _listBox9._set_property_value_by_name("SelectionMode", SelectionMode.Extended);
        const _listBoxItem10 = new ListBoxItem();
        const _textBlock11 = new TextBlock();
        _textBlock11._set_property_value_by_name("Text", "Apples");
        _listBoxItem10.Content = _textBlock11;
        _listBox9.AddChild(_listBoxItem10);
        const _listBoxItem12 = new ListBoxItem();
        const _textBlock13 = new TextBlock();
        _textBlock13._set_property_value_by_name("Text", "Bananas");
        _listBoxItem12.Content = _textBlock13;
        _listBox9.AddChild(_listBoxItem12);
        const _listBoxItem14 = new ListBoxItem();
        const _textBlock15 = new TextBlock();
        _textBlock15._set_property_value_by_name("Text", "Cherries");
        _listBoxItem14.Content = _textBlock15;
        _listBox9.AddChild(_listBoxItem14);
        const _listBoxItem16 = new ListBoxItem();
        const _textBlock17 = new TextBlock();
        _textBlock17._set_property_value_by_name("Text", "Durian");
        _listBoxItem16.Content = _textBlock17;
        _listBox9.AddChild(_listBoxItem16);
        const _listBoxItem18 = new ListBoxItem();
        const _textBlock19 = new TextBlock();
        _textBlock19._set_property_value_by_name("Text", "Elderberry");
        _listBoxItem18.Content = _textBlock19;
        _listBox9.AddChild(_listBoxItem18);
        const _listBoxItem20 = new ListBoxItem();
        const _textBlock21 = new TextBlock();
        _textBlock21._set_property_value_by_name("Text", "Fig");
        _listBoxItem20.Content = _textBlock21;
        _listBox9.AddChild(_listBoxItem20);
        _stackPanel7.AddChild(_listBox9);
        _stackPanel6.AddChild(_stackPanel7);
        const _border22 = new Border();
        _border22._set_property_value_by_name("Width", 1);
        _border22._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#e0e0e0')));
        _border22._set_property_value_by_name("Margin", new Thickness(0, 12, 0, 12));
        _stackPanel6.AddChild(_border22);
        const _stackPanel23 = new StackPanel();
        _stackPanel23._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel23._set_property_value_by_name("Width", 240);
        _stackPanel23._set_property_value_by_name("Margin", new Thickness(6, 12, 6, 12));
        const _textBlock24 = new TextBlock();
        _textBlock24._set_property_value_by_name("Text", "Items=[…] convenience");
        _textBlock24._set_property_value_by_name("FontSize", 12);
        _textBlock24._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock24._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel23.AddChild(_textBlock24);
        const _listBox25 = new ListBox();
        _listBox25._set_property_value_by_name("Items", ["Red", "Green", "Blue", "Yellow", "Magenta", "Cyan"]);
        _stackPanel23.AddChild(_listBox25);
        _stackPanel6.AddChild(_stackPanel23);
        const _border26 = new Border();
        _border26._set_property_value_by_name("Width", 1);
        _border26._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#e0e0e0')));
        _border26._set_property_value_by_name("Margin", new Thickness(0, 12, 0, 12));
        _stackPanel6.AddChild(_border26);
        const _stackPanel27 = new StackPanel();
        _stackPanel27._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel27._set_property_value_by_name("Width", 240);
        _stackPanel27._set_property_value_by_name("Margin", new Thickness(6, 12, 12, 12));
        const _textBlock28 = new TextBlock();
        _textBlock28._set_property_value_by_name("Text", "ItemsSource + CollectionView");
        _textBlock28._set_property_value_by_name("FontSize", 12);
        _textBlock28._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock28._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        _stackPanel27.AddChild(_textBlock28);
        const _stackPanel29 = new StackPanel();
        _stackPanel29._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel29._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        const _button30 = new Button();
        _button30.Name = "btnSort";
        _border2.nameScope.Register("btnSort", _button30);
        _button30._set_property_value_by_name("Margin", new Thickness(0, 0, 4, 0));
        const _textBlock31 = new TextBlock();
        _textBlock31._set_property_value_by_name("Text", "Sort A↕Z");
        _textBlock31._set_property_value_by_name("FontSize", 11);
        _button30.Content = _textBlock31;
        _stackPanel29.AddChild(_button30);
        const _button32 = new Button();
        _button32.Name = "btnFilter";
        _border2.nameScope.Register("btnFilter", _button32);
        const _textBlock33 = new TextBlock();
        _textBlock33._set_property_value_by_name("Text", "Engineers only");
        _textBlock33._set_property_value_by_name("FontSize", 11);
        _button32.Content = _textBlock33;
        _stackPanel29.AddChild(_button32);
        _stackPanel27.AddChild(_stackPanel29);
        const _textBlock34 = new TextBlock();
        _textBlock34.Name = "statusLine";
        _border2.nameScope.Register("statusLine", _textBlock34);
        _textBlock34._set_property_value_by_name("Text", "6 of 6 visible");
        _textBlock34._set_property_value_by_name("FontSize", 10);
        _textBlock34._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#1976d2')));
        _textBlock34._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 4));
        _stackPanel27.AddChild(_textBlock34);
        const _listBox35 = new ListBox();
        _listBox35.Name = "bound";
        _border2.nameScope.Register("bound", _listBox35);
        _stackPanel27.AddChild(_listBox35);
        _stackPanel6.AddChild(_stackPanel27);
        _dockPanel3.AddChild(_stackPanel6);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, "ListBoxVM");
    _rd0.Set("ListBoxTemplate", _tmpl1);
    return _rd0;
}
