import { ListBoxVM } from "./list-box-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock, TextWrapping } from "@pragmatic-lab/mural/basic";
import { Button } from "@pragmatic-lab/mural/framework/buttons/button.js";
import { ListBox, ListBoxItem, SelectionMode } from "@pragmatic-lab/mural/framework/list/list-box.js";
import { DynamicResource, NameScope, ResourceDictionary, Thickness } from "@pragmatic-lab/mural/runtime";
import { FontWeight, Pen } from "@pragmatic-lab/mural/visual-engine";


const _gate_ListBoxDemo = Symbol("ListBoxDemo.ctor");
export class ListBoxDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_ListBoxDemo) {
            throw new Error("ListBoxDemo is private — use ListBoxDemo.Clone()");
        }
    }
    static Clone() {
        const t = new ListBoxDemo(_gate_ListBoxDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            let _button1, _button2, _textBlock3, _listBox4;
            const _border5 = new Border();
            _border5.SetNameScope(new NameScope());
            _border5.set_property_value(Border.FillKey, DynamicResource(_border5, "Surface"));
            _border5.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            const _dockPanel6 = new DockPanel();
            const _border7 = new Border();
            _border7.set_property_value(DockPanel.DockKey, Dock.Top);
            _border7.set_property_value(Border.FillKey, DynamicResource(_border7, "Primary"));
            _border7.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _textBlock8 = new TextBlock();
            _textBlock8.set_property_value(TextBlock.TextKey, "ListBox demo — declarative vs. Items");
            _textBlock8.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock8.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock8.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock8, "OnPrimary"));
            _border7.SetChild(_textBlock8);
            _dockPanel6.AddChild(_border7);
            const _stackPanel9 = new StackPanel();
            _stackPanel9.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _stackPanel10 = new StackPanel();
            _stackPanel10.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel10.set_property_value(StackPanel.WidthKey, 240);
            _stackPanel10.set_property_value(StackPanel.MarginKey, new Thickness(12, 12, 6, 12));
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "Declarative + marquee select");
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock11.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock11.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel10.AddChild(_textBlock11);
            const _textBlock12 = new TextBlock();
            _textBlock12.set_property_value(TextBlock.TextKey, "Drag in empty space to marquee-select. Ctrl=add. Shift=extend.");
            _textBlock12.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock12.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock12, "OnSurfaceVariant"));
            _textBlock12.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock12.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel10.AddChild(_textBlock12);
            const _listBox13 = new ListBox();
            _listBox13.set_property_value(ListBox.SelectionModeKey, SelectionMode.Extended);
            _listBox13.set_property_value(ListBox.AllowMarqueeSelectionKey, true);
            const _listBoxItem14 = new ListBoxItem();
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, "Apples");
            _listBoxItem14.Content = _textBlock15;
            _listBox13.AddChild(_listBoxItem14);
            const _listBoxItem16 = new ListBoxItem();
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "Bananas");
            _listBoxItem16.Content = _textBlock17;
            _listBox13.AddChild(_listBoxItem16);
            const _listBoxItem18 = new ListBoxItem();
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "Cherries");
            _listBoxItem18.Content = _textBlock19;
            _listBox13.AddChild(_listBoxItem18);
            const _listBoxItem20 = new ListBoxItem();
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "Durian");
            _listBoxItem20.Content = _textBlock21;
            _listBox13.AddChild(_listBoxItem20);
            const _listBoxItem22 = new ListBoxItem();
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, "Elderberry");
            _listBoxItem22.Content = _textBlock23;
            _listBox13.AddChild(_listBoxItem22);
            const _listBoxItem24 = new ListBoxItem();
            const _textBlock25 = new TextBlock();
            _textBlock25.set_property_value(TextBlock.TextKey, "Fig");
            _listBoxItem24.Content = _textBlock25;
            _listBox13.AddChild(_listBoxItem24);
            const _listBoxItem26 = new ListBoxItem();
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, "Grape");
            _listBoxItem26.Content = _textBlock27;
            _listBox13.AddChild(_listBoxItem26);
            const _listBoxItem28 = new ListBoxItem();
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, "Honeydew");
            _listBoxItem28.Content = _textBlock29;
            _listBox13.AddChild(_listBoxItem28);
            const _listBoxItem30 = new ListBoxItem();
            const _textBlock31 = new TextBlock();
            _textBlock31.set_property_value(TextBlock.TextKey, "Kiwi");
            _listBoxItem30.Content = _textBlock31;
            _listBox13.AddChild(_listBoxItem30);
            const _listBoxItem32 = new ListBoxItem();
            const _textBlock33 = new TextBlock();
            _textBlock33.set_property_value(TextBlock.TextKey, "Lemon");
            _listBoxItem32.Content = _textBlock33;
            _listBox13.AddChild(_listBoxItem32);
            _stackPanel10.AddChild(_listBox13);
            _stackPanel9.AddChild(_stackPanel10);
            const _border34 = new Border();
            _border34.set_property_value(Border.WidthKey, 1);
            _border34.set_property_value(Border.FillKey, DynamicResource(_border34, "OutlineVariant"));
            _border34.set_property_value(Border.MarginKey, new Thickness(0, 12, 0, 12));
            _stackPanel9.AddChild(_border34);
            const _stackPanel35 = new StackPanel();
            _stackPanel35.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel35.set_property_value(StackPanel.WidthKey, 240);
            _stackPanel35.set_property_value(StackPanel.MarginKey, new Thickness(6, 12, 6, 12));
            const _textBlock36 = new TextBlock();
            _textBlock36.set_property_value(TextBlock.TextKey, "Items=[…] convenience");
            _textBlock36.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock36.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock36.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel35.AddChild(_textBlock36);
            const _listBox37 = new ListBox();
            _listBox37.set_property_value(ListBox.ItemsKey, ["Red", "Green", "Blue", "Yellow", "Magenta", "Cyan"]);
            _stackPanel35.AddChild(_listBox37);
            _stackPanel9.AddChild(_stackPanel35);
            const _border38 = new Border();
            _border38.set_property_value(Border.WidthKey, 1);
            _border38.set_property_value(Border.FillKey, DynamicResource(_border38, "OutlineVariant"));
            _border38.set_property_value(Border.MarginKey, new Thickness(0, 12, 0, 12));
            _stackPanel9.AddChild(_border38);
            const _stackPanel39 = new StackPanel();
            _stackPanel39.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel39.set_property_value(StackPanel.WidthKey, 240);
            _stackPanel39.set_property_value(StackPanel.MarginKey, new Thickness(6, 12, 12, 12));
            const _textBlock40 = new TextBlock();
            _textBlock40.set_property_value(TextBlock.TextKey, "ItemsSource + CollectionView");
            _textBlock40.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock40.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock40.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel39.AddChild(_textBlock40);
            const _stackPanel41 = new StackPanel();
            _stackPanel41.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel41.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 8));
            _button1 = new Button();
            _button1.Name = "btnSort";
            _button1.set_property_value(Button.MarginKey, new Thickness(0, 0, 4, 0));
            const _textBlock42 = new TextBlock();
            _textBlock42.set_property_value(TextBlock.TextKey, "Sort A↕Z");
            _textBlock42.set_property_value(TextBlock.FontSizeKey, 11);
            _button1.Content = _textBlock42;
            _stackPanel41.AddChild(_button1);
            _button2 = new Button();
            _button2.Name = "btnFilter";
            const _textBlock43 = new TextBlock();
            _textBlock43.set_property_value(TextBlock.TextKey, "Engineers only");
            _textBlock43.set_property_value(TextBlock.FontSizeKey, 11);
            _button2.Content = _textBlock43;
            _stackPanel41.AddChild(_button2);
            _stackPanel39.AddChild(_stackPanel41);
            _textBlock3 = new TextBlock();
            _textBlock3.Name = "statusLine";
            _textBlock3.set_property_value(TextBlock.TextKey, "6 of 6 visible");
            _textBlock3.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock3.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock3, "Primary"));
            _textBlock3.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel39.AddChild(_textBlock3);
            _listBox4 = new ListBox();
            _listBox4.Name = "bound";
            _stackPanel39.AddChild(_listBox4);
            _stackPanel9.AddChild(_stackPanel39);
            _dockPanel6.AddChild(_stackPanel9);
            _border5.SetChild(_dockPanel6);
            return _border5;
        }, ListBoxVM);
        t.Set(ListBoxVM, _tmpl0);
        return t;
    }
}
