import { ListBoxVM } from "./list-box-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/basic";
import { Button } from "@visualisation-sub/mural/framework/button.js";
import { ListBox, ListBoxItem, SelectionMode } from "@visualisation-sub/mural/framework/list/list-box.js";
import { DynamicResource, NameScope, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_ListBoxDemo = Symbol("ListBoxDemo.ctor");
export class ListBoxDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_ListBoxDemo) {
            throw new Error("ListBoxDemo is private — use ListBoxDemo.Clone()");
        }
    }
    static Clone() {
        const t = new ListBoxDemo(_gate_ListBoxDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.SetNameScope(new NameScope());
            _border1.set_property_value(Border.BackgroundKey, DynamicResource(_border1, "Surface"));
            _border1.set_property_value(Border.BorderBrushKey, DynamicResource(_border1, "OutlineVariant"));
            _border1.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.BackgroundKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(16, 12, 16, 12));
            const _textBlock4 = new TextBlock();
            _textBlock4.set_property_value(TextBlock.TextKey, "ListBox demo — declarative vs. Items");
            _textBlock4.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock4.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock4.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock4, "OnPrimary"));
            _border3.SetChild(_textBlock4);
            _dockPanel2.AddChild(_border3);
            const _stackPanel5 = new StackPanel();
            _stackPanel5.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _stackPanel6 = new StackPanel();
            _stackPanel6.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel6.set_property_value(StackPanel.WidthKey, 240);
            _stackPanel6.set_property_value(StackPanel.MarginKey, new Thickness(12, 12, 6, 12));
            const _textBlock7 = new TextBlock();
            _textBlock7.set_property_value(TextBlock.TextKey, "Declarative + marquee select");
            _textBlock7.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock7.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock7.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel6.AddChild(_textBlock7);
            const _textBlock8 = new TextBlock();
            _textBlock8.set_property_value(TextBlock.TextKey, "Drag in empty space to marquee-select. Ctrl=add. Shift=extend.");
            _textBlock8.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock8.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock8, "OnSurfaceVariant"));
            _textBlock8.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock8.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel6.AddChild(_textBlock8);
            const _listBox9 = new ListBox();
            _listBox9.set_property_value(ListBox.SelectionModeKey, SelectionMode.Extended);
            _listBox9.set_property_value(ListBox.AllowMarqueeSelectionKey, true);
            const _listBoxItem10 = new ListBoxItem();
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "Apples");
            _listBoxItem10.Content = _textBlock11;
            _listBox9.AddChild(_listBoxItem10);
            const _listBoxItem12 = new ListBoxItem();
            const _textBlock13 = new TextBlock();
            _textBlock13.set_property_value(TextBlock.TextKey, "Bananas");
            _listBoxItem12.Content = _textBlock13;
            _listBox9.AddChild(_listBoxItem12);
            const _listBoxItem14 = new ListBoxItem();
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, "Cherries");
            _listBoxItem14.Content = _textBlock15;
            _listBox9.AddChild(_listBoxItem14);
            const _listBoxItem16 = new ListBoxItem();
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "Durian");
            _listBoxItem16.Content = _textBlock17;
            _listBox9.AddChild(_listBoxItem16);
            const _listBoxItem18 = new ListBoxItem();
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "Elderberry");
            _listBoxItem18.Content = _textBlock19;
            _listBox9.AddChild(_listBoxItem18);
            const _listBoxItem20 = new ListBoxItem();
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "Fig");
            _listBoxItem20.Content = _textBlock21;
            _listBox9.AddChild(_listBoxItem20);
            const _listBoxItem22 = new ListBoxItem();
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, "Grape");
            _listBoxItem22.Content = _textBlock23;
            _listBox9.AddChild(_listBoxItem22);
            const _listBoxItem24 = new ListBoxItem();
            const _textBlock25 = new TextBlock();
            _textBlock25.set_property_value(TextBlock.TextKey, "Honeydew");
            _listBoxItem24.Content = _textBlock25;
            _listBox9.AddChild(_listBoxItem24);
            const _listBoxItem26 = new ListBoxItem();
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, "Kiwi");
            _listBoxItem26.Content = _textBlock27;
            _listBox9.AddChild(_listBoxItem26);
            const _listBoxItem28 = new ListBoxItem();
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, "Lemon");
            _listBoxItem28.Content = _textBlock29;
            _listBox9.AddChild(_listBoxItem28);
            _stackPanel6.AddChild(_listBox9);
            _stackPanel5.AddChild(_stackPanel6);
            const _border30 = new Border();
            _border30.set_property_value(Border.WidthKey, 1);
            _border30.set_property_value(Border.BackgroundKey, DynamicResource(_border30, "OutlineVariant"));
            _border30.set_property_value(Border.MarginKey, new Thickness(0, 12, 0, 12));
            _stackPanel5.AddChild(_border30);
            const _stackPanel31 = new StackPanel();
            _stackPanel31.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel31.set_property_value(StackPanel.WidthKey, 240);
            _stackPanel31.set_property_value(StackPanel.MarginKey, new Thickness(6, 12, 6, 12));
            const _textBlock32 = new TextBlock();
            _textBlock32.set_property_value(TextBlock.TextKey, "Items=[…] convenience");
            _textBlock32.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock32.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock32.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel31.AddChild(_textBlock32);
            const _listBox33 = new ListBox();
            _listBox33.set_property_value(ListBox.ItemsKey, ["Red", "Green", "Blue", "Yellow", "Magenta", "Cyan"]);
            _stackPanel31.AddChild(_listBox33);
            _stackPanel5.AddChild(_stackPanel31);
            const _border34 = new Border();
            _border34.set_property_value(Border.WidthKey, 1);
            _border34.set_property_value(Border.BackgroundKey, DynamicResource(_border34, "OutlineVariant"));
            _border34.set_property_value(Border.MarginKey, new Thickness(0, 12, 0, 12));
            _stackPanel5.AddChild(_border34);
            const _stackPanel35 = new StackPanel();
            _stackPanel35.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel35.set_property_value(StackPanel.WidthKey, 240);
            _stackPanel35.set_property_value(StackPanel.MarginKey, new Thickness(6, 12, 12, 12));
            const _textBlock36 = new TextBlock();
            _textBlock36.set_property_value(TextBlock.TextKey, "ItemsSource + CollectionView");
            _textBlock36.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock36.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock36.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _stackPanel35.AddChild(_textBlock36);
            const _stackPanel37 = new StackPanel();
            _stackPanel37.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel37.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 8));
            const _button38 = new Button();
            _button38.Name = "btnSort";
            _button38.set_property_value(Button.MarginKey, new Thickness(0, 0, 4, 0));
            const _textBlock39 = new TextBlock();
            _textBlock39.set_property_value(TextBlock.TextKey, "Sort A↕Z");
            _textBlock39.set_property_value(TextBlock.FontSizeKey, 11);
            _button38.Content = _textBlock39;
            _stackPanel37.AddChild(_button38);
            const _button40 = new Button();
            _button40.Name = "btnFilter";
            const _textBlock41 = new TextBlock();
            _textBlock41.set_property_value(TextBlock.TextKey, "Engineers only");
            _textBlock41.set_property_value(TextBlock.FontSizeKey, 11);
            _button40.Content = _textBlock41;
            _stackPanel37.AddChild(_button40);
            _stackPanel35.AddChild(_stackPanel37);
            const _textBlock42 = new TextBlock();
            _textBlock42.Name = "statusLine";
            _textBlock42.set_property_value(TextBlock.TextKey, "6 of 6 visible");
            _textBlock42.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock42.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock42, "Primary"));
            _textBlock42.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel35.AddChild(_textBlock42);
            const _listBox43 = new ListBox();
            _listBox43.Name = "bound";
            _stackPanel35.AddChild(_listBox43);
            _stackPanel5.AddChild(_stackPanel35);
            _dockPanel2.AddChild(_stackPanel5);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, ListBoxVM);
        t.Set("ListBoxTemplate", _tmpl0);
        return t;
    }
    get ListBoxTemplate() { return this.Resolve("ListBoxTemplate"); }
    set ListBoxTemplate(v) { this.Set("ListBoxTemplate", v); }
}
