import { DrawerVM } from "./drawer-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock, TextWrapping } from "@pragmatic-lab/mural/basic";
import { Button } from "@pragmatic-lab/mural/framework/buttons/button.js";
import { Drawer, DrawerVariant } from "@pragmatic-lab/mural/framework/surfaces/drawer.js";
import { DataContextBinding, DynamicResource, ResourceDictionary, Thickness } from "@pragmatic-lab/mural/runtime";
import { FontWeight } from "@pragmatic-lab/mural/visual-engine";


const _gate_DrawerDemo = Symbol("DrawerDemo.ctor");
export class DrawerDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_DrawerDemo) {
            throw new Error("DrawerDemo is private — use DrawerDemo.Clone()");
        }
    }
    static Clone() {
        const t = new DrawerDemo(_gate_DrawerDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.set_property_value(Border.FillKey, DynamicResource(_border1, "Surface"));
            _border1.set_property_value(Border.BorderBrushKey, DynamicResource(_border1, "OutlineVariant"));
            _border1.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.HeightKey, 56);
            _border3.set_property_value(Border.FillKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 0, 0));
            const _stackPanel4 = new StackPanel();
            _stackPanel4.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _button5 = new Button();
            _button5.set_property_value(Button.WidthKey, 44);
            _button5.set_property_value(Button.CommandKey, DataContextBinding(_button5, "ToggleNav"));
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "≡");
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 20);
            _button5.Content = _textBlock6;
            _stackPanel4.AddChild(_button5);
            const _textBlock7 = new TextBlock();
            _textBlock7.set_property_value(TextBlock.TextKey, "Drawer demo");
            _textBlock7.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock7.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock7.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock7, "OnPrimary"));
            _textBlock7.set_property_value(TextBlock.MarginKey, new Thickness(16, 16, 0, 0));
            _stackPanel4.AddChild(_textBlock7);
            _border3.SetChild(_stackPanel4);
            _dockPanel2.AddChild(_border3);
            const _drawer8 = new Drawer();
            _drawer8.set_property_value(DockPanel.DockKey, Dock.Left);
            _drawer8.set_property_value(Drawer.VariantKey, DrawerVariant.Persistent);
            _drawer8.set_property_value(Drawer.AnchorKey, Dock.Left);
            _drawer8.set_property_value(Drawer.DrawerSizeKey, 200);
            _drawer8.set_property_value(Drawer.RailSizeKey, 56);
            _drawer8.set_property_value(Drawer.IsOpenKey, DataContextBinding(_drawer8, "NavOpen"));
            const _border9 = new Border();
            _border9.set_property_value(Border.FillKey, DynamicResource(_border9, "SurfaceContainerLow"));
            _border9.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 1, 0));
            _border9.set_property_value(Border.BorderBrushKey, DynamicResource(_border9, "OutlineVariant"));
            const _stackPanel10 = new StackPanel();
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "🏠");
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock11.set_property_value(TextBlock.MarginKey, new Thickness(20, 16, 0, 0));
            _stackPanel10.AddChild(_textBlock11);
            const _textBlock12 = new TextBlock();
            _textBlock12.set_property_value(TextBlock.TextKey, "📊");
            _textBlock12.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock12.set_property_value(TextBlock.MarginKey, new Thickness(20, 16, 0, 0));
            _stackPanel10.AddChild(_textBlock12);
            const _textBlock13 = new TextBlock();
            _textBlock13.set_property_value(TextBlock.TextKey, "⚙");
            _textBlock13.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock13.set_property_value(TextBlock.MarginKey, new Thickness(20, 16, 0, 0));
            _stackPanel10.AddChild(_textBlock13);
            _border9.SetChild(_stackPanel10);
            _drawer8.Content = _border9;
            _dockPanel2.AddChild(_drawer8);
            const _drawer14 = new Drawer();
            _drawer14.set_property_value(Drawer.VariantKey, DrawerVariant.Temporary);
            _drawer14.set_property_value(Drawer.AnchorKey, Dock.Right);
            _drawer14.set_property_value(Drawer.DrawerSizeKey, 320);
            _drawer14.set_property_value(Drawer.IsOpenKey, DataContextBinding(_drawer14, "OptionsOpen"));
            const _border15 = new Border();
            _border15.set_property_value(Border.FillKey, DynamicResource(_border15, "Surface"));
            _border15.set_property_value(Border.BorderThicknessKey, new Thickness(1, 0, 0, 0));
            _border15.set_property_value(Border.BorderBrushKey, DynamicResource(_border15, "OutlineVariant"));
            _border15.set_property_value(Border.PaddingKey, new Thickness(24));
            const _stackPanel16 = new StackPanel();
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "Options");
            _textBlock17.set_property_value(TextBlock.FontSizeKey, 20);
            _textBlock17.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock17.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock17, "OnSurface"));
            _stackPanel16.AddChild(_textBlock17);
            const _textBlock18 = new TextBlock();
            _textBlock18.set_property_value(TextBlock.TextKey, "Drag the slider, flip the\n                                            toggles, pick a colour.\n                                            Click outside to dismiss.");
            _textBlock18.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock18.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock18.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock18, "OnSurfaceVariant"));
            _textBlock18.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel16.AddChild(_textBlock18);
            const _button19 = new Button();
            _button19.set_property_value(Button.CommandKey, DataContextBinding(_button19, "CloseOptions"));
            _button19.set_property_value(Button.MarginKey, new Thickness(0, 24, 0, 0));
            _button19.set_property_value(Button.WidthKey, 120);
            const _textBlock20 = new TextBlock();
            _textBlock20.set_property_value(TextBlock.TextKey, "Close");
            _button19.Content = _textBlock20;
            _stackPanel16.AddChild(_button19);
            _border15.SetChild(_stackPanel16);
            _drawer14.Content = _border15;
            _dockPanel2.AddChild(_drawer14);
            const _border21 = new Border();
            _border21.set_property_value(Border.FillKey, DynamicResource(_border21, "Surface"));
            _border21.set_property_value(Border.PaddingKey, new Thickness(24));
            const _stackPanel22 = new StackPanel();
            const _textBlock23 = new TextBlock();
            _textBlock23.set_property_value(TextBlock.TextKey, "The left drawer is Persistent —\n                                        the rail is always visible (56\n                                        DIPs); the header button toggles\n                                        the pane open / closed (200 DIPs).");
            _textBlock23.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock23.set_property_value(TextBlock.FontSizeKey, 13);
            _textBlock23.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock23, "OnSurface"));
            _stackPanel22.AddChild(_textBlock23);
            const _button24 = new Button();
            _button24.set_property_value(Button.CommandKey, DataContextBinding(_button24, "OpenOptions"));
            _button24.set_property_value(Button.WidthKey, 180);
            _button24.set_property_value(Button.MarginKey, new Thickness(0, 16, 0, 0));
            const _textBlock25 = new TextBlock();
            _textBlock25.set_property_value(TextBlock.TextKey, "Open options →");
            _button24.Content = _textBlock25;
            _stackPanel22.AddChild(_button24);
            const _textBlock26 = new TextBlock();
            _textBlock26.set_property_value(TextBlock.TextKey, "The Options pane is Temporary —\n                                        it mounts onto the overlay layer\n                                        with a click-away scrim. Click\n                                        the scrim or the Close button to\n                                        dismiss.");
            _textBlock26.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock26.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock26.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock26, "OnSurfaceVariant"));
            _textBlock26.set_property_value(TextBlock.MarginKey, new Thickness(0, 16, 0, 0));
            _stackPanel22.AddChild(_textBlock26);
            _border21.SetChild(_stackPanel22);
            _dockPanel2.AddChild(_border21);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, DrawerVM);
        t.Set(DrawerVM, _tmpl0);
        return t;
    }
}
