import { Border, Button, DataTemplate, DockPanel, Drawer, Orientation, StackPanel, TextBlock, TextWrapping } from "@visualisation-sub/mural/Controls";
import { Color, DataContextBinding, ResourceDictionary, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2.set_property_value("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2.set_property_value("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2.set_property_value("BorderThickness", new Thickness(1));
        const _dockPanel3 = new DockPanel();
        const _border4 = new Border();
        _border4.set_property_value(DockPanel, "Dock", "Top");
        _border4.set_property_value("Height", 56);
        _border4.set_property_value("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border4.set_property_value("BorderThickness", new Thickness(0, 0, 0, 0));
        const _stackPanel5 = new StackPanel();
        _stackPanel5.set_property_value("Orientation", Orientation.Horizontal);
        const _button6 = new Button();
        _button6.set_property_value("Width", 44);
        _button6.set_property_value("Command", DataContextBinding(_button6, "ToggleNav"));
        const _textBlock7 = new TextBlock();
        _textBlock7.set_property_value("Text", "≡");
        _textBlock7.set_property_value("FontSize", 20);
        _button6.Content = _textBlock7;
        _stackPanel5.AddChild(_button6);
        const _textBlock8 = new TextBlock();
        _textBlock8.set_property_value("Text", "Drawer demo");
        _textBlock8.set_property_value("FontSize", 18);
        _textBlock8.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock8.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _textBlock8.set_property_value("Margin", new Thickness(16, 16, 0, 0));
        _stackPanel5.AddChild(_textBlock8);
        _border4.SetChild(_stackPanel5);
        _dockPanel3.AddChild(_border4);
        const _drawer9 = new Drawer();
        _drawer9.set_property_value(DockPanel, "Dock", "Left");
        _drawer9.set_property_value("Variant", "Persistent");
        _drawer9.set_property_value("Anchor", "Left");
        _drawer9.set_property_value("DrawerSize", 200);
        _drawer9.set_property_value("RailSize", 56);
        _drawer9.set_property_value("IsOpen", DataContextBinding(_drawer9, "NavOpen"));
        const _border10 = new Border();
        _border10.set_property_value("Background", new SolidColorBrush(Color.FromHex('#f8fafc')));
        _border10.set_property_value("BorderThickness", new Thickness(0, 0, 1, 0));
        _border10.set_property_value("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        const _stackPanel11 = new StackPanel();
        const _textBlock12 = new TextBlock();
        _textBlock12.set_property_value("Text", "🏠");
        _textBlock12.set_property_value("FontSize", 18);
        _textBlock12.set_property_value("Margin", new Thickness(20, 16, 0, 0));
        _stackPanel11.AddChild(_textBlock12);
        const _textBlock13 = new TextBlock();
        _textBlock13.set_property_value("Text", "📊");
        _textBlock13.set_property_value("FontSize", 18);
        _textBlock13.set_property_value("Margin", new Thickness(20, 16, 0, 0));
        _stackPanel11.AddChild(_textBlock13);
        const _textBlock14 = new TextBlock();
        _textBlock14.set_property_value("Text", "⚙");
        _textBlock14.set_property_value("FontSize", 18);
        _textBlock14.set_property_value("Margin", new Thickness(20, 16, 0, 0));
        _stackPanel11.AddChild(_textBlock14);
        _border10.SetChild(_stackPanel11);
        _drawer9.Content = _border10;
        _dockPanel3.AddChild(_drawer9);
        const _drawer15 = new Drawer();
        _drawer15.set_property_value("Variant", "Temporary");
        _drawer15.set_property_value("Anchor", "Right");
        _drawer15.set_property_value("DrawerSize", 320);
        _drawer15.set_property_value("IsOpen", DataContextBinding(_drawer15, "OptionsOpen"));
        const _border16 = new Border();
        _border16.set_property_value("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border16.set_property_value("BorderThickness", new Thickness(1, 0, 0, 0));
        _border16.set_property_value("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border16.set_property_value("Padding", new Thickness(24));
        const _stackPanel17 = new StackPanel();
        const _textBlock18 = new TextBlock();
        _textBlock18.set_property_value("Text", "Options");
        _textBlock18.set_property_value("FontSize", 20);
        _textBlock18.set_property_value("FontWeight", FontWeight.Bold);
        _textBlock18.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#1f2937')));
        _stackPanel17.AddChild(_textBlock18);
        const _textBlock19 = new TextBlock();
        _textBlock19.set_property_value("Text", "Drag the slider, flip the\n                                            toggles, pick a colour.\n                                            Click outside to dismiss.");
        _textBlock19.set_property_value("TextWrapping", TextWrapping.Wrap);
        _textBlock19.set_property_value("FontSize", 12);
        _textBlock19.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock19.set_property_value("Margin", new Thickness(0, 8, 0, 0));
        _stackPanel17.AddChild(_textBlock19);
        const _button20 = new Button();
        _button20.set_property_value("Command", DataContextBinding(_button20, "CloseOptions"));
        _button20.set_property_value("Margin", new Thickness(0, 24, 0, 0));
        _button20.set_property_value("Width", 120);
        const _textBlock21 = new TextBlock();
        _textBlock21.set_property_value("Text", "Close");
        _button20.Content = _textBlock21;
        _stackPanel17.AddChild(_button20);
        _border16.SetChild(_stackPanel17);
        _drawer15.Content = _border16;
        _dockPanel3.AddChild(_drawer15);
        const _border22 = new Border();
        _border22.set_property_value("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border22.set_property_value("Padding", new Thickness(24));
        const _stackPanel23 = new StackPanel();
        const _textBlock24 = new TextBlock();
        _textBlock24.set_property_value("Text", "The left drawer is Persistent —\n                                        the rail is always visible (56\n                                        DIPs); the header button toggles\n                                        the pane open / closed (200 DIPs).");
        _textBlock24.set_property_value("TextWrapping", TextWrapping.Wrap);
        _textBlock24.set_property_value("FontSize", 13);
        _textBlock24.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#1f2937')));
        _stackPanel23.AddChild(_textBlock24);
        const _button25 = new Button();
        _button25.set_property_value("Command", DataContextBinding(_button25, "OpenOptions"));
        _button25.set_property_value("Width", 180);
        _button25.set_property_value("Margin", new Thickness(0, 16, 0, 0));
        const _textBlock26 = new TextBlock();
        _textBlock26.set_property_value("Text", "Open options →");
        _button25.Content = _textBlock26;
        _stackPanel23.AddChild(_button25);
        const _textBlock27 = new TextBlock();
        _textBlock27.set_property_value("Text", "The Options pane is Temporary —\n                                        it mounts onto the overlay layer\n                                        with a click-away scrim. Click\n                                        the scrim or the Close button to\n                                        dismiss.");
        _textBlock27.set_property_value("TextWrapping", TextWrapping.Wrap);
        _textBlock27.set_property_value("FontSize", 12);
        _textBlock27.set_property_value("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock27.set_property_value("Margin", new Thickness(0, 16, 0, 0));
        _stackPanel23.AddChild(_textBlock27);
        _border22.SetChild(_stackPanel23);
        _dockPanel3.AddChild(_border22);
        _border2.SetChild(_dockPanel3);
        return _border2;
    }, "DrawerVM");
    _rd0.Set("DrawerTemplate", _tmpl1);
    return _rd0;
}
