import { AnimationNamedVM } from "./animation-named-vm.mjs";
import { Border, Button, DataTemplate, Dock, DockPanel, Orientation, StackPanel, TextBlock } from "@visualisation-sub/mural/Controls";
import { BeginStoryboardAction, Color, DoubleAnimation, EventTrigger, PauseStoryboardAction, PropertyTrigger, ResourceDictionary, ResumeStoryboardAction, StopStoryboardAction, Storyboard, Style, Thickness } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _tmpl1 = new DataTemplate((_data) => {
        const _border2 = new Border();
        _border2._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border2._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#e2e8f0')));
        _border2._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _rd3 = _border2.Resources;
        const _act5 = new BeginStoryboardAction((_target) => {
            const _sb4 = new Storyboard();
            _sb4.Add(_target, "Width", new DoubleAnimation({ From: 80, To: 240, Duration: 800, AutoReverse: true, RepeatBehavior: Infinity }));
            return _sb4;
        }, "loop");
        const _evt6 = new EventTrigger("Loaded", [_act5]);
        const _act7 = new PauseStoryboardAction("loop");
        const _act8 = new ResumeStoryboardAction("loop");
        const _sArr9 = [];
        const _enter10 = [_act7];
        const _exit11 = [_act8];
        const _trigger12 = new PropertyTrigger(Button, "IsMouseOver", true, _sArr9, _enter10, _exit11);
        const _act13 = new StopStoryboardAction("loop");
        const _evt14 = new EventTrigger("Click", [_act13]);
        const _style15 = new Style(Button, [], undefined, [_trigger12], [], [_evt6, _evt14]);
        _rd3.Set(Button, _style15);
        const _dockPanel16 = new DockPanel();
        const _border17 = new Border();
        _border17._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border17._set_property_value_by_name("Background", new SolidColorBrush(Color.FromHex('#1976d2')));
        _border17._set_property_value_by_name("Padding", new Thickness(16, 12, 16, 12));
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", "Named storyboards — Begin / Pause / Resume / Stop");
        _textBlock18._set_property_value_by_name("FontSize", 15);
        _textBlock18._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock18._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#ffffff')));
        _border17.SetChild(_textBlock18);
        _dockPanel16.AddChild(_border17);
        const _stackPanel19 = new StackPanel();
        _stackPanel19._set_property_value_by_name("Orientation", Orientation.Vertical);
        _stackPanel19._set_property_value_by_name("Margin", new Thickness(20, 24, 20, 20));
        const _textBlock20 = new TextBlock();
        _textBlock20._set_property_value_by_name("Text", "Each button starts a looping Width animation on Loaded. Hover pauses; un-hover resumes; click stops for good.");
        _textBlock20._set_property_value_by_name("FontSize", 12);
        _textBlock20._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock20._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 16));
        _stackPanel19.AddChild(_textBlock20);
        const _stackPanel21 = new StackPanel();
        _stackPanel21._set_property_value_by_name("Orientation", Orientation.Vertical);
        const _button22 = new Button();
        _button22._set_property_value_by_name("Height", 28);
        _button22._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        const _textBlock23 = new TextBlock();
        _textBlock23._set_property_value_by_name("Text", "Loop A");
        _button22.Content = _textBlock23;
        _stackPanel21.AddChild(_button22);
        const _button24 = new Button();
        _button24._set_property_value_by_name("Height", 28);
        _button24._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        const _textBlock25 = new TextBlock();
        _textBlock25._set_property_value_by_name("Text", "Loop B");
        _button24.Content = _textBlock25;
        _stackPanel21.AddChild(_button24);
        const _button26 = new Button();
        _button26._set_property_value_by_name("Height", 28);
        _button26._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        const _textBlock27 = new TextBlock();
        _textBlock27._set_property_value_by_name("Text", "Loop C");
        _button26.Content = _textBlock27;
        _stackPanel21.AddChild(_button26);
        _stackPanel19.AddChild(_stackPanel21);
        const _textBlock28 = new TextBlock();
        _textBlock28._set_property_value_by_name("Text", "The named registry is per-Visual — pausing Loop A doesn't pause Loop B or C.");
        _textBlock28._set_property_value_by_name("FontSize", 11);
        _textBlock28._set_property_value_by_name("Foreground", new SolidColorBrush(Color.FromHex('#6b7280')));
        _textBlock28._set_property_value_by_name("Margin", new Thickness(0, 16, 0, 0));
        _stackPanel19.AddChild(_textBlock28);
        _dockPanel16.AddChild(_stackPanel19);
        _border2.SetChild(_dockPanel16);
        return _border2;
    }, AnimationNamedVM);
    _rd0.Set("AnimationNamedTemplate", _tmpl1);
    return _rd0;
}
