import { ArchShapeVM, ArrowShapeVM, BoomShapeVM, BunShapeVM, BurstShapeVM, ClamshellShapeVM, DiamondShapeVM, EightLeafCloverShapeVM, EllipseShapeVM, FanShapeVM, FlowerShapeVM, FourCookieShapeVM, FourLeafCloverShapeVM, GemShapeVM, GhostishShapeVM, GroupVM, HeartShapeVM, NineCookieShapeVM, PentagonShapeVM, PillShapeVM, PixelCircleShapeVM, PixelTriangleShapeVM, PuffyDiamondShapeVM, PuffyShapeVM, RectangleShapeVM, SemicircleShapeVM, SevenCookieShapeVM, SixCookieShapeVM, SlantedShapeVM, SoftBoomShapeVM, SoftBurstShapeVM, SquircleShapeVM, SunnyShapeVM, TriangleShapeVM, TwelveCookieShapeVM, VerySunnyShapeVM } from "./diagram-vm.mjs";
import { Arch, Arrow, Boom, Border, Bun, Burst, Canvas, Clamshell, DataTemplate, Diamond, EightLeafClover, Ellipse, Fan, Flower, FourLeafClover, FourSidedCookie, Gem, Ghostish, Heart, NineSidedCookie, Pentagon, Pill, PixelCircle, PixelTriangle, Puffy, PuffyDiamond, Rectangle, Semicircle, SevenSidedCookie, SixSidedCookie, Slanted, SoftBoom, SoftBurst, Squircle, Sunny, TargetedSetter, TemplateDataTrigger, TextBlock, Triangle, TwelveSidedCookie, VerySunny } from "@visualisation-sub/mural/basic";
import { Color, DataContextBinding, DynamicResource, HorizontalAlignment, NameScope, ResourceDictionary, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_DiagramShapeTemplates = Symbol("DiagramShapeTemplates.ctor");
export class DiagramShapeTemplates extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_DiagramShapeTemplates) {
            throw new Error("DiagramShapeTemplates is private — use DiagramShapeTemplates.Clone()");
        }
    }
    static Clone() {
        const t = new DiagramShapeTemplates(_gate_DiagramShapeTemplates);
        const _tmpl0 = new DataTemplate((_data) => {
            const _canvas1 = new Canvas();
            _canvas1.SetNameScope(new NameScope());
            _canvas1._set_property_value_by_name("Width", DataContextBinding(_canvas1, "Width"));
            _canvas1._set_property_value_by_name("Height", DataContextBinding(_canvas1, "Height"));
            const _rectangle2 = new Rectangle();
            _rectangle2.Name = "chrome";
            _rectangle2._set_property_value_by_name("Width", DataContextBinding(_rectangle2, "Width"));
            _rectangle2._set_property_value_by_name("Height", DataContextBinding(_rectangle2, "Height"));
            _rectangle2._set_property_value_by_name("Fill", DataContextBinding(_rectangle2, "FillBrush"));
            _rectangle2._set_property_value_by_name("Stroke", DataContextBinding(_rectangle2, "Stroke"));
            _canvas1.AddChild(_rectangle2);
            const _textBlock3 = new TextBlock();
            _textBlock3._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock3._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock3._set_property_value_by_name("Width", DataContextBinding(_textBlock3, "Width"));
            _textBlock3._set_property_value_by_name("Height", DataContextBinding(_textBlock3, "Height"));
            _textBlock3._set_property_value_by_name("Text", DataContextBinding(_textBlock3, "LabelText"));
            _textBlock3._set_property_value_by_name("FontSize", 11);
            _textBlock3._set_property_value_by_name("Foreground", DynamicResource(_textBlock3, "OnSurface"));
            _textBlock3._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock3._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas1.AddChild(_textBlock3);
            return _canvas1;
        }, RectangleShapeVM);
        t.Set(RectangleShapeVM, _tmpl0);
        const _tmpl4 = new DataTemplate((_data) => {
            const _canvas5 = new Canvas();
            _canvas5.SetNameScope(new NameScope());
            _canvas5._set_property_value_by_name("Width", DataContextBinding(_canvas5, "Width"));
            _canvas5._set_property_value_by_name("Height", DataContextBinding(_canvas5, "Height"));
            const _ellipse6 = new Ellipse();
            _ellipse6.Name = "chrome";
            _ellipse6._set_property_value_by_name("Width", DataContextBinding(_ellipse6, "Width"));
            _ellipse6._set_property_value_by_name("Height", DataContextBinding(_ellipse6, "Height"));
            _ellipse6._set_property_value_by_name("Fill", DataContextBinding(_ellipse6, "FillBrush"));
            _ellipse6._set_property_value_by_name("Stroke", DataContextBinding(_ellipse6, "Stroke"));
            _canvas5.AddChild(_ellipse6);
            const _textBlock7 = new TextBlock();
            _textBlock7._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock7._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock7._set_property_value_by_name("Width", DataContextBinding(_textBlock7, "Width"));
            _textBlock7._set_property_value_by_name("Height", DataContextBinding(_textBlock7, "Height"));
            _textBlock7._set_property_value_by_name("Text", DataContextBinding(_textBlock7, "LabelText"));
            _textBlock7._set_property_value_by_name("FontSize", 11);
            _textBlock7._set_property_value_by_name("Foreground", DynamicResource(_textBlock7, "OnSurface"));
            _textBlock7._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock7._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas5.AddChild(_textBlock7);
            return _canvas5;
        }, EllipseShapeVM);
        t.Set(EllipseShapeVM, _tmpl4);
        const _tmpl8 = new DataTemplate((_data) => {
            const _canvas9 = new Canvas();
            _canvas9.SetNameScope(new NameScope());
            _canvas9._set_property_value_by_name("Width", DataContextBinding(_canvas9, "Width"));
            _canvas9._set_property_value_by_name("Height", DataContextBinding(_canvas9, "Height"));
            const _squircle10 = new Squircle();
            _squircle10.Name = "chrome";
            _squircle10._set_property_value_by_name("Width", DataContextBinding(_squircle10, "Width"));
            _squircle10._set_property_value_by_name("Height", DataContextBinding(_squircle10, "Height"));
            _squircle10._set_property_value_by_name("Fill", DataContextBinding(_squircle10, "FillBrush"));
            _squircle10._set_property_value_by_name("Stroke", DataContextBinding(_squircle10, "Stroke"));
            _canvas9.AddChild(_squircle10);
            const _textBlock11 = new TextBlock();
            _textBlock11._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock11._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock11._set_property_value_by_name("Width", DataContextBinding(_textBlock11, "Width"));
            _textBlock11._set_property_value_by_name("Height", DataContextBinding(_textBlock11, "Height"));
            _textBlock11._set_property_value_by_name("Text", DataContextBinding(_textBlock11, "LabelText"));
            _textBlock11._set_property_value_by_name("FontSize", 11);
            _textBlock11._set_property_value_by_name("Foreground", DynamicResource(_textBlock11, "OnSurface"));
            _textBlock11._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock11._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas9.AddChild(_textBlock11);
            return _canvas9;
        }, SquircleShapeVM);
        t.Set(SquircleShapeVM, _tmpl8);
        const _tmpl12 = new DataTemplate((_data) => {
            const _canvas13 = new Canvas();
            _canvas13.SetNameScope(new NameScope());
            _canvas13._set_property_value_by_name("Width", DataContextBinding(_canvas13, "Width"));
            _canvas13._set_property_value_by_name("Height", DataContextBinding(_canvas13, "Height"));
            const _slanted14 = new Slanted();
            _slanted14.Name = "chrome";
            _slanted14._set_property_value_by_name("Width", DataContextBinding(_slanted14, "Width"));
            _slanted14._set_property_value_by_name("Height", DataContextBinding(_slanted14, "Height"));
            _slanted14._set_property_value_by_name("Fill", DataContextBinding(_slanted14, "FillBrush"));
            _slanted14._set_property_value_by_name("Stroke", DataContextBinding(_slanted14, "Stroke"));
            _canvas13.AddChild(_slanted14);
            const _textBlock15 = new TextBlock();
            _textBlock15._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock15._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock15._set_property_value_by_name("Width", DataContextBinding(_textBlock15, "Width"));
            _textBlock15._set_property_value_by_name("Height", DataContextBinding(_textBlock15, "Height"));
            _textBlock15._set_property_value_by_name("Text", DataContextBinding(_textBlock15, "LabelText"));
            _textBlock15._set_property_value_by_name("FontSize", 11);
            _textBlock15._set_property_value_by_name("Foreground", DynamicResource(_textBlock15, "OnSurface"));
            _textBlock15._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock15._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas13.AddChild(_textBlock15);
            return _canvas13;
        }, SlantedShapeVM);
        t.Set(SlantedShapeVM, _tmpl12);
        const _tmpl16 = new DataTemplate((_data) => {
            const _canvas17 = new Canvas();
            _canvas17.SetNameScope(new NameScope());
            _canvas17._set_property_value_by_name("Width", DataContextBinding(_canvas17, "Width"));
            _canvas17._set_property_value_by_name("Height", DataContextBinding(_canvas17, "Height"));
            const _pill18 = new Pill();
            _pill18.Name = "chrome";
            _pill18._set_property_value_by_name("Width", DataContextBinding(_pill18, "Width"));
            _pill18._set_property_value_by_name("Height", DataContextBinding(_pill18, "Height"));
            _pill18._set_property_value_by_name("Fill", DataContextBinding(_pill18, "FillBrush"));
            _pill18._set_property_value_by_name("Stroke", DataContextBinding(_pill18, "Stroke"));
            _canvas17.AddChild(_pill18);
            const _textBlock19 = new TextBlock();
            _textBlock19._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock19._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock19._set_property_value_by_name("Width", DataContextBinding(_textBlock19, "Width"));
            _textBlock19._set_property_value_by_name("Height", DataContextBinding(_textBlock19, "Height"));
            _textBlock19._set_property_value_by_name("Text", DataContextBinding(_textBlock19, "LabelText"));
            _textBlock19._set_property_value_by_name("FontSize", 11);
            _textBlock19._set_property_value_by_name("Foreground", DynamicResource(_textBlock19, "OnSurface"));
            _textBlock19._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock19._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas17.AddChild(_textBlock19);
            return _canvas17;
        }, PillShapeVM);
        t.Set(PillShapeVM, _tmpl16);
        const _tmpl20 = new DataTemplate((_data) => {
            const _canvas21 = new Canvas();
            _canvas21.SetNameScope(new NameScope());
            _canvas21._set_property_value_by_name("Width", DataContextBinding(_canvas21, "Width"));
            _canvas21._set_property_value_by_name("Height", DataContextBinding(_canvas21, "Height"));
            const _diamond22 = new Diamond();
            _diamond22.Name = "chrome";
            _diamond22._set_property_value_by_name("Width", DataContextBinding(_diamond22, "Width"));
            _diamond22._set_property_value_by_name("Height", DataContextBinding(_diamond22, "Height"));
            _diamond22._set_property_value_by_name("Fill", DataContextBinding(_diamond22, "FillBrush"));
            _diamond22._set_property_value_by_name("Stroke", DataContextBinding(_diamond22, "Stroke"));
            _canvas21.AddChild(_diamond22);
            const _textBlock23 = new TextBlock();
            _textBlock23._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock23._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock23._set_property_value_by_name("Width", DataContextBinding(_textBlock23, "Width"));
            _textBlock23._set_property_value_by_name("Height", DataContextBinding(_textBlock23, "Height"));
            _textBlock23._set_property_value_by_name("Text", DataContextBinding(_textBlock23, "LabelText"));
            _textBlock23._set_property_value_by_name("FontSize", 11);
            _textBlock23._set_property_value_by_name("Foreground", DynamicResource(_textBlock23, "OnSurface"));
            _textBlock23._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock23._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas21.AddChild(_textBlock23);
            return _canvas21;
        }, DiamondShapeVM);
        t.Set(DiamondShapeVM, _tmpl20);
        const _tmpl24 = new DataTemplate((_data) => {
            const _canvas25 = new Canvas();
            _canvas25.SetNameScope(new NameScope());
            _canvas25._set_property_value_by_name("Width", DataContextBinding(_canvas25, "Width"));
            _canvas25._set_property_value_by_name("Height", DataContextBinding(_canvas25, "Height"));
            const _pentagon26 = new Pentagon();
            _pentagon26.Name = "chrome";
            _pentagon26._set_property_value_by_name("Width", DataContextBinding(_pentagon26, "Width"));
            _pentagon26._set_property_value_by_name("Height", DataContextBinding(_pentagon26, "Height"));
            _pentagon26._set_property_value_by_name("Fill", DataContextBinding(_pentagon26, "FillBrush"));
            _pentagon26._set_property_value_by_name("Stroke", DataContextBinding(_pentagon26, "Stroke"));
            _canvas25.AddChild(_pentagon26);
            const _textBlock27 = new TextBlock();
            _textBlock27._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock27._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock27._set_property_value_by_name("Width", DataContextBinding(_textBlock27, "Width"));
            _textBlock27._set_property_value_by_name("Height", DataContextBinding(_textBlock27, "Height"));
            _textBlock27._set_property_value_by_name("Text", DataContextBinding(_textBlock27, "LabelText"));
            _textBlock27._set_property_value_by_name("FontSize", 11);
            _textBlock27._set_property_value_by_name("Foreground", DynamicResource(_textBlock27, "OnSurface"));
            _textBlock27._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock27._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas25.AddChild(_textBlock27);
            return _canvas25;
        }, PentagonShapeVM);
        t.Set(PentagonShapeVM, _tmpl24);
        const _tmpl28 = new DataTemplate((_data) => {
            const _canvas29 = new Canvas();
            _canvas29.SetNameScope(new NameScope());
            _canvas29._set_property_value_by_name("Width", DataContextBinding(_canvas29, "Width"));
            _canvas29._set_property_value_by_name("Height", DataContextBinding(_canvas29, "Height"));
            const _gem30 = new Gem();
            _gem30.Name = "chrome";
            _gem30._set_property_value_by_name("Width", DataContextBinding(_gem30, "Width"));
            _gem30._set_property_value_by_name("Height", DataContextBinding(_gem30, "Height"));
            _gem30._set_property_value_by_name("Fill", DataContextBinding(_gem30, "FillBrush"));
            _gem30._set_property_value_by_name("Stroke", DataContextBinding(_gem30, "Stroke"));
            _canvas29.AddChild(_gem30);
            const _textBlock31 = new TextBlock();
            _textBlock31._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock31._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock31._set_property_value_by_name("Width", DataContextBinding(_textBlock31, "Width"));
            _textBlock31._set_property_value_by_name("Height", DataContextBinding(_textBlock31, "Height"));
            _textBlock31._set_property_value_by_name("Text", DataContextBinding(_textBlock31, "LabelText"));
            _textBlock31._set_property_value_by_name("FontSize", 11);
            _textBlock31._set_property_value_by_name("Foreground", DynamicResource(_textBlock31, "OnSurface"));
            _textBlock31._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock31._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas29.AddChild(_textBlock31);
            return _canvas29;
        }, GemShapeVM);
        t.Set(GemShapeVM, _tmpl28);
        const _tmpl32 = new DataTemplate((_data) => {
            const _canvas33 = new Canvas();
            _canvas33.SetNameScope(new NameScope());
            _canvas33._set_property_value_by_name("Width", DataContextBinding(_canvas33, "Width"));
            _canvas33._set_property_value_by_name("Height", DataContextBinding(_canvas33, "Height"));
            const _arch34 = new Arch();
            _arch34.Name = "chrome";
            _arch34._set_property_value_by_name("Width", DataContextBinding(_arch34, "Width"));
            _arch34._set_property_value_by_name("Height", DataContextBinding(_arch34, "Height"));
            _arch34._set_property_value_by_name("Fill", DataContextBinding(_arch34, "FillBrush"));
            _arch34._set_property_value_by_name("Stroke", DataContextBinding(_arch34, "Stroke"));
            _canvas33.AddChild(_arch34);
            const _textBlock35 = new TextBlock();
            _textBlock35._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock35._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock35._set_property_value_by_name("Width", DataContextBinding(_textBlock35, "Width"));
            _textBlock35._set_property_value_by_name("Height", DataContextBinding(_textBlock35, "Height"));
            _textBlock35._set_property_value_by_name("Text", DataContextBinding(_textBlock35, "LabelText"));
            _textBlock35._set_property_value_by_name("FontSize", 11);
            _textBlock35._set_property_value_by_name("Foreground", DynamicResource(_textBlock35, "OnSurface"));
            _textBlock35._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock35._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas33.AddChild(_textBlock35);
            return _canvas33;
        }, ArchShapeVM);
        t.Set(ArchShapeVM, _tmpl32);
        const _tmpl36 = new DataTemplate((_data) => {
            const _canvas37 = new Canvas();
            _canvas37.SetNameScope(new NameScope());
            _canvas37._set_property_value_by_name("Width", DataContextBinding(_canvas37, "Width"));
            _canvas37._set_property_value_by_name("Height", DataContextBinding(_canvas37, "Height"));
            const _semicircle38 = new Semicircle();
            _semicircle38.Name = "chrome";
            _semicircle38._set_property_value_by_name("Width", DataContextBinding(_semicircle38, "Width"));
            _semicircle38._set_property_value_by_name("Height", DataContextBinding(_semicircle38, "Height"));
            _semicircle38._set_property_value_by_name("Fill", DataContextBinding(_semicircle38, "FillBrush"));
            _semicircle38._set_property_value_by_name("Stroke", DataContextBinding(_semicircle38, "Stroke"));
            _canvas37.AddChild(_semicircle38);
            const _textBlock39 = new TextBlock();
            _textBlock39._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock39._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock39._set_property_value_by_name("Width", DataContextBinding(_textBlock39, "Width"));
            _textBlock39._set_property_value_by_name("Height", DataContextBinding(_textBlock39, "Height"));
            _textBlock39._set_property_value_by_name("Text", DataContextBinding(_textBlock39, "LabelText"));
            _textBlock39._set_property_value_by_name("FontSize", 11);
            _textBlock39._set_property_value_by_name("Foreground", DynamicResource(_textBlock39, "OnSurface"));
            _textBlock39._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock39._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas37.AddChild(_textBlock39);
            return _canvas37;
        }, SemicircleShapeVM);
        t.Set(SemicircleShapeVM, _tmpl36);
        const _tmpl40 = new DataTemplate((_data) => {
            const _canvas41 = new Canvas();
            _canvas41.SetNameScope(new NameScope());
            _canvas41._set_property_value_by_name("Width", DataContextBinding(_canvas41, "Width"));
            _canvas41._set_property_value_by_name("Height", DataContextBinding(_canvas41, "Height"));
            const _triangle42 = new Triangle();
            _triangle42.Name = "chrome";
            _triangle42._set_property_value_by_name("Width", DataContextBinding(_triangle42, "Width"));
            _triangle42._set_property_value_by_name("Height", DataContextBinding(_triangle42, "Height"));
            _triangle42._set_property_value_by_name("CornerRadius", 10);
            _triangle42._set_property_value_by_name("Fill", DataContextBinding(_triangle42, "FillBrush"));
            _triangle42._set_property_value_by_name("Stroke", DataContextBinding(_triangle42, "Stroke"));
            _canvas41.AddChild(_triangle42);
            const _textBlock43 = new TextBlock();
            _textBlock43._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock43._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock43._set_property_value_by_name("Width", DataContextBinding(_textBlock43, "Width"));
            _textBlock43._set_property_value_by_name("Height", DataContextBinding(_textBlock43, "Height"));
            _textBlock43._set_property_value_by_name("Text", DataContextBinding(_textBlock43, "LabelText"));
            _textBlock43._set_property_value_by_name("FontSize", 11);
            _textBlock43._set_property_value_by_name("Foreground", DynamicResource(_textBlock43, "OnSurface"));
            _textBlock43._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock43._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas41.AddChild(_textBlock43);
            return _canvas41;
        }, TriangleShapeVM);
        t.Set(TriangleShapeVM, _tmpl40);
        const _tmpl44 = new DataTemplate((_data) => {
            const _canvas45 = new Canvas();
            _canvas45.SetNameScope(new NameScope());
            _canvas45._set_property_value_by_name("Width", DataContextBinding(_canvas45, "Width"));
            _canvas45._set_property_value_by_name("Height", DataContextBinding(_canvas45, "Height"));
            const _arrow46 = new Arrow();
            _arrow46.Name = "chrome";
            _arrow46._set_property_value_by_name("Width", DataContextBinding(_arrow46, "Width"));
            _arrow46._set_property_value_by_name("Height", DataContextBinding(_arrow46, "Height"));
            _arrow46._set_property_value_by_name("CornerRadius", 10);
            _arrow46._set_property_value_by_name("Fill", DataContextBinding(_arrow46, "FillBrush"));
            _arrow46._set_property_value_by_name("Stroke", DataContextBinding(_arrow46, "Stroke"));
            _canvas45.AddChild(_arrow46);
            const _textBlock47 = new TextBlock();
            _textBlock47._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock47._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock47._set_property_value_by_name("Width", DataContextBinding(_textBlock47, "Width"));
            _textBlock47._set_property_value_by_name("Height", DataContextBinding(_textBlock47, "Height"));
            _textBlock47._set_property_value_by_name("Text", DataContextBinding(_textBlock47, "LabelText"));
            _textBlock47._set_property_value_by_name("FontSize", 11);
            _textBlock47._set_property_value_by_name("Foreground", DynamicResource(_textBlock47, "OnSurface"));
            _textBlock47._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock47._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas45.AddChild(_textBlock47);
            return _canvas45;
        }, ArrowShapeVM);
        t.Set(ArrowShapeVM, _tmpl44);
        const _tmpl48 = new DataTemplate((_data) => {
            const _canvas49 = new Canvas();
            _canvas49.SetNameScope(new NameScope());
            _canvas49._set_property_value_by_name("Width", DataContextBinding(_canvas49, "Width"));
            _canvas49._set_property_value_by_name("Height", DataContextBinding(_canvas49, "Height"));
            const _fan50 = new Fan();
            _fan50.Name = "chrome";
            _fan50._set_property_value_by_name("Width", DataContextBinding(_fan50, "Width"));
            _fan50._set_property_value_by_name("Height", DataContextBinding(_fan50, "Height"));
            _fan50._set_property_value_by_name("Fill", DataContextBinding(_fan50, "FillBrush"));
            _fan50._set_property_value_by_name("Stroke", DataContextBinding(_fan50, "Stroke"));
            _canvas49.AddChild(_fan50);
            const _textBlock51 = new TextBlock();
            _textBlock51._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock51._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock51._set_property_value_by_name("Width", DataContextBinding(_textBlock51, "Width"));
            _textBlock51._set_property_value_by_name("Height", DataContextBinding(_textBlock51, "Height"));
            _textBlock51._set_property_value_by_name("Text", DataContextBinding(_textBlock51, "LabelText"));
            _textBlock51._set_property_value_by_name("FontSize", 11);
            _textBlock51._set_property_value_by_name("Foreground", DynamicResource(_textBlock51, "OnSurface"));
            _textBlock51._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock51._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas49.AddChild(_textBlock51);
            return _canvas49;
        }, FanShapeVM);
        t.Set(FanShapeVM, _tmpl48);
        const _tmpl52 = new DataTemplate((_data) => {
            const _canvas53 = new Canvas();
            _canvas53.SetNameScope(new NameScope());
            _canvas53._set_property_value_by_name("Width", DataContextBinding(_canvas53, "Width"));
            _canvas53._set_property_value_by_name("Height", DataContextBinding(_canvas53, "Height"));
            const _clamshell54 = new Clamshell();
            _clamshell54.Name = "chrome";
            _clamshell54._set_property_value_by_name("Width", DataContextBinding(_clamshell54, "Width"));
            _clamshell54._set_property_value_by_name("Height", DataContextBinding(_clamshell54, "Height"));
            _clamshell54._set_property_value_by_name("CornerRadius", 8);
            _clamshell54._set_property_value_by_name("Fill", DataContextBinding(_clamshell54, "FillBrush"));
            _clamshell54._set_property_value_by_name("Stroke", DataContextBinding(_clamshell54, "Stroke"));
            _canvas53.AddChild(_clamshell54);
            const _textBlock55 = new TextBlock();
            _textBlock55._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock55._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock55._set_property_value_by_name("Width", DataContextBinding(_textBlock55, "Width"));
            _textBlock55._set_property_value_by_name("Height", DataContextBinding(_textBlock55, "Height"));
            _textBlock55._set_property_value_by_name("Text", DataContextBinding(_textBlock55, "LabelText"));
            _textBlock55._set_property_value_by_name("FontSize", 11);
            _textBlock55._set_property_value_by_name("Foreground", DynamicResource(_textBlock55, "OnSurface"));
            _textBlock55._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock55._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas53.AddChild(_textBlock55);
            return _canvas53;
        }, ClamshellShapeVM);
        t.Set(ClamshellShapeVM, _tmpl52);
        const _tmpl56 = new DataTemplate((_data) => {
            const _canvas57 = new Canvas();
            _canvas57.SetNameScope(new NameScope());
            _canvas57._set_property_value_by_name("Width", DataContextBinding(_canvas57, "Width"));
            _canvas57._set_property_value_by_name("Height", DataContextBinding(_canvas57, "Height"));
            const _fourSidedCookie58 = new FourSidedCookie();
            _fourSidedCookie58.Name = "chrome";
            _fourSidedCookie58._set_property_value_by_name("Width", DataContextBinding(_fourSidedCookie58, "Width"));
            _fourSidedCookie58._set_property_value_by_name("Height", DataContextBinding(_fourSidedCookie58, "Height"));
            _fourSidedCookie58._set_property_value_by_name("CornerRadius", 10);
            _fourSidedCookie58._set_property_value_by_name("Fill", DataContextBinding(_fourSidedCookie58, "FillBrush"));
            _fourSidedCookie58._set_property_value_by_name("Stroke", DataContextBinding(_fourSidedCookie58, "Stroke"));
            _canvas57.AddChild(_fourSidedCookie58);
            const _textBlock59 = new TextBlock();
            _textBlock59._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock59._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock59._set_property_value_by_name("Width", DataContextBinding(_textBlock59, "Width"));
            _textBlock59._set_property_value_by_name("Height", DataContextBinding(_textBlock59, "Height"));
            _textBlock59._set_property_value_by_name("Text", DataContextBinding(_textBlock59, "LabelText"));
            _textBlock59._set_property_value_by_name("FontSize", 11);
            _textBlock59._set_property_value_by_name("Foreground", DynamicResource(_textBlock59, "OnSurface"));
            _textBlock59._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock59._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas57.AddChild(_textBlock59);
            return _canvas57;
        }, FourCookieShapeVM);
        t.Set(FourCookieShapeVM, _tmpl56);
        const _tmpl60 = new DataTemplate((_data) => {
            const _canvas61 = new Canvas();
            _canvas61.SetNameScope(new NameScope());
            _canvas61._set_property_value_by_name("Width", DataContextBinding(_canvas61, "Width"));
            _canvas61._set_property_value_by_name("Height", DataContextBinding(_canvas61, "Height"));
            const _sixSidedCookie62 = new SixSidedCookie();
            _sixSidedCookie62.Name = "chrome";
            _sixSidedCookie62._set_property_value_by_name("Width", DataContextBinding(_sixSidedCookie62, "Width"));
            _sixSidedCookie62._set_property_value_by_name("Height", DataContextBinding(_sixSidedCookie62, "Height"));
            _sixSidedCookie62._set_property_value_by_name("CornerRadius", 8);
            _sixSidedCookie62._set_property_value_by_name("Fill", DataContextBinding(_sixSidedCookie62, "FillBrush"));
            _sixSidedCookie62._set_property_value_by_name("Stroke", DataContextBinding(_sixSidedCookie62, "Stroke"));
            _canvas61.AddChild(_sixSidedCookie62);
            const _textBlock63 = new TextBlock();
            _textBlock63._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock63._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock63._set_property_value_by_name("Width", DataContextBinding(_textBlock63, "Width"));
            _textBlock63._set_property_value_by_name("Height", DataContextBinding(_textBlock63, "Height"));
            _textBlock63._set_property_value_by_name("Text", DataContextBinding(_textBlock63, "LabelText"));
            _textBlock63._set_property_value_by_name("FontSize", 11);
            _textBlock63._set_property_value_by_name("Foreground", DynamicResource(_textBlock63, "OnSurface"));
            _textBlock63._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock63._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas61.AddChild(_textBlock63);
            return _canvas61;
        }, SixCookieShapeVM);
        t.Set(SixCookieShapeVM, _tmpl60);
        const _tmpl64 = new DataTemplate((_data) => {
            const _canvas65 = new Canvas();
            _canvas65.SetNameScope(new NameScope());
            _canvas65._set_property_value_by_name("Width", DataContextBinding(_canvas65, "Width"));
            _canvas65._set_property_value_by_name("Height", DataContextBinding(_canvas65, "Height"));
            const _sevenSidedCookie66 = new SevenSidedCookie();
            _sevenSidedCookie66.Name = "chrome";
            _sevenSidedCookie66._set_property_value_by_name("Width", DataContextBinding(_sevenSidedCookie66, "Width"));
            _sevenSidedCookie66._set_property_value_by_name("Height", DataContextBinding(_sevenSidedCookie66, "Height"));
            _sevenSidedCookie66._set_property_value_by_name("CornerRadius", 8);
            _sevenSidedCookie66._set_property_value_by_name("Fill", DataContextBinding(_sevenSidedCookie66, "FillBrush"));
            _sevenSidedCookie66._set_property_value_by_name("Stroke", DataContextBinding(_sevenSidedCookie66, "Stroke"));
            _canvas65.AddChild(_sevenSidedCookie66);
            const _textBlock67 = new TextBlock();
            _textBlock67._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock67._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock67._set_property_value_by_name("Width", DataContextBinding(_textBlock67, "Width"));
            _textBlock67._set_property_value_by_name("Height", DataContextBinding(_textBlock67, "Height"));
            _textBlock67._set_property_value_by_name("Text", DataContextBinding(_textBlock67, "LabelText"));
            _textBlock67._set_property_value_by_name("FontSize", 11);
            _textBlock67._set_property_value_by_name("Foreground", DynamicResource(_textBlock67, "OnSurface"));
            _textBlock67._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock67._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas65.AddChild(_textBlock67);
            return _canvas65;
        }, SevenCookieShapeVM);
        t.Set(SevenCookieShapeVM, _tmpl64);
        const _tmpl68 = new DataTemplate((_data) => {
            const _canvas69 = new Canvas();
            _canvas69.SetNameScope(new NameScope());
            _canvas69._set_property_value_by_name("Width", DataContextBinding(_canvas69, "Width"));
            _canvas69._set_property_value_by_name("Height", DataContextBinding(_canvas69, "Height"));
            const _nineSidedCookie70 = new NineSidedCookie();
            _nineSidedCookie70.Name = "chrome";
            _nineSidedCookie70._set_property_value_by_name("Width", DataContextBinding(_nineSidedCookie70, "Width"));
            _nineSidedCookie70._set_property_value_by_name("Height", DataContextBinding(_nineSidedCookie70, "Height"));
            _nineSidedCookie70._set_property_value_by_name("CornerRadius", 6);
            _nineSidedCookie70._set_property_value_by_name("Fill", DataContextBinding(_nineSidedCookie70, "FillBrush"));
            _nineSidedCookie70._set_property_value_by_name("Stroke", DataContextBinding(_nineSidedCookie70, "Stroke"));
            _canvas69.AddChild(_nineSidedCookie70);
            const _textBlock71 = new TextBlock();
            _textBlock71._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock71._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock71._set_property_value_by_name("Width", DataContextBinding(_textBlock71, "Width"));
            _textBlock71._set_property_value_by_name("Height", DataContextBinding(_textBlock71, "Height"));
            _textBlock71._set_property_value_by_name("Text", DataContextBinding(_textBlock71, "LabelText"));
            _textBlock71._set_property_value_by_name("FontSize", 11);
            _textBlock71._set_property_value_by_name("Foreground", DynamicResource(_textBlock71, "OnSurface"));
            _textBlock71._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock71._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas69.AddChild(_textBlock71);
            return _canvas69;
        }, NineCookieShapeVM);
        t.Set(NineCookieShapeVM, _tmpl68);
        const _tmpl72 = new DataTemplate((_data) => {
            const _canvas73 = new Canvas();
            _canvas73.SetNameScope(new NameScope());
            _canvas73._set_property_value_by_name("Width", DataContextBinding(_canvas73, "Width"));
            _canvas73._set_property_value_by_name("Height", DataContextBinding(_canvas73, "Height"));
            const _twelveSidedCookie74 = new TwelveSidedCookie();
            _twelveSidedCookie74.Name = "chrome";
            _twelveSidedCookie74._set_property_value_by_name("Width", DataContextBinding(_twelveSidedCookie74, "Width"));
            _twelveSidedCookie74._set_property_value_by_name("Height", DataContextBinding(_twelveSidedCookie74, "Height"));
            _twelveSidedCookie74._set_property_value_by_name("CornerRadius", 5);
            _twelveSidedCookie74._set_property_value_by_name("Fill", DataContextBinding(_twelveSidedCookie74, "FillBrush"));
            _twelveSidedCookie74._set_property_value_by_name("Stroke", DataContextBinding(_twelveSidedCookie74, "Stroke"));
            _canvas73.AddChild(_twelveSidedCookie74);
            const _textBlock75 = new TextBlock();
            _textBlock75._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock75._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock75._set_property_value_by_name("Width", DataContextBinding(_textBlock75, "Width"));
            _textBlock75._set_property_value_by_name("Height", DataContextBinding(_textBlock75, "Height"));
            _textBlock75._set_property_value_by_name("Text", DataContextBinding(_textBlock75, "LabelText"));
            _textBlock75._set_property_value_by_name("FontSize", 11);
            _textBlock75._set_property_value_by_name("Foreground", DynamicResource(_textBlock75, "OnSurface"));
            _textBlock75._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock75._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas73.AddChild(_textBlock75);
            return _canvas73;
        }, TwelveCookieShapeVM);
        t.Set(TwelveCookieShapeVM, _tmpl72);
        const _tmpl76 = new DataTemplate((_data) => {
            const _canvas77 = new Canvas();
            _canvas77.SetNameScope(new NameScope());
            _canvas77._set_property_value_by_name("Width", DataContextBinding(_canvas77, "Width"));
            _canvas77._set_property_value_by_name("Height", DataContextBinding(_canvas77, "Height"));
            const _fourLeafClover78 = new FourLeafClover();
            _fourLeafClover78.Name = "chrome";
            _fourLeafClover78._set_property_value_by_name("Width", DataContextBinding(_fourLeafClover78, "Width"));
            _fourLeafClover78._set_property_value_by_name("Height", DataContextBinding(_fourLeafClover78, "Height"));
            _fourLeafClover78._set_property_value_by_name("Fill", DataContextBinding(_fourLeafClover78, "FillBrush"));
            _fourLeafClover78._set_property_value_by_name("Stroke", DataContextBinding(_fourLeafClover78, "Stroke"));
            _canvas77.AddChild(_fourLeafClover78);
            const _textBlock79 = new TextBlock();
            _textBlock79._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock79._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock79._set_property_value_by_name("Width", DataContextBinding(_textBlock79, "Width"));
            _textBlock79._set_property_value_by_name("Height", DataContextBinding(_textBlock79, "Height"));
            _textBlock79._set_property_value_by_name("Text", DataContextBinding(_textBlock79, "LabelText"));
            _textBlock79._set_property_value_by_name("FontSize", 11);
            _textBlock79._set_property_value_by_name("Foreground", DynamicResource(_textBlock79, "OnSurface"));
            _textBlock79._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock79._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas77.AddChild(_textBlock79);
            return _canvas77;
        }, FourLeafCloverShapeVM);
        t.Set(FourLeafCloverShapeVM, _tmpl76);
        const _tmpl80 = new DataTemplate((_data) => {
            const _canvas81 = new Canvas();
            _canvas81.SetNameScope(new NameScope());
            _canvas81._set_property_value_by_name("Width", DataContextBinding(_canvas81, "Width"));
            _canvas81._set_property_value_by_name("Height", DataContextBinding(_canvas81, "Height"));
            const _eightLeafClover82 = new EightLeafClover();
            _eightLeafClover82.Name = "chrome";
            _eightLeafClover82._set_property_value_by_name("Width", DataContextBinding(_eightLeafClover82, "Width"));
            _eightLeafClover82._set_property_value_by_name("Height", DataContextBinding(_eightLeafClover82, "Height"));
            _eightLeafClover82._set_property_value_by_name("Fill", DataContextBinding(_eightLeafClover82, "FillBrush"));
            _eightLeafClover82._set_property_value_by_name("Stroke", DataContextBinding(_eightLeafClover82, "Stroke"));
            _canvas81.AddChild(_eightLeafClover82);
            const _textBlock83 = new TextBlock();
            _textBlock83._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock83._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock83._set_property_value_by_name("Width", DataContextBinding(_textBlock83, "Width"));
            _textBlock83._set_property_value_by_name("Height", DataContextBinding(_textBlock83, "Height"));
            _textBlock83._set_property_value_by_name("Text", DataContextBinding(_textBlock83, "LabelText"));
            _textBlock83._set_property_value_by_name("FontSize", 11);
            _textBlock83._set_property_value_by_name("Foreground", DynamicResource(_textBlock83, "OnSurface"));
            _textBlock83._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock83._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas81.AddChild(_textBlock83);
            return _canvas81;
        }, EightLeafCloverShapeVM);
        t.Set(EightLeafCloverShapeVM, _tmpl80);
        const _tmpl84 = new DataTemplate((_data) => {
            const _canvas85 = new Canvas();
            _canvas85.SetNameScope(new NameScope());
            _canvas85._set_property_value_by_name("Width", DataContextBinding(_canvas85, "Width"));
            _canvas85._set_property_value_by_name("Height", DataContextBinding(_canvas85, "Height"));
            const _sunny86 = new Sunny();
            _sunny86.Name = "chrome";
            _sunny86._set_property_value_by_name("Width", DataContextBinding(_sunny86, "Width"));
            _sunny86._set_property_value_by_name("Height", DataContextBinding(_sunny86, "Height"));
            _sunny86._set_property_value_by_name("Fill", DataContextBinding(_sunny86, "FillBrush"));
            _sunny86._set_property_value_by_name("Stroke", DataContextBinding(_sunny86, "Stroke"));
            _canvas85.AddChild(_sunny86);
            const _textBlock87 = new TextBlock();
            _textBlock87._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock87._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock87._set_property_value_by_name("Width", DataContextBinding(_textBlock87, "Width"));
            _textBlock87._set_property_value_by_name("Height", DataContextBinding(_textBlock87, "Height"));
            _textBlock87._set_property_value_by_name("Text", DataContextBinding(_textBlock87, "LabelText"));
            _textBlock87._set_property_value_by_name("FontSize", 11);
            _textBlock87._set_property_value_by_name("Foreground", DynamicResource(_textBlock87, "OnSurface"));
            _textBlock87._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock87._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas85.AddChild(_textBlock87);
            return _canvas85;
        }, SunnyShapeVM);
        t.Set(SunnyShapeVM, _tmpl84);
        const _tmpl88 = new DataTemplate((_data) => {
            const _canvas89 = new Canvas();
            _canvas89.SetNameScope(new NameScope());
            _canvas89._set_property_value_by_name("Width", DataContextBinding(_canvas89, "Width"));
            _canvas89._set_property_value_by_name("Height", DataContextBinding(_canvas89, "Height"));
            const _verySunny90 = new VerySunny();
            _verySunny90.Name = "chrome";
            _verySunny90._set_property_value_by_name("Width", DataContextBinding(_verySunny90, "Width"));
            _verySunny90._set_property_value_by_name("Height", DataContextBinding(_verySunny90, "Height"));
            _verySunny90._set_property_value_by_name("Fill", DataContextBinding(_verySunny90, "FillBrush"));
            _verySunny90._set_property_value_by_name("Stroke", DataContextBinding(_verySunny90, "Stroke"));
            _canvas89.AddChild(_verySunny90);
            const _textBlock91 = new TextBlock();
            _textBlock91._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock91._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock91._set_property_value_by_name("Width", DataContextBinding(_textBlock91, "Width"));
            _textBlock91._set_property_value_by_name("Height", DataContextBinding(_textBlock91, "Height"));
            _textBlock91._set_property_value_by_name("Text", DataContextBinding(_textBlock91, "LabelText"));
            _textBlock91._set_property_value_by_name("FontSize", 11);
            _textBlock91._set_property_value_by_name("Foreground", DynamicResource(_textBlock91, "OnSurface"));
            _textBlock91._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock91._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas89.AddChild(_textBlock91);
            return _canvas89;
        }, VerySunnyShapeVM);
        t.Set(VerySunnyShapeVM, _tmpl88);
        const _tmpl92 = new DataTemplate((_data) => {
            const _canvas93 = new Canvas();
            _canvas93.SetNameScope(new NameScope());
            _canvas93._set_property_value_by_name("Width", DataContextBinding(_canvas93, "Width"));
            _canvas93._set_property_value_by_name("Height", DataContextBinding(_canvas93, "Height"));
            const _burst94 = new Burst();
            _burst94.Name = "chrome";
            _burst94._set_property_value_by_name("Width", DataContextBinding(_burst94, "Width"));
            _burst94._set_property_value_by_name("Height", DataContextBinding(_burst94, "Height"));
            _burst94._set_property_value_by_name("Fill", DataContextBinding(_burst94, "FillBrush"));
            _burst94._set_property_value_by_name("Stroke", DataContextBinding(_burst94, "Stroke"));
            _canvas93.AddChild(_burst94);
            const _textBlock95 = new TextBlock();
            _textBlock95._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock95._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock95._set_property_value_by_name("Width", DataContextBinding(_textBlock95, "Width"));
            _textBlock95._set_property_value_by_name("Height", DataContextBinding(_textBlock95, "Height"));
            _textBlock95._set_property_value_by_name("Text", DataContextBinding(_textBlock95, "LabelText"));
            _textBlock95._set_property_value_by_name("FontSize", 11);
            _textBlock95._set_property_value_by_name("Foreground", DynamicResource(_textBlock95, "OnSurface"));
            _textBlock95._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock95._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas93.AddChild(_textBlock95);
            return _canvas93;
        }, BurstShapeVM);
        t.Set(BurstShapeVM, _tmpl92);
        const _tmpl96 = new DataTemplate((_data) => {
            const _canvas97 = new Canvas();
            _canvas97.SetNameScope(new NameScope());
            _canvas97._set_property_value_by_name("Width", DataContextBinding(_canvas97, "Width"));
            _canvas97._set_property_value_by_name("Height", DataContextBinding(_canvas97, "Height"));
            const _softBurst98 = new SoftBurst();
            _softBurst98.Name = "chrome";
            _softBurst98._set_property_value_by_name("Width", DataContextBinding(_softBurst98, "Width"));
            _softBurst98._set_property_value_by_name("Height", DataContextBinding(_softBurst98, "Height"));
            _softBurst98._set_property_value_by_name("Fill", DataContextBinding(_softBurst98, "FillBrush"));
            _softBurst98._set_property_value_by_name("Stroke", DataContextBinding(_softBurst98, "Stroke"));
            _canvas97.AddChild(_softBurst98);
            const _textBlock99 = new TextBlock();
            _textBlock99._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock99._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock99._set_property_value_by_name("Width", DataContextBinding(_textBlock99, "Width"));
            _textBlock99._set_property_value_by_name("Height", DataContextBinding(_textBlock99, "Height"));
            _textBlock99._set_property_value_by_name("Text", DataContextBinding(_textBlock99, "LabelText"));
            _textBlock99._set_property_value_by_name("FontSize", 11);
            _textBlock99._set_property_value_by_name("Foreground", DynamicResource(_textBlock99, "OnSurface"));
            _textBlock99._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock99._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas97.AddChild(_textBlock99);
            return _canvas97;
        }, SoftBurstShapeVM);
        t.Set(SoftBurstShapeVM, _tmpl96);
        const _tmpl100 = new DataTemplate((_data) => {
            const _canvas101 = new Canvas();
            _canvas101.SetNameScope(new NameScope());
            _canvas101._set_property_value_by_name("Width", DataContextBinding(_canvas101, "Width"));
            _canvas101._set_property_value_by_name("Height", DataContextBinding(_canvas101, "Height"));
            const _boom102 = new Boom();
            _boom102.Name = "chrome";
            _boom102._set_property_value_by_name("Width", DataContextBinding(_boom102, "Width"));
            _boom102._set_property_value_by_name("Height", DataContextBinding(_boom102, "Height"));
            _boom102._set_property_value_by_name("Fill", DataContextBinding(_boom102, "FillBrush"));
            _boom102._set_property_value_by_name("Stroke", DataContextBinding(_boom102, "Stroke"));
            _canvas101.AddChild(_boom102);
            const _textBlock103 = new TextBlock();
            _textBlock103._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock103._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock103._set_property_value_by_name("Width", DataContextBinding(_textBlock103, "Width"));
            _textBlock103._set_property_value_by_name("Height", DataContextBinding(_textBlock103, "Height"));
            _textBlock103._set_property_value_by_name("Text", DataContextBinding(_textBlock103, "LabelText"));
            _textBlock103._set_property_value_by_name("FontSize", 11);
            _textBlock103._set_property_value_by_name("Foreground", DynamicResource(_textBlock103, "OnSurface"));
            _textBlock103._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock103._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas101.AddChild(_textBlock103);
            return _canvas101;
        }, BoomShapeVM);
        t.Set(BoomShapeVM, _tmpl100);
        const _tmpl104 = new DataTemplate((_data) => {
            const _canvas105 = new Canvas();
            _canvas105.SetNameScope(new NameScope());
            _canvas105._set_property_value_by_name("Width", DataContextBinding(_canvas105, "Width"));
            _canvas105._set_property_value_by_name("Height", DataContextBinding(_canvas105, "Height"));
            const _softBoom106 = new SoftBoom();
            _softBoom106.Name = "chrome";
            _softBoom106._set_property_value_by_name("Width", DataContextBinding(_softBoom106, "Width"));
            _softBoom106._set_property_value_by_name("Height", DataContextBinding(_softBoom106, "Height"));
            _softBoom106._set_property_value_by_name("Fill", DataContextBinding(_softBoom106, "FillBrush"));
            _softBoom106._set_property_value_by_name("Stroke", DataContextBinding(_softBoom106, "Stroke"));
            _canvas105.AddChild(_softBoom106);
            const _textBlock107 = new TextBlock();
            _textBlock107._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock107._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock107._set_property_value_by_name("Width", DataContextBinding(_textBlock107, "Width"));
            _textBlock107._set_property_value_by_name("Height", DataContextBinding(_textBlock107, "Height"));
            _textBlock107._set_property_value_by_name("Text", DataContextBinding(_textBlock107, "LabelText"));
            _textBlock107._set_property_value_by_name("FontSize", 11);
            _textBlock107._set_property_value_by_name("Foreground", DynamicResource(_textBlock107, "OnSurface"));
            _textBlock107._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock107._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas105.AddChild(_textBlock107);
            return _canvas105;
        }, SoftBoomShapeVM);
        t.Set(SoftBoomShapeVM, _tmpl104);
        const _tmpl108 = new DataTemplate((_data) => {
            const _canvas109 = new Canvas();
            _canvas109.SetNameScope(new NameScope());
            _canvas109._set_property_value_by_name("Width", DataContextBinding(_canvas109, "Width"));
            _canvas109._set_property_value_by_name("Height", DataContextBinding(_canvas109, "Height"));
            const _flower110 = new Flower();
            _flower110.Name = "chrome";
            _flower110._set_property_value_by_name("Width", DataContextBinding(_flower110, "Width"));
            _flower110._set_property_value_by_name("Height", DataContextBinding(_flower110, "Height"));
            _flower110._set_property_value_by_name("Fill", DataContextBinding(_flower110, "FillBrush"));
            _flower110._set_property_value_by_name("Stroke", DataContextBinding(_flower110, "Stroke"));
            _canvas109.AddChild(_flower110);
            const _textBlock111 = new TextBlock();
            _textBlock111._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock111._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock111._set_property_value_by_name("Width", DataContextBinding(_textBlock111, "Width"));
            _textBlock111._set_property_value_by_name("Height", DataContextBinding(_textBlock111, "Height"));
            _textBlock111._set_property_value_by_name("Text", DataContextBinding(_textBlock111, "LabelText"));
            _textBlock111._set_property_value_by_name("FontSize", 11);
            _textBlock111._set_property_value_by_name("Foreground", DynamicResource(_textBlock111, "OnSurface"));
            _textBlock111._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock111._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas109.AddChild(_textBlock111);
            return _canvas109;
        }, FlowerShapeVM);
        t.Set(FlowerShapeVM, _tmpl108);
        const _tmpl112 = new DataTemplate((_data) => {
            const _canvas113 = new Canvas();
            _canvas113.SetNameScope(new NameScope());
            _canvas113._set_property_value_by_name("Width", DataContextBinding(_canvas113, "Width"));
            _canvas113._set_property_value_by_name("Height", DataContextBinding(_canvas113, "Height"));
            const _puffy114 = new Puffy();
            _puffy114.Name = "chrome";
            _puffy114._set_property_value_by_name("Width", DataContextBinding(_puffy114, "Width"));
            _puffy114._set_property_value_by_name("Height", DataContextBinding(_puffy114, "Height"));
            _puffy114._set_property_value_by_name("Fill", DataContextBinding(_puffy114, "FillBrush"));
            _puffy114._set_property_value_by_name("Stroke", DataContextBinding(_puffy114, "Stroke"));
            _canvas113.AddChild(_puffy114);
            const _textBlock115 = new TextBlock();
            _textBlock115._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock115._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock115._set_property_value_by_name("Width", DataContextBinding(_textBlock115, "Width"));
            _textBlock115._set_property_value_by_name("Height", DataContextBinding(_textBlock115, "Height"));
            _textBlock115._set_property_value_by_name("Text", DataContextBinding(_textBlock115, "LabelText"));
            _textBlock115._set_property_value_by_name("FontSize", 11);
            _textBlock115._set_property_value_by_name("Foreground", DynamicResource(_textBlock115, "OnSurface"));
            _textBlock115._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock115._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas113.AddChild(_textBlock115);
            return _canvas113;
        }, PuffyShapeVM);
        t.Set(PuffyShapeVM, _tmpl112);
        const _tmpl116 = new DataTemplate((_data) => {
            const _canvas117 = new Canvas();
            _canvas117.SetNameScope(new NameScope());
            _canvas117._set_property_value_by_name("Width", DataContextBinding(_canvas117, "Width"));
            _canvas117._set_property_value_by_name("Height", DataContextBinding(_canvas117, "Height"));
            const _puffyDiamond118 = new PuffyDiamond();
            _puffyDiamond118.Name = "chrome";
            _puffyDiamond118._set_property_value_by_name("Width", DataContextBinding(_puffyDiamond118, "Width"));
            _puffyDiamond118._set_property_value_by_name("Height", DataContextBinding(_puffyDiamond118, "Height"));
            _puffyDiamond118._set_property_value_by_name("Fill", DataContextBinding(_puffyDiamond118, "FillBrush"));
            _puffyDiamond118._set_property_value_by_name("Stroke", DataContextBinding(_puffyDiamond118, "Stroke"));
            _canvas117.AddChild(_puffyDiamond118);
            const _textBlock119 = new TextBlock();
            _textBlock119._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock119._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock119._set_property_value_by_name("Width", DataContextBinding(_textBlock119, "Width"));
            _textBlock119._set_property_value_by_name("Height", DataContextBinding(_textBlock119, "Height"));
            _textBlock119._set_property_value_by_name("Text", DataContextBinding(_textBlock119, "LabelText"));
            _textBlock119._set_property_value_by_name("FontSize", 11);
            _textBlock119._set_property_value_by_name("Foreground", DynamicResource(_textBlock119, "OnSurface"));
            _textBlock119._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock119._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas117.AddChild(_textBlock119);
            return _canvas117;
        }, PuffyDiamondShapeVM);
        t.Set(PuffyDiamondShapeVM, _tmpl116);
        const _tmpl120 = new DataTemplate((_data) => {
            const _canvas121 = new Canvas();
            _canvas121.SetNameScope(new NameScope());
            _canvas121._set_property_value_by_name("Width", DataContextBinding(_canvas121, "Width"));
            _canvas121._set_property_value_by_name("Height", DataContextBinding(_canvas121, "Height"));
            const _ghostish122 = new Ghostish();
            _ghostish122.Name = "chrome";
            _ghostish122._set_property_value_by_name("Width", DataContextBinding(_ghostish122, "Width"));
            _ghostish122._set_property_value_by_name("Height", DataContextBinding(_ghostish122, "Height"));
            _ghostish122._set_property_value_by_name("Fill", DataContextBinding(_ghostish122, "FillBrush"));
            _ghostish122._set_property_value_by_name("Stroke", DataContextBinding(_ghostish122, "Stroke"));
            _canvas121.AddChild(_ghostish122);
            const _textBlock123 = new TextBlock();
            _textBlock123._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock123._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock123._set_property_value_by_name("Width", DataContextBinding(_textBlock123, "Width"));
            _textBlock123._set_property_value_by_name("Height", DataContextBinding(_textBlock123, "Height"));
            _textBlock123._set_property_value_by_name("Text", DataContextBinding(_textBlock123, "LabelText"));
            _textBlock123._set_property_value_by_name("FontSize", 11);
            _textBlock123._set_property_value_by_name("Foreground", DynamicResource(_textBlock123, "OnSurface"));
            _textBlock123._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock123._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas121.AddChild(_textBlock123);
            return _canvas121;
        }, GhostishShapeVM);
        t.Set(GhostishShapeVM, _tmpl120);
        const _tmpl124 = new DataTemplate((_data) => {
            const _canvas125 = new Canvas();
            _canvas125.SetNameScope(new NameScope());
            _canvas125._set_property_value_by_name("Width", DataContextBinding(_canvas125, "Width"));
            _canvas125._set_property_value_by_name("Height", DataContextBinding(_canvas125, "Height"));
            const _bun126 = new Bun();
            _bun126.Name = "chrome";
            _bun126._set_property_value_by_name("Width", DataContextBinding(_bun126, "Width"));
            _bun126._set_property_value_by_name("Height", DataContextBinding(_bun126, "Height"));
            _bun126._set_property_value_by_name("Fill", DataContextBinding(_bun126, "FillBrush"));
            _bun126._set_property_value_by_name("Stroke", DataContextBinding(_bun126, "Stroke"));
            _canvas125.AddChild(_bun126);
            const _textBlock127 = new TextBlock();
            _textBlock127._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock127._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock127._set_property_value_by_name("Width", DataContextBinding(_textBlock127, "Width"));
            _textBlock127._set_property_value_by_name("Height", DataContextBinding(_textBlock127, "Height"));
            _textBlock127._set_property_value_by_name("Text", DataContextBinding(_textBlock127, "LabelText"));
            _textBlock127._set_property_value_by_name("FontSize", 11);
            _textBlock127._set_property_value_by_name("Foreground", DynamicResource(_textBlock127, "OnSurface"));
            _textBlock127._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock127._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas125.AddChild(_textBlock127);
            return _canvas125;
        }, BunShapeVM);
        t.Set(BunShapeVM, _tmpl124);
        const _tmpl128 = new DataTemplate((_data) => {
            const _canvas129 = new Canvas();
            _canvas129.SetNameScope(new NameScope());
            _canvas129._set_property_value_by_name("Width", DataContextBinding(_canvas129, "Width"));
            _canvas129._set_property_value_by_name("Height", DataContextBinding(_canvas129, "Height"));
            const _heart130 = new Heart();
            _heart130.Name = "chrome";
            _heart130._set_property_value_by_name("Width", DataContextBinding(_heart130, "Width"));
            _heart130._set_property_value_by_name("Height", DataContextBinding(_heart130, "Height"));
            _heart130._set_property_value_by_name("Fill", DataContextBinding(_heart130, "FillBrush"));
            _heart130._set_property_value_by_name("Stroke", DataContextBinding(_heart130, "Stroke"));
            _canvas129.AddChild(_heart130);
            const _textBlock131 = new TextBlock();
            _textBlock131._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock131._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock131._set_property_value_by_name("Width", DataContextBinding(_textBlock131, "Width"));
            _textBlock131._set_property_value_by_name("Height", DataContextBinding(_textBlock131, "Height"));
            _textBlock131._set_property_value_by_name("Text", DataContextBinding(_textBlock131, "LabelText"));
            _textBlock131._set_property_value_by_name("FontSize", 11);
            _textBlock131._set_property_value_by_name("Foreground", DynamicResource(_textBlock131, "OnSurface"));
            _textBlock131._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock131._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas129.AddChild(_textBlock131);
            return _canvas129;
        }, HeartShapeVM);
        t.Set(HeartShapeVM, _tmpl128);
        const _tmpl132 = new DataTemplate((_data) => {
            const _canvas133 = new Canvas();
            _canvas133.SetNameScope(new NameScope());
            _canvas133._set_property_value_by_name("Width", DataContextBinding(_canvas133, "Width"));
            _canvas133._set_property_value_by_name("Height", DataContextBinding(_canvas133, "Height"));
            const _pixelCircle134 = new PixelCircle();
            _pixelCircle134.Name = "chrome";
            _pixelCircle134._set_property_value_by_name("Width", DataContextBinding(_pixelCircle134, "Width"));
            _pixelCircle134._set_property_value_by_name("Height", DataContextBinding(_pixelCircle134, "Height"));
            _pixelCircle134._set_property_value_by_name("Fill", DataContextBinding(_pixelCircle134, "FillBrush"));
            _pixelCircle134._set_property_value_by_name("Stroke", DataContextBinding(_pixelCircle134, "Stroke"));
            _canvas133.AddChild(_pixelCircle134);
            const _textBlock135 = new TextBlock();
            _textBlock135._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock135._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock135._set_property_value_by_name("Width", DataContextBinding(_textBlock135, "Width"));
            _textBlock135._set_property_value_by_name("Height", DataContextBinding(_textBlock135, "Height"));
            _textBlock135._set_property_value_by_name("Text", DataContextBinding(_textBlock135, "LabelText"));
            _textBlock135._set_property_value_by_name("FontSize", 11);
            _textBlock135._set_property_value_by_name("Foreground", DynamicResource(_textBlock135, "OnSurface"));
            _textBlock135._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock135._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas133.AddChild(_textBlock135);
            return _canvas133;
        }, PixelCircleShapeVM);
        t.Set(PixelCircleShapeVM, _tmpl132);
        const _tmpl136 = new DataTemplate((_data) => {
            const _canvas137 = new Canvas();
            _canvas137.SetNameScope(new NameScope());
            _canvas137._set_property_value_by_name("Width", DataContextBinding(_canvas137, "Width"));
            _canvas137._set_property_value_by_name("Height", DataContextBinding(_canvas137, "Height"));
            const _pixelTriangle138 = new PixelTriangle();
            _pixelTriangle138.Name = "chrome";
            _pixelTriangle138._set_property_value_by_name("Width", DataContextBinding(_pixelTriangle138, "Width"));
            _pixelTriangle138._set_property_value_by_name("Height", DataContextBinding(_pixelTriangle138, "Height"));
            _pixelTriangle138._set_property_value_by_name("Fill", DataContextBinding(_pixelTriangle138, "FillBrush"));
            _pixelTriangle138._set_property_value_by_name("Stroke", DataContextBinding(_pixelTriangle138, "Stroke"));
            _canvas137.AddChild(_pixelTriangle138);
            const _textBlock139 = new TextBlock();
            _textBlock139._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock139._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock139._set_property_value_by_name("Width", DataContextBinding(_textBlock139, "Width"));
            _textBlock139._set_property_value_by_name("Height", DataContextBinding(_textBlock139, "Height"));
            _textBlock139._set_property_value_by_name("Text", DataContextBinding(_textBlock139, "LabelText"));
            _textBlock139._set_property_value_by_name("FontSize", 11);
            _textBlock139._set_property_value_by_name("Foreground", DynamicResource(_textBlock139, "OnSurface"));
            _textBlock139._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock139._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas137.AddChild(_textBlock139);
            return _canvas137;
        }, PixelTriangleShapeVM);
        t.Set(PixelTriangleShapeVM, _tmpl136);
        const _tmpl140 = (() => {
            const _factory = (_data) => {
                const _border141 = new Border();
                _border141.Name = "bbox";
                _border141._set_property_value_by_name("Width", DataContextBinding(_border141, "Width"));
                _border141._set_property_value_by_name("Height", DataContextBinding(_border141, "Height"));
                _border141._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#00000000')));
                _border141._set_property_value_by_name("BorderThickness", new Thickness(2));
                _border141._set_property_value_by_name("IsHitTestVisible", false);
                return _border141;
            };
            const _tplSet142 = [new TargetedSetter(Border, "BorderBrush", new SolidColorBrush(Color.FromHex('#f97316')), "bbox")];
            const _tplDataTrig143 = new TemplateDataTrigger("IsSelected", true, _tplSet142);
            return new DataTemplate(_factory, GroupVM, [], [_tplDataTrig143]);
        })();
        t.Set(GroupVM, _tmpl140);
        return t;
    }
}
