import { DiagramVM, EllipseNodeVM, NoteNodeVM, RectNodeVM, ToolboxShapeVM } from "./diagram-vm.mjs";
import { Border, Canvas, DataTemplate, Dock, DockPanel, Ellipse, ItemsPanelTemplate, Orientation, StackPanel, TargetedSetter, TemplateDataTrigger, TextBlock, TextWrapping } from "@visualisation-sub/mural/Basic";
import { Button } from "@visualisation-sub/mural/framework/button.js";
import { DiagramNode } from "@visualisation-sub/mural/framework/diagram/diagram-node.js";
import { Diagram } from "@visualisation-sub/mural/framework/diagram/diagram.js";
import { ItemsControl } from "@visualisation-sub/mural/framework/items-control.js";
import { SelectionMode } from "@visualisation-sub/mural/framework/list/list-box.js";
import { Color, DataContextBinding, DynamicResource, HorizontalAlignment, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight, SolidColorBrush } from "@visualisation-sub/mural/visual-engine";

export function create() {
    const _rd0 = new ResourceDictionary();
    const _setter1 = new Setter(DiagramNode, "X", new SetterFactory((_t) => DataContextBinding(_t, "X")));
    const _setter2 = new Setter(DiagramNode, "Y", new SetterFactory((_t) => DataContextBinding(_t, "Y")));
    const _style3 = new Style(DiagramNode, [_setter1, _setter2], undefined, [], []);
    _rd0.Set("DiagramNodeStyle", _style3);
    const _tmpl4 = new ItemsPanelTemplate(() => {
        const _canvas5 = new Canvas();
        return _canvas5;
    });
    _rd0.Set("DiagramCanvasPanel", _tmpl4);
    const _tmpl6 = new ItemsPanelTemplate(() => {
        const _stackPanel7 = new StackPanel();
        return _stackPanel7;
    });
    _rd0.Set("DiagramToolboxPanel", _tmpl6);
    const _setter8 = new Setter(Border, "BorderBrush", new SetterFactory((_t) => DynamicResource(_t, "Primary")));
    const _style9 = new Style(Border, [_setter8], undefined, [], []);
    _rd0.Set("DiagramRectChromeStyle", _style9);
    const _setter10 = new Setter(Border, "BorderBrush", new SolidColorBrush(Color.FromHex('#a16207')));
    const _style11 = new Style(Border, [_setter10], undefined, [], []);
    _rd0.Set("DiagramNoteChromeStyle", _style11);
    const _setter12 = new Setter(Ellipse, "Stroke", new SolidColorBrush(Color.FromHex('#15803d')));
    const _style13 = new Style(Ellipse, [_setter12], undefined, [], []);
    _rd0.Set("DiagramEllipseChromeStyle", _style13);
    const _tmpl14 = new DataTemplate((_data) => {
        const _border15 = new Border();
        _border15.SetNameScope(new NameScope());
        _border15._set_property_value_by_name("IsDraggable", true);
        _border15._set_property_value_by_name("OnDragStart", DataContextBinding(_border15, "BeginKindDragData"));
        _border15._set_property_value_by_name("Background", DynamicResource(_border15, "Surface"));
        _border15._set_property_value_by_name("BorderBrush", DynamicResource(_border15, "OutlineVariant"));
        _border15._set_property_value_by_name("BorderThickness", new Thickness(1));
        _border15._set_property_value_by_name("Padding", new Thickness(8));
        _border15._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        const _stackPanel16 = new StackPanel();
        _stackPanel16._set_property_value_by_name("Orientation", Orientation.Horizontal);
        const _border17 = new Border();
        _border17._set_property_value_by_name("Width", 28);
        _border17._set_property_value_by_name("Height", 18);
        _border17._set_property_value_by_name("Background", DataContextBinding(_border17, "Swatch"));
        _border17._set_property_value_by_name("Margin", new Thickness(0, 4, 8, 0));
        _stackPanel16.AddChild(_border17);
        const _textBlock18 = new TextBlock();
        _textBlock18._set_property_value_by_name("Text", DataContextBinding(_textBlock18, "Label"));
        _textBlock18._set_property_value_by_name("FontSize", 12);
        _textBlock18._set_property_value_by_name("Foreground", DynamicResource(_textBlock18, "OnSurface"));
        _textBlock18._set_property_value_by_name("Margin", new Thickness(0, 6, 0, 0));
        _stackPanel16.AddChild(_textBlock18);
        _border15.SetChild(_stackPanel16);
        return _border15;
    }, ToolboxShapeVM);
    _rd0.Set("DiagramTileTemplate", _tmpl14);
    const _tmpl19 = (() => {
        const _factory = (_data) => {
            const _border20 = new Border();
            _border20.Name = "chrome";
            _border20._set_property_value_by_name("Style", _style9);
            _border20._set_property_value_by_name("Width", 130);
            _border20._set_property_value_by_name("Height", 60);
            _border20._set_property_value_by_name("Background", DataContextBinding(_border20, "FillBrush"));
            _border20._set_property_value_by_name("BorderThickness", new Thickness(1.5));
            _border20._set_property_value_by_name("CornerRadius", 4);
            const _textBlock21 = new TextBlock();
            _textBlock21._set_property_value_by_name("Text", DataContextBinding(_textBlock21, "LabelText"));
            _textBlock21._set_property_value_by_name("FontSize", 13);
            _textBlock21._set_property_value_by_name("Foreground", DynamicResource(_textBlock21, "OnSurface"));
            _textBlock21._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock21._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _border20.SetChild(_textBlock21);
            return _border20;
        };
        const _tplSet22 = [new TargetedSetter(Border, "BorderBrush", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
        const _tplDataTrig23 = new TemplateDataTrigger("IsSelected", true, _tplSet22);
        return new DataTemplate(_factory, RectNodeVM, [], [_tplDataTrig23]);
    })();
    _rd0.Set(RectNodeVM, _tmpl19);
    const _tmpl24 = (() => {
        const _factory = (_data) => {
            const _canvas25 = new Canvas();
            _canvas25.SetNameScope(new NameScope());
            _canvas25._set_property_value_by_name("Width", 130);
            _canvas25._set_property_value_by_name("Height", 60);
            const _ellipse26 = new Ellipse();
            _ellipse26.Name = "chrome";
            _ellipse26._set_property_value_by_name("Style", _style13);
            _ellipse26._set_property_value_by_name("Width", 130);
            _ellipse26._set_property_value_by_name("Height", 60);
            _ellipse26._set_property_value_by_name("Fill", DataContextBinding(_ellipse26, "FillBrush"));
            _ellipse26._set_property_value_by_name("StrokeThickness", 1.5);
            _canvas25.AddChild(_ellipse26);
            const _textBlock27 = new TextBlock();
            _textBlock27._set_property_value_by_name(Canvas, "Left", 0);
            _textBlock27._set_property_value_by_name(Canvas, "Top", 0);
            _textBlock27._set_property_value_by_name("Width", 130);
            _textBlock27._set_property_value_by_name("Height", 60);
            _textBlock27._set_property_value_by_name("Text", DataContextBinding(_textBlock27, "LabelText"));
            _textBlock27._set_property_value_by_name("FontSize", 13);
            _textBlock27._set_property_value_by_name("Foreground", DynamicResource(_textBlock27, "OnSurface"));
            _textBlock27._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock27._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _canvas25.AddChild(_textBlock27);
            return _canvas25;
        };
        const _tplSet28 = [new TargetedSetter(Ellipse, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
        const _tplDataTrig29 = new TemplateDataTrigger("IsSelected", true, _tplSet28);
        return new DataTemplate(_factory, EllipseNodeVM, [], [_tplDataTrig29]);
    })();
    _rd0.Set(EllipseNodeVM, _tmpl24);
    const _tmpl30 = (() => {
        const _factory = (_data) => {
            const _border31 = new Border();
            _border31.Name = "chrome";
            _border31._set_property_value_by_name("Style", _style11);
            _border31._set_property_value_by_name("Width", 130);
            _border31._set_property_value_by_name("Height", 60);
            _border31._set_property_value_by_name("Background", DataContextBinding(_border31, "FillBrush"));
            _border31._set_property_value_by_name("BorderThickness", new Thickness(1.5));
            _border31._set_property_value_by_name("CornerRadius", 2);
            const _textBlock32 = new TextBlock();
            _textBlock32._set_property_value_by_name("Text", DataContextBinding(_textBlock32, "LabelText"));
            _textBlock32._set_property_value_by_name("FontSize", 13);
            _textBlock32._set_property_value_by_name("Foreground", DynamicResource(_textBlock32, "OnSurface"));
            _textBlock32._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock32._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _border31.SetChild(_textBlock32);
            return _border31;
        };
        const _tplSet33 = [new TargetedSetter(Border, "BorderBrush", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
        const _tplDataTrig34 = new TemplateDataTrigger("IsSelected", true, _tplSet33);
        return new DataTemplate(_factory, NoteNodeVM, [], [_tplDataTrig34]);
    })();
    _rd0.Set(NoteNodeVM, _tmpl30);
    const _tmpl35 = new DataTemplate((_data) => {
        const _border36 = new Border();
        _border36.SetNameScope(new NameScope());
        _border36._set_property_value_by_name("Background", DynamicResource(_border36, "Surface"));
        _border36._set_property_value_by_name("BorderBrush", DynamicResource(_border36, "OutlineVariant"));
        _border36._set_property_value_by_name("BorderThickness", new Thickness(1));
        const _dockPanel37 = new DockPanel();
        const _border38 = new Border();
        _border38._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
        _border38._set_property_value_by_name("Height", 44);
        _border38._set_property_value_by_name("Background", DynamicResource(_border38, "Primary"));
        const _stackPanel39 = new StackPanel();
        _stackPanel39._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel39._set_property_value_by_name("Margin", new Thickness(16, 10, 0, 0));
        const _textBlock40 = new TextBlock();
        _textBlock40._set_property_value_by_name("Text", "Diagrammer");
        _textBlock40._set_property_value_by_name("FontSize", 15);
        _textBlock40._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock40._set_property_value_by_name("Foreground", DynamicResource(_textBlock40, "OnPrimary"));
        _stackPanel39.AddChild(_textBlock40);
        const _textBlock41 = new TextBlock();
        _textBlock41._set_property_value_by_name("Text", DataContextBinding(_textBlock41, "Status"));
        _textBlock41._set_property_value_by_name("FontSize", 12);
        _textBlock41._set_property_value_by_name("Foreground", DynamicResource(_textBlock41, "OnPrimary"));
        _textBlock41._set_property_value_by_name("Margin", new Thickness(20, 3, 0, 0));
        _stackPanel39.AddChild(_textBlock41);
        _border38.SetChild(_stackPanel39);
        _dockPanel37.AddChild(_border38);
        const _border42 = new Border();
        _border42._set_property_value_by_name(DockPanel, "Dock", Dock.Left);
        _border42._set_property_value_by_name("Width", 140);
        _border42._set_property_value_by_name("Background", DynamicResource(_border42, "SurfaceContainerLow"));
        _border42._set_property_value_by_name("BorderBrush", DynamicResource(_border42, "OutlineVariant"));
        _border42._set_property_value_by_name("BorderThickness", new Thickness(0, 0, 1, 0));
        _border42._set_property_value_by_name("Padding", new Thickness(12));
        const _stackPanel43 = new StackPanel();
        const _textBlock44 = new TextBlock();
        _textBlock44._set_property_value_by_name("Text", "Shapes");
        _textBlock44._set_property_value_by_name("FontSize", 11);
        _textBlock44._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock44._set_property_value_by_name("Foreground", DynamicResource(_textBlock44, "OnSurfaceVariant"));
        _textBlock44._set_property_value_by_name("Margin", new Thickness(2, 0, 0, 8));
        _stackPanel43.AddChild(_textBlock44);
        const _itemsControl45 = new ItemsControl();
        _itemsControl45.Name = "toolbox";
        _itemsControl45._set_property_value_by_name("ItemsSource", DataContextBinding(_itemsControl45, "ToolboxShapes"));
        _itemsControl45._set_property_value_by_name("ItemsPanel", _tmpl6);
        _stackPanel43.AddChild(_itemsControl45);
        const _textBlock46 = new TextBlock();
        _textBlock46._set_property_value_by_name("Text", "Document");
        _textBlock46._set_property_value_by_name("FontSize", 11);
        _textBlock46._set_property_value_by_name("FontWeight", FontWeight.Bold);
        _textBlock46._set_property_value_by_name("Foreground", DynamicResource(_textBlock46, "OnSurfaceVariant"));
        _textBlock46._set_property_value_by_name("Margin", new Thickness(2, 12, 0, 8));
        _stackPanel43.AddChild(_textBlock46);
        const _stackPanel47 = new StackPanel();
        _stackPanel47._set_property_value_by_name("Orientation", Orientation.Horizontal);
        _stackPanel47._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
        const _button48 = new Button();
        _button48.Name = "btnSave";
        _button48._set_property_value_by_name("Command", DataContextBinding(_button48, "SaveCommand"));
        _button48._set_property_value_by_name("Margin", new Thickness(0, 0, 4, 0));
        const _textBlock49 = new TextBlock();
        _textBlock49._set_property_value_by_name("Text", "Save");
        _textBlock49._set_property_value_by_name("FontSize", 11);
        _button48.Content = _textBlock49;
        _stackPanel47.AddChild(_button48);
        const _button50 = new Button();
        _button50.Name = "btnLoad";
        _button50._set_property_value_by_name("Command", DataContextBinding(_button50, "LoadCommand"));
        const _textBlock51 = new TextBlock();
        _textBlock51._set_property_value_by_name("Text", "Load");
        _textBlock51._set_property_value_by_name("FontSize", 11);
        _button50.Content = _textBlock51;
        _stackPanel47.AddChild(_button50);
        _stackPanel43.AddChild(_stackPanel47);
        const _textBlock52 = new TextBlock();
        _textBlock52._set_property_value_by_name("Text", "Drag a shape onto the canvas to\n                                        place it. Click a node to\n                                        select; Ctrl-click to toggle;\n                                        Shift-click to range-extend.\n                                        Drag-rectangle on empty space\n                                        for marquee. Click empty space\n                                        to clear. Drag a node to move.\n                                        Delete removes every selected\n                                        node.");
        _textBlock52._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
        _textBlock52._set_property_value_by_name("FontSize", 10);
        _textBlock52._set_property_value_by_name("Foreground", DynamicResource(_textBlock52, "OnSurfaceVariant"));
        _textBlock52._set_property_value_by_name("Margin", new Thickness(2, 16, 2, 0));
        _stackPanel43.AddChild(_textBlock52);
        _border42.SetChild(_stackPanel43);
        _dockPanel37.AddChild(_border42);
        const _border53 = new Border();
        _border53.Name = "surface";
        _border53._set_property_value_by_name("Background", DynamicResource(_border53, "SurfaceContainerLow"));
        const _diagram54 = new Diagram();
        _diagram54.Name = "nodes";
        _diagram54._set_property_value_by_name("ItemsSource", DataContextBinding(_diagram54, "Nodes"));
        _diagram54._set_property_value_by_name("ItemsPanel", _tmpl4);
        _diagram54._set_property_value_by_name("ItemContainerStyle", _style3);
        _diagram54._set_property_value_by_name("SelectionMode", SelectionMode.Extended);
        _diagram54._set_property_value_by_name("AllowMarqueeSelection", true);
        _border53.SetChild(_diagram54);
        _dockPanel37.AddChild(_border53);
        _border36.SetChild(_dockPanel37);
        return _border36;
    }, DiagramVM);
    _rd0.Set("DiagramTemplate", _tmpl35);
    return _rd0;
}
