import { DiagramVM, ToolboxShapeVM } from "./diagram-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Icon, ItemsPanelTemplate, Orientation, PaginatedCanvas, Splitter, StackPanel, TextBlock, TextWrapping, UniformGrid } from "@visualisation-sub/mural/basic";
import { ShapeFormatControl } from "@visualisation-sub/mural/framework";
import { ContentControl } from "@visualisation-sub/mural/framework/base/content-control.js";
import { ItemsControl } from "@visualisation-sub/mural/framework/base/items-control.js";
import { Button, ButtonVariant } from "@visualisation-sub/mural/framework/buttons/button.js";
import { IconButton } from "@visualisation-sub/mural/framework/buttons/icon-button.js";
import { Diagram } from "@visualisation-sub/mural/framework/diagram/diagram.js";
import { Figure } from "@visualisation-sub/mural/framework/diagram/figure.js";
import { SelectionMode } from "@visualisation-sub/mural/framework/list/list-box.js";
import { ScrollViewer } from "@visualisation-sub/mural/framework/surfaces/scroll-viewer.js";
import { DataContextBinding, DynamicResource, ElementNameBinding, HorizontalAlignment, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_DiagramDemo = Symbol("DiagramDemo.ctor");
export class DiagramDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_DiagramDemo) {
            throw new Error("DiagramDemo is private — use DiagramDemo.Clone()");
        }
    }
    static Clone() {
        const t = new DiagramDemo(_gate_DiagramDemo);
        const _setter0 = new Setter(Figure, "Left", new SetterFactory((_t) => DataContextBinding(_t, "Left")));
        const _setter1 = new Setter(Figure, "Top", new SetterFactory((_t) => DataContextBinding(_t, "Top")));
        const _style2 = new Style(Figure, [_setter0, _setter1], undefined, [], []);
        t.Set("DiagramNodeStyle", _style2);
        const _tmpl3 = new ItemsPanelTemplate(() => {
            const _paginatedCanvas4 = new PaginatedCanvas();
            _paginatedCanvas4.set_property_value(PaginatedCanvas.PageWidthKey, 800);
            _paginatedCanvas4.set_property_value(PaginatedCanvas.PageHeightKey, 600);
            return _paginatedCanvas4;
        });
        t.Set("DiagramCanvasPanel", _tmpl3);
        const _tmpl5 = new ItemsPanelTemplate(() => {
            const _uniformGrid6 = new UniformGrid();
            _uniformGrid6.set_property_value(UniformGrid.ColumnsKey, 2);
            return _uniformGrid6;
        });
        t.Set("DiagramToolboxPanel", _tmpl5);
        const _tmpl7 = new DataTemplate((_data) => {
            const _border8 = new Border();
            _border8.SetNameScope(new NameScope());
            _border8.set_property_value(Border.IsDraggableKey, true);
            _border8.set_property_value(Border.OnDragStartKey, DataContextBinding(_border8, "BeginKindDragData"));
            _border8.set_property_value(Border.BackgroundKey, DynamicResource(_border8, "Surface"));
            _border8.set_property_value(Border.BorderBrushKey, DynamicResource(_border8, "OutlineVariant"));
            _border8.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            _border8.set_property_value(Border.CornerRadiusKey, 4);
            _border8.set_property_value(Border.PaddingKey, new Thickness(4, 8, 4, 8));
            _border8.set_property_value(Border.MarginKey, new Thickness(2, 0, 2, 4));
            const _stackPanel9 = new StackPanel();
            _stackPanel9.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel9.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _contentControl10 = new ContentControl();
            _contentControl10.set_property_value(ContentControl.ContentKey, DataContextBinding(_contentControl10, "PreviewNode"));
            _contentControl10.set_property_value(ContentControl.WidthKey, 48);
            _contentControl10.set_property_value(ContentControl.HeightKey, 48);
            _contentControl10.set_property_value(ContentControl.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel9.AddChild(_contentControl10);
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock11, "Label"));
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock11.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock11, "OnSurface"));
            _textBlock11.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _textBlock11.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel9.AddChild(_textBlock11);
            _border8.SetChild(_stackPanel9);
            return _border8;
        }, ToolboxShapeVM);
        t.Set("DiagramTileTemplate", _tmpl7);
        const _tmpl12 = new DataTemplate((_data) => {
            let _iconButton13, _iconButton14, _iconButton15, _iconButton16, _iconButton17, _iconButton18, _iconButton19, _iconButton20, _iconButton21, _iconButton22, _iconButton23, _iconButton24, _iconButton25, _button26, _button27, _itemsControl28, _border29, _border30, _scrollViewer31, _diagram32;
            const _border33 = new Border();
            _border33.SetNameScope(new NameScope());
            _border33.set_property_value(Border.BackgroundKey, DynamicResource(_border33, "Surface"));
            _border33.set_property_value(Border.BorderBrushKey, DynamicResource(_border33, "OutlineVariant"));
            _border33.set_property_value(Border.BorderThicknessKey, new Thickness(1));
            const _dockPanel34 = new DockPanel();
            const _border35 = new Border();
            _border35.set_property_value(DockPanel.DockKey, Dock.Top);
            _border35.set_property_value(Border.HeightKey, 44);
            _border35.set_property_value(Border.BackgroundKey, DynamicResource(_border35, "Primary"));
            const _stackPanel36 = new StackPanel();
            _stackPanel36.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel36.set_property_value(StackPanel.MarginKey, new Thickness(16, 0, 0, 0));
            const _icon37 = new Icon();
            _icon37.set_property_value(Icon.SourceKey, DynamicResource(_icon37, "home"));
            _icon37.set_property_value(Icon.ForegroundKey, DynamicResource(_icon37, "OnPrimary"));
            _icon37.set_property_value(Icon.VerticalAlignmentKey, VerticalAlignment.Center);
            _stackPanel36.AddChild(_icon37);
            const _textBlock38 = new TextBlock();
            _textBlock38.set_property_value(TextBlock.TextKey, "Diagrammer");
            _textBlock38.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock38.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock38.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock38, "OnPrimary"));
            _textBlock38.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
            _textBlock38.set_property_value(TextBlock.MarginKey, new Thickness(8, 0, 0, 0));
            _stackPanel36.AddChild(_textBlock38);
            const _textBlock39 = new TextBlock();
            _textBlock39.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock39, "Status"));
            _textBlock39.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock39.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock39, "OnPrimary"));
            _textBlock39.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
            _textBlock39.set_property_value(TextBlock.MarginKey, new Thickness(20, 0, 0, 0));
            _stackPanel36.AddChild(_textBlock39);
            _border35.SetChild(_stackPanel36);
            _dockPanel34.AddChild(_border35);
            const _border40 = new Border();
            _border40.set_property_value(DockPanel.DockKey, Dock.Top);
            _border40.set_property_value(Border.HeightKey, 48);
            _border40.set_property_value(Border.BackgroundKey, DynamicResource(_border40, "SurfaceContainer"));
            _border40.set_property_value(Border.BorderBrushKey, DynamicResource(_border40, "OutlineVariant"));
            _border40.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 0, 1));
            _border40.set_property_value(Border.PaddingKey, new Thickness(8, 4, 8, 4));
            const _stackPanel41 = new StackPanel();
            _stackPanel41.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _iconButton13 = new IconButton();
            _iconButton13.Name = "btnAlignLeft";
            _iconButton13.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton13.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "AlignLeftCommand"));
            const _icon42 = new Icon();
            _icon42.set_property_value(Icon.SourceKey, DynamicResource(_icon42, "alignLeft"));
            _icon42.set_property_value(Icon.ForegroundKey, DynamicResource(_icon42, "OnSurfaceVariant"));
            _iconButton13.Content = _icon42;
            _stackPanel41.AddChild(_iconButton13);
            _iconButton14 = new IconButton();
            _iconButton14.Name = "btnAlignRight";
            _iconButton14.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton14.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "AlignRightCommand"));
            const _icon43 = new Icon();
            _icon43.set_property_value(Icon.SourceKey, DynamicResource(_icon43, "alignRight"));
            _icon43.set_property_value(Icon.ForegroundKey, DynamicResource(_icon43, "OnSurfaceVariant"));
            _iconButton14.Content = _icon43;
            _stackPanel41.AddChild(_iconButton14);
            _iconButton15 = new IconButton();
            _iconButton15.Name = "btnAlignTop";
            _iconButton15.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton15.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "AlignTopCommand"));
            _iconButton15.set_property_value(IconButton.MarginKey, new Thickness(8, 0, 0, 0));
            const _icon44 = new Icon();
            _icon44.set_property_value(Icon.SourceKey, DynamicResource(_icon44, "alignTop"));
            _icon44.set_property_value(Icon.ForegroundKey, DynamicResource(_icon44, "OnSurfaceVariant"));
            _iconButton15.Content = _icon44;
            _stackPanel41.AddChild(_iconButton15);
            _iconButton16 = new IconButton();
            _iconButton16.Name = "btnAlignMiddle";
            _iconButton16.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton16.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "AlignMiddleCommand"));
            const _icon45 = new Icon();
            _icon45.set_property_value(Icon.SourceKey, DynamicResource(_icon45, "alignMiddle"));
            _icon45.set_property_value(Icon.ForegroundKey, DynamicResource(_icon45, "OnSurfaceVariant"));
            _iconButton16.Content = _icon45;
            _stackPanel41.AddChild(_iconButton16);
            _iconButton17 = new IconButton();
            _iconButton17.Name = "btnAlignCenter";
            _iconButton17.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton17.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "AlignCenterCommand"));
            const _icon46 = new Icon();
            _icon46.set_property_value(Icon.SourceKey, DynamicResource(_icon46, "alignCenter"));
            _icon46.set_property_value(Icon.ForegroundKey, DynamicResource(_icon46, "OnSurfaceVariant"));
            _iconButton17.Content = _icon46;
            _stackPanel41.AddChild(_iconButton17);
            _iconButton18 = new IconButton();
            _iconButton18.Name = "btnDistH";
            _iconButton18.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton18.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "DistributeHorizontalCommand"));
            _iconButton18.set_property_value(IconButton.MarginKey, new Thickness(8, 0, 0, 0));
            const _icon47 = new Icon();
            _icon47.set_property_value(Icon.SourceKey, DynamicResource(_icon47, "distributeHorizontal"));
            _icon47.set_property_value(Icon.ForegroundKey, DynamicResource(_icon47, "OnSurfaceVariant"));
            _iconButton18.Content = _icon47;
            _stackPanel41.AddChild(_iconButton18);
            _iconButton19 = new IconButton();
            _iconButton19.Name = "btnDistV";
            _iconButton19.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton19.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "DistributeVerticalCommand"));
            const _icon48 = new Icon();
            _icon48.set_property_value(Icon.SourceKey, DynamicResource(_icon48, "distributeVertical"));
            _icon48.set_property_value(Icon.ForegroundKey, DynamicResource(_icon48, "OnSurfaceVariant"));
            _iconButton19.Content = _icon48;
            _stackPanel41.AddChild(_iconButton19);
            _iconButton20 = new IconButton();
            _iconButton20.Name = "btnGroup";
            _iconButton20.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton20.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "GroupCommand"));
            _iconButton20.set_property_value(IconButton.MarginKey, new Thickness(8, 0, 0, 0));
            const _icon49 = new Icon();
            _icon49.set_property_value(Icon.SourceKey, DynamicResource(_icon49, "group"));
            _icon49.set_property_value(Icon.ForegroundKey, DynamicResource(_icon49, "OnSurfaceVariant"));
            _iconButton20.Content = _icon49;
            _stackPanel41.AddChild(_iconButton20);
            _iconButton21 = new IconButton();
            _iconButton21.Name = "btnUngroup";
            _iconButton21.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton21.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "UngroupCommand"));
            const _icon50 = new Icon();
            _icon50.set_property_value(Icon.SourceKey, DynamicResource(_icon50, "ungroup"));
            _icon50.set_property_value(Icon.ForegroundKey, DynamicResource(_icon50, "OnSurfaceVariant"));
            _iconButton21.Content = _icon50;
            _stackPanel41.AddChild(_iconButton21);
            _iconButton22 = new IconButton();
            _iconButton22.Name = "btnCombineUnion";
            _iconButton22.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton22.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "CombineUnionCommand"));
            _iconButton22.set_property_value(IconButton.MarginKey, new Thickness(8, 0, 0, 0));
            const _textBlock51 = new TextBlock();
            _textBlock51.set_property_value(TextBlock.TextKey, "∪");
            _textBlock51.set_property_value(TextBlock.FontSizeKey, 16);
            _textBlock51.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock51.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock51, "OnSurfaceVariant"));
            _iconButton22.Content = _textBlock51;
            _stackPanel41.AddChild(_iconButton22);
            _iconButton23 = new IconButton();
            _iconButton23.Name = "btnCombineIntersect";
            _iconButton23.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton23.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "CombineIntersectCommand"));
            const _textBlock52 = new TextBlock();
            _textBlock52.set_property_value(TextBlock.TextKey, "∩");
            _textBlock52.set_property_value(TextBlock.FontSizeKey, 16);
            _textBlock52.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock52.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock52, "OnSurfaceVariant"));
            _iconButton23.Content = _textBlock52;
            _stackPanel41.AddChild(_iconButton23);
            _iconButton24 = new IconButton();
            _iconButton24.Name = "btnCombineSubtract";
            _iconButton24.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton24.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "CombineSubtractCommand"));
            const _textBlock53 = new TextBlock();
            _textBlock53.set_property_value(TextBlock.TextKey, "−");
            _textBlock53.set_property_value(TextBlock.FontSizeKey, 16);
            _textBlock53.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock53.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock53, "OnSurfaceVariant"));
            _iconButton24.Content = _textBlock53;
            _stackPanel41.AddChild(_iconButton24);
            _iconButton25 = new IconButton();
            _iconButton25.Name = "btnCombineExclude";
            _iconButton25.set_property_value(IconButton.VariantKey, ButtonVariant.Standard);
            _iconButton25.set_property_value(IconButton.CommandKey, ElementNameBinding(() => _diagram32, "CombineExcludeCommand"));
            const _textBlock54 = new TextBlock();
            _textBlock54.set_property_value(TextBlock.TextKey, "⊕");
            _textBlock54.set_property_value(TextBlock.FontSizeKey, 16);
            _textBlock54.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock54.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock54, "OnSurfaceVariant"));
            _iconButton25.Content = _textBlock54;
            _stackPanel41.AddChild(_iconButton25);
            _border40.SetChild(_stackPanel41);
            _dockPanel34.AddChild(_border40);
            const _border55 = new Border();
            _border55.set_property_value(DockPanel.DockKey, Dock.Left);
            _border55.set_property_value(Border.WidthKey, 200);
            _border55.set_property_value(Border.BackgroundKey, DynamicResource(_border55, "SurfaceContainerLow"));
            _border55.set_property_value(Border.BorderBrushKey, DynamicResource(_border55, "OutlineVariant"));
            _border55.set_property_value(Border.BorderThicknessKey, new Thickness(0, 0, 1, 0));
            _border55.set_property_value(Border.PaddingKey, new Thickness(8));
            const _dockPanel56 = new DockPanel();
            const _textBlock57 = new TextBlock();
            _textBlock57.set_property_value(DockPanel.DockKey, Dock.Top);
            _textBlock57.set_property_value(TextBlock.TextKey, "Shapes");
            _textBlock57.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock57.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock57.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock57, "OnSurfaceVariant"));
            _textBlock57.set_property_value(TextBlock.MarginKey, new Thickness(2, 0, 0, 8));
            _dockPanel56.AddChild(_textBlock57);
            const _stackPanel58 = new StackPanel();
            _stackPanel58.set_property_value(DockPanel.DockKey, Dock.Bottom);
            const _textBlock59 = new TextBlock();
            _textBlock59.set_property_value(TextBlock.TextKey, "Document");
            _textBlock59.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock59.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock59.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock59, "OnSurfaceVariant"));
            _textBlock59.set_property_value(TextBlock.MarginKey, new Thickness(2, 12, 0, 8));
            _stackPanel58.AddChild(_textBlock59);
            const _stackPanel60 = new StackPanel();
            _stackPanel60.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel60.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 8));
            _button26 = new Button();
            _button26.Name = "btnSave";
            _button26.set_property_value(Button.CommandKey, DataContextBinding(_button26, "SaveCommand"));
            _button26.set_property_value(Button.MarginKey, new Thickness(0, 0, 4, 0));
            const _textBlock61 = new TextBlock();
            _textBlock61.set_property_value(TextBlock.TextKey, "Save");
            _textBlock61.set_property_value(TextBlock.FontSizeKey, 11);
            _button26.Content = _textBlock61;
            _stackPanel60.AddChild(_button26);
            _button27 = new Button();
            _button27.Name = "btnLoad";
            _button27.set_property_value(Button.CommandKey, DataContextBinding(_button27, "LoadCommand"));
            const _textBlock62 = new TextBlock();
            _textBlock62.set_property_value(TextBlock.TextKey, "Load");
            _textBlock62.set_property_value(TextBlock.FontSizeKey, 11);
            _button27.Content = _textBlock62;
            _stackPanel60.AddChild(_button27);
            _stackPanel58.AddChild(_stackPanel60);
            const _textBlock63 = new TextBlock();
            _textBlock63.set_property_value(TextBlock.TextKey, "Drag a shape onto the canvas to\n                                            place it. Click a node to\n                                            select; Ctrl-click to toggle;\n                                            Shift-click to range-extend.\n                                            Drag-rectangle on empty space\n                                            for marquee. Click empty space\n                                            to clear. Delete removes every\n                                            selected node.");
            _textBlock63.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock63.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock63.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock63, "OnSurfaceVariant"));
            _textBlock63.set_property_value(TextBlock.MarginKey, new Thickness(2, 4, 2, 0));
            _stackPanel58.AddChild(_textBlock63);
            _dockPanel56.AddChild(_stackPanel58);
            const _scrollViewer64 = new ScrollViewer();
            _scrollViewer64.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, false);
            _itemsControl28 = new ItemsControl();
            _itemsControl28.Name = "toolbox";
            _itemsControl28.set_property_value(ItemsControl.ItemsSourceKey, DataContextBinding(_itemsControl28, "ToolboxShapes"));
            _itemsControl28.set_property_value(ItemsControl.ItemsPanelKey, _tmpl5);
            _scrollViewer64.Content = _itemsControl28;
            _dockPanel56.AddChild(_scrollViewer64);
            _border55.SetChild(_dockPanel56);
            _dockPanel34.AddChild(_border55);
            _border29 = new Border();
            _border29.Name = "formatPane";
            _border29.set_property_value(DockPanel.DockKey, Dock.Right);
            _border29.set_property_value(Border.WidthKey, 320);
            _border29.set_property_value(Border.BackgroundKey, DynamicResource(_border29, "SurfaceContainerLow"));
            _border29.set_property_value(Border.BorderBrushKey, DynamicResource(_border29, "OutlineVariant"));
            _border29.set_property_value(Border.BorderThicknessKey, new Thickness(1, 0, 0, 0));
            _border29.set_property_value(Border.PaddingKey, new Thickness(12));
            const _dockPanel65 = new DockPanel();
            const _textBlock66 = new TextBlock();
            _textBlock66.set_property_value(DockPanel.DockKey, Dock.Top);
            _textBlock66.set_property_value(TextBlock.TextKey, "Format Shape");
            _textBlock66.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock66.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock66.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock66, "OnSurfaceVariant"));
            _textBlock66.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _dockPanel65.AddChild(_textBlock66);
            const _scrollViewer67 = new ScrollViewer();
            _scrollViewer67.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, false);
            const _shapeFormatControl68 = new ShapeFormatControl();
            _shapeFormatControl68.set_property_value(ShapeFormatControl.FillKey, ElementNameBinding(() => _diagram32, "SelectionFormatFill"));
            _shapeFormatControl68.set_property_value(ShapeFormatControl.StrokeKey, ElementNameBinding(() => _diagram32, "SelectionFormatStroke"));
            _scrollViewer67.Content = _shapeFormatControl68;
            _dockPanel65.AddChild(_scrollViewer67);
            _border29.SetChild(_dockPanel65);
            _dockPanel34.AddChild(_border29);
            const _splitter69 = new Splitter();
            _splitter69.set_property_value(DockPanel.DockKey, Dock.Right);
            _splitter69.set_property_value(Splitter.WidthKey, 6);
            _splitter69.set_property_value(Splitter.OrientationKey, Orientation.Vertical);
            _splitter69.set_property_value(Splitter.ReverseDirectionKey, true);
            _dockPanel34.AddChild(_splitter69);
            _border30 = new Border();
            _border30.Name = "surface";
            _scrollViewer31 = new ScrollViewer();
            _scrollViewer31.Name = "scroll";
            _scrollViewer31.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, false);
            _diagram32 = new Diagram();
            _diagram32.Name = "nodes";
            _diagram32.set_property_value(Diagram.ItemsSourceKey, DataContextBinding(_diagram32, "Nodes"));
            _diagram32.set_property_value(Diagram.ItemsPanelKey, _tmpl3);
            _diagram32.set_property_value(Diagram.ItemContainerStyleKey, _style2);
            _diagram32.set_property_value(Diagram.SelectionModeKey, SelectionMode.Extended);
            _diagram32.set_property_value(Diagram.AllowMarqueeSelectionKey, true);
            _diagram32.set_property_value(Diagram.AlignmentGuidesEnabledKey, true);
            _diagram32.set_property_value(Diagram.SelectionResizeEnabledKey, true);
            _diagram32.set_property_value(Diagram.ReflectSelectionToItemsKey, true);
            _diagram32.set_property_value(Diagram.DropReceiverKey, ElementNameBinding(() => _border30, ""));
            _diagram32.set_property_value(Diagram.MutatorKey, DataContextBinding(_diagram32, "Self"));
            _diagram32.set_property_value(Diagram.FocusableKey, true);
            _scrollViewer31.Content = _diagram32;
            _border30.SetChild(_scrollViewer31);
            _dockPanel34.AddChild(_border30);
            _border33.SetChild(_dockPanel34);
            return _border33;
        }, DiagramVM);
        t.Set("DiagramTemplate", _tmpl12);
        return t;
    }
    get DiagramNodeStyle() { return this.Resolve("DiagramNodeStyle"); }
    set DiagramNodeStyle(v) { this.Set("DiagramNodeStyle", v); }
    get DiagramCanvasPanel() { return this.Resolve("DiagramCanvasPanel"); }
    set DiagramCanvasPanel(v) { this.Set("DiagramCanvasPanel", v); }
    get DiagramToolboxPanel() { return this.Resolve("DiagramToolboxPanel"); }
    set DiagramToolboxPanel(v) { this.Set("DiagramToolboxPanel", v); }
    get DiagramTileTemplate() { return this.Resolve("DiagramTileTemplate"); }
    set DiagramTileTemplate(v) { this.Set("DiagramTileTemplate", v); }
    get DiagramTemplate() { return this.Resolve("DiagramTemplate"); }
    set DiagramTemplate(v) { this.Set("DiagramTemplate", v); }
}
