import { DiagramVM, ToolboxShapeVM } from "./diagram-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Icon, ItemsPanelTemplate, Orientation, PaginatedCanvas, StackPanel, TextBlock, TextWrapping, UniformGrid } from "@visualisation-sub/mural/basic";
import { Button } from "@visualisation-sub/mural/framework/button.js";
import { ContentControl } from "@visualisation-sub/mural/framework/content-control.js";
import { DiagramNode } from "@visualisation-sub/mural/framework/diagram/diagram-node.js";
import { Diagram } from "@visualisation-sub/mural/framework/diagram/diagram.js";
import { ItemsControl } from "@visualisation-sub/mural/framework/items-control.js";
import { SelectionMode } from "@visualisation-sub/mural/framework/list/list-box.js";
import { ScrollViewer } from "@visualisation-sub/mural/framework/scroll-viewer.js";
import { DataContextBinding, DynamicResource, HorizontalAlignment, NameScope, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { FontWeight } from "@visualisation-sub/mural/visual-engine";


const _gate_DiagramDemo = Symbol("DiagramDemo.ctor");
export class DiagramDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_DiagramDemo) {
            throw new Error("DiagramDemo is private — use DiagramDemo.Clone()");
        }
    }
    static Clone() {
        const t = new DiagramDemo(_gate_DiagramDemo);
        const _setter0 = new Setter(DiagramNode, "X", new SetterFactory((_t) => DataContextBinding(_t, "X")));
        const _setter1 = new Setter(DiagramNode, "Y", new SetterFactory((_t) => DataContextBinding(_t, "Y")));
        const _style2 = new Style(DiagramNode, [_setter0, _setter1], undefined, [], []);
        t.Set("DiagramNodeStyle", _style2);
        const _tmpl3 = new ItemsPanelTemplate(() => {
            const _paginatedCanvas4 = new PaginatedCanvas();
            _paginatedCanvas4._set_property_value_by_name("PageWidth", 800);
            _paginatedCanvas4._set_property_value_by_name("PageHeight", 600);
            return _paginatedCanvas4;
        });
        t.Set("DiagramCanvasPanel", _tmpl3);
        const _tmpl5 = new ItemsPanelTemplate(() => {
            const _uniformGrid6 = new UniformGrid();
            _uniformGrid6._set_property_value_by_name("Columns", 2);
            return _uniformGrid6;
        });
        t.Set("DiagramToolboxPanel", _tmpl5);
        const _tmpl7 = new DataTemplate((_data) => {
            const _border8 = new Border();
            _border8.SetNameScope(new NameScope());
            _border8._set_property_value_by_name("IsDraggable", true);
            _border8._set_property_value_by_name("OnDragStart", DataContextBinding(_border8, "BeginKindDragData"));
            _border8._set_property_value_by_name("Background", DynamicResource(_border8, "Surface"));
            _border8._set_property_value_by_name("BorderBrush", DynamicResource(_border8, "OutlineVariant"));
            _border8._set_property_value_by_name("BorderThickness", new Thickness(1));
            _border8._set_property_value_by_name("CornerRadius", 4);
            _border8._set_property_value_by_name("Padding", new Thickness(4, 8, 4, 8));
            _border8._set_property_value_by_name("Margin", new Thickness(2, 0, 2, 4));
            const _stackPanel9 = new StackPanel();
            _stackPanel9._set_property_value_by_name("Orientation", Orientation.Vertical);
            _stackPanel9._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            const _contentControl10 = new ContentControl();
            _contentControl10._set_property_value_by_name("Content", DataContextBinding(_contentControl10, "PreviewNode"));
            _contentControl10._set_property_value_by_name("Width", 48);
            _contentControl10._set_property_value_by_name("Height", 48);
            _contentControl10._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _stackPanel9.AddChild(_contentControl10);
            const _textBlock11 = new TextBlock();
            _textBlock11._set_property_value_by_name("Text", DataContextBinding(_textBlock11, "Label"));
            _textBlock11._set_property_value_by_name("FontSize", 10);
            _textBlock11._set_property_value_by_name("Foreground", DynamicResource(_textBlock11, "OnSurface"));
            _textBlock11._set_property_value_by_name("Margin", new Thickness(0, 4, 0, 0));
            _textBlock11._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _stackPanel9.AddChild(_textBlock11);
            _border8.SetChild(_stackPanel9);
            return _border8;
        }, ToolboxShapeVM);
        t.Set("DiagramTileTemplate", _tmpl7);
        const _tmpl12 = new DataTemplate((_data) => {
            const _border13 = new Border();
            _border13.SetNameScope(new NameScope());
            _border13._set_property_value_by_name("Background", DynamicResource(_border13, "Surface"));
            _border13._set_property_value_by_name("BorderBrush", DynamicResource(_border13, "OutlineVariant"));
            _border13._set_property_value_by_name("BorderThickness", new Thickness(1));
            const _dockPanel14 = new DockPanel();
            const _border15 = new Border();
            _border15._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border15._set_property_value_by_name("Height", 44);
            _border15._set_property_value_by_name("Background", DynamicResource(_border15, "Primary"));
            const _stackPanel16 = new StackPanel();
            _stackPanel16._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel16._set_property_value_by_name("Margin", new Thickness(16, 0, 0, 0));
            const _icon17 = new Icon();
            _icon17._set_property_value_by_name("Source", DynamicResource(_icon17, "home"));
            _icon17._set_property_value_by_name("Foreground", DynamicResource(_icon17, "OnPrimary"));
            _icon17._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _stackPanel16.AddChild(_icon17);
            const _textBlock18 = new TextBlock();
            _textBlock18._set_property_value_by_name("Text", "Diagrammer");
            _textBlock18._set_property_value_by_name("FontSize", 15);
            _textBlock18._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock18._set_property_value_by_name("Foreground", DynamicResource(_textBlock18, "OnPrimary"));
            _textBlock18._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _textBlock18._set_property_value_by_name("Margin", new Thickness(8, 0, 0, 0));
            _stackPanel16.AddChild(_textBlock18);
            const _textBlock19 = new TextBlock();
            _textBlock19._set_property_value_by_name("Text", DataContextBinding(_textBlock19, "Status"));
            _textBlock19._set_property_value_by_name("FontSize", 12);
            _textBlock19._set_property_value_by_name("Foreground", DynamicResource(_textBlock19, "OnPrimary"));
            _textBlock19._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _textBlock19._set_property_value_by_name("Margin", new Thickness(20, 0, 0, 0));
            _stackPanel16.AddChild(_textBlock19);
            _border15.SetChild(_stackPanel16);
            _dockPanel14.AddChild(_border15);
            const _border20 = new Border();
            _border20._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _border20._set_property_value_by_name("Height", 40);
            _border20._set_property_value_by_name("Background", DynamicResource(_border20, "SurfaceContainer"));
            _border20._set_property_value_by_name("BorderBrush", DynamicResource(_border20, "OutlineVariant"));
            _border20._set_property_value_by_name("BorderThickness", new Thickness(0, 0, 0, 1));
            _border20._set_property_value_by_name("Padding", new Thickness(8, 4, 8, 4));
            const _stackPanel21 = new StackPanel();
            _stackPanel21._set_property_value_by_name("Orientation", Orientation.Horizontal);
            const _button22 = new Button();
            _button22.Name = "btnAlignLeft";
            _button22._set_property_value_by_name("Command", DataContextBinding(_button22, "AlignLeftCommand"));
            _button22._set_property_value_by_name("Margin", new Thickness(0, 0, 2, 0));
            _button22._set_property_value_by_name("MinWidth", 32);
            _button22._set_property_value_by_name("MinHeight", 32);
            const _textBlock23 = new TextBlock();
            _textBlock23._set_property_value_by_name("Text", "align_horizontal_left");
            _textBlock23._set_property_value_by_name("FontFamily", "Material Symbols Outlined");
            _textBlock23._set_property_value_by_name("FontSize", 20);
            _textBlock23._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock23._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _button22.Content = _textBlock23;
            _stackPanel21.AddChild(_button22);
            const _button24 = new Button();
            _button24.Name = "btnAlignRight";
            _button24._set_property_value_by_name("Command", DataContextBinding(_button24, "AlignRightCommand"));
            _button24._set_property_value_by_name("Margin", new Thickness(0, 0, 2, 0));
            _button24._set_property_value_by_name("MinWidth", 32);
            _button24._set_property_value_by_name("MinHeight", 32);
            const _textBlock25 = new TextBlock();
            _textBlock25._set_property_value_by_name("Text", "align_horizontal_right");
            _textBlock25._set_property_value_by_name("FontFamily", "Material Symbols Outlined");
            _textBlock25._set_property_value_by_name("FontSize", 20);
            _textBlock25._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock25._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _button24.Content = _textBlock25;
            _stackPanel21.AddChild(_button24);
            const _button26 = new Button();
            _button26.Name = "btnAlignTop";
            _button26._set_property_value_by_name("Command", DataContextBinding(_button26, "AlignTopCommand"));
            _button26._set_property_value_by_name("Margin", new Thickness(8, 0, 2, 0));
            _button26._set_property_value_by_name("MinWidth", 32);
            _button26._set_property_value_by_name("MinHeight", 32);
            const _textBlock27 = new TextBlock();
            _textBlock27._set_property_value_by_name("Text", "align_vertical_top");
            _textBlock27._set_property_value_by_name("FontFamily", "Material Symbols Outlined");
            _textBlock27._set_property_value_by_name("FontSize", 20);
            _textBlock27._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock27._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _button26.Content = _textBlock27;
            _stackPanel21.AddChild(_button26);
            const _button28 = new Button();
            _button28.Name = "btnAlignMiddle";
            _button28._set_property_value_by_name("Command", DataContextBinding(_button28, "AlignMiddleCommand"));
            _button28._set_property_value_by_name("Margin", new Thickness(0, 0, 2, 0));
            _button28._set_property_value_by_name("MinWidth", 32);
            _button28._set_property_value_by_name("MinHeight", 32);
            const _textBlock29 = new TextBlock();
            _textBlock29._set_property_value_by_name("Text", "align_vertical_center");
            _textBlock29._set_property_value_by_name("FontFamily", "Material Symbols Outlined");
            _textBlock29._set_property_value_by_name("FontSize", 20);
            _textBlock29._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock29._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _button28.Content = _textBlock29;
            _stackPanel21.AddChild(_button28);
            const _button30 = new Button();
            _button30.Name = "btnAlignCenter";
            _button30._set_property_value_by_name("Command", DataContextBinding(_button30, "AlignCenterCommand"));
            _button30._set_property_value_by_name("Margin", new Thickness(0, 0, 2, 0));
            _button30._set_property_value_by_name("MinWidth", 32);
            _button30._set_property_value_by_name("MinHeight", 32);
            const _textBlock31 = new TextBlock();
            _textBlock31._set_property_value_by_name("Text", "align_horizontal_center");
            _textBlock31._set_property_value_by_name("FontFamily", "Material Symbols Outlined");
            _textBlock31._set_property_value_by_name("FontSize", 20);
            _textBlock31._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock31._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _button30.Content = _textBlock31;
            _stackPanel21.AddChild(_button30);
            const _button32 = new Button();
            _button32.Name = "btnDistH";
            _button32._set_property_value_by_name("Command", DataContextBinding(_button32, "DistributeHorizontalCommand"));
            _button32._set_property_value_by_name("Margin", new Thickness(8, 0, 2, 0));
            _button32._set_property_value_by_name("MinWidth", 32);
            _button32._set_property_value_by_name("MinHeight", 32);
            const _textBlock33 = new TextBlock();
            _textBlock33._set_property_value_by_name("Text", "horizontal_distribute");
            _textBlock33._set_property_value_by_name("FontFamily", "Material Symbols Outlined");
            _textBlock33._set_property_value_by_name("FontSize", 20);
            _textBlock33._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock33._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _button32.Content = _textBlock33;
            _stackPanel21.AddChild(_button32);
            const _button34 = new Button();
            _button34.Name = "btnDistV";
            _button34._set_property_value_by_name("Command", DataContextBinding(_button34, "DistributeVerticalCommand"));
            _button34._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 0));
            _button34._set_property_value_by_name("MinWidth", 32);
            _button34._set_property_value_by_name("MinHeight", 32);
            const _textBlock35 = new TextBlock();
            _textBlock35._set_property_value_by_name("Text", "vertical_distribute");
            _textBlock35._set_property_value_by_name("FontFamily", "Material Symbols Outlined");
            _textBlock35._set_property_value_by_name("FontSize", 20);
            _textBlock35._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock35._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _button34.Content = _textBlock35;
            _stackPanel21.AddChild(_button34);
            const _button36 = new Button();
            _button36.Name = "btnGroup";
            _button36._set_property_value_by_name("Command", DataContextBinding(_button36, "GroupCommand"));
            _button36._set_property_value_by_name("Margin", new Thickness(8, 0, 2, 0));
            _button36._set_property_value_by_name("MinWidth", 32);
            _button36._set_property_value_by_name("MinHeight", 32);
            const _textBlock37 = new TextBlock();
            _textBlock37._set_property_value_by_name("Text", "group_work");
            _textBlock37._set_property_value_by_name("FontFamily", "Material Symbols Outlined");
            _textBlock37._set_property_value_by_name("FontSize", 20);
            _textBlock37._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock37._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _button36.Content = _textBlock37;
            _stackPanel21.AddChild(_button36);
            const _button38 = new Button();
            _button38.Name = "btnUngroup";
            _button38._set_property_value_by_name("Command", DataContextBinding(_button38, "UngroupCommand"));
            _button38._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 0));
            _button38._set_property_value_by_name("MinWidth", 32);
            _button38._set_property_value_by_name("MinHeight", 32);
            const _textBlock39 = new TextBlock();
            _textBlock39._set_property_value_by_name("Text", "group_off");
            _textBlock39._set_property_value_by_name("FontFamily", "Material Symbols Outlined");
            _textBlock39._set_property_value_by_name("FontSize", 20);
            _textBlock39._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
            _textBlock39._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
            _button38.Content = _textBlock39;
            _stackPanel21.AddChild(_button38);
            _border20.SetChild(_stackPanel21);
            _dockPanel14.AddChild(_border20);
            const _border40 = new Border();
            _border40._set_property_value_by_name(DockPanel, "Dock", Dock.Left);
            _border40._set_property_value_by_name("Width", 200);
            _border40._set_property_value_by_name("Background", DynamicResource(_border40, "SurfaceContainerLow"));
            _border40._set_property_value_by_name("BorderBrush", DynamicResource(_border40, "OutlineVariant"));
            _border40._set_property_value_by_name("BorderThickness", new Thickness(0, 0, 1, 0));
            _border40._set_property_value_by_name("Padding", new Thickness(8));
            const _dockPanel41 = new DockPanel();
            const _textBlock42 = new TextBlock();
            _textBlock42._set_property_value_by_name(DockPanel, "Dock", Dock.Top);
            _textBlock42._set_property_value_by_name("Text", "Shapes");
            _textBlock42._set_property_value_by_name("FontSize", 11);
            _textBlock42._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock42._set_property_value_by_name("Foreground", DynamicResource(_textBlock42, "OnSurfaceVariant"));
            _textBlock42._set_property_value_by_name("Margin", new Thickness(2, 0, 0, 8));
            _dockPanel41.AddChild(_textBlock42);
            const _stackPanel43 = new StackPanel();
            _stackPanel43._set_property_value_by_name(DockPanel, "Dock", Dock.Bottom);
            const _textBlock44 = new TextBlock();
            _textBlock44._set_property_value_by_name("Text", "Document");
            _textBlock44._set_property_value_by_name("FontSize", 11);
            _textBlock44._set_property_value_by_name("FontWeight", FontWeight.Bold);
            _textBlock44._set_property_value_by_name("Foreground", DynamicResource(_textBlock44, "OnSurfaceVariant"));
            _textBlock44._set_property_value_by_name("Margin", new Thickness(2, 12, 0, 8));
            _stackPanel43.AddChild(_textBlock44);
            const _stackPanel45 = new StackPanel();
            _stackPanel45._set_property_value_by_name("Orientation", Orientation.Horizontal);
            _stackPanel45._set_property_value_by_name("Margin", new Thickness(0, 0, 0, 8));
            const _button46 = new Button();
            _button46.Name = "btnSave";
            _button46._set_property_value_by_name("Command", DataContextBinding(_button46, "SaveCommand"));
            _button46._set_property_value_by_name("Margin", new Thickness(0, 0, 4, 0));
            const _textBlock47 = new TextBlock();
            _textBlock47._set_property_value_by_name("Text", "Save");
            _textBlock47._set_property_value_by_name("FontSize", 11);
            _button46.Content = _textBlock47;
            _stackPanel45.AddChild(_button46);
            const _button48 = new Button();
            _button48.Name = "btnLoad";
            _button48._set_property_value_by_name("Command", DataContextBinding(_button48, "LoadCommand"));
            const _textBlock49 = new TextBlock();
            _textBlock49._set_property_value_by_name("Text", "Load");
            _textBlock49._set_property_value_by_name("FontSize", 11);
            _button48.Content = _textBlock49;
            _stackPanel45.AddChild(_button48);
            _stackPanel43.AddChild(_stackPanel45);
            const _textBlock50 = new TextBlock();
            _textBlock50._set_property_value_by_name("Text", "Drag a shape onto the canvas to\n                                            place it. Click a node to\n                                            select; Ctrl-click to toggle;\n                                            Shift-click to range-extend.\n                                            Drag-rectangle on empty space\n                                            for marquee. Click empty space\n                                            to clear. Delete removes every\n                                            selected node.");
            _textBlock50._set_property_value_by_name("TextWrapping", TextWrapping.Wrap);
            _textBlock50._set_property_value_by_name("FontSize", 10);
            _textBlock50._set_property_value_by_name("Foreground", DynamicResource(_textBlock50, "OnSurfaceVariant"));
            _textBlock50._set_property_value_by_name("Margin", new Thickness(2, 4, 2, 0));
            _stackPanel43.AddChild(_textBlock50);
            _dockPanel41.AddChild(_stackPanel43);
            const _scrollViewer51 = new ScrollViewer();
            _scrollViewer51._set_property_value_by_name("IsAutoHideScrollBars", false);
            const _itemsControl52 = new ItemsControl();
            _itemsControl52.Name = "toolbox";
            _itemsControl52._set_property_value_by_name("ItemsSource", DataContextBinding(_itemsControl52, "ToolboxShapes"));
            _itemsControl52._set_property_value_by_name("ItemsPanel", _tmpl5);
            _scrollViewer51.Content = _itemsControl52;
            _dockPanel41.AddChild(_scrollViewer51);
            _border40.SetChild(_dockPanel41);
            _dockPanel14.AddChild(_border40);
            const _border53 = new Border();
            _border53.Name = "surface";
            const _scrollViewer54 = new ScrollViewer();
            _scrollViewer54.Name = "scroll";
            _scrollViewer54._set_property_value_by_name("IsAutoHideScrollBars", false);
            const _diagram55 = new Diagram();
            _diagram55.Name = "nodes";
            _diagram55._set_property_value_by_name("ItemsSource", DataContextBinding(_diagram55, "Nodes"));
            _diagram55._set_property_value_by_name("ItemsPanel", _tmpl3);
            _diagram55._set_property_value_by_name("ItemContainerStyle", _style2);
            _diagram55._set_property_value_by_name("SelectionMode", SelectionMode.Extended);
            _diagram55._set_property_value_by_name("AllowMarqueeSelection", true);
            _diagram55._set_property_value_by_name("Focusable", true);
            _scrollViewer54.Content = _diagram55;
            _border53.SetChild(_scrollViewer54);
            _dockPanel14.AddChild(_border53);
            _border13.SetChild(_dockPanel14);
            return _border13;
        }, DiagramVM);
        t.Set("DiagramTemplate", _tmpl12);
        return t;
    }
    get DiagramNodeStyle() { return this.Resolve("DiagramNodeStyle"); }
    set DiagramNodeStyle(v) { this.Set("DiagramNodeStyle", v); }
    get DiagramCanvasPanel() { return this.Resolve("DiagramCanvasPanel"); }
    set DiagramCanvasPanel(v) { this.Set("DiagramCanvasPanel", v); }
    get DiagramToolboxPanel() { return this.Resolve("DiagramToolboxPanel"); }
    set DiagramToolboxPanel(v) { this.Set("DiagramToolboxPanel", v); }
    get DiagramTileTemplate() { return this.Resolve("DiagramTileTemplate"); }
    set DiagramTileTemplate(v) { this.Set("DiagramTileTemplate", v); }
    get DiagramTemplate() { return this.Resolve("DiagramTemplate"); }
    set DiagramTemplate(v) { this.Set("DiagramTemplate", v); }
}
