import { ArchShapeVM, ArrowShapeVM, BoomShapeVM, BunShapeVM, BurstShapeVM, ClamshellShapeVM, DiamondShapeVM, EightLeafCloverShapeVM, EllipseShapeVM, FanShapeVM, FlowerShapeVM, FourCookieShapeVM, FourLeafCloverShapeVM, GemShapeVM, GhostishShapeVM, GroupVM, HeartShapeVM, NineCookieShapeVM, PentagonShapeVM, PillShapeVM, PixelCircleShapeVM, PixelTriangleShapeVM, PuffyDiamondShapeVM, PuffyShapeVM, RectangleShapeVM, SemicircleShapeVM, SevenCookieShapeVM, SixCookieShapeVM, SlantedShapeVM, SoftBoomShapeVM, SoftBurstShapeVM, SquircleShapeVM, SunnyShapeVM, TriangleShapeVM, TwelveCookieShapeVM, VerySunnyShapeVM } from "./diagram-vm.mjs";
import { Arch, Arrow, Boom, Border, Bun, Burst, Canvas, Clamshell, DataTemplate, Diamond, EightLeafClover, Ellipse, Fan, Flower, FourLeafClover, FourSidedCookie, Gem, Ghostish, Heart, NineSidedCookie, Pentagon, Pill, PixelCircle, PixelTriangle, Puffy, PuffyDiamond, Rectangle, Semicircle, SevenSidedCookie, SixSidedCookie, Slanted, SoftBoom, SoftBurst, Squircle, Sunny, TargetedSetter, TemplateDataTrigger, TextBlock, Triangle, TwelveSidedCookie, VerySunny } from "@visualisation-sub/mural/basic";
import { Color, DataContextBinding, DynamicResource, HorizontalAlignment, NameScope, ResourceDictionary, Thickness, VerticalAlignment } from "@visualisation-sub/mural/runtime";
import { SolidColorBrush } from "@visualisation-sub/mural/visual-engine";


const _gate_DiagramShapeTemplates = Symbol("DiagramShapeTemplates.ctor");
export class DiagramShapeTemplates extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_DiagramShapeTemplates) {
            throw new Error("DiagramShapeTemplates is private — use DiagramShapeTemplates.Clone()");
        }
    }
    static Clone() {
        const t = new DiagramShapeTemplates(_gate_DiagramShapeTemplates);
        const _tmpl0 = (() => {
            const _factory = (_data) => {
                const _canvas1 = new Canvas();
                _canvas1.SetNameScope(new NameScope());
                _canvas1._set_property_value_by_name("Width", DataContextBinding(_canvas1, "Width"));
                _canvas1._set_property_value_by_name("Height", DataContextBinding(_canvas1, "Height"));
                const _rectangle2 = new Rectangle();
                _rectangle2.Name = "chrome";
                _rectangle2._set_property_value_by_name("Width", DataContextBinding(_rectangle2, "Width"));
                _rectangle2._set_property_value_by_name("Height", DataContextBinding(_rectangle2, "Height"));
                _rectangle2._set_property_value_by_name("Background", DataContextBinding(_rectangle2, "FillBrush"));
                _rectangle2._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _rectangle2._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas1.AddChild(_rectangle2);
                const _textBlock3 = new TextBlock();
                _textBlock3._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock3._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock3._set_property_value_by_name("Width", DataContextBinding(_textBlock3, "Width"));
                _textBlock3._set_property_value_by_name("Height", DataContextBinding(_textBlock3, "Height"));
                _textBlock3._set_property_value_by_name("Text", DataContextBinding(_textBlock3, "LabelText"));
                _textBlock3._set_property_value_by_name("FontSize", 11);
                _textBlock3._set_property_value_by_name("Foreground", DynamicResource(_textBlock3, "OnSurface"));
                _textBlock3._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock3._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas1.AddChild(_textBlock3);
                return _canvas1;
            };
            const _tplSet4 = [new TargetedSetter(Rectangle, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig5 = new TemplateDataTrigger("IsSelected", true, _tplSet4);
            return new DataTemplate(_factory, RectangleShapeVM, [], [_tplDataTrig5]);
        })();
        t.Set(RectangleShapeVM, _tmpl0);
        const _tmpl6 = (() => {
            const _factory = (_data) => {
                const _canvas7 = new Canvas();
                _canvas7.SetNameScope(new NameScope());
                _canvas7._set_property_value_by_name("Width", DataContextBinding(_canvas7, "Width"));
                _canvas7._set_property_value_by_name("Height", DataContextBinding(_canvas7, "Height"));
                const _ellipse8 = new Ellipse();
                _ellipse8.Name = "chrome";
                _ellipse8._set_property_value_by_name("Width", DataContextBinding(_ellipse8, "Width"));
                _ellipse8._set_property_value_by_name("Height", DataContextBinding(_ellipse8, "Height"));
                _ellipse8._set_property_value_by_name("Background", DataContextBinding(_ellipse8, "FillBrush"));
                _ellipse8._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _ellipse8._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas7.AddChild(_ellipse8);
                const _textBlock9 = new TextBlock();
                _textBlock9._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock9._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock9._set_property_value_by_name("Width", DataContextBinding(_textBlock9, "Width"));
                _textBlock9._set_property_value_by_name("Height", DataContextBinding(_textBlock9, "Height"));
                _textBlock9._set_property_value_by_name("Text", DataContextBinding(_textBlock9, "LabelText"));
                _textBlock9._set_property_value_by_name("FontSize", 11);
                _textBlock9._set_property_value_by_name("Foreground", DynamicResource(_textBlock9, "OnSurface"));
                _textBlock9._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock9._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas7.AddChild(_textBlock9);
                return _canvas7;
            };
            const _tplSet10 = [new TargetedSetter(Ellipse, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig11 = new TemplateDataTrigger("IsSelected", true, _tplSet10);
            return new DataTemplate(_factory, EllipseShapeVM, [], [_tplDataTrig11]);
        })();
        t.Set(EllipseShapeVM, _tmpl6);
        const _tmpl12 = (() => {
            const _factory = (_data) => {
                const _canvas13 = new Canvas();
                _canvas13.SetNameScope(new NameScope());
                _canvas13._set_property_value_by_name("Width", DataContextBinding(_canvas13, "Width"));
                _canvas13._set_property_value_by_name("Height", DataContextBinding(_canvas13, "Height"));
                const _squircle14 = new Squircle();
                _squircle14.Name = "chrome";
                _squircle14._set_property_value_by_name("Width", DataContextBinding(_squircle14, "Width"));
                _squircle14._set_property_value_by_name("Height", DataContextBinding(_squircle14, "Height"));
                _squircle14._set_property_value_by_name("Background", DataContextBinding(_squircle14, "FillBrush"));
                _squircle14._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _squircle14._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas13.AddChild(_squircle14);
                const _textBlock15 = new TextBlock();
                _textBlock15._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock15._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock15._set_property_value_by_name("Width", DataContextBinding(_textBlock15, "Width"));
                _textBlock15._set_property_value_by_name("Height", DataContextBinding(_textBlock15, "Height"));
                _textBlock15._set_property_value_by_name("Text", DataContextBinding(_textBlock15, "LabelText"));
                _textBlock15._set_property_value_by_name("FontSize", 11);
                _textBlock15._set_property_value_by_name("Foreground", DynamicResource(_textBlock15, "OnSurface"));
                _textBlock15._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock15._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas13.AddChild(_textBlock15);
                return _canvas13;
            };
            const _tplSet16 = [new TargetedSetter(Squircle, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig17 = new TemplateDataTrigger("IsSelected", true, _tplSet16);
            return new DataTemplate(_factory, SquircleShapeVM, [], [_tplDataTrig17]);
        })();
        t.Set(SquircleShapeVM, _tmpl12);
        const _tmpl18 = (() => {
            const _factory = (_data) => {
                const _canvas19 = new Canvas();
                _canvas19.SetNameScope(new NameScope());
                _canvas19._set_property_value_by_name("Width", DataContextBinding(_canvas19, "Width"));
                _canvas19._set_property_value_by_name("Height", DataContextBinding(_canvas19, "Height"));
                const _slanted20 = new Slanted();
                _slanted20.Name = "chrome";
                _slanted20._set_property_value_by_name("Width", DataContextBinding(_slanted20, "Width"));
                _slanted20._set_property_value_by_name("Height", DataContextBinding(_slanted20, "Height"));
                _slanted20._set_property_value_by_name("Background", DataContextBinding(_slanted20, "FillBrush"));
                _slanted20._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _slanted20._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas19.AddChild(_slanted20);
                const _textBlock21 = new TextBlock();
                _textBlock21._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock21._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock21._set_property_value_by_name("Width", DataContextBinding(_textBlock21, "Width"));
                _textBlock21._set_property_value_by_name("Height", DataContextBinding(_textBlock21, "Height"));
                _textBlock21._set_property_value_by_name("Text", DataContextBinding(_textBlock21, "LabelText"));
                _textBlock21._set_property_value_by_name("FontSize", 11);
                _textBlock21._set_property_value_by_name("Foreground", DynamicResource(_textBlock21, "OnSurface"));
                _textBlock21._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock21._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas19.AddChild(_textBlock21);
                return _canvas19;
            };
            const _tplSet22 = [new TargetedSetter(Slanted, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig23 = new TemplateDataTrigger("IsSelected", true, _tplSet22);
            return new DataTemplate(_factory, SlantedShapeVM, [], [_tplDataTrig23]);
        })();
        t.Set(SlantedShapeVM, _tmpl18);
        const _tmpl24 = (() => {
            const _factory = (_data) => {
                const _canvas25 = new Canvas();
                _canvas25.SetNameScope(new NameScope());
                _canvas25._set_property_value_by_name("Width", DataContextBinding(_canvas25, "Width"));
                _canvas25._set_property_value_by_name("Height", DataContextBinding(_canvas25, "Height"));
                const _pill26 = new Pill();
                _pill26.Name = "chrome";
                _pill26._set_property_value_by_name("Width", DataContextBinding(_pill26, "Width"));
                _pill26._set_property_value_by_name("Height", DataContextBinding(_pill26, "Height"));
                _pill26._set_property_value_by_name("Background", DataContextBinding(_pill26, "FillBrush"));
                _pill26._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _pill26._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas25.AddChild(_pill26);
                const _textBlock27 = new TextBlock();
                _textBlock27._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock27._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock27._set_property_value_by_name("Width", DataContextBinding(_textBlock27, "Width"));
                _textBlock27._set_property_value_by_name("Height", DataContextBinding(_textBlock27, "Height"));
                _textBlock27._set_property_value_by_name("Text", DataContextBinding(_textBlock27, "LabelText"));
                _textBlock27._set_property_value_by_name("FontSize", 11);
                _textBlock27._set_property_value_by_name("Foreground", DynamicResource(_textBlock27, "OnSurface"));
                _textBlock27._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock27._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas25.AddChild(_textBlock27);
                return _canvas25;
            };
            const _tplSet28 = [new TargetedSetter(Pill, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig29 = new TemplateDataTrigger("IsSelected", true, _tplSet28);
            return new DataTemplate(_factory, PillShapeVM, [], [_tplDataTrig29]);
        })();
        t.Set(PillShapeVM, _tmpl24);
        const _tmpl30 = (() => {
            const _factory = (_data) => {
                const _canvas31 = new Canvas();
                _canvas31.SetNameScope(new NameScope());
                _canvas31._set_property_value_by_name("Width", DataContextBinding(_canvas31, "Width"));
                _canvas31._set_property_value_by_name("Height", DataContextBinding(_canvas31, "Height"));
                const _diamond32 = new Diamond();
                _diamond32.Name = "chrome";
                _diamond32._set_property_value_by_name("Width", DataContextBinding(_diamond32, "Width"));
                _diamond32._set_property_value_by_name("Height", DataContextBinding(_diamond32, "Height"));
                _diamond32._set_property_value_by_name("Background", DataContextBinding(_diamond32, "FillBrush"));
                _diamond32._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _diamond32._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas31.AddChild(_diamond32);
                const _textBlock33 = new TextBlock();
                _textBlock33._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock33._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock33._set_property_value_by_name("Width", DataContextBinding(_textBlock33, "Width"));
                _textBlock33._set_property_value_by_name("Height", DataContextBinding(_textBlock33, "Height"));
                _textBlock33._set_property_value_by_name("Text", DataContextBinding(_textBlock33, "LabelText"));
                _textBlock33._set_property_value_by_name("FontSize", 11);
                _textBlock33._set_property_value_by_name("Foreground", DynamicResource(_textBlock33, "OnSurface"));
                _textBlock33._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock33._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas31.AddChild(_textBlock33);
                return _canvas31;
            };
            const _tplSet34 = [new TargetedSetter(Diamond, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig35 = new TemplateDataTrigger("IsSelected", true, _tplSet34);
            return new DataTemplate(_factory, DiamondShapeVM, [], [_tplDataTrig35]);
        })();
        t.Set(DiamondShapeVM, _tmpl30);
        const _tmpl36 = (() => {
            const _factory = (_data) => {
                const _canvas37 = new Canvas();
                _canvas37.SetNameScope(new NameScope());
                _canvas37._set_property_value_by_name("Width", DataContextBinding(_canvas37, "Width"));
                _canvas37._set_property_value_by_name("Height", DataContextBinding(_canvas37, "Height"));
                const _pentagon38 = new Pentagon();
                _pentagon38.Name = "chrome";
                _pentagon38._set_property_value_by_name("Width", DataContextBinding(_pentagon38, "Width"));
                _pentagon38._set_property_value_by_name("Height", DataContextBinding(_pentagon38, "Height"));
                _pentagon38._set_property_value_by_name("Background", DataContextBinding(_pentagon38, "FillBrush"));
                _pentagon38._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _pentagon38._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas37.AddChild(_pentagon38);
                const _textBlock39 = new TextBlock();
                _textBlock39._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock39._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock39._set_property_value_by_name("Width", DataContextBinding(_textBlock39, "Width"));
                _textBlock39._set_property_value_by_name("Height", DataContextBinding(_textBlock39, "Height"));
                _textBlock39._set_property_value_by_name("Text", DataContextBinding(_textBlock39, "LabelText"));
                _textBlock39._set_property_value_by_name("FontSize", 11);
                _textBlock39._set_property_value_by_name("Foreground", DynamicResource(_textBlock39, "OnSurface"));
                _textBlock39._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock39._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas37.AddChild(_textBlock39);
                return _canvas37;
            };
            const _tplSet40 = [new TargetedSetter(Pentagon, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig41 = new TemplateDataTrigger("IsSelected", true, _tplSet40);
            return new DataTemplate(_factory, PentagonShapeVM, [], [_tplDataTrig41]);
        })();
        t.Set(PentagonShapeVM, _tmpl36);
        const _tmpl42 = (() => {
            const _factory = (_data) => {
                const _canvas43 = new Canvas();
                _canvas43.SetNameScope(new NameScope());
                _canvas43._set_property_value_by_name("Width", DataContextBinding(_canvas43, "Width"));
                _canvas43._set_property_value_by_name("Height", DataContextBinding(_canvas43, "Height"));
                const _gem44 = new Gem();
                _gem44.Name = "chrome";
                _gem44._set_property_value_by_name("Width", DataContextBinding(_gem44, "Width"));
                _gem44._set_property_value_by_name("Height", DataContextBinding(_gem44, "Height"));
                _gem44._set_property_value_by_name("Background", DataContextBinding(_gem44, "FillBrush"));
                _gem44._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _gem44._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas43.AddChild(_gem44);
                const _textBlock45 = new TextBlock();
                _textBlock45._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock45._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock45._set_property_value_by_name("Width", DataContextBinding(_textBlock45, "Width"));
                _textBlock45._set_property_value_by_name("Height", DataContextBinding(_textBlock45, "Height"));
                _textBlock45._set_property_value_by_name("Text", DataContextBinding(_textBlock45, "LabelText"));
                _textBlock45._set_property_value_by_name("FontSize", 11);
                _textBlock45._set_property_value_by_name("Foreground", DynamicResource(_textBlock45, "OnSurface"));
                _textBlock45._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock45._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas43.AddChild(_textBlock45);
                return _canvas43;
            };
            const _tplSet46 = [new TargetedSetter(Gem, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig47 = new TemplateDataTrigger("IsSelected", true, _tplSet46);
            return new DataTemplate(_factory, GemShapeVM, [], [_tplDataTrig47]);
        })();
        t.Set(GemShapeVM, _tmpl42);
        const _tmpl48 = (() => {
            const _factory = (_data) => {
                const _canvas49 = new Canvas();
                _canvas49.SetNameScope(new NameScope());
                _canvas49._set_property_value_by_name("Width", DataContextBinding(_canvas49, "Width"));
                _canvas49._set_property_value_by_name("Height", DataContextBinding(_canvas49, "Height"));
                const _arch50 = new Arch();
                _arch50.Name = "chrome";
                _arch50._set_property_value_by_name("Width", DataContextBinding(_arch50, "Width"));
                _arch50._set_property_value_by_name("Height", DataContextBinding(_arch50, "Height"));
                _arch50._set_property_value_by_name("Background", DataContextBinding(_arch50, "FillBrush"));
                _arch50._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _arch50._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas49.AddChild(_arch50);
                const _textBlock51 = new TextBlock();
                _textBlock51._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock51._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock51._set_property_value_by_name("Width", DataContextBinding(_textBlock51, "Width"));
                _textBlock51._set_property_value_by_name("Height", DataContextBinding(_textBlock51, "Height"));
                _textBlock51._set_property_value_by_name("Text", DataContextBinding(_textBlock51, "LabelText"));
                _textBlock51._set_property_value_by_name("FontSize", 11);
                _textBlock51._set_property_value_by_name("Foreground", DynamicResource(_textBlock51, "OnSurface"));
                _textBlock51._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock51._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas49.AddChild(_textBlock51);
                return _canvas49;
            };
            const _tplSet52 = [new TargetedSetter(Arch, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig53 = new TemplateDataTrigger("IsSelected", true, _tplSet52);
            return new DataTemplate(_factory, ArchShapeVM, [], [_tplDataTrig53]);
        })();
        t.Set(ArchShapeVM, _tmpl48);
        const _tmpl54 = (() => {
            const _factory = (_data) => {
                const _canvas55 = new Canvas();
                _canvas55.SetNameScope(new NameScope());
                _canvas55._set_property_value_by_name("Width", DataContextBinding(_canvas55, "Width"));
                _canvas55._set_property_value_by_name("Height", DataContextBinding(_canvas55, "Height"));
                const _semicircle56 = new Semicircle();
                _semicircle56.Name = "chrome";
                _semicircle56._set_property_value_by_name("Width", DataContextBinding(_semicircle56, "Width"));
                _semicircle56._set_property_value_by_name("Height", DataContextBinding(_semicircle56, "Height"));
                _semicircle56._set_property_value_by_name("Background", DataContextBinding(_semicircle56, "FillBrush"));
                _semicircle56._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _semicircle56._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas55.AddChild(_semicircle56);
                const _textBlock57 = new TextBlock();
                _textBlock57._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock57._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock57._set_property_value_by_name("Width", DataContextBinding(_textBlock57, "Width"));
                _textBlock57._set_property_value_by_name("Height", DataContextBinding(_textBlock57, "Height"));
                _textBlock57._set_property_value_by_name("Text", DataContextBinding(_textBlock57, "LabelText"));
                _textBlock57._set_property_value_by_name("FontSize", 11);
                _textBlock57._set_property_value_by_name("Foreground", DynamicResource(_textBlock57, "OnSurface"));
                _textBlock57._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock57._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas55.AddChild(_textBlock57);
                return _canvas55;
            };
            const _tplSet58 = [new TargetedSetter(Semicircle, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig59 = new TemplateDataTrigger("IsSelected", true, _tplSet58);
            return new DataTemplate(_factory, SemicircleShapeVM, [], [_tplDataTrig59]);
        })();
        t.Set(SemicircleShapeVM, _tmpl54);
        const _tmpl60 = (() => {
            const _factory = (_data) => {
                const _canvas61 = new Canvas();
                _canvas61.SetNameScope(new NameScope());
                _canvas61._set_property_value_by_name("Width", DataContextBinding(_canvas61, "Width"));
                _canvas61._set_property_value_by_name("Height", DataContextBinding(_canvas61, "Height"));
                const _triangle62 = new Triangle();
                _triangle62.Name = "chrome";
                _triangle62._set_property_value_by_name("Width", DataContextBinding(_triangle62, "Width"));
                _triangle62._set_property_value_by_name("Height", DataContextBinding(_triangle62, "Height"));
                _triangle62._set_property_value_by_name("CornerRadius", 10);
                _triangle62._set_property_value_by_name("Background", DataContextBinding(_triangle62, "FillBrush"));
                _triangle62._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _triangle62._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas61.AddChild(_triangle62);
                const _textBlock63 = new TextBlock();
                _textBlock63._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock63._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock63._set_property_value_by_name("Width", DataContextBinding(_textBlock63, "Width"));
                _textBlock63._set_property_value_by_name("Height", DataContextBinding(_textBlock63, "Height"));
                _textBlock63._set_property_value_by_name("Text", DataContextBinding(_textBlock63, "LabelText"));
                _textBlock63._set_property_value_by_name("FontSize", 11);
                _textBlock63._set_property_value_by_name("Foreground", DynamicResource(_textBlock63, "OnSurface"));
                _textBlock63._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock63._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas61.AddChild(_textBlock63);
                return _canvas61;
            };
            const _tplSet64 = [new TargetedSetter(Triangle, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig65 = new TemplateDataTrigger("IsSelected", true, _tplSet64);
            return new DataTemplate(_factory, TriangleShapeVM, [], [_tplDataTrig65]);
        })();
        t.Set(TriangleShapeVM, _tmpl60);
        const _tmpl66 = (() => {
            const _factory = (_data) => {
                const _canvas67 = new Canvas();
                _canvas67.SetNameScope(new NameScope());
                _canvas67._set_property_value_by_name("Width", DataContextBinding(_canvas67, "Width"));
                _canvas67._set_property_value_by_name("Height", DataContextBinding(_canvas67, "Height"));
                const _arrow68 = new Arrow();
                _arrow68.Name = "chrome";
                _arrow68._set_property_value_by_name("Width", DataContextBinding(_arrow68, "Width"));
                _arrow68._set_property_value_by_name("Height", DataContextBinding(_arrow68, "Height"));
                _arrow68._set_property_value_by_name("CornerRadius", 10);
                _arrow68._set_property_value_by_name("Background", DataContextBinding(_arrow68, "FillBrush"));
                _arrow68._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _arrow68._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas67.AddChild(_arrow68);
                const _textBlock69 = new TextBlock();
                _textBlock69._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock69._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock69._set_property_value_by_name("Width", DataContextBinding(_textBlock69, "Width"));
                _textBlock69._set_property_value_by_name("Height", DataContextBinding(_textBlock69, "Height"));
                _textBlock69._set_property_value_by_name("Text", DataContextBinding(_textBlock69, "LabelText"));
                _textBlock69._set_property_value_by_name("FontSize", 11);
                _textBlock69._set_property_value_by_name("Foreground", DynamicResource(_textBlock69, "OnSurface"));
                _textBlock69._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock69._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas67.AddChild(_textBlock69);
                return _canvas67;
            };
            const _tplSet70 = [new TargetedSetter(Arrow, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig71 = new TemplateDataTrigger("IsSelected", true, _tplSet70);
            return new DataTemplate(_factory, ArrowShapeVM, [], [_tplDataTrig71]);
        })();
        t.Set(ArrowShapeVM, _tmpl66);
        const _tmpl72 = (() => {
            const _factory = (_data) => {
                const _canvas73 = new Canvas();
                _canvas73.SetNameScope(new NameScope());
                _canvas73._set_property_value_by_name("Width", DataContextBinding(_canvas73, "Width"));
                _canvas73._set_property_value_by_name("Height", DataContextBinding(_canvas73, "Height"));
                const _fan74 = new Fan();
                _fan74.Name = "chrome";
                _fan74._set_property_value_by_name("Width", DataContextBinding(_fan74, "Width"));
                _fan74._set_property_value_by_name("Height", DataContextBinding(_fan74, "Height"));
                _fan74._set_property_value_by_name("Background", DataContextBinding(_fan74, "FillBrush"));
                _fan74._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _fan74._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas73.AddChild(_fan74);
                const _textBlock75 = new TextBlock();
                _textBlock75._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock75._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock75._set_property_value_by_name("Width", DataContextBinding(_textBlock75, "Width"));
                _textBlock75._set_property_value_by_name("Height", DataContextBinding(_textBlock75, "Height"));
                _textBlock75._set_property_value_by_name("Text", DataContextBinding(_textBlock75, "LabelText"));
                _textBlock75._set_property_value_by_name("FontSize", 11);
                _textBlock75._set_property_value_by_name("Foreground", DynamicResource(_textBlock75, "OnSurface"));
                _textBlock75._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock75._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas73.AddChild(_textBlock75);
                return _canvas73;
            };
            const _tplSet76 = [new TargetedSetter(Fan, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig77 = new TemplateDataTrigger("IsSelected", true, _tplSet76);
            return new DataTemplate(_factory, FanShapeVM, [], [_tplDataTrig77]);
        })();
        t.Set(FanShapeVM, _tmpl72);
        const _tmpl78 = (() => {
            const _factory = (_data) => {
                const _canvas79 = new Canvas();
                _canvas79.SetNameScope(new NameScope());
                _canvas79._set_property_value_by_name("Width", DataContextBinding(_canvas79, "Width"));
                _canvas79._set_property_value_by_name("Height", DataContextBinding(_canvas79, "Height"));
                const _clamshell80 = new Clamshell();
                _clamshell80.Name = "chrome";
                _clamshell80._set_property_value_by_name("Width", DataContextBinding(_clamshell80, "Width"));
                _clamshell80._set_property_value_by_name("Height", DataContextBinding(_clamshell80, "Height"));
                _clamshell80._set_property_value_by_name("CornerRadius", 8);
                _clamshell80._set_property_value_by_name("Background", DataContextBinding(_clamshell80, "FillBrush"));
                _clamshell80._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _clamshell80._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas79.AddChild(_clamshell80);
                const _textBlock81 = new TextBlock();
                _textBlock81._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock81._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock81._set_property_value_by_name("Width", DataContextBinding(_textBlock81, "Width"));
                _textBlock81._set_property_value_by_name("Height", DataContextBinding(_textBlock81, "Height"));
                _textBlock81._set_property_value_by_name("Text", DataContextBinding(_textBlock81, "LabelText"));
                _textBlock81._set_property_value_by_name("FontSize", 11);
                _textBlock81._set_property_value_by_name("Foreground", DynamicResource(_textBlock81, "OnSurface"));
                _textBlock81._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock81._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas79.AddChild(_textBlock81);
                return _canvas79;
            };
            const _tplSet82 = [new TargetedSetter(Clamshell, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig83 = new TemplateDataTrigger("IsSelected", true, _tplSet82);
            return new DataTemplate(_factory, ClamshellShapeVM, [], [_tplDataTrig83]);
        })();
        t.Set(ClamshellShapeVM, _tmpl78);
        const _tmpl84 = (() => {
            const _factory = (_data) => {
                const _canvas85 = new Canvas();
                _canvas85.SetNameScope(new NameScope());
                _canvas85._set_property_value_by_name("Width", DataContextBinding(_canvas85, "Width"));
                _canvas85._set_property_value_by_name("Height", DataContextBinding(_canvas85, "Height"));
                const _fourSidedCookie86 = new FourSidedCookie();
                _fourSidedCookie86.Name = "chrome";
                _fourSidedCookie86._set_property_value_by_name("Width", DataContextBinding(_fourSidedCookie86, "Width"));
                _fourSidedCookie86._set_property_value_by_name("Height", DataContextBinding(_fourSidedCookie86, "Height"));
                _fourSidedCookie86._set_property_value_by_name("CornerRadius", 10);
                _fourSidedCookie86._set_property_value_by_name("Background", DataContextBinding(_fourSidedCookie86, "FillBrush"));
                _fourSidedCookie86._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _fourSidedCookie86._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas85.AddChild(_fourSidedCookie86);
                const _textBlock87 = new TextBlock();
                _textBlock87._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock87._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock87._set_property_value_by_name("Width", DataContextBinding(_textBlock87, "Width"));
                _textBlock87._set_property_value_by_name("Height", DataContextBinding(_textBlock87, "Height"));
                _textBlock87._set_property_value_by_name("Text", DataContextBinding(_textBlock87, "LabelText"));
                _textBlock87._set_property_value_by_name("FontSize", 11);
                _textBlock87._set_property_value_by_name("Foreground", DynamicResource(_textBlock87, "OnSurface"));
                _textBlock87._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock87._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas85.AddChild(_textBlock87);
                return _canvas85;
            };
            const _tplSet88 = [new TargetedSetter(FourSidedCookie, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig89 = new TemplateDataTrigger("IsSelected", true, _tplSet88);
            return new DataTemplate(_factory, FourCookieShapeVM, [], [_tplDataTrig89]);
        })();
        t.Set(FourCookieShapeVM, _tmpl84);
        const _tmpl90 = (() => {
            const _factory = (_data) => {
                const _canvas91 = new Canvas();
                _canvas91.SetNameScope(new NameScope());
                _canvas91._set_property_value_by_name("Width", DataContextBinding(_canvas91, "Width"));
                _canvas91._set_property_value_by_name("Height", DataContextBinding(_canvas91, "Height"));
                const _sixSidedCookie92 = new SixSidedCookie();
                _sixSidedCookie92.Name = "chrome";
                _sixSidedCookie92._set_property_value_by_name("Width", DataContextBinding(_sixSidedCookie92, "Width"));
                _sixSidedCookie92._set_property_value_by_name("Height", DataContextBinding(_sixSidedCookie92, "Height"));
                _sixSidedCookie92._set_property_value_by_name("CornerRadius", 8);
                _sixSidedCookie92._set_property_value_by_name("Background", DataContextBinding(_sixSidedCookie92, "FillBrush"));
                _sixSidedCookie92._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _sixSidedCookie92._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas91.AddChild(_sixSidedCookie92);
                const _textBlock93 = new TextBlock();
                _textBlock93._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock93._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock93._set_property_value_by_name("Width", DataContextBinding(_textBlock93, "Width"));
                _textBlock93._set_property_value_by_name("Height", DataContextBinding(_textBlock93, "Height"));
                _textBlock93._set_property_value_by_name("Text", DataContextBinding(_textBlock93, "LabelText"));
                _textBlock93._set_property_value_by_name("FontSize", 11);
                _textBlock93._set_property_value_by_name("Foreground", DynamicResource(_textBlock93, "OnSurface"));
                _textBlock93._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock93._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas91.AddChild(_textBlock93);
                return _canvas91;
            };
            const _tplSet94 = [new TargetedSetter(SixSidedCookie, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig95 = new TemplateDataTrigger("IsSelected", true, _tplSet94);
            return new DataTemplate(_factory, SixCookieShapeVM, [], [_tplDataTrig95]);
        })();
        t.Set(SixCookieShapeVM, _tmpl90);
        const _tmpl96 = (() => {
            const _factory = (_data) => {
                const _canvas97 = new Canvas();
                _canvas97.SetNameScope(new NameScope());
                _canvas97._set_property_value_by_name("Width", DataContextBinding(_canvas97, "Width"));
                _canvas97._set_property_value_by_name("Height", DataContextBinding(_canvas97, "Height"));
                const _sevenSidedCookie98 = new SevenSidedCookie();
                _sevenSidedCookie98.Name = "chrome";
                _sevenSidedCookie98._set_property_value_by_name("Width", DataContextBinding(_sevenSidedCookie98, "Width"));
                _sevenSidedCookie98._set_property_value_by_name("Height", DataContextBinding(_sevenSidedCookie98, "Height"));
                _sevenSidedCookie98._set_property_value_by_name("CornerRadius", 8);
                _sevenSidedCookie98._set_property_value_by_name("Background", DataContextBinding(_sevenSidedCookie98, "FillBrush"));
                _sevenSidedCookie98._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _sevenSidedCookie98._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas97.AddChild(_sevenSidedCookie98);
                const _textBlock99 = new TextBlock();
                _textBlock99._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock99._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock99._set_property_value_by_name("Width", DataContextBinding(_textBlock99, "Width"));
                _textBlock99._set_property_value_by_name("Height", DataContextBinding(_textBlock99, "Height"));
                _textBlock99._set_property_value_by_name("Text", DataContextBinding(_textBlock99, "LabelText"));
                _textBlock99._set_property_value_by_name("FontSize", 11);
                _textBlock99._set_property_value_by_name("Foreground", DynamicResource(_textBlock99, "OnSurface"));
                _textBlock99._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock99._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas97.AddChild(_textBlock99);
                return _canvas97;
            };
            const _tplSet100 = [new TargetedSetter(SevenSidedCookie, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig101 = new TemplateDataTrigger("IsSelected", true, _tplSet100);
            return new DataTemplate(_factory, SevenCookieShapeVM, [], [_tplDataTrig101]);
        })();
        t.Set(SevenCookieShapeVM, _tmpl96);
        const _tmpl102 = (() => {
            const _factory = (_data) => {
                const _canvas103 = new Canvas();
                _canvas103.SetNameScope(new NameScope());
                _canvas103._set_property_value_by_name("Width", DataContextBinding(_canvas103, "Width"));
                _canvas103._set_property_value_by_name("Height", DataContextBinding(_canvas103, "Height"));
                const _nineSidedCookie104 = new NineSidedCookie();
                _nineSidedCookie104.Name = "chrome";
                _nineSidedCookie104._set_property_value_by_name("Width", DataContextBinding(_nineSidedCookie104, "Width"));
                _nineSidedCookie104._set_property_value_by_name("Height", DataContextBinding(_nineSidedCookie104, "Height"));
                _nineSidedCookie104._set_property_value_by_name("CornerRadius", 6);
                _nineSidedCookie104._set_property_value_by_name("Background", DataContextBinding(_nineSidedCookie104, "FillBrush"));
                _nineSidedCookie104._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _nineSidedCookie104._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas103.AddChild(_nineSidedCookie104);
                const _textBlock105 = new TextBlock();
                _textBlock105._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock105._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock105._set_property_value_by_name("Width", DataContextBinding(_textBlock105, "Width"));
                _textBlock105._set_property_value_by_name("Height", DataContextBinding(_textBlock105, "Height"));
                _textBlock105._set_property_value_by_name("Text", DataContextBinding(_textBlock105, "LabelText"));
                _textBlock105._set_property_value_by_name("FontSize", 11);
                _textBlock105._set_property_value_by_name("Foreground", DynamicResource(_textBlock105, "OnSurface"));
                _textBlock105._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock105._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas103.AddChild(_textBlock105);
                return _canvas103;
            };
            const _tplSet106 = [new TargetedSetter(NineSidedCookie, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig107 = new TemplateDataTrigger("IsSelected", true, _tplSet106);
            return new DataTemplate(_factory, NineCookieShapeVM, [], [_tplDataTrig107]);
        })();
        t.Set(NineCookieShapeVM, _tmpl102);
        const _tmpl108 = (() => {
            const _factory = (_data) => {
                const _canvas109 = new Canvas();
                _canvas109.SetNameScope(new NameScope());
                _canvas109._set_property_value_by_name("Width", DataContextBinding(_canvas109, "Width"));
                _canvas109._set_property_value_by_name("Height", DataContextBinding(_canvas109, "Height"));
                const _twelveSidedCookie110 = new TwelveSidedCookie();
                _twelveSidedCookie110.Name = "chrome";
                _twelveSidedCookie110._set_property_value_by_name("Width", DataContextBinding(_twelveSidedCookie110, "Width"));
                _twelveSidedCookie110._set_property_value_by_name("Height", DataContextBinding(_twelveSidedCookie110, "Height"));
                _twelveSidedCookie110._set_property_value_by_name("CornerRadius", 5);
                _twelveSidedCookie110._set_property_value_by_name("Background", DataContextBinding(_twelveSidedCookie110, "FillBrush"));
                _twelveSidedCookie110._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _twelveSidedCookie110._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas109.AddChild(_twelveSidedCookie110);
                const _textBlock111 = new TextBlock();
                _textBlock111._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock111._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock111._set_property_value_by_name("Width", DataContextBinding(_textBlock111, "Width"));
                _textBlock111._set_property_value_by_name("Height", DataContextBinding(_textBlock111, "Height"));
                _textBlock111._set_property_value_by_name("Text", DataContextBinding(_textBlock111, "LabelText"));
                _textBlock111._set_property_value_by_name("FontSize", 11);
                _textBlock111._set_property_value_by_name("Foreground", DynamicResource(_textBlock111, "OnSurface"));
                _textBlock111._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock111._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas109.AddChild(_textBlock111);
                return _canvas109;
            };
            const _tplSet112 = [new TargetedSetter(TwelveSidedCookie, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig113 = new TemplateDataTrigger("IsSelected", true, _tplSet112);
            return new DataTemplate(_factory, TwelveCookieShapeVM, [], [_tplDataTrig113]);
        })();
        t.Set(TwelveCookieShapeVM, _tmpl108);
        const _tmpl114 = (() => {
            const _factory = (_data) => {
                const _canvas115 = new Canvas();
                _canvas115.SetNameScope(new NameScope());
                _canvas115._set_property_value_by_name("Width", DataContextBinding(_canvas115, "Width"));
                _canvas115._set_property_value_by_name("Height", DataContextBinding(_canvas115, "Height"));
                const _fourLeafClover116 = new FourLeafClover();
                _fourLeafClover116.Name = "chrome";
                _fourLeafClover116._set_property_value_by_name("Width", DataContextBinding(_fourLeafClover116, "Width"));
                _fourLeafClover116._set_property_value_by_name("Height", DataContextBinding(_fourLeafClover116, "Height"));
                _fourLeafClover116._set_property_value_by_name("Background", DataContextBinding(_fourLeafClover116, "FillBrush"));
                _fourLeafClover116._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _fourLeafClover116._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas115.AddChild(_fourLeafClover116);
                const _textBlock117 = new TextBlock();
                _textBlock117._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock117._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock117._set_property_value_by_name("Width", DataContextBinding(_textBlock117, "Width"));
                _textBlock117._set_property_value_by_name("Height", DataContextBinding(_textBlock117, "Height"));
                _textBlock117._set_property_value_by_name("Text", DataContextBinding(_textBlock117, "LabelText"));
                _textBlock117._set_property_value_by_name("FontSize", 11);
                _textBlock117._set_property_value_by_name("Foreground", DynamicResource(_textBlock117, "OnSurface"));
                _textBlock117._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock117._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas115.AddChild(_textBlock117);
                return _canvas115;
            };
            const _tplSet118 = [new TargetedSetter(FourLeafClover, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig119 = new TemplateDataTrigger("IsSelected", true, _tplSet118);
            return new DataTemplate(_factory, FourLeafCloverShapeVM, [], [_tplDataTrig119]);
        })();
        t.Set(FourLeafCloverShapeVM, _tmpl114);
        const _tmpl120 = (() => {
            const _factory = (_data) => {
                const _canvas121 = new Canvas();
                _canvas121.SetNameScope(new NameScope());
                _canvas121._set_property_value_by_name("Width", DataContextBinding(_canvas121, "Width"));
                _canvas121._set_property_value_by_name("Height", DataContextBinding(_canvas121, "Height"));
                const _eightLeafClover122 = new EightLeafClover();
                _eightLeafClover122.Name = "chrome";
                _eightLeafClover122._set_property_value_by_name("Width", DataContextBinding(_eightLeafClover122, "Width"));
                _eightLeafClover122._set_property_value_by_name("Height", DataContextBinding(_eightLeafClover122, "Height"));
                _eightLeafClover122._set_property_value_by_name("Background", DataContextBinding(_eightLeafClover122, "FillBrush"));
                _eightLeafClover122._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _eightLeafClover122._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas121.AddChild(_eightLeafClover122);
                const _textBlock123 = new TextBlock();
                _textBlock123._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock123._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock123._set_property_value_by_name("Width", DataContextBinding(_textBlock123, "Width"));
                _textBlock123._set_property_value_by_name("Height", DataContextBinding(_textBlock123, "Height"));
                _textBlock123._set_property_value_by_name("Text", DataContextBinding(_textBlock123, "LabelText"));
                _textBlock123._set_property_value_by_name("FontSize", 11);
                _textBlock123._set_property_value_by_name("Foreground", DynamicResource(_textBlock123, "OnSurface"));
                _textBlock123._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock123._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas121.AddChild(_textBlock123);
                return _canvas121;
            };
            const _tplSet124 = [new TargetedSetter(EightLeafClover, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig125 = new TemplateDataTrigger("IsSelected", true, _tplSet124);
            return new DataTemplate(_factory, EightLeafCloverShapeVM, [], [_tplDataTrig125]);
        })();
        t.Set(EightLeafCloverShapeVM, _tmpl120);
        const _tmpl126 = (() => {
            const _factory = (_data) => {
                const _canvas127 = new Canvas();
                _canvas127.SetNameScope(new NameScope());
                _canvas127._set_property_value_by_name("Width", DataContextBinding(_canvas127, "Width"));
                _canvas127._set_property_value_by_name("Height", DataContextBinding(_canvas127, "Height"));
                const _sunny128 = new Sunny();
                _sunny128.Name = "chrome";
                _sunny128._set_property_value_by_name("Width", DataContextBinding(_sunny128, "Width"));
                _sunny128._set_property_value_by_name("Height", DataContextBinding(_sunny128, "Height"));
                _sunny128._set_property_value_by_name("Background", DataContextBinding(_sunny128, "FillBrush"));
                _sunny128._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _sunny128._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas127.AddChild(_sunny128);
                const _textBlock129 = new TextBlock();
                _textBlock129._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock129._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock129._set_property_value_by_name("Width", DataContextBinding(_textBlock129, "Width"));
                _textBlock129._set_property_value_by_name("Height", DataContextBinding(_textBlock129, "Height"));
                _textBlock129._set_property_value_by_name("Text", DataContextBinding(_textBlock129, "LabelText"));
                _textBlock129._set_property_value_by_name("FontSize", 11);
                _textBlock129._set_property_value_by_name("Foreground", DynamicResource(_textBlock129, "OnSurface"));
                _textBlock129._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock129._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas127.AddChild(_textBlock129);
                return _canvas127;
            };
            const _tplSet130 = [new TargetedSetter(Sunny, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig131 = new TemplateDataTrigger("IsSelected", true, _tplSet130);
            return new DataTemplate(_factory, SunnyShapeVM, [], [_tplDataTrig131]);
        })();
        t.Set(SunnyShapeVM, _tmpl126);
        const _tmpl132 = (() => {
            const _factory = (_data) => {
                const _canvas133 = new Canvas();
                _canvas133.SetNameScope(new NameScope());
                _canvas133._set_property_value_by_name("Width", DataContextBinding(_canvas133, "Width"));
                _canvas133._set_property_value_by_name("Height", DataContextBinding(_canvas133, "Height"));
                const _verySunny134 = new VerySunny();
                _verySunny134.Name = "chrome";
                _verySunny134._set_property_value_by_name("Width", DataContextBinding(_verySunny134, "Width"));
                _verySunny134._set_property_value_by_name("Height", DataContextBinding(_verySunny134, "Height"));
                _verySunny134._set_property_value_by_name("Background", DataContextBinding(_verySunny134, "FillBrush"));
                _verySunny134._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _verySunny134._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas133.AddChild(_verySunny134);
                const _textBlock135 = new TextBlock();
                _textBlock135._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock135._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock135._set_property_value_by_name("Width", DataContextBinding(_textBlock135, "Width"));
                _textBlock135._set_property_value_by_name("Height", DataContextBinding(_textBlock135, "Height"));
                _textBlock135._set_property_value_by_name("Text", DataContextBinding(_textBlock135, "LabelText"));
                _textBlock135._set_property_value_by_name("FontSize", 11);
                _textBlock135._set_property_value_by_name("Foreground", DynamicResource(_textBlock135, "OnSurface"));
                _textBlock135._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock135._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas133.AddChild(_textBlock135);
                return _canvas133;
            };
            const _tplSet136 = [new TargetedSetter(VerySunny, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig137 = new TemplateDataTrigger("IsSelected", true, _tplSet136);
            return new DataTemplate(_factory, VerySunnyShapeVM, [], [_tplDataTrig137]);
        })();
        t.Set(VerySunnyShapeVM, _tmpl132);
        const _tmpl138 = (() => {
            const _factory = (_data) => {
                const _canvas139 = new Canvas();
                _canvas139.SetNameScope(new NameScope());
                _canvas139._set_property_value_by_name("Width", DataContextBinding(_canvas139, "Width"));
                _canvas139._set_property_value_by_name("Height", DataContextBinding(_canvas139, "Height"));
                const _burst140 = new Burst();
                _burst140.Name = "chrome";
                _burst140._set_property_value_by_name("Width", DataContextBinding(_burst140, "Width"));
                _burst140._set_property_value_by_name("Height", DataContextBinding(_burst140, "Height"));
                _burst140._set_property_value_by_name("Background", DataContextBinding(_burst140, "FillBrush"));
                _burst140._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _burst140._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas139.AddChild(_burst140);
                const _textBlock141 = new TextBlock();
                _textBlock141._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock141._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock141._set_property_value_by_name("Width", DataContextBinding(_textBlock141, "Width"));
                _textBlock141._set_property_value_by_name("Height", DataContextBinding(_textBlock141, "Height"));
                _textBlock141._set_property_value_by_name("Text", DataContextBinding(_textBlock141, "LabelText"));
                _textBlock141._set_property_value_by_name("FontSize", 11);
                _textBlock141._set_property_value_by_name("Foreground", DynamicResource(_textBlock141, "OnSurface"));
                _textBlock141._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock141._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas139.AddChild(_textBlock141);
                return _canvas139;
            };
            const _tplSet142 = [new TargetedSetter(Burst, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig143 = new TemplateDataTrigger("IsSelected", true, _tplSet142);
            return new DataTemplate(_factory, BurstShapeVM, [], [_tplDataTrig143]);
        })();
        t.Set(BurstShapeVM, _tmpl138);
        const _tmpl144 = (() => {
            const _factory = (_data) => {
                const _canvas145 = new Canvas();
                _canvas145.SetNameScope(new NameScope());
                _canvas145._set_property_value_by_name("Width", DataContextBinding(_canvas145, "Width"));
                _canvas145._set_property_value_by_name("Height", DataContextBinding(_canvas145, "Height"));
                const _softBurst146 = new SoftBurst();
                _softBurst146.Name = "chrome";
                _softBurst146._set_property_value_by_name("Width", DataContextBinding(_softBurst146, "Width"));
                _softBurst146._set_property_value_by_name("Height", DataContextBinding(_softBurst146, "Height"));
                _softBurst146._set_property_value_by_name("Background", DataContextBinding(_softBurst146, "FillBrush"));
                _softBurst146._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _softBurst146._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas145.AddChild(_softBurst146);
                const _textBlock147 = new TextBlock();
                _textBlock147._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock147._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock147._set_property_value_by_name("Width", DataContextBinding(_textBlock147, "Width"));
                _textBlock147._set_property_value_by_name("Height", DataContextBinding(_textBlock147, "Height"));
                _textBlock147._set_property_value_by_name("Text", DataContextBinding(_textBlock147, "LabelText"));
                _textBlock147._set_property_value_by_name("FontSize", 11);
                _textBlock147._set_property_value_by_name("Foreground", DynamicResource(_textBlock147, "OnSurface"));
                _textBlock147._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock147._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas145.AddChild(_textBlock147);
                return _canvas145;
            };
            const _tplSet148 = [new TargetedSetter(SoftBurst, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig149 = new TemplateDataTrigger("IsSelected", true, _tplSet148);
            return new DataTemplate(_factory, SoftBurstShapeVM, [], [_tplDataTrig149]);
        })();
        t.Set(SoftBurstShapeVM, _tmpl144);
        const _tmpl150 = (() => {
            const _factory = (_data) => {
                const _canvas151 = new Canvas();
                _canvas151.SetNameScope(new NameScope());
                _canvas151._set_property_value_by_name("Width", DataContextBinding(_canvas151, "Width"));
                _canvas151._set_property_value_by_name("Height", DataContextBinding(_canvas151, "Height"));
                const _boom152 = new Boom();
                _boom152.Name = "chrome";
                _boom152._set_property_value_by_name("Width", DataContextBinding(_boom152, "Width"));
                _boom152._set_property_value_by_name("Height", DataContextBinding(_boom152, "Height"));
                _boom152._set_property_value_by_name("Background", DataContextBinding(_boom152, "FillBrush"));
                _boom152._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _boom152._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas151.AddChild(_boom152);
                const _textBlock153 = new TextBlock();
                _textBlock153._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock153._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock153._set_property_value_by_name("Width", DataContextBinding(_textBlock153, "Width"));
                _textBlock153._set_property_value_by_name("Height", DataContextBinding(_textBlock153, "Height"));
                _textBlock153._set_property_value_by_name("Text", DataContextBinding(_textBlock153, "LabelText"));
                _textBlock153._set_property_value_by_name("FontSize", 11);
                _textBlock153._set_property_value_by_name("Foreground", DynamicResource(_textBlock153, "OnSurface"));
                _textBlock153._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock153._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas151.AddChild(_textBlock153);
                return _canvas151;
            };
            const _tplSet154 = [new TargetedSetter(Boom, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig155 = new TemplateDataTrigger("IsSelected", true, _tplSet154);
            return new DataTemplate(_factory, BoomShapeVM, [], [_tplDataTrig155]);
        })();
        t.Set(BoomShapeVM, _tmpl150);
        const _tmpl156 = (() => {
            const _factory = (_data) => {
                const _canvas157 = new Canvas();
                _canvas157.SetNameScope(new NameScope());
                _canvas157._set_property_value_by_name("Width", DataContextBinding(_canvas157, "Width"));
                _canvas157._set_property_value_by_name("Height", DataContextBinding(_canvas157, "Height"));
                const _softBoom158 = new SoftBoom();
                _softBoom158.Name = "chrome";
                _softBoom158._set_property_value_by_name("Width", DataContextBinding(_softBoom158, "Width"));
                _softBoom158._set_property_value_by_name("Height", DataContextBinding(_softBoom158, "Height"));
                _softBoom158._set_property_value_by_name("Background", DataContextBinding(_softBoom158, "FillBrush"));
                _softBoom158._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _softBoom158._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas157.AddChild(_softBoom158);
                const _textBlock159 = new TextBlock();
                _textBlock159._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock159._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock159._set_property_value_by_name("Width", DataContextBinding(_textBlock159, "Width"));
                _textBlock159._set_property_value_by_name("Height", DataContextBinding(_textBlock159, "Height"));
                _textBlock159._set_property_value_by_name("Text", DataContextBinding(_textBlock159, "LabelText"));
                _textBlock159._set_property_value_by_name("FontSize", 11);
                _textBlock159._set_property_value_by_name("Foreground", DynamicResource(_textBlock159, "OnSurface"));
                _textBlock159._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock159._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas157.AddChild(_textBlock159);
                return _canvas157;
            };
            const _tplSet160 = [new TargetedSetter(SoftBoom, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig161 = new TemplateDataTrigger("IsSelected", true, _tplSet160);
            return new DataTemplate(_factory, SoftBoomShapeVM, [], [_tplDataTrig161]);
        })();
        t.Set(SoftBoomShapeVM, _tmpl156);
        const _tmpl162 = (() => {
            const _factory = (_data) => {
                const _canvas163 = new Canvas();
                _canvas163.SetNameScope(new NameScope());
                _canvas163._set_property_value_by_name("Width", DataContextBinding(_canvas163, "Width"));
                _canvas163._set_property_value_by_name("Height", DataContextBinding(_canvas163, "Height"));
                const _flower164 = new Flower();
                _flower164.Name = "chrome";
                _flower164._set_property_value_by_name("Width", DataContextBinding(_flower164, "Width"));
                _flower164._set_property_value_by_name("Height", DataContextBinding(_flower164, "Height"));
                _flower164._set_property_value_by_name("Background", DataContextBinding(_flower164, "FillBrush"));
                _flower164._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _flower164._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas163.AddChild(_flower164);
                const _textBlock165 = new TextBlock();
                _textBlock165._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock165._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock165._set_property_value_by_name("Width", DataContextBinding(_textBlock165, "Width"));
                _textBlock165._set_property_value_by_name("Height", DataContextBinding(_textBlock165, "Height"));
                _textBlock165._set_property_value_by_name("Text", DataContextBinding(_textBlock165, "LabelText"));
                _textBlock165._set_property_value_by_name("FontSize", 11);
                _textBlock165._set_property_value_by_name("Foreground", DynamicResource(_textBlock165, "OnSurface"));
                _textBlock165._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock165._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas163.AddChild(_textBlock165);
                return _canvas163;
            };
            const _tplSet166 = [new TargetedSetter(Flower, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig167 = new TemplateDataTrigger("IsSelected", true, _tplSet166);
            return new DataTemplate(_factory, FlowerShapeVM, [], [_tplDataTrig167]);
        })();
        t.Set(FlowerShapeVM, _tmpl162);
        const _tmpl168 = (() => {
            const _factory = (_data) => {
                const _canvas169 = new Canvas();
                _canvas169.SetNameScope(new NameScope());
                _canvas169._set_property_value_by_name("Width", DataContextBinding(_canvas169, "Width"));
                _canvas169._set_property_value_by_name("Height", DataContextBinding(_canvas169, "Height"));
                const _puffy170 = new Puffy();
                _puffy170.Name = "chrome";
                _puffy170._set_property_value_by_name("Width", DataContextBinding(_puffy170, "Width"));
                _puffy170._set_property_value_by_name("Height", DataContextBinding(_puffy170, "Height"));
                _puffy170._set_property_value_by_name("Background", DataContextBinding(_puffy170, "FillBrush"));
                _puffy170._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _puffy170._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas169.AddChild(_puffy170);
                const _textBlock171 = new TextBlock();
                _textBlock171._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock171._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock171._set_property_value_by_name("Width", DataContextBinding(_textBlock171, "Width"));
                _textBlock171._set_property_value_by_name("Height", DataContextBinding(_textBlock171, "Height"));
                _textBlock171._set_property_value_by_name("Text", DataContextBinding(_textBlock171, "LabelText"));
                _textBlock171._set_property_value_by_name("FontSize", 11);
                _textBlock171._set_property_value_by_name("Foreground", DynamicResource(_textBlock171, "OnSurface"));
                _textBlock171._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock171._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas169.AddChild(_textBlock171);
                return _canvas169;
            };
            const _tplSet172 = [new TargetedSetter(Puffy, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig173 = new TemplateDataTrigger("IsSelected", true, _tplSet172);
            return new DataTemplate(_factory, PuffyShapeVM, [], [_tplDataTrig173]);
        })();
        t.Set(PuffyShapeVM, _tmpl168);
        const _tmpl174 = (() => {
            const _factory = (_data) => {
                const _canvas175 = new Canvas();
                _canvas175.SetNameScope(new NameScope());
                _canvas175._set_property_value_by_name("Width", DataContextBinding(_canvas175, "Width"));
                _canvas175._set_property_value_by_name("Height", DataContextBinding(_canvas175, "Height"));
                const _puffyDiamond176 = new PuffyDiamond();
                _puffyDiamond176.Name = "chrome";
                _puffyDiamond176._set_property_value_by_name("Width", DataContextBinding(_puffyDiamond176, "Width"));
                _puffyDiamond176._set_property_value_by_name("Height", DataContextBinding(_puffyDiamond176, "Height"));
                _puffyDiamond176._set_property_value_by_name("Background", DataContextBinding(_puffyDiamond176, "FillBrush"));
                _puffyDiamond176._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _puffyDiamond176._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas175.AddChild(_puffyDiamond176);
                const _textBlock177 = new TextBlock();
                _textBlock177._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock177._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock177._set_property_value_by_name("Width", DataContextBinding(_textBlock177, "Width"));
                _textBlock177._set_property_value_by_name("Height", DataContextBinding(_textBlock177, "Height"));
                _textBlock177._set_property_value_by_name("Text", DataContextBinding(_textBlock177, "LabelText"));
                _textBlock177._set_property_value_by_name("FontSize", 11);
                _textBlock177._set_property_value_by_name("Foreground", DynamicResource(_textBlock177, "OnSurface"));
                _textBlock177._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock177._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas175.AddChild(_textBlock177);
                return _canvas175;
            };
            const _tplSet178 = [new TargetedSetter(PuffyDiamond, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig179 = new TemplateDataTrigger("IsSelected", true, _tplSet178);
            return new DataTemplate(_factory, PuffyDiamondShapeVM, [], [_tplDataTrig179]);
        })();
        t.Set(PuffyDiamondShapeVM, _tmpl174);
        const _tmpl180 = (() => {
            const _factory = (_data) => {
                const _canvas181 = new Canvas();
                _canvas181.SetNameScope(new NameScope());
                _canvas181._set_property_value_by_name("Width", DataContextBinding(_canvas181, "Width"));
                _canvas181._set_property_value_by_name("Height", DataContextBinding(_canvas181, "Height"));
                const _ghostish182 = new Ghostish();
                _ghostish182.Name = "chrome";
                _ghostish182._set_property_value_by_name("Width", DataContextBinding(_ghostish182, "Width"));
                _ghostish182._set_property_value_by_name("Height", DataContextBinding(_ghostish182, "Height"));
                _ghostish182._set_property_value_by_name("Background", DataContextBinding(_ghostish182, "FillBrush"));
                _ghostish182._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _ghostish182._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas181.AddChild(_ghostish182);
                const _textBlock183 = new TextBlock();
                _textBlock183._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock183._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock183._set_property_value_by_name("Width", DataContextBinding(_textBlock183, "Width"));
                _textBlock183._set_property_value_by_name("Height", DataContextBinding(_textBlock183, "Height"));
                _textBlock183._set_property_value_by_name("Text", DataContextBinding(_textBlock183, "LabelText"));
                _textBlock183._set_property_value_by_name("FontSize", 11);
                _textBlock183._set_property_value_by_name("Foreground", DynamicResource(_textBlock183, "OnSurface"));
                _textBlock183._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock183._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas181.AddChild(_textBlock183);
                return _canvas181;
            };
            const _tplSet184 = [new TargetedSetter(Ghostish, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig185 = new TemplateDataTrigger("IsSelected", true, _tplSet184);
            return new DataTemplate(_factory, GhostishShapeVM, [], [_tplDataTrig185]);
        })();
        t.Set(GhostishShapeVM, _tmpl180);
        const _tmpl186 = (() => {
            const _factory = (_data) => {
                const _canvas187 = new Canvas();
                _canvas187.SetNameScope(new NameScope());
                _canvas187._set_property_value_by_name("Width", DataContextBinding(_canvas187, "Width"));
                _canvas187._set_property_value_by_name("Height", DataContextBinding(_canvas187, "Height"));
                const _bun188 = new Bun();
                _bun188.Name = "chrome";
                _bun188._set_property_value_by_name("Width", DataContextBinding(_bun188, "Width"));
                _bun188._set_property_value_by_name("Height", DataContextBinding(_bun188, "Height"));
                _bun188._set_property_value_by_name("Background", DataContextBinding(_bun188, "FillBrush"));
                _bun188._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _bun188._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas187.AddChild(_bun188);
                const _textBlock189 = new TextBlock();
                _textBlock189._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock189._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock189._set_property_value_by_name("Width", DataContextBinding(_textBlock189, "Width"));
                _textBlock189._set_property_value_by_name("Height", DataContextBinding(_textBlock189, "Height"));
                _textBlock189._set_property_value_by_name("Text", DataContextBinding(_textBlock189, "LabelText"));
                _textBlock189._set_property_value_by_name("FontSize", 11);
                _textBlock189._set_property_value_by_name("Foreground", DynamicResource(_textBlock189, "OnSurface"));
                _textBlock189._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock189._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas187.AddChild(_textBlock189);
                return _canvas187;
            };
            const _tplSet190 = [new TargetedSetter(Bun, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig191 = new TemplateDataTrigger("IsSelected", true, _tplSet190);
            return new DataTemplate(_factory, BunShapeVM, [], [_tplDataTrig191]);
        })();
        t.Set(BunShapeVM, _tmpl186);
        const _tmpl192 = (() => {
            const _factory = (_data) => {
                const _canvas193 = new Canvas();
                _canvas193.SetNameScope(new NameScope());
                _canvas193._set_property_value_by_name("Width", DataContextBinding(_canvas193, "Width"));
                _canvas193._set_property_value_by_name("Height", DataContextBinding(_canvas193, "Height"));
                const _heart194 = new Heart();
                _heart194.Name = "chrome";
                _heart194._set_property_value_by_name("Width", DataContextBinding(_heart194, "Width"));
                _heart194._set_property_value_by_name("Height", DataContextBinding(_heart194, "Height"));
                _heart194._set_property_value_by_name("Background", DataContextBinding(_heart194, "FillBrush"));
                _heart194._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _heart194._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas193.AddChild(_heart194);
                const _textBlock195 = new TextBlock();
                _textBlock195._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock195._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock195._set_property_value_by_name("Width", DataContextBinding(_textBlock195, "Width"));
                _textBlock195._set_property_value_by_name("Height", DataContextBinding(_textBlock195, "Height"));
                _textBlock195._set_property_value_by_name("Text", DataContextBinding(_textBlock195, "LabelText"));
                _textBlock195._set_property_value_by_name("FontSize", 11);
                _textBlock195._set_property_value_by_name("Foreground", DynamicResource(_textBlock195, "OnSurface"));
                _textBlock195._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock195._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas193.AddChild(_textBlock195);
                return _canvas193;
            };
            const _tplSet196 = [new TargetedSetter(Heart, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig197 = new TemplateDataTrigger("IsSelected", true, _tplSet196);
            return new DataTemplate(_factory, HeartShapeVM, [], [_tplDataTrig197]);
        })();
        t.Set(HeartShapeVM, _tmpl192);
        const _tmpl198 = (() => {
            const _factory = (_data) => {
                const _canvas199 = new Canvas();
                _canvas199.SetNameScope(new NameScope());
                _canvas199._set_property_value_by_name("Width", DataContextBinding(_canvas199, "Width"));
                _canvas199._set_property_value_by_name("Height", DataContextBinding(_canvas199, "Height"));
                const _pixelCircle200 = new PixelCircle();
                _pixelCircle200.Name = "chrome";
                _pixelCircle200._set_property_value_by_name("Width", DataContextBinding(_pixelCircle200, "Width"));
                _pixelCircle200._set_property_value_by_name("Height", DataContextBinding(_pixelCircle200, "Height"));
                _pixelCircle200._set_property_value_by_name("Background", DataContextBinding(_pixelCircle200, "FillBrush"));
                _pixelCircle200._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _pixelCircle200._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas199.AddChild(_pixelCircle200);
                const _textBlock201 = new TextBlock();
                _textBlock201._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock201._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock201._set_property_value_by_name("Width", DataContextBinding(_textBlock201, "Width"));
                _textBlock201._set_property_value_by_name("Height", DataContextBinding(_textBlock201, "Height"));
                _textBlock201._set_property_value_by_name("Text", DataContextBinding(_textBlock201, "LabelText"));
                _textBlock201._set_property_value_by_name("FontSize", 11);
                _textBlock201._set_property_value_by_name("Foreground", DynamicResource(_textBlock201, "OnSurface"));
                _textBlock201._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock201._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas199.AddChild(_textBlock201);
                return _canvas199;
            };
            const _tplSet202 = [new TargetedSetter(PixelCircle, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig203 = new TemplateDataTrigger("IsSelected", true, _tplSet202);
            return new DataTemplate(_factory, PixelCircleShapeVM, [], [_tplDataTrig203]);
        })();
        t.Set(PixelCircleShapeVM, _tmpl198);
        const _tmpl204 = (() => {
            const _factory = (_data) => {
                const _canvas205 = new Canvas();
                _canvas205.SetNameScope(new NameScope());
                _canvas205._set_property_value_by_name("Width", DataContextBinding(_canvas205, "Width"));
                _canvas205._set_property_value_by_name("Height", DataContextBinding(_canvas205, "Height"));
                const _pixelTriangle206 = new PixelTriangle();
                _pixelTriangle206.Name = "chrome";
                _pixelTriangle206._set_property_value_by_name("Width", DataContextBinding(_pixelTriangle206, "Width"));
                _pixelTriangle206._set_property_value_by_name("Height", DataContextBinding(_pixelTriangle206, "Height"));
                _pixelTriangle206._set_property_value_by_name("Background", DataContextBinding(_pixelTriangle206, "FillBrush"));
                _pixelTriangle206._set_property_value_by_name("Stroke", new SolidColorBrush(Color.FromHex('#1976d2')));
                _pixelTriangle206._set_property_value_by_name("StrokeThickness", 1.5);
                _canvas205.AddChild(_pixelTriangle206);
                const _textBlock207 = new TextBlock();
                _textBlock207._set_property_value_by_name(Canvas, "Left", 0);
                _textBlock207._set_property_value_by_name(Canvas, "Top", 0);
                _textBlock207._set_property_value_by_name("Width", DataContextBinding(_textBlock207, "Width"));
                _textBlock207._set_property_value_by_name("Height", DataContextBinding(_textBlock207, "Height"));
                _textBlock207._set_property_value_by_name("Text", DataContextBinding(_textBlock207, "LabelText"));
                _textBlock207._set_property_value_by_name("FontSize", 11);
                _textBlock207._set_property_value_by_name("Foreground", DynamicResource(_textBlock207, "OnSurface"));
                _textBlock207._set_property_value_by_name("HorizontalAlignment", HorizontalAlignment.Center);
                _textBlock207._set_property_value_by_name("VerticalAlignment", VerticalAlignment.Center);
                _canvas205.AddChild(_textBlock207);
                return _canvas205;
            };
            const _tplSet208 = [new TargetedSetter(PixelTriangle, "Stroke", new SolidColorBrush(Color.FromHex('#f97316')), "chrome")];
            const _tplDataTrig209 = new TemplateDataTrigger("IsSelected", true, _tplSet208);
            return new DataTemplate(_factory, PixelTriangleShapeVM, [], [_tplDataTrig209]);
        })();
        t.Set(PixelTriangleShapeVM, _tmpl204);
        const _tmpl210 = (() => {
            const _factory = (_data) => {
                const _border211 = new Border();
                _border211.Name = "bbox";
                _border211._set_property_value_by_name("Width", DataContextBinding(_border211, "Width"));
                _border211._set_property_value_by_name("Height", DataContextBinding(_border211, "Height"));
                _border211._set_property_value_by_name("BorderBrush", new SolidColorBrush(Color.FromHex('#00000000')));
                _border211._set_property_value_by_name("BorderThickness", new Thickness(2));
                _border211._set_property_value_by_name("IsHitTestVisible", false);
                return _border211;
            };
            const _tplSet212 = [new TargetedSetter(Border, "BorderBrush", new SolidColorBrush(Color.FromHex('#f97316')), "bbox")];
            const _tplDataTrig213 = new TemplateDataTrigger("IsSelected", true, _tplSet212);
            return new DataTemplate(_factory, GroupVM, [], [_tplDataTrig213]);
        })();
        t.Set(GroupVM, _tmpl210);
        return t;
    }
}
